interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_00000000:
    base_addr: 0x0
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: Stepper-Motor.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1d77c
symbols:
  0x0:
  - startup/startup_stm32f446xx.o
  - crtstuff.c
  - _arm_addsubsf3.o
  - _arm_muldivsf3.o
  - _arm_cmpsf2.o
  - _arm_fixsfsi.o
  - _arm_fixunssfsi.o
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - lib_a-strlen.o
  - lib_a-memchr.o
  - lib_a-memcpy.o
  - _arm_addsubdf3.o
  - _arm_muldivdf3.o
  - _arm_cmpdf2.o
  - _arm_unorddf2.o
  - _arm_fixdfsi.o
  - stm32f4xx_hal.c
  - stm32f4xx_hal_cortex.c
  - stm32f4xx_hal_dma.c
  - stm32f4xx_hal_flash.c
  - stm32f4xx_hal_flash_ex.c
  - stm32f4xx_hal_gpio.c
  - stm32f4xx_hal_pwr_ex.c
  - stm32f4xx_hal_rcc.c
  - stm32f4xx_hal_rcc_ex.c
  - stm32f4xx_hal_tim.c
  - stm32f4xx_hal_tim_ex.c
  - stm32f4xx_hal_uart.c
  - afl_call.c
  - main.c
  - serial.c
  - stepperCommands.c
  - stepperController.c
  - stm32f4xx_hal_msp.c
  - stm32f4xx_it.c
  - syscalls.c
  - system_stm32f4xx.c
  - errno.c
  - init.c
  - memset.c
  - printf.c
  - puts.c
  - vfprintf.c
  - wsetup.c
  - __call_atexit.c
  - atexit.c
  - dtoa.c
  - fflush.c
  - findfp.c
  - fini.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - localeconv.c
  - lock.c
  - makebuf.c
  - mallocr.c
  - memmove.c
  - mlock.c
  - mprec.c
  - mallocr.c
  - s_frexp.c
  - sbrkr.c
  - stdio.c
  - strncpy.c
  - vfprintf.c
  - writer.c
  - __atexit.c
  - mallocr.c
  - closer.c
  - fclose.c
  - fputwc.c
  - fstatr.c
  - isattyr.c
  - locale.c
  - lseekr.c
  - mbtowc_r.c
  - readr.c
  - wbuf.c
  - wcrtomb.c
  - wctomb_r.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crtn.o
  - impure.c
  - ctype_.c
  - reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000201: __do_global_dtors_aux
  0x8000225: frame_dummy
  0x8000241: __aeabi_frsub
  0x8000249:
  - __subsf3
  - __aeabi_fsub
  0x800024d:
  - __aeabi_fadd
  - __addsf3
  0x80003ad:
  - __aeabi_ui2f
  - __floatunsisf
  0x80003b5:
  - __aeabi_i2f
  - __floatsisf
  0x80003d1:
  - __floatundisf
  - __aeabi_ul2f
  0x80003e1:
  - __floatdisf
  - __aeabi_l2f
  0x800045d:
  - __mulsf3
  - __aeabi_fmul
  0x80005c5:
  - __divsf3
  - __aeabi_fdiv
  0x80006fd:
  - __gtsf2
  - __gesf2
  0x8000705:
  - __lesf2
  - __ltsf2
  0x800070d:
  - __nesf2
  - __eqsf2
  - __cmpsf2
  0x800076d: __aeabi_cfrcmple
  0x8000775:
  - __aeabi_cfcmple
  - __aeabi_cfcmpeq
  0x8000785: __aeabi_fcmpeq
  0x8000799: __aeabi_fcmplt
  0x80007ad: __aeabi_fcmple
  0x80007c1: __aeabi_fcmpge
  0x80007d5: __aeabi_fcmpgt
  0x80007e9:
  - __fixsfsi
  - __aeabi_f2iz
  0x8000835:
  - __aeabi_f2uiz
  - __fixunssfsi
  0x8000875: __aeabi_uldivmod
  0x80008a5: __udivmoddi4
  0x8000b71:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x8000b81: strlen
  0x8000c61: memchr
  0x8000d01: memcpy
  0x8000e35: __aeabi_drsub
  0x8000e3d:
  - __aeabi_dsub
  - __subdf3
  0x8000e41:
  - __adddf3
  - __aeabi_dadd
  0x80010b9:
  - __aeabi_ui2d
  - __floatunsidf
  0x80010d9:
  - __floatsidf
  - __aeabi_i2d
  0x80010fd:
  - __extendsfdf2
  - __aeabi_f2d
  0x8001141:
  - __aeabi_ul2d
  - __floatundidf
  0x8001151:
  - __floatdidf
  - __aeabi_l2d
  0x80011ad:
  - __aeabi_dmul
  - __muldf3
  0x8001401:
  - __aeabi_ddiv
  - __divdf3
  0x80015d1:
  - __gtdf2
  - __gedf2
  0x80015d9:
  - __ltdf2
  - __ledf2
  0x80015e1:
  - __cmpdf2
  - __eqdf2
  - __nedf2
  0x800165d: __aeabi_cdrcmple
  0x800166d:
  - __aeabi_cdcmple
  - __aeabi_cdcmpeq
  0x800167d: __aeabi_dcmpeq
  0x8001691: __aeabi_dcmplt
  0x80016a5: __aeabi_dcmple
  0x80016b9: __aeabi_dcmpge
  0x80016cd: __aeabi_dcmpgt
  0x80016e1:
  - __aeabi_dcmpun
  - __unorddf2
  0x800170d:
  - __fixdfsi
  - __aeabi_d2iz
  0x800175d: HAL_Init
  0x80017a1: HAL_InitTick
  0x8001801: HAL_IncTick
  0x8001825: HAL_GetTick
  0x8001839: HAL_Delay
  0x800184d: __NVIC_SetPriorityGrouping
  0x8001895: __NVIC_GetPriorityGrouping
  0x80018b1: __NVIC_EnableIRQ
  0x80018e9: __NVIC_SetPriority
  0x800193d: NVIC_EncodePriority
  0x80019a1: SysTick_Config
  0x80019e5: HAL_NVIC_SetPriorityGrouping
  0x80019fb: HAL_NVIC_SetPriority
  0x8001a33: HAL_NVIC_EnableIRQ
  0x8001a4f: HAL_SYSTICK_Config
  0x8001a69: HAL_SYSTICK_CLKSourceConfig
  0x8001aa1: HAL_SYSTICK_IRQHandler
  0x8001aad: HAL_SYSTICK_Callback
  0x8001ab9: HAL_DMA_Init
  0x8001c15: HAL_DMA_Start_IT
  0x8001cd5: HAL_DMA_Abort_IT
  0x8001d19: HAL_DMA_IRQHandler
  0x800202d: DMA_SetConfig
  0x8002089: DMA_CalcBaseAndBitshift
  0x80020f1: DMA_CheckFifoParam
  0x80021e5: HAL_FLASH_Program
  0x800228d: HAL_FLASH_Unlock
  0x80022d1: HAL_FLASH_Lock
  0x80022f1: FLASH_WaitForLastOperation
  0x8002371: FLASH_Program_DoubleWord
  0x80023cd: FLASH_Program_Word
  0x8002411: FLASH_Program_HalfWord
  0x8002455: FLASH_Program_Byte
  0x8002495: FLASH_SetErrorCode
  0x8002561: FLASH_Erase_Sector
  0x80025f1: HAL_GPIO_Init
  0x8002915: HAL_GPIO_WritePin
  0x8002945: HAL_GPIO_EXTI_IRQHandler
  0x8002975: HAL_GPIO_EXTI_Callback
  0x8002989: HAL_PWREx_EnableOverDrive
  0x8002a29: HAL_RCC_ClockConfig
  0x8002bed: HAL_RCC_GetHCLKFreq
  0x8002c01: HAL_RCC_GetPCLK1Freq
  0x8002c29: HAL_RCC_GetPCLK2Freq
  0x8002c51: HAL_RCCEx_PeriphCLKConfig
  0x80032a5: HAL_RCC_GetSysClockFreq
  0x80035e5: HAL_RCC_OscConfig
  0x8003a99: HAL_TIM_Base_Init
  0x8003aef: HAL_TIM_Base_Start_IT
  0x8003b35: HAL_TIM_PWM_Init
  0x8003b8b: HAL_TIM_PWM_MspInit
  0x8003b9d: HAL_TIM_PWM_Start
  0x8003c19: HAL_TIM_PWM_Stop
  0x8003cc9: HAL_TIM_PWM_ConfigChannel
  0x8003e55: HAL_TIM_ConfigClockSource
  0x8003fc5: TIM_Base_SetConfig
  0x8004101: TIM_OC1_SetConfig
  0x80041e1: TIM_OC2_SetConfig
  0x80042c9: TIM_OC3_SetConfig
  0x80043b1: TIM_OC4_SetConfig
  0x8004459: TIM_TI1_ConfigInputStage
  0x80044b5: TIM_TI2_ConfigInputStage
  0x8004513: TIM_ITRx_SetConfig
  0x8004547: TIM_ETR_SetConfig
  0x8004585: TIM_CCxChannelCmd
  0x80045cd: HAL_TIMEx_MasterConfigSynchronization
  0x8004655: HAL_TIMEx_ConfigBreakDeadTime
  0x80046f7: HAL_UART_Init
  0x8004791: HAL_UART_Transmit_DMA
  0x8004869: HAL_UART_Receive_DMA
  0x8004969: HAL_UART_IRQHandler
  0x8004b61: HAL_UART_TxHalfCpltCallback
  0x8004b73: HAL_UART_RxHalfCpltCallback
  0x8004b85: HAL_UART_ErrorCallback
  0x8004b97: UART_DMATransmitCplt
  0x8004be9: UART_DMATxHalfCplt
  0x8004c05: UART_DMAReceiveCplt
  0x8004c6d: UART_DMARxHalfCplt
  0x8004c89: UART_DMAError
  0x8004d1d: UART_EndTxTransfer
  0x8004d47: UART_EndRxTransfer
  0x8004d81: UART_DMAAbortOnError
  0x8004da9: UART_Transmit_IT
  0x8004e53: UART_EndTransmit_IT
  0x8004e83: UART_Receive_IT
  0x8004f85: UART_SetConfig
  0x8005399: aflCall
  0x80053a1: startForkserver
  0x80053d1: main
  0x800557d: SystemClock_Config
  0x8005675: MX_TIM1_Init
  0x800573d: MX_TIM2_Init
  0x80057c5: MX_TIM3_Init
  0x8005851: MX_TIM14_Init
  0x8005889: MX_USART2_UART_Init
  0x80058d1: MX_DMA_Init
  0x8005921: MX_GPIO_Init
  0x8005a31: TIM1_UP_TIM10_IRQHandler
  0x8005a69: TIM2_IRQHandler
  0x8005aa1: TIM3_IRQHandler
  0x8005ad9: TIM8_TRG_COM_TIM14_IRQHandler
  0x8005b1d: HAL_UART_TxCpltCallback
  0x8005be9: Serial_ExecutePendingTransmits
  0x8005ce1: HAL_UART_RxCpltCallback
  0x8005d49: Serial_InitRxSequence
  0x8005d89: Serial_CheckRxTimeout
  0x8005de9: GetParamValue
  0x8005e95: SetParamValue
  0x8005f09: PrintStepperStatusStr
  0x8005fcd: ExecuteRequest
  0x8006369: CleanupDecoder
  0x80063b5: DecodeCmd
  0x80064c1: DecodeStepper
  0x8006511: DecodeParam
  0x800664d: DecodeValue
  0x8006761: Decode
  0x80067d1: Serial_RxCallback
  0x80067ed: SetAccelerationByMinSPS
  0x8006941: SetStepTimerByCurrentSPS
  0x80069b5: DecrementSPS
  0x80069e5: IncrementSPS
  0x8006a15: GetState
  0x8006a6d: GetStepDirectionUnit
  0x8006a97: GetStepsToTarget
  0x8006ae5: Stepper_SetupPeripherals
  0x8006b85: Stepper_InitDefaultState
  0x8006c31: ExecuteController
  0x8006e65: Stepper_PulseTimerUpdate
  0x8006f75: Stepper_ExecuteAllControllers
  0x8006fb9: Stepper_SetTargetPosition
  0x8006fe9: Stepper_SetCurrentPosition
  0x8007031: Stepper_SetMinSPS
  0x80070d1: Stepper_SetMaxSPS
  0x8007169: Stepper_GetTargetPosition
  0x8007193: Stepper_GetCurrentPosition
  0x80071bd: Stepper_GetMinSPS
  0x80071e7: Stepper_GetMaxSPS
  0x8007211: Stepper_GetCurrentSPS
  0x800723b: Stepper_GetAccSPS
  0x8007265: Stepper_GetAccPrescaler
  0x800728f: Stepper_GetStatus
  0x80072bd: Stepper_LoadConfig
  0x8007395: Stepper_SaveConfig
  0x8007489: HAL_MspInit
  0x80074d5: HAL_TIM_Base_MspInit
  0x80075d5: HAL_TIM_MspPostInit
  0x8007679: HAL_UART_MspInit
  0x80077a1: NMI_Handler
  0x80077ad: HardFault_Handler
  0x80077b3: MemManage_Handler
  0x80077b9: BusFault_Handler
  0x80077bf: UsageFault_Handler
  0x80077c5: DebugMon_Handler
  0x80077cb: SysTick_Handler
  0x80077dd: DMA1_Stream5_IRQHandler
  0x80077f1: DMA1_Stream6_IRQHandler
  0x8007805: USART2_IRQHandler
  0x8007819: EXTI15_10_IRQHandler
  0x8007829: _read
  0x8007863: _write
  0x800789d: _sbrk
  0x80078f5: _close
  0x800790b: _fstat
  0x8007929: _isatty
  0x800793d: _lseek
  0x8007955: SystemInit
  0x80079b1: Reset_Handler
  0x80079b8: CopyDataInit
  0x80079c0: LoopCopyDataInit
  0x80079ce: FillZerobss
  0x80079d4: LoopFillZerobss
  0x8007a00:
  - Infinite_Loop
  - Default_Handler
  0x8007a01:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM8_CC_IRQHandler
  - FMPI2C1_EV_IRQHandler
  - SPI4_IRQHandler
  - TIM1_CC_IRQHandler
  - DMA2_Stream5_IRQHandler
  - PVD_IRQHandler
  - SDIO_IRQHandler
  - TAMP_STAMP_IRQHandler
  - PendSV_Handler
  - CAN2_RX1_IRQHandler
  - EXTI3_IRQHandler
  - TIM8_UP_TIM13_IRQHandler
  - I2C3_ER_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - DMA1_Stream2_IRQHandler
  - CAN1_RX0_IRQHandler
  - FPU_IRQHandler
  - OTG_HS_WKUP_IRQHandler
  - CAN2_SCE_IRQHandler
  - DMA2_Stream2_IRQHandler
  - SPI1_IRQHandler
  - TIM6_DAC_IRQHandler
  - TIM1_BRK_TIM9_IRQHandler
  - DCMI_IRQHandler
  - CAN2_RX0_IRQHandler
  - DMA2_Stream3_IRQHandler
  - SAI2_IRQHandler
  - USART6_IRQHandler
  - USART3_IRQHandler
  - CAN1_RX1_IRQHandler
  - UART5_IRQHandler
  - DMA2_Stream0_IRQHandler
  - TIM4_IRQHandler
  - QUADSPI_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Stream1_IRQHandler
  - UART4_IRQHandler
  - RCC_IRQHandler
  - TIM8_BRK_TIM12_IRQHandler
  - CEC_IRQHandler
  - ADC_IRQHandler
  - DMA1_Stream7_IRQHandler
  - TIM7_IRQHandler
  - CAN2_TX_IRQHandler
  - TIM5_IRQHandler
  - DMA2_Stream7_IRQHandler
  - I2C3_EV_IRQHandler
  - EXTI9_5_IRQHandler
  - RTC_WKUP_IRQHandler
  - SPDIF_RX_IRQHandler
  - SPI2_IRQHandler
  - OTG_HS_EP1_IN_IRQHandler
  - DMA1_Stream0_IRQHandler
  - CAN1_TX_IRQHandler
  - SVC_Handler
  - FMPI2C1_ER_IRQHandler
  - EXTI4_IRQHandler
  - OTG_HS_EP1_OUT_IRQHandler
  - WWDG_IRQHandler
  - OTG_FS_WKUP_IRQHandler
  - TIM1_TRG_COM_TIM11_IRQHandler
  - OTG_HS_IRQHandler
  - EXTI1_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA2_Stream1_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - DMA2_Stream4_IRQHandler
  - USART1_IRQHandler
  - OTG_FS_IRQHandler
  - SPI3_IRQHandler
  - DMA1_Stream4_IRQHandler
  - I2C1_ER_IRQHandler
  - FMC_IRQHandler
  - DMA2_Stream6_IRQHandler
  - SAI1_IRQHandler
  - DMA1_Stream3_IRQHandler
  0x8007a05: __errno
  0x8007a11: __libc_init_array
  0x8007a59: memset
  0x8007aed: printf
  0x8007b15: _puts_r
  0x8007bb1: puts
  0x8007bc1: _vfprintf_r
  0x8009641: __sbprintf
  0x80096c5: __swsetup_r
  0x8009791: register_fini
  0x80097a5: atexit
  0x80097b1: quorem
  0x80098d9: _dtoa_r
  0x800a6cd: __sflush_r
  0x800a821: _fflush_r
  0x800a87d: std
  0x800a8cd: _cleanup_r
  0x800a8d9: __sinit
  0x800a931: __sfp_lock_acquire
  0x800a93d: __sfp_lock_release
  0x800a949: __libc_fini_array
  0x800a97d: _malloc_trim_r
  0x800aa1d: _free_r
  0x800ac05: __sfvwrite_r
  0x800af01: _fwalk_reent
  0x800af55: _localeconv_r
  0x800af71: __retarget_lock_init_recursive
  0x800af75: __retarget_lock_close_recursive
  0x800af79: __retarget_lock_acquire_recursive
  0x800af7d: __retarget_lock_release_recursive
  0x800af81: __swhatbuf_r
  0x800afdd: __smakebuf_r
  0x800b071: _malloc_r
  0x800b5b9: memmove
  0x800b681: __malloc_lock
  0x800b68d: __malloc_unlock
  0x800b699: _Balloc
  0x800b6e5: _Bfree
  0x800b6f9: __multadd
  0x800b779: __hi0bits
  0x800b7b9: __lo0bits
  0x800b819: __i2b
  0x800b82d: __multiply
  0x800b979: __pow5mult
  0x800ba19: __lshift
  0x800bac5: __mcmp
  0x800bafd: __mdiff
  0x800bbe9: __d2b
  0x800bc99: _realloc_r
  0x800bff5: frexp
  0x800c059: _sbrk_r
  0x800c07d: __sread
  0x800c0a1: __swrite
  0x800c0dd: __sseek
  0x800c0fd: __sclose
  0x800c105: strncpy
  0x800c169: __sprint_r.part.0
  0x800c1e1: __sprint_r
  0x800c1f5: _write_r
  0x800c221: __register_exitproc
  0x800c2e1: _calloc_r
  0x800c349: _close_r
  0x800c36d: _fclose_r
  0x800c43d: __fputwc
  0x800c4dd: _fputwc_r
  0x800c541: _fstat_r
  0x800c569: _isatty_r
  0x800c58d: __locale_mb_cur_max
  0x800c5a9: _lseek_r
  0x800c5d5: __ascii_mbtowc
  0x800c601: _read_r
  0x800c62d: __swbuf_r
  0x800c6dd: _wcrtomb_r
  0x800c72d: __ascii_wctomb
  0x800c748: __EH_FRAME_BEGIN__
  0x800c749: _init
  0x800c755: _fini
  0x800c760:
  - flagBitshiftOffset.10402
  - _etext
  0x800caa8: INT32_OVERFLOW.10959
  0x800cabc: AHBPrescTable
  0x800cacc: APBPrescTable
  0x800cad4: _global_impure_ptr
  0x800cb20: blanks.7330
  0x800cb30: zeroes.7331
  0x800cb50: __mprec_bigtens
  0x800cb78: __mprec_tens
  0x800cc40: p05.6092
  0x800cc5c: _ctype_
  0x800cd60: __exidx_start
  0x800cd68:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  0x800cd6c: __frame_dummy_init_array_entry
  0x800cd70:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x800cd74:
  - __fini_array_end
  - _sidata
  0x20000000:
  - _sdata
  - uwTickPrio
  0x20000004: uwTickFreq
  0x20000008: TX_OVERFLOW_MSG
  0x2000000c: txOutPtr
  0x20000010: txInPtr
  0x20000014: rxPtr
  0x20000018: request_commands_arry
  0x2000002c: request_params_arry
  0x20000054: filteredItems
  0x20000058: SystemCoreClock
  0x2000005c: _impure_ptr
  0x20000060: impure_data
  0x20000488: __atexit_recursive_mutex
  0x2000048c: __malloc_av_
  0x20000894: __malloc_sbrk_base
  0x20000898: __malloc_trim_threshold
  0x2000089c: __global_locale
  0x20000a08:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x20000a0c: object.8660
  0x20000a24: noHyperCall
  0x20000a28: txBuffer
  0x20000e28: rxBuffer
  0x20001228: syncLock
  0x2000122c: txInSnapshot
  0x20001230: serialStatus
  0x20001238: currentReqField
  0x2000123c: currentReqFieldIndex
  0x20001240: req
  0x20001258: steppers
  0x200014b0: initializedSteppersCount
  0x200014b4: __env
  0x200014b8: heap_end.5959
  0x200014bc: __malloc_current_mallinfo
  0x200014e4: __malloc_max_sbrked_mem
  0x200014e8: __malloc_max_total_mem
  0x200014ec: __malloc_top_pad
  0x200014f0: uwTick
  0x200014f4: pFlash
  0x20001514: hdma_usart2_rx
  0x20001574: htim3
  0x200015b4: hdma_usart2_tx
  0x20001614: STEP_CONTROLLER_PERIOD_US
  0x20001618: htim1
  0x20001658: STEP_TIMER_CLOCK
  0x2000165c: htim2
  0x2000169c: huart2
  0x200016dc: htim14
  0x2000171c: __lock___atexit_recursive_mutex
  0x20001720: __lock___arc4random_mutex
  0x20001724: __lock___env_recursive_mutex
  0x20001728: __lock___sinit_recursive_mutex
  0x2000172c: __lock___malloc_recursive_mutex
  0x20001730: __lock___at_quick_exit_mutex
  0x20001734: __lock___dd_hash_mutex
  0x20001738: __lock___tz_mutex
  0x2000173c: __lock___sfp_recursive_mutex
  0x20001740: errno
  0x20001744:
  - _ebss
  - __bss_end__
  0x20001748: end
  0x20020000: _estack
