interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103-RIOT-SPI.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12418
symbols:
  0x0:
  - vectors_cortexm.c
  - vectors.c
  - syscalls.c
  - sched.c
  - thread_arch.c
  - irq_arch.c
  - stdio_uart.c
  - pm.c
  - uart.c
  - board.c
  - panic.c
  - kernel_init.c
  - thread.c
  - gpio.c
  - pm.c
  - stmclk.c
  - stmclk_common.c
  - cpu_init.c
  - cpu_common.c
  - init.c
  - main.c
  - auto_init.c
  - cortexm_init.c
  - spi.c
  - spi.c
  - mutex.c
  - init.c
  - nano-mallocr.c
  - printf.c
  - puts.c
  - wbuf.c
  - wsetup.c
  - fflush.c
  - findfp.c
  - fwalk.c
  - lock.c
  - makebuf.c
  - memset.c
  - mlock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - stdio.c
  - memchr-stub.c
  - impure.c
  - _sbackup_bss
  - _rom_offset
  - _backup_ram_len
  - ccmram_length
  - _backup_ram_start_addr
  - _ebackup_data
  - _ebackup_bss
  - _sbackup_data
  0x5000: _ram_length
  0x20000:
  - _rom_length
  - _fw_rom_length
  0x8000000:
  - _rom_start_addr
  - _sfixed
  - _isr_vectors
  - cortex_vector_base
  0x8000040: vector_cpu
  0x80000ed:
  - isr_pvd
  - isr_usb_lp_can1_rx0
  - isr_dma1_channel4
  - isr_exti
  - isr_tim7
  - isr_tim5
  - isr_i2c1_ev
  - isr_tim1_brk
  - isr_dma1_channel5
  - isr_tim4
  - isr_dma1_channel2
  - isr_adc3
  - isr_can1_sce
  - isr_dma1_channel7
  - isr_usb_hp_can1_tx
  - isr_tim1_up
  - isr_tim2
  - isr_sdio
  - isr_spi2
  - isr_tim1_trg_com
  - isr_dma1_channel1
  - dummy_handler
  - isr_adc1_2
  - isr_can1_rx1
  - isr_fsmc
  - isr_spi1
  - isr_tim6
  - isr_rcc
  - isr_flash
  - isr_uart5
  - isr_rtc
  - isr_tim1_cc
  - isr_usbwakeup
  - isr_dma2_channel1
  - isr_uart4
  - isr_tim8_brk
  - isr_i2c2_er
  - isr_dma2_channel4_5
  - isr_dma1_channel6
  - isr_spi3
  - isr_tim3
  - isr_tim8_up
  - isr_tim8_cc
  - isr_i2c2_ev
  - isr_dma2_channel2
  - isr_dma2_channel3
  - isr_rtc_alarm
  - isr_tamper
  - isr_dma1_channel3
  - isr_tim8_trg_com
  - isr_i2c1_er
  - isr_wwdg
  0x80000f1: _init
  0x80000f3: _fini
  0x80000f5: _sbrk_r
  0x8000131: _read_r
  0x8000139: _write_r
  0x8000141: _close_r
  0x800014b: _lseek_r
  0x8000155: _fstat_r
  0x800015f: _isatty_r
  0x800016d: sched_run
  0x80001d1: sched_set_status
  0x8000251: sched_switch
  0x8000281: sched_task_exit
  0x80002bd: thread_stack_init
  0x8000325: cpu_switch_context_exit
  0x800032a: unreachable329
  0x800032d: thread_yield_higher
  0x800033d: isr_pendsv
  0x8000359: isr_svc
  0x800035d: context_restore
  0x8000375: hard_fault_default
  0x8000388: fix_msp
  0x800038e: test_sp
  0x800039c: use_psp
  0x80003a0: out
  0x80003b9: nmi_default
  0x80003c9: mem_manage_default
  0x80003d9: bus_fault_default
  0x80003e9: usage_fault_default
  0x80003f9: debug_mon_default
  0x8000409:
  - dummy_handler_default
  - isr_systick
  0x8000419: pre_startup
  0x800041b: post_startup
  0x800041d: reset_handler_default
  0x8000489: hard_fault_handler
  0x8000611: irq_disable
  0x8000619: irq_enable
  0x8000621: irq_restore
  0x8000627: irq_is_in
  0x800062f: stdio_init
  0x800063d: stdio_read
  0x8000643: stdio_write
  0x8000655: pm_off
  0x8000659: uart_enable_clock
  0x8000689: irq_handler
  0x80006d1: uart_init
  0x8000791: uart_write
  0x80007d1: isr_usart2
  0x80007d7: isr_usart1
  0x80007dd: isr_usart3
  0x80007e3: board_init
  0x80007e7: panic_arch
  0x80007e9: core_panic
  0x800082d: main_trampoline
  0x8000845: idle_thread
  0x800084d: kernel_init
  0x80008a5: thread_add_to_list
  0x80008d5: thread_create
  0x80009cd: gpio_init
  0x8000a61: gpio_init_af
  0x8000aa5: gpio_set
  0x8000ab7: gpio_clear
  0x8000ac9: pm_set_lowest
  0x8000ae1: pm_block
  0x8000b11: pm_unblock
  0x8000b41: stmclk_init_sysclk
  0x8000bc1: stmclk_enable_hsi
  0x8000bd9: stmclk_disable_hsi
  0x8000bf1: cpu_init
  0x8000c91: periph_apb_clk
  0x8000ca9: periph_clk_en
  0x8000cd9: periph_clk_dis
  0x8000d0d: periph_init
  0x8000d21: main
  0x8000d61: auto_init
  0x8000d65: cortexm_init
  0x8000da5: spi_init_pins
  0x8000dd1: spi_init
  0x8000e29: spi_acquire
  0x8000ea5: spi_release
  0x8000ee5: spi_transfer_bytes
  0x8000fc5: spi_transfer_byte
  0x8000fe9: _mutex_lock
  0x8001049: mutex_unlock
  0x8001095: __libc_init_array
  0x80010dd: _malloc_r
  0x8001191:
  - printf
  - iprintf
  0x80011c1: _puts_r
  0x800129d: puts
  0x80012ad: __swbuf_r
  0x8001351: __swsetup_r
  0x800142d: __sflush_r
  0x8001539: _fflush_r
  0x80015b1: std
  0x80015f9: _cleanup_r
  0x8001605: __sfmoreglue
  0x8001631: __sfp_lock_acquire
  0x800163d: __sfp_lock_release
  0x8001649: __sinit_lock_acquire
  0x8001655: __sinit_lock_release
  0x8001661: __sinit
  0x80016d1: __sfp
  0x800175d: _fwalk_reent
  0x800179b: __retarget_lock_init_recursive
  0x800179d: __retarget_lock_acquire_recursive
  0x800179f: __retarget_lock_release_recursive
  0x80017a1: __swhatbuf_r
  0x80017e9: __smakebuf_r
  0x8001869: memset
  0x8001879: __malloc_lock
  0x8001885: __malloc_unlock
  0x8001891: _free_r
  0x8001929: __sfputc_r
  0x8001953: __sfputs_r
  0x8001979:
  - _vfiprintf_r
  - _vfprintf_r
  0x8001bd9: _printf_common
  0x8001cb9: _printf_i
  0x8001f05: __sread
  0x8001f27: __swrite
  0x8001f5f: __sseek
  0x8001f83: __sclose
  0x8001f8b: memchr
  0x8002200: uart_config
  0x800226a: assert_crash_message
  0x80022c4: spi_config
  0x80022fc: spi_divtable
  0x8002308: _global_impure_ptr
  0x800230c: __sf_fake_stderr
  0x800232c: __sf_fake_stdin
  0x800234c: __sf_fake_stdout
  0x80023a0:
  - _etext
  - __fini_array_end
  - __fini_array_start
  - __init_array_end
  - _efixed
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x8002418: _sbackup_data_load
  0x20000000:
  - _ram_start_addr
  - _sstack
  - _sram
  - isr_stack
  0x20000200:
  - _srelocate
  - heap_top
  - _estack
  0x20000204: idle_name
  0x20000208: main_name
  0x2000020c: pm_blocker
  0x20000210: _impure_ptr
  0x20000214: impure_data
  0x20000274: _tcb_name_offset
  0x20000275: max_threads
  0x20000278:
  - runqueue_bitcache
  - _sbss
  - _szero
  - _erelocate
  0x2000027c: sched_active_pid
  0x20000280: sched_active_thread
  0x20000284: sched_context_switch_request
  0x20000288: sched_num_threads
  0x2000028c: sched_runqueues
  0x200002cc: sched_threads
  0x20000350: isr_ctx
  0x20000374: crashed
  0x20000378: idle_stack
  0x20000478: main_stack
  0x20000a78: dRX
  0x20000a79: dTX
  0x20000a7c: locks
  0x20000a84: __malloc_free_list
  0x20000a88: __malloc_sbrk_start
  0x20000a8c: __lock___atexit_recursive_mutex
  0x20000a8d: __lock___arc4random_mutex
  0x20000a8e: __lock___env_recursive_mutex
  0x20000a8f: __lock___sinit_recursive_mutex
  0x20000a90: __lock___malloc_recursive_mutex
  0x20000a91: __lock___at_quick_exit_mutex
  0x20000a92: __lock___dd_hash_mutex
  0x20000a93: __lock___tz_mutex
  0x20000a94: __lock___sfp_recursive_mutex
  0x20000a98:
  - _sheap
  - _ebss
  - _ezero
  - __noinit_start
  - __noinit_end
  0x20005000:
  - _eram
  - _eheap
