interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .stack:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0xa7c
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: K64F-RIOT-ADC.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x128f8
symbols:
  0x0:
  - vectors_cortexm.c
  - vectors.c
  - isr_kinetis.c
  - fcfield.c
  - syscalls.c
  - sched.c
  - thread_arch.c
  - irq_arch.c
  - wdog.c
  - stdio_uart.c
  - pm.c
  - board.c
  - panic.c
  - kernel_init.c
  - thread.c
  - pm.c
  - cpu.c
  - uart.c
  - mcg.c
  - gpio.c
  - init.c
  - main.c
  - auto_init.c
  - cortexm_init.c
  - spi.c
  - adc.c
  - mutex.c
  - init.c
  - nano-mallocr.c
  - printf.c
  - puts.c
  - wbuf.c
  - wsetup.c
  - fflush.c
  - findfp.c
  - fwalk.c
  - lock.c
  - makebuf.c
  - memset.c
  - mlock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - stdio.c
  - lib_a-memchr.o
  - impure.c
  - _rom_start_addr
  - _sbackup_bss
  - _rom_offset
  - _backup_ram_len
  - _isr_vectors
  - _backup_ram_start_addr
  - cortex_vector_base
  - _ebackup_data
  - _ebackup_bss
  - _sbackup_data
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400:
  - _flash_sec_offset
  - flash_configuration_field
  - _vectors_length
  0x410: _sfixed
  0x411: _init
  0x413: _fini
  0x415: _sbrk_r
  0x451: _read_r
  0x459: _write_r
  0x461: _close_r
  0x46b: _lseek_r
  0x475: _fstat_r
  0x47f: _isatty_r
  0x491: sched_run
  0x4f5: sched_set_status
  0x575: sched_switch
  0x5a5: sched_task_exit
  0x5e1: thread_stack_init
  0x649: cpu_switch_context_exit
  0x64e: unreachable325
  0x651: thread_yield_higher
  0x661: isr_pendsv
  0x67d: isr_svc
  0x681: context_restore
  0x699: hard_fault_default
  0x6ac: fix_msp
  0x6b2: test_sp
  0x6c0: use_psp
  0x6c4: out
  0x6dd: nmi_default
  0x6ed: mem_manage_default
  0x6fd: bus_fault_default
  0x70d: usage_fault_default
  0x71d: debug_mon_default
  0x72d:
  - dummy_handler_default
  - isr_systick
  0x73d: post_startup
  0x741: reset_handler_default
  0x7ad: hard_fault_handler
  0x935: irq_disable
  0x93d: irq_enable
  0x945: irq_restore
  0x94b: irq_is_in
  0x955: pre_startup
  0x969:
  - isr_uart3
  - isr_cmp1
  - isr_i2c1
  - isr_dma5_dma21
  - isr_portb_portc
  - isr_dac0
  - isr_can0_bus_off
  - isr_enet_transmit
  - isr_dma5
  - isr_lpuart5
  - isr_dma8
  - isr_porta
  - isr_ftm3
  - isr_dma3_dma19
  - isr_can0_wake_up
  - isr_adc0
  - isr_portb
  - isr_ftfe_collision
  - isr_cmp3
  - isr_i2c0
  - isr_pit1
  - isr_dac1
  - isr_spi0
  - isr_dma15_dma31
  - isr_dma6_dma22
  - isr_enet_receive
  - isr_llwu
  - isr_lpuart2
  - isr_i2c3
  - isr_dma0
  - isr_can1_error
  - isr_mcg
  - isr_dma14_dma30
  - isr_i2s0_rx
  - isr_tpm1
  - isr_ftfa
  - isr_dma_error
  - isr_ftfa_collision
  - isr_uart2
  - isr_usbhs
  - isr_uart3_rx_tx
  - isr_enet_1588_timer
  - isr_ftfl_collision
  - isr_dma3
  - isr_dma11_dma27
  - isr_ftfl
  - isr_can0_error
  - isr_tpm0
  - isr_dma2_dma18
  - isr_can0_ored_message_buffer
  - isr_dma2
  - isr_usb0
  - isr_i2c2
  - isr_uart2_rx_tx
  - isr_pit2
  - isr_dma7_dma23
  - isr_dma14
  - isr_cmp0
  - isr_spi2
  - isr_uart0
  - isr_dma9
  - isr_dma7
  - dummy_handler
  - isr_can1_rx_warning
  - isr_ftfe
  - isr_uart1
  - isr_uart0_lon
  - isr_uart4_err
  - isr_usbhsdcd
  - isr_dma10_dma26
  - isr_radio_0
  - isr_swi
  - isr_cmp2
  - isr_dma10
  - isr_spi1
  - isr_lpuart0
  - isr_portd
  - isr_uart1_rx_tx
  - isr_can1_bus_off
  - isr_uart5
  - isr_adc2
  - isr_tpm2
  - isr_mscan_tx
  - isr_rtc
  - isr_ftm0
  - isr_dma11
  - isr_lpuart1
  - isr_dma13_dma29
  - isr_mscan_rx
  - isr_porte
  - isr_mcm
  - isr_pit
  - isr_uart5_err
  - isr_radio_1
  - isr_dma4
  - isr_dma12_dma28
  - isr_dma12
  - isr_can0_rx_warning
  - isr_tsi0
  - isr_adc1
  - isr_i2s0_tx
  - isr_uart4
  - isr_sdhc
  - isr_dma6
  - isr_uart3_err
  - isr_dma15
  - isr_ftm2
  - isr_lptmr0
  - isr_dma0_dma16
  - isr_pit0
  - isr_portc
  - isr_can1_ored_message_buffer
  - isr_rtc_seconds
  - isr_can0_tx_warning
  - isr_cmt
  - isr_dma4_dma20
  - isr_can1_wake_up
  - isr_trng0
  - isr_lpuart4
  - isr_rng
  - isr_uart1_err
  - isr_enet_error
  - isr_can1_tx_warning
  - isr_usbdcd
  - isr_dma1_dma17
  - isr_uart4_rx_tx
  - isr_uart0_err
  - isr_uart5_rx_tx
  - isr_ftm1
  - isr_dma9_dma25
  - isr_dma13
  - isr_uart2_err
  - isr_pdb0
  - isr_dma1
  - isr_lpuart3
  - isr_lvd_lvw
  - isr_pit3
  - isr_dma8_dma24
  - isr_wdog_ewm
  0x96d: wdog_disable
  0x985: stdio_init
  0x993: stdio_read
  0x999: stdio_write
  0x9ab: pm_off
  0x9b5: board_init
  0xa19: panic_arch
  0xa1d: core_panic
  0xa61: main_trampoline
  0xa79: idle_thread
  0xa81: kernel_init
  0xad9: thread_add_to_list
  0xb09: thread_create
  0xbfd: pm_set_lowest
  0xc01: cpu_init
  0xc25: uart_init
  0xce1: uart_write
  0xd01: isr_uart0_rx_tx
  0xd35: bit_clear8
  0xd55: kinetis_mcg_set_fll_factor
  0xd69: kinetis_mcg_enable_osc
  0xd89: kinetis_mcg_set_mode
  0xf09: kinetis_mcg_init
  0x100d: gpio_init_port
  0x1039: gpio_init
  0x1085: gpio_set
  0x109f: periph_init
  0x10a5: main
  0x10bd: auto_init
  0x10c1: cortexm_init
  0x1101: poweron
  0x114d: poweroff
  0x1199: spi_init_pins
  0x11c5: spi_init
  0x1209: done
  0x1255: prep
  0x12a1: kinetis_adc_calibrate
  0x1309: adc_init
  0x135d: adc_sample
  0x13a9: _mutex_lock
  0x1409: mutex_unlock
  0x1455: __libc_init_array
  0x149d: _malloc_r
  0x1551:
  - printf
  - iprintf
  0x1581: _puts_r
  0x165d: puts
  0x166d: __swbuf_r
  0x1711: __swsetup_r
  0x17ed: __sflush_r
  0x18f9: _fflush_r
  0x1971: std
  0x19b9: _cleanup_r
  0x19c5: __sfmoreglue
  0x19f1: __sfp_lock_acquire
  0x19fd: __sfp_lock_release
  0x1a09: __sinit_lock_acquire
  0x1a15: __sinit_lock_release
  0x1a21: __sinit
  0x1a91: __sfp
  0x1b1d: _fwalk_reent
  0x1b5b: __retarget_lock_init_recursive
  0x1b5d: __retarget_lock_acquire_recursive
  0x1b5f: __retarget_lock_release_recursive
  0x1b61: __swhatbuf_r
  0x1ba9: __smakebuf_r
  0x1c29: memset
  0x1c39: __malloc_lock
  0x1c45: __malloc_unlock
  0x1c51: _free_r
  0x1ced: __sfputc_r
  0x1d17: __sfputs_r
  0x1d3d:
  - _vfiprintf_r
  - _vfprintf_r
  0x1f9d: _printf_common
  0x2079: _printf_i
  0x22c5: __sread
  0x22e7: __swrite
  0x231f: __sseek
  0x2343: __sclose
  0x2351: memchr
  0x2677: assert_crash_message
  0x26d0: uart_config
  0x26f0: mcg_mode_routing
  0x2730: spi_config
  0x274c: adc_config
  0x27ec: _global_impure_ptr
  0x27f0: __sf_fake_stderr
  0x2810: __sf_fake_stdin
  0x2830: __sf_fake_stdout
  0x2884:
  - _etext
  - __fini_array_end
  - __fini_array_start
  - __init_array_end
  - _efixed
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x28f8: _sbackup_data_load
  0x40000: _ram_length
  0x100000:
  - _rom_length
  - _fw_rom_length
  0x1fff0000:
  - _ram_start_addr
  - _sstack
  - _sram
  - isr_stack
  0x1fff0200:
  - _srelocate
  - heap_top
  - _estack
  0x1fff0204: idle_name
  0x1fff0208: main_name
  0x1fff020c: _impure_ptr
  0x1fff0210: impure_data
  0x1fff0270: _tcb_name_offset
  0x1fff0271: max_threads
  0x1fff0274:
  - runqueue_bitcache
  - _sbss
  - _szero
  - _erelocate
  0x1fff0278: sched_active_pid
  0x1fff027c: sched_active_thread
  0x1fff0280: sched_context_switch_request
  0x1fff0284: sched_num_threads
  0x1fff0288: sched_runqueues
  0x1fff02c8: sched_threads
  0x1fff034c: crashed
  0x1fff0350: idle_stack
  0x1fff0450: main_stack
  0x1fff0a50: config
  0x1fff0a58: current_mode
  0x1fff0a5c: locks
  0x1fff0a60: locks
  0x1fff0a68: __malloc_free_list
  0x1fff0a6c: __malloc_sbrk_start
  0x1fff0a70: __lock___atexit_recursive_mutex
  0x1fff0a71: __lock___arc4random_mutex
  0x1fff0a72: __lock___env_recursive_mutex
  0x1fff0a73: __lock___sinit_recursive_mutex
  0x1fff0a74: __lock___malloc_recursive_mutex
  0x1fff0a75: __lock___at_quick_exit_mutex
  0x1fff0a76: __lock___dd_hash_mutex
  0x1fff0a77: __lock___tz_mutex
  0x1fff0a78: __lock___sfp_recursive_mutex
  0x1fff0a7c:
  - _sheap
  - _ebss
  - _ezero
  - __noinit_start
  - __noinit_end
  0x20030000:
  - _eram
  - _eheap
