interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_ChibiOS_acelerometer.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x146b0
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - _arm_addsubdf3.o
  - _arm_muldivdf3.o
  - _arm_truncdfsf2.o
  - _arm_addsubsf3.o
  - _arm_muldivsf3.o
  - _arm_cmpsf2.o
  - _arm_unordsf2.o
  - lib_a-memcpy.o
  - wf_sqrt.c
  - ef_sqrt.c
  - s_matherr.c
  - errno.c
  - s_lib_ver.c
  - impure.c
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __ram4_start__
  - __flash7_free__
  - __ram5_clear__
  - __ram1_free__
  - __ram6_start__
  - __ram5_end__
  - __ram5_noinit__
  - __flash1_free__
  - __ram5_size__
  - __flash7_size__
  - __flash4_free__
  - __ram1_size__
  - __flash3_free__
  - __ram1_clear__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __ram4_size__
  - __ram1_end__
  - __ram4_end__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __ram4_clear__
  - __ram5_free__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __ram2_noinit__
  - __flash3_start__
  - __ram6_noinit__
  - __ram4_init__
  - __ram7_clear__
  - __ram7_size__
  - __ram4_noinit__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram2_clear__
  - __ram3_end__
  - __ram2_size__
  - __ram1_start__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __ram1_noinit__
  - __flash2_size__
  - __flash4_end__
  - __ram2_init__
  - __ram2_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram2_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __ram5_init__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __ram1_init__
  - __ram5_start__
  - __flash6_size__
  - __ram2_free__
  - __ram4_free__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x5000: __ram0_size__
  0x748c: crt1.c.c94fd8ad
  0x77e9: hal.c.157d53b2
  0x8cd1: hal_st.c.3c40b827
  0xa3e6: hal_buffers.c.82bca721
  0xc90c: hal_queues.c.81e80a5d
  0xec4b: hal_i2c.c.1d64ef9b
  0x1041f: hal_pal.c.ea48c21f
  0x11b5d: hal_serial.c.4c7e3148
  0x1351b: nvic.c.2cd99a91
  0x14d6f: stm32_isr.c.89aca5f8
  0x16500: hal_lld.c.bcd6acac
  0x17b60: stm32_dma.c.7ab8f58c
  0x19436: hal_pal_lld.c.a447ca02
  0x1ad3f: hal_i2c_lld.c.74a1552e
  0x1cb64: hal_st_lld.c.8e540c83
  0x1e305: hal_serial_lld.c.f862ff7f
  0x1fae9: board.c.4035dec0
  0x20000: __flash0_size__
  0x20fd8: chsys.c.d21735e6
  0x227c9: chdebug.c.98495075
  0x2343e: chtrace.c.144c007e
  0x244cc: chvt.c.d4d90169
  0x253aa: chschd.c.137c6836
  0x26305: chthreads.c.39301f6d
  0x2790e: chtm.c.202a8ce0
  0x28791: chregistry.c.e7ed54db
  0x29d6c: chmtx.c.d93473d9
  0x2acc2: chevents.c.2a66560a
  0x2be00: chdynamic.c.108c6072
  0x2ccad: chmemcore.c.27126ccb
  0x2d9d9: chmemheaps.c.b2e3160f
  0x2e8a3: chmempools.c.f14598d7
  0x2f822: chfactory.c.874756bb
  0x316f1: chcore_v7m.c.22234a96
  0x325ba: lsm303dlhc.c.30c2cbd7
  0x347ed: main.c.d14a6da2
  0x366e5: lis3.c.973e988b
  0x385f5: fake.c.a804a948
  0x8000000:
  - _vectors
  - __flash0_start__
  0x8000160:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x8000161: _crt0_entry
  0x8000194: msloop
  0x80001a2: psloop
  0x80001b2: dloop
  0x80001c6: bloop
  0x80001dc: initloop
  0x80001e8: endinitloop
  0x80001f0: finiloop
  0x80001fc: endfiniloop
  0x8000239: Reset_Handler
  0x800023b:
  - VectorE8
  - VectorAC
  - DebugMon_Handler
  - Vector11C
  - HardFault_Handler
  - Vector8C
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - Vector110
  - Vector120
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - Vector150
  - Vector124
  - Vector148
  - Vector118
  - VectorCC
  - Vector54
  - Vector98
  - VectorD8
  - Vector138
  - Vector24
  - VectorD0
  - Vector140
  - VectorE4
  - Vector158
  - Vector130
  - Vector134
  - VectorF0
  - Vector12C
  - Vector13C
  - Vector100
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector90
  - Vector114
  - Vector1C
  - Vector48
  - VectorD4
  - Vector4C
  - Vector144
  - Vector15C
  - Vector88
  - Vector104
  - Vector10C
  - Vector14C
  - BusFault_Handler
  - Vector50
  - Vector154
  - Vector44
  - Vector28
  - VectorB8
  - VectorFC
  - Vector34
  - Vector128
  - VectorA4
  - Vector20
  0x800023e: .stay
  0x800023f: _unhandled_exception
  0x8000241: _port_switch
  0x8000251: _port_thread_start
  0x8000265: _port_switch_from_isr
  0x8000270: _port_exit_from_isr
  0x8000275: __aeabi_drsub
  0x800027d:
  - __aeabi_dsub
  - __subdf3
  0x8000281:
  - __adddf3
  - __aeabi_dadd
  0x80004f9:
  - __aeabi_ui2d
  - __floatunsidf
  0x8000519:
  - __floatsidf
  - __aeabi_i2d
  0x800053d:
  - __extendsfdf2
  - __aeabi_f2d
  0x8000581:
  - __aeabi_ul2d
  - __floatundidf
  0x8000591:
  - __floatdidf
  - __aeabi_l2d
  0x80005ed:
  - __aeabi_dmul
  - __muldf3
  0x8000841:
  - __aeabi_ddiv
  - __divdf3
  0x8000a11:
  - __aeabi_d2f
  - __truncdfsf2
  0x8000ab1: __aeabi_frsub
  0x8000ab9:
  - __subsf3
  - __aeabi_fsub
  0x8000abd:
  - __aeabi_fadd
  - __addsf3
  0x8000c1d:
  - __aeabi_ui2f
  - __floatunsisf
  0x8000c25:
  - __aeabi_i2f
  - __floatsisf
  0x8000c41:
  - __floatundisf
  - __aeabi_ul2f
  0x8000c51:
  - __floatdisf
  - __aeabi_l2f
  0x8000ccd:
  - __mulsf3
  - __aeabi_fmul
  0x8000e35:
  - __divsf3
  - __aeabi_fdiv
  0x8000f6d:
  - __gtsf2
  - __gesf2
  0x8000f75:
  - __lesf2
  - __ltsf2
  0x8000f7d:
  - __nesf2
  - __eqsf2
  - __cmpsf2
  0x8000fdd: __aeabi_cfrcmple
  0x8000fe5:
  - __aeabi_cfcmple
  - __aeabi_cfcmpeq
  0x8000ff5: __aeabi_fcmpeq
  0x8001009: __aeabi_fcmplt
  0x800101d: __aeabi_fcmple
  0x8001031: __aeabi_fcmpge
  0x8001045: __aeabi_fcmpgt
  0x8001059:
  - __aeabi_fcmpun
  - __unordsf2
  0x8001085: memcpy
  0x8001171: chTMStartMeasurementX.constprop.0
  0x8001181: notify3
  0x8001191: _port_irq_epilogue
  0x80011f1: chTMStopMeasurementX
  0x8001241: trace_next
  0x8001281: _trace_switch.part.0
  0x80012a1: _trace_isr_leave
  0x80012d1: _trace_isr_enter
  0x8001301: chSysHalt
  0x8001331: i2c_lld_serve_tx_end_irq
  0x8001371: chDbgCheckClassS
  0x8001391: chDbgCheckClassI
  0x80013b1: dmaStreamAllocI.constprop.0
  0x8001481: chCoreAllocAlignedWithOffsetI
  0x80014d1: chCoreAllocAlignedI
  0x80014e1: chSchReadyI
  0x8001531: chThdDequeueNextI.constprop.0
  0x8001561: chThdResumeI
  0x8001591: _dbg_check_leave_isr
  0x80015c1: _dbg_check_enter_isr
  0x80015f1: _dbg_check_unlock_from_isr
  0x8001621: _dbg_check_lock_from_isr
  0x8001651: i2c_lld_serve_rx_end_irq
  0x80016c1: wakeup
  0x8001721: _idle_thread
  0x8001731: dmaServeInterrupt
  0x8001771: _ctl
  0x8001791: stSetAlarm
  0x80017b1: chEvtBroadcastFlagsI.constprop.0
  0x8001841: chSchWakeupS.constprop.0
  0x80018c1: chSchGoSleepS
  0x8001921: chSchGoSleepTimeoutS
  0x8001ab1: chThdEnqueueTimeoutS
  0x8001ae1: SVC_Handler
  0x8001b01:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8001b91: _dbg_check_unlock
  0x8001bb1: chSysUnlock.lto_priv.3
  0x8001be1: _dbg_check_lock
  0x8001c01: i2cMasterTransmitTimeout.constprop.0
  0x8001d91: chCoreAllocAlignedWithOffset
  0x8001de1: chMtxUnlock
  0x8001eb1: chMtxLock
  0x8001fd1: PollFakeThread
  0x8002181: PollAccelThread
  0x8002331: chRegFindThreadByWorkingArea
  0x8002551: chThdCreateStatic.constprop.0
  0x8002601: main
  0x8002db1: chThdExit
  0x8002e11: oqWriteTimeout
  0x8002f21: _writet
  0x8002f31: _write
  0x8002f41: oqPutTimeout
  0x8002fe1: _putt
  0x8002ff1: _put
  0x8003001: iqReadTimeout
  0x8003121: _readt
  0x8003131: _read
  0x8003141: iqGetTimeout
  0x80031c1: _gett
  0x80031d1: _get
  0x80031e1: __early_init
  0x8003261: VectorDC
  0x8003431: VectorB0
  0x8003551: VectorC0
  0x8003641: VectorBC
  0x8003761: Vector84
  0x8003791: Vector80
  0x80037c1: Vector7C
  0x80037f1: Vector78
  0x8003821: Vector74
  0x8003851: Vector70
  0x8003881: Vector6C
  0x80038b1: VectorE0
  0x8003941: Vector9C
  0x80039c1: Vector68
  0x8003a11: Vector64
  0x8003a61: Vector60
  0x8003ab1: Vector5C
  0x8003b01: Vector58
  0x8003b51: __init_ram_areas
  0x8003bc1: __default_exit
  0x8003bd1: __late_init
  0x8003be1: __core_init
  0x8003be5: sqrtf
  0x8003c89: __ieee754_sqrtf
  0x8003d31: matherr
  0x8003d35: __errno
  0x8003d40:
  - __text_end
  - __rodata_base__
  0x8003dcc: __func__.4292.lto_priv.0
  0x8003dd8: __func__.4292.lto_priv.1
  0x8003de4: __func__.5513.lto_priv.0
  0x8003df0: __func__.5513.lto_priv.1
  0x8003dfc: __func__.5513.lto_priv.2
  0x8003e08: __func__.5513.lto_priv.3
  0x8003e14: __func__.5513.lto_priv.4
  0x8003e20: __func__.5513.lto_priv.5
  0x8003e2c: __func__.5599
  0x8003e38: __func__.5714
  0x8003e4c: __func__.5915.lto_priv.0
  0x8003e58: __func__.5915.lto_priv.1
  0x8003e64: __func__.6503
  0x8003e70: __func__.6506.lto_priv.0
  0x8003e7c: __func__.6506.lto_priv.1
  0x8003e88: __func__.6510.lto_priv.0
  0x8003e9c: __func__.6510.lto_priv.1
  0x8003ebc: __func__.6525.lto_priv.0
  0x8003ec8: __func__.6525.lto_priv.1
  0x8003ed4: __func__.6528.lto_priv.1
  0x8003ee0: __func__.6529
  0x8003eec: __func__.6534
  0x8003f00: __func__.6539
  0x8003f10: __func__.6545
  0x8003f20: __func__.6546
  0x8003f30: __func__.6561
  0x8003f3c: __func__.6600
  0x8003f54: __func__.6606
  0x8003f64: __func__.6906
  0x8003f74: __func__.7259
  0x8003f80: __func__.7260
  0x8003f8c: __func__.7262
  0x8003f9c: __func__.7263
  0x8003fac: __func__.7265
  0x8003fb8: __func__.7266
  0x8003fc4: __func__.7268
  0x8003fd0: __func__.7269.lto_priv.0
  0x8003fdc: __func__.7269.lto_priv.1
  0x8003ff0: __func__.7270
  0x8003ffc: __func__.7272
  0x8004008: __func__.7275
  0x8004014: __func__.7276
  0x8004020: __func__.7280.lto_priv.0
  0x800402c: __func__.7280.lto_priv.1
  0x8004038: __func__.7284
  0x8004044: __func__.7285.lto_priv.0
  0x8004060: __func__.7285.lto_priv.1
  0x800406c: __func__.7288
  0x8004078: __func__.7289
  0x8004084: __func__.7290
  0x8004090: __func__.7292
  0x800409c: __func__.7294
  0x80040b4: __func__.7300
  0x80040bc: __func__.7310
  0x80040c8: __func__.7315
  0x80040d4: __func__.7323
  0x80040e4: __func__.7352
  0x8004104: __func__.7716
  0x8004114: __func__.7767
  0x8004124: __func__.8588
  0x8004130: __func__.8603
  0x800413c: _stm32_dma_streams
  0x80041ac: ch_debug
  0x80041c4: i2cfg1
  0x80041d0: ram_areas
  0x8004250: vmt
  0x8004280:
  - __exidx_end
  - __rodata_end__
  - __exidx_start
  - _textdata_start
  0x80046b0:
  - __ram3_init_text__
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  0x8020000: __flash0_end__
  0x10000000: ICSR_PENDSVSET
  0x20000000:
  - __ram0_start__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - __main_thread_stack_end__
  - __fdlib_version
  - _data_start
  - __process_stack_end__
  0x20000804: _impure_ptr
  0x20000808: impure_data
  0x20000c30:
  - I2CD1
  - _bss_start
  - _data_end
  0x20000c68: PollAccelThreadWA
  0x20000e30: PollFakeThreadWA
  0x20000ff8: SD3
  0x20001074: _pal_events
  0x200010f4: acc
  0x20001100: accel_rx_data
  0x20001108: accel_tx_data
  0x20001110: ch
  0x20001998: ch_factory
  0x200019e0: ch_idle_thread_wa
  0x20001ab8: ch_memcore
  0x20001ac0: default_heap
  0x20001adc: dma
  0x20001b1c: rx_data
  0x20001b20:
  - __ram0_init__
  - __ram0_free__
  - __heap_base__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x20005000:
  - __heap_end__
  - __ram0_end__
  0xe000ed04: SCB_ICSR
