interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0x194
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: uart_sg_example.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1475c
symbols:
  0x0:
  - startup_MK64F12.S.obj
  - crt0.o
  - libc_a-strlen.o
  - crtstuff.c
  - uart_edma_rb_transfer.c
  - pin_mux.c
  - clock_config.c
  - fsl_debug_console.c
  - fsl_assert.c
  - fsl_edma.c
  - fsl_dmamux.c
  - fsl_uart_edma.c
  - fsl_uart.c
  - fsl_clock.c
  - system_MK64F12.c
  - exit.c
  - init.c
  - memcpy-stub.c
  - memset.c
  - _exit.c
  - crti.o
  - crtn.o
  - findfp.c
  - __isr_vector
  0x400:
  - STACK_SIZE
  - HEAP_SIZE
  0x411: _stack_init
  0x419:
  - _mainCRTStartup
  - _start
  0x48d: Reset_Handler
  0x4ed:
  - DebugMon_Handler
  - SPI1_DriverIRQHandler
  - DMA_Error_DriverIRQHandler
  - SDHC_DriverIRQHandler
  - PIT0_IRQHandler
  - CMP2_IRQHandler
  - LLWU_IRQHandler
  - I2S0_Tx_DriverIRQHandler
  - ENET_1588_Timer_DriverIRQHandler
  - I2C2_DriverIRQHandler
  - SWI_IRQHandler
  - ADC0_IRQHandler
  - UsageFault_Handler
  - CMT_IRQHandler
  - DefaultISR
  - UART5_ERR_DriverIRQHandler
  - CMP1_IRQHandler
  - Reserved71_IRQHandler
  - PORTD_IRQHandler
  - PORTB_IRQHandler
  - UART2_ERR_DriverIRQHandler
  - SPI2_DriverIRQHandler
  - ADC1_IRQHandler
  - PIT2_IRQHandler
  - RTC_IRQHandler
  - UART3_ERR_DriverIRQHandler
  - PDB0_IRQHandler
  - FTM1_IRQHandler
  - PIT3_IRQHandler
  - RTC_Seconds_IRQHandler
  - MCG_IRQHandler
  - FTFE_IRQHandler
  - UART0_ERR_DriverIRQHandler
  - Read_Collision_IRQHandler
  - USBDCD_IRQHandler
  - I2S0_Rx_DriverIRQHandler
  - USB0_IRQHandler
  - UART4_ERR_DriverIRQHandler
  - WDOG_EWM_IRQHandler
  - MemManage_Handler
  - UART0_LON_DriverIRQHandler
  - RNG_IRQHandler
  - I2C1_DriverIRQHandler
  - ENET_Receive_DriverIRQHandler
  - DAC0_IRQHandler
  - ENET_Error_DriverIRQHandler
  - SPI0_DriverIRQHandler
  - PIT1_IRQHandler
  - LVD_LVW_IRQHandler
  - FTM0_IRQHandler
  - PORTA_IRQHandler
  - DAC1_IRQHandler
  - MCM_IRQHandler
  - CAN0_DriverIRQHandler
  - FTM3_IRQHandler
  - PORTE_IRQHandler
  - FTM2_IRQHandler
  - LPTMR0_IRQHandler
  - BusFault_Handler
  - UART1_ERR_DriverIRQHandler
  - ENET_Transmit_DriverIRQHandler
  - I2C0_DriverIRQHandler
  - CMP0_IRQHandler
  - PORTC_IRQHandler
  0x4f1: NMI_Handler
  0x4f5: HardFault_Handler
  0x4f9: SVC_Handler
  0x4fd: PendSV_Handler
  0x501: SysTick_Handler
  0x505: DMA0_IRQHandler
  0x509: DMA1_IRQHandler
  0x50d: DMA2_IRQHandler
  0x511: DMA3_IRQHandler
  0x515: DMA4_IRQHandler
  0x519: DMA5_IRQHandler
  0x51d: DMA6_IRQHandler
  0x521: DMA7_IRQHandler
  0x525: DMA8_IRQHandler
  0x529: DMA9_IRQHandler
  0x52d: DMA10_IRQHandler
  0x531: DMA11_IRQHandler
  0x535: DMA12_IRQHandler
  0x539: DMA13_IRQHandler
  0x53d: DMA14_IRQHandler
  0x541: DMA15_IRQHandler
  0x545: DMA_Error_IRQHandler
  0x549: I2C0_IRQHandler
  0x54d: I2C1_IRQHandler
  0x551: SPI0_IRQHandler
  0x555: SPI1_IRQHandler
  0x559: I2S0_Tx_IRQHandler
  0x55d: I2S0_Rx_IRQHandler
  0x561: UART0_LON_IRQHandler
  0x569: UART0_ERR_IRQHandler
  0x56d: UART1_RX_TX_IRQHandler
  0x571: UART1_ERR_IRQHandler
  0x575: UART2_RX_TX_IRQHandler
  0x579: UART2_ERR_IRQHandler
  0x57d: UART3_RX_TX_IRQHandler
  0x581: UART3_ERR_IRQHandler
  0x585: SPI2_IRQHandler
  0x589: UART4_RX_TX_IRQHandler
  0x58d: UART4_ERR_IRQHandler
  0x591: UART5_RX_TX_IRQHandler
  0x595: UART5_ERR_IRQHandler
  0x599: I2C2_IRQHandler
  0x59d: CAN0_ORed_Message_buffer_IRQHandler
  0x5a1: CAN0_Bus_Off_IRQHandler
  0x5a5: CAN0_Error_IRQHandler
  0x5a9: CAN0_Tx_Warning_IRQHandler
  0x5ad: CAN0_Rx_Warning_IRQHandler
  0x5b1: CAN0_Wake_Up_IRQHandler
  0x5b5: SDHC_IRQHandler
  0x5b9: ENET_1588_Timer_IRQHandler
  0x5bd: ENET_Transmit_IRQHandler
  0x5c1: ENET_Receive_IRQHandler
  0x5c5: ENET_Error_IRQHandler
  0x68d: strlen
  0x69d: deregister_tm_clones
  0x6b9: register_tm_clones
  0x6dd: __do_global_dtors_aux
  0x705: frame_dummy
  0x729: __NVIC_EnableIRQ
  0x765: EnableIRQ
  0x797: UART_GetDataRegisterAddress
  0x7af: UART_EnableRxDMA
  0x811: DMAMUX_EnableChannel
  0x85d: DMAMUX_SetSource
  0x8b9: pwcheck_success
  0x8d5: pwcheck_passed_1
  0x8f1: pwcheck_passed_2
  0x90d: pwcheck_passed_3
  0x929: pwcheck_passed_4
  0x945: pwcheck_passed_5
  0x961: pwcheck_passed_6
  0x97d: pwcheck_passed_7
  0x999: pwcheck_passed_8
  0x9b5: check_password_scatter_gather
  0xa51: EXAMPLE_InitUART
  0xa8d: EXAMPLE_InitEDMA
  0xb21: StartSGDMA
  0xc2d: UART_UserCallback
  0xc5d: UART0_RX_TX_IRQHandler
  0xc9d: main
  0xd01: CLOCK_EnableClock
  0xd35: PORT_SetPinMux
  0xd6f: BOARD_InitBootPins
  0xd7d: BOARD_InitPins
  0xdc1: CLOCK_SetSimSafeDivs
  0xde1: CLOCK_SetXtal0Freq
  0xe01: CLOCK_CONFIG_SetFllExtRefDiv
  0xe3d: BOARD_InitBootClocks
  0xe49: BOARD_BootClockRUN
  0xea9: DbgConsole_Printf
  0xed5: DbgConsole_Vprintf
  0xf11: DbgConsole_Putchar
  0xf41: DbgConsole_PrintfPaddingCharacter
  0xf81: DbgConsole_ConvertRadixNumToString
  0x1045: DbgConsole_PrintfFormattedData
  0x1425: fsl_assert_hook
  0x1441: __assert_func
  0x1471: __NVIC_EnableIRQ
  0x14ad: CLOCK_EnableClock
  0x14e1: EnableIRQ
  0x1513: DisableGlobalIRQ
  0x1535: EnableGlobalIRQ
  0x1555: EDMA_GetInstance
  0x15a9: EDMA_InstallTCD
  0x170d: EDMA_Init
  0x17b1: EDMA_GetDefaultConfig
  0x1801: EDMA_TcdReset
  0x1891: EDMA_TcdSetTransferConfig
  0x19f1: EDMA_GetInstanceOffset
  0x1a49: EDMA_CreateHandle
  0x1b41: EDMA_InstallTCDMemory
  0x1bb1: EDMA_SetCallback
  0x1bf1: EDMA_TransferWidthMapping
  0x1cd1: EDMA_PrepareTransferConfig
  0x1e4d: EDMA_PrepareTransfer
  0x1f09: EDMA_StartTransfer
  0x1fc9: EDMA_AbortTransfer
  0x2061: EDMA_HandleIRQ
  0x2231: DMA0_DriverIRQHandler
  0x224d: DMA1_DriverIRQHandler
  0x2269: DMA2_DriverIRQHandler
  0x2285: DMA3_DriverIRQHandler
  0x22a1: DMA4_DriverIRQHandler
  0x22bd: DMA5_DriverIRQHandler
  0x22d9: DMA6_DriverIRQHandler
  0x22f5: DMA7_DriverIRQHandler
  0x2311: DMA8_DriverIRQHandler
  0x232d: DMA9_DriverIRQHandler
  0x2349: DMA10_DriverIRQHandler
  0x2365: DMA11_DriverIRQHandler
  0x2381: DMA12_DriverIRQHandler
  0x239d: DMA13_DriverIRQHandler
  0x23b9: DMA14_DriverIRQHandler
  0x23d5: DMA15_DriverIRQHandler
  0x23f1: CLOCK_EnableClock
  0x2425: DMAMUX_GetInstance
  0x2479: DMAMUX_Init
  0x249d: __NVIC_EnableIRQ
  0x24d9: EnableIRQ
  0x250b: UART_EnableTxDMA
  0x256b: UART_EnableRxDMA
  0x25cd: UART_SendEDMACallback
  0x262d: UART_ReceiveEDMACallback
  0x26a1: UART_TransferCreateHandleEDMA
  0x27a9: UART_TransferAbortReceiveEDMA
  0x280d: UART_TransferEdmaHandleIRQ
  0x286d: CLOCK_EnableClock
  0x28a1: UART_GetInstance
  0x2901: UART_Init
  0x2c15: UART_GetDefaultConfig
  0x2c8d: UART_EnableInterrupts
  0x2cfd: UART_DisableInterrupts
  0x2d8d: UART_GetStatusFlags
  0x2dd5: UART_ClearStatusFlags
  0x2e55: UART0_DriverIRQHandler
  0x2e7d: UART0_RX_TX_DriverIRQHandler
  0x2e91: UART1_DriverIRQHandler
  0x2eb9: UART1_RX_TX_DriverIRQHandler
  0x2ecd: UART2_DriverIRQHandler
  0x2ef5: UART2_RX_TX_DriverIRQHandler
  0x2f09: UART3_DriverIRQHandler
  0x2f31: UART3_RX_TX_DriverIRQHandler
  0x2f45: UART4_DriverIRQHandler
  0x2f6d: UART4_RX_TX_DriverIRQHandler
  0x2f81: UART5_DriverIRQHandler
  0x2fa9: UART5_RX_TX_DriverIRQHandler
  0x2fbd: CLOCK_SetEr32kClock
  0x2fed: CLOCK_SetPllFllSelClock
  0x3025: OSC_SetExtRefClkConfig
  0x3059: OSC_SetCapLoad
  0x308d: CLOCK_GetMcgExtClkFreq
  0x311d: CLOCK_GetFllExtRefClkFreq
  0x31cd: CLOCK_GetInternalRefClkSelectFreq
  0x3219: CLOCK_GetFllRefClkFreq
  0x324d: CLOCK_GetPll0RefFreq
  0x325d: CLOCK_GetOscRangeFromFreq
  0x3299: CLOCK_GetOsc0ErClkFreq
  0x32ed: CLOCK_GetEr32kClkFreq
  0x3371: CLOCK_GetPllFllSelClkFreq
  0x33c5: CLOCK_GetFreq
  0x3505: CLOCK_SetSimConfig
  0x3539: CLOCK_GetOutClkFreq
  0x359d: CLOCK_GetFllFreq
  0x3621: CLOCK_GetInternalRefClkFreq
  0x3651: CLOCK_GetFixedFreqClkFreq
  0x3685: CLOCK_GetPll0Freq
  0x370d: CLOCK_SetExternalRefClkConfig
  0x3779: CLOCK_SetInternalRefClkConfig
  0x387d: CLOCK_EnablePll0
  0x3915: CLOCK_InitOsc0
  0x39a1: CLOCK_SetPbeMode
  0x3a59: CLOCK_BootToPeeMode
  0x3ac9: SystemInit
  0x3b05: SystemInitHook
  0x3b15: exit
  0x3b39: __libc_init_array
  0x3b81: memcpy
  0x3b9d: memset
  0x3bad: _exit
  0x4380: __func__.1
  0x4394: __func__.0
  0x43ac: mcgConfig_BOARD_BootClockRUN
  0x43b8: simConfig_BOARD_BootClockRUN
  0x43c0: oscConfig_BOARD_BootClockRUN
  0x43c8: s_edmaIRQNumber
  0x43d8: __func__.36
  0x43ec: __func__.35
  0x43fc: __func__.34
  0x4408: __func__.33
  0x4420: __func__.22
  0x4430: __func__.21
  0x444c: __func__.10
  0x4464: __func__.9
  0x4478: __func__.8
  0x4490: __func__.7
  0x44a4: __func__.6
  0x44c0: __func__.5
  0x44dc: __func__.4
  0x44f4: __func__.2
  0x4508: __func__.0
  0x4518: __func__.0
  0x452c: __func__.9
  0x4544: __func__.8
  0x4560: __func__.7
  0x4580: __func__.3
  0x45a0: __func__.0
  0x45bc: s_uartBases
  0x45d4: s_uartIRQ
  0x45dc: s_uartClock
  0x45f4: __func__.20
  0x4608: __func__.17
  0x4614: __func__.16
  0x462c: __func__.9
  0x4644: __func__.8
  0x465c: __func__.7
  0x4674: fllFactorTable.6
  0x4684: __func__.5
  0x4698: __func__.4
  0x46ac: __func__.2
  0x46c0: __func__.1
  0x46d4: __EH_FRAME_BEGIN__
  0x46d5: _init
  0x46e1: _fini
  0x46ec: __exidx_start
  0x46f4:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __DTOR_END__
  - __CTOR_LIST__
  - __CTOR_END__
  - __DTOR_LIST__
  0x46f8:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x46fc:
  - __etext
  - __DATA_ROM
  0x475c: __DATA_END
  0x100000: text_end
  0x1fff0000:
  - s_slowIrcFreq
  - __data_start__
  - __DATA_RAM
  0x1fff0004: s_fastIrcFreq
  0x1fff0008: SystemCoreClock
  0x1fff0020: tcdMemoryPoolPtr
  0x1fff0060:
  - completed.1
  - __TMC_END__
  - __START_BSS
  - __bss_start__
  - __data_end__
  0x1fff0064: object.0
  0x1fff007c: num_correct
  0x1fff0080: g_uartEdmaHandle
  0x1fff009c: g_uartTxEdmaHandle
  0x1fff00b4: g_uartRxEdmaHandle
  0x1fff00cc: txOnGoing
  0x1fff00cd: rxIdleLineDetected
  0x1fff00d0: dma_buf_1
  0x1fff00e0: dma_buf_2
  0x1fff00e4: s_debugConsole
  0x1fff00f8: s_EDMAHandle
  0x1fff0138: startInstanceNum.11
  0x1fff013c: s_edmaPrivateHandle
  0x1fff016c: s_uartHandle
  0x1fff0184: s_uartIsr
  0x1fff0188: g_xtal0Freq
  0x1fff018c: g_xtal32Freq
  0x1fff0190: __stdio_exit_handler
  0x1fff0194:
  - __bss_end__
  - __END_BSS
  0x20000000:
  - __HeapBase
  - end
  - __end__
  0x20000400:
  - __heap_limit
  - __HeapLimit
  0x2002fc00: __StackLimit
  0x20030000:
  - __StackTop
  - __stack
  0xe000ed08: VTOR
