interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_I2C_OneBoard_AdvCommunication_DMAAndIT.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x122ec
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - lib_a-strlen.o
  - init.c
  - memset.c
  - syscalls.c
  - system_stm32f1xx.c
  - stm32f1xx_ll_rcc.c
  - stm32f1xx_ll_utils.c
  - main.c
  - stm32f1xx_it.c
  - errno.c
  - findfp.c
  - fwalk.c
  - nano-mallocr.c
  - printf.c
  - sbrkr.c
  - stdio.c
  - strncmp.c
  - writer.c
  - closer.c
  - fflush.c
  - lseekr.c
  - mlock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - readr.c
  - wbuf.c
  - wsetup.c
  - makebuf.c
  - memchr-stub.c
  - fstatr.c
  - isattyr.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  - impure.c
  - reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: strlen
  0x800015d: __libc_init_array
  0x80001a5: memset
  0x80001b5: findslot
  0x80001e9: checkerror
  0x8000209: error
  0x8000225: _swiread
  0x8000245: _read
  0x8000279: _swilseek
  0x80002f3: _lseek
  0x80002f7: _swiwrite
  0x8000317: _write
  0x8000357: _swiclose
  0x8000375: _close
  0x80003c1: _sbrk
  0x8000409: _swistat
  0x800044b: _fstat
  0x8000467: _stat
  0x80004a1: _swiopen
  0x8000555: _get_semihosting_exts
  0x8000609: initialise_semihosting_exts
  0x800063d: _has_ext_stdout_stderr
  0x8000655: initialise_monitor_handles
  0x8000711: _isatty
  0x8000749: SystemInit
  0x8000795: RCC_GetHCLKClockFreq
  0x80007ad: RCC_GetPCLK1ClockFreq
  0x80007c5: RCC_GetPCLK2ClockFreq
  0x80007dd: RCC_PLL_GetFreqDomain_SYS
  0x8000811: RCC_GetSystemClockFreq
  0x800082d: LL_RCC_GetSystemClocksFreq
  0x800084d: LL_Init1msTick
  0x8000869: LL_mDelay
  0x800087d: LL_SetSystemCoreClock
  0x8000889: Reset_Handler
  0x800088c: CopyDataInit
  0x8000894: LoopCopyDataInit
  0x80008a2: FillZerobss
  0x80008a8: LoopFillZerobss
  0x80008d0:
  - Infinite_Loop
  - Default_Handler
  0x80008d1:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - USBWakeUp_IRQHandler
  0x80008d5: LL_APB2_GRP1_EnableClock
  0x80008f1: LL_GPIO_SetPinMode
  0x800091f: LL_GPIO_SetPinOutputType.constprop.12
  0x8000955: LL_GPIO_SetPinSpeed.constprop.13
  0x800098d: Configure_DMA
  0x8000a5d: Configure_I2C_Slave
  0x8000b2d: Configure_I2C_Master
  0x8000c49: Activate_I2C_Slave
  0x8000c69: Activate_I2C_Master
  0x8000c89: FlushBuffer8
  0x8000c95: Buffercmp8
  0x8000cb9: LED_Init
  0x8000cd5: LED_Blinking
  0x8000cf5: UserButton_Init
  0x8000d61: Handle_I2C_Slave
  0x8000d71: Handle_I2C_Master_Transmit
  0x8000e15: Handle_I2C_Master_TransmitReceive
  0x8000f0d: SystemClock_Config
  0x8000f9d: main
  0x800101d: UserButton_Callback
  0x8001029: Slave_Ready_To_Transmit_Callback
  0x8001061: Slave_Reception_Callback
  0x80010c9: Slave_Complete_Callback
  0x80010dd: Transfer_Complete_Callback
  0x80010e9: Transfer_Error_Callback
  0x8001101: Error_Callback
  0x8001121: NMI_Handler
  0x8001123: HardFault_Handler
  0x8001125: MemManage_Handler
  0x8001127: BusFault_Handler
  0x8001129: UsageFault_Handler
  0x800112b: SVC_Handler
  0x800112d: DebugMon_Handler
  0x800112f: PendSV_Handler
  0x8001131: SysTick_Handler
  0x8001135: EXTI15_10_IRQHandler
  0x800114d: I2C1_EV_IRQHandler
  0x80011d5: I2C1_ER_IRQHandler
  0x8001201: I2C2_EV_IRQHandler
  0x8001295: I2C2_ER_IRQHandler
  0x8001299: DMA1_Channel4_IRQHandler
  0x80012bd: DMA1_Channel5_IRQHandler
  0x80012e1: __errno
  0x80012ed: std
  0x8001335: _cleanup_r
  0x8001341: __sfmoreglue
  0x800136d: __sinit
  0x80013cd: __sfp
  0x8001445: _fwalk_reent
  0x8001481: _malloc_r
  0x8001535:
  - printf
  - iprintf
  0x8001565: _sbrk_r
  0x8001585: __sread
  0x80015a7: __swrite
  0x80015df: __sseek
  0x8001603: __sclose
  0x800160b: strncmp
  0x8001631: _write_r
  0x8001655: _close_r
  0x8001675: __sflush_r
  0x8001781: _fflush_r
  0x80017d5: _lseek_r
  0x80017f9: __malloc_lock
  0x80017fb: __malloc_unlock
  0x80017fd: _free_r
  0x8001895: __sfputc_r
  0x80018bf: __sfputs_r
  0x80018e5:
  - _vfiprintf_r
  - _vfprintf_r
  0x8001b11: _printf_common
  0x8001bfd: _printf_i
  0x8001e21: _read_r
  0x8001e45: __swbuf_r
  0x8001ee9: __swsetup_r
  0x8001fc5: __swhatbuf_r
  0x800200d: __smakebuf_r
  0x800208d: memchr
  0x80020a9: _fstat_r
  0x80020cd: _isatty_r
  0x80020ec: __EH_FRAME_BEGIN__
  0x80020ed: _init
  0x80020f9: _fini
  0x8002104:
  - _etext
  - AHBPrescTable
  0x8002114: APBPrescTable
  0x800211c: _global_impure_ptr
  0x800218c: __sf_fake_stderr
  0x80021ac: __sf_fake_stdin
  0x80021cc: __sf_fake_stdout
  0x8002220:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8002224:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8002228: _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: pMasterTransmitBuffer
  0x20000008: aCommandCode
  0x20000048: ubMasterNbDataToReceive
  0x20000049: ubMasterNbCommandCode
  0x2000004a: ubSlaveInfoIndex
  0x2000004c: aSlaveInfo
  0x20000054: _impure_ptr
  0x20000058: impure_data
  0x200000b8: __heap_limit
  0x200000bc: supports_ext_exit_extended
  0x200000c0: supports_ext_stdout_stderr
  0x200000c4:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x200000c8: object.8660
  0x200000e0: aMasterReceiveBuffer
  0x200000ef: ubMasterCommandIndex
  0x200000f0: ubMasterNbDataToTransmit
  0x200000f1: ubMasterRequestDirection
  0x200000f2: ubMasterTransferComplete
  0x200000f3: ubMasterReceiveIndex
  0x200000f4: ubButtonPress
  0x200000f5: ubSlaveNbDataToTransmit
  0x200000f8: pSlaveTransmitBuffer
  0x200000fc: ubSlaveReceiveIndex
  0x200000fd: aSlaveReceiveBuffer
  0x2000010c: ubSlaveReceiveComplete
  0x2000010d: ubMasterXferDirection
  0x20000110: heap_end.6247
  0x20000114: monitor_stderr
  0x20000118: monitor_stdin
  0x2000011c: monitor_stdout
  0x20000120: openfiles
  0x200001c0: __malloc_free_list
  0x200001c4: __malloc_sbrk_start
  0x200001c8: errno
  0x200001cc:
  - _ebss
  - __bss_end__
  0x200001d0: end
  0x20005000: _estack
  0xf108f85f: BootRAM
