interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x800328c
    permissions: r-x
    size: 0xd74
  .heap:
    base_addr: 0x8003b90
    permissions: r--
    size: 0x42c70
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x10000000
    file: mtb-psoc6-json-parser-dma.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x358d4
symbols:
  0x0:
  - psoc6_cm0p_bless.c
  - startup_psoc6_01_cm4.o
  - crtbegin.o
  - system_psoc6_cm4.c
  - cycfg.c
  - cycfg_clocks.c
  - cycfg_dmas.c
  - cycfg_peripherals.c
  - cycfg_pins.c
  - cycfg_routing.c
  - cycfg_system.c
  - UartDma.c
  - main.c
  - cy_syslib_ext.o
  - cyhal_hwmgr.c
  - cy_device.c
  - cy_ble_clk.c
  - cy_dma.c
  - cy_flash.c
  - cy_gpio.c
  - cy_ipc_drv.c
  - cy_ipc_pipe.c
  - cy_ipc_sema.c
  - cy_prot.c
  - cy_scb_uart.c
  - cy_sysclk.c
  - cy_sysint.c
  - cy_syslib.c
  - cy_syspm.c
  - cy_systick.c
  - cy_trigmux.c
  - _aeabi_uldivmod.o
  - _udivmoddi4.o
  - _dvmd_tls.o
  - libc_a-init.o
  - libc_a-fini.o
  - libc_a-malloc.o
  - libc_a-mallocr.o
  - libc_a-mlock.o
  - libc_a-sbrkr.o
  - libc_a-lock.o
  - sbrk.o
  - crti.o
  - crtn.o
  - crtend.o
  - libc_a-impure.o
  - cyhal_comp_ctb.c
  - cyhal_gpio.c
  - cyhal_pdmpcm.c
  0x1: __cy_memory_4_row_size
  0x200:
  - __cy_memory_1_row_size
  - __cy_memory_0_row_size
  - __cy_memory_3_row_size
  - __cy_memory_2_row_size
  0x28c: __VectorsSize
  0x400: Heap_Size
  0x1000:
  - Stack_Size
  - STACK_SIZE
  0x8000:
  - __cy_memory_2_length
  - __cy_memory_1_length
  0x20000: FLASH_CM0P_SIZE
  0xe0000: FLASH_CM4_SIZE
  0x100000:
  - __cy_memory_0_length
  - __cy_memory_4_length
  0x8000000: __cy_memory_3_length
  0x8003000:
  - __ram_vectors_start__
  - __ramVectors
  0x800328c:
  - __data_start__
  - __ram_vectors_end__
  - SystemCoreClock
  0x8003290: cy_AhbFreqHz
  0x8003294: cy_Hfclk0FreqHz
  0x8003298: cy_PeriClkFreqHz
  0x800329c: cy_delayFreqKhz
  0x80032a0: cy_delayFreqMhz
  0x80032a4: _impure_data
  0x80032f0: _impure_ptr
  0x80032f4:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x80032f8:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x80032fc: __fini_array_end
  0x80032fd: Cy_Flash_RAMDelay
  0x8003361: Cy_Flash_ResumeIrqHandler
  0x80033f1: Cy_Flash_NotifyHandler
  0x800345d: Cy_Flash_SendCmd
  0x80035c5: EnterDeepSleepRam
  0x8003679: __Cy_SysLib_ExitCriticalSection_veneer
  0x8003681: __Cy_IPC_Sema_Status_veneer
  0x8003689: __Cy_IPC_Sema_Clear_veneer
  0x8003691: __Cy_SysLib_EnterCriticalSection_veneer
  0x8003699: __Cy_SysClk_ClkSlowGetFrequency_veneer
  0x80036a1: __Cy_Flash_OperationStatus_veneer
  0x80036a9: __Cy_IPC_Drv_SendMsgWord_veneer
  0x80036b1: __Cy_IPC_Pipe_SendMessage_veneer
  0x80036b8:
  - ipcWaitMessageStc.4
  - __TMC_END__
  - __data_end__
  0x80036bc: cy_semaData.0
  0x80036c8: _cyhal_comp_ctb_config_structs
  0x80036d0: _cyhal_gpio_callbacks
  0x800370c: _cyhal_gpio_source_signals
  0x8003718: _cyhal_pdm_pcm_config_structs_inst0
  0x800371c: cy_assertFileName
  0x8003738: cy_assertLine
  0x800373c: cy_faultFrame
  0x80037b4:
  - completed.1
  - __bss_start__
  0x80037b8: object.0
  0x80037d0: cy_BleEcoClockFreqHz
  0x80037d4: systemIpcPipeEpArray.2
  0x8003934: systemIpcPipeSysCbArray.0
  0x8003954: RxDma_Descriptor_0
  0x800396c: RxDma_Descriptor_1
  0x8003984: rx_dma_done
  0x8003985: rx_dma_error
  0x8003988: rx_dma_uart_buffer
  0x80039c8: uart_error
  0x80039cc: cyhal_used
  0x80039f0: cy_device
  0x80039f4: flashContext
  0x8003a04: ipcWaitMessage
  0x8003a08: semaIndex.2
  0x8003a0c: semaMask.1
  0x8003a10: semaPtr.0
  0x8003a14: semaStruct.3
  0x8003a18: cy_ipc_pipe_epArray
  0x8003a1c: cy_semaIpcStruct
  0x8003a20: cySysClkExtFreq
  0x8003a24: ecoFrequency
  0x8003a28: wasEventSent
  0x8003a2c: Cy_SysTick_Callbacks
  0x8003a40: __malloc_free_list
  0x8003a44: __malloc_sbrk_start
  0x8003a48: __sf
  0x8003b80: __lock___malloc_recursive_mutex
  0x8003b84: errno
  0x8003b88: heap_end.0
  0x8003b8c: __bss_end__
  0x8003b90:
  - __HeapBase
  - end
  - __end__
  0x8046800:
  - __HeapLimit
  - __StackLimit
  0x8047800:
  - __StackTop
  - __stack
  0x10000000:
  - __cy_m0p_code_start
  - FLASH_CM0P_START
  - cy_m0p_image
  - __cy_memory_0_start
  0x1001b610: __cy_m0p_code_end
  0x10020000:
  - FLASH_CM4_START
  - __Vectors
  0x1002028c:
  - __Vectors_Size
  - __Vectors_End
  0x1002028d: deregister_tm_clones
  0x100202a9: register_tm_clones
  0x100202cd: __do_global_dtors_aux
  0x100202f5: frame_dummy
  0x10020319: Cy_OnResetUser
  0x1002031b: cy_toolchain_init
  0x1002031d: Reset_Handler
  0x1002038d:
  - lpcomp_interrupt_IRQHandler
  - cpuss_interrupts_dw0_5_IRQHandler
  - cpuss_interrupts_ipc_6_IRQHandler
  - DebugMon_Handler
  - tcpwm_1_interrupts_11_IRQHandler
  - cpuss_interrupts_ipc_0_IRQHandler
  - tcpwm_1_interrupts_15_IRQHandler
  - tcpwm_1_interrupts_13_IRQHandler
  - cpuss_interrupts_dw1_8_IRQHandler
  - tcpwm_0_interrupts_0_IRQHandler
  - SysTick_Handler
  - cpuss_interrupt_fm_IRQHandler
  - cpuss_interrupts_ipc_7_IRQHandler
  - tcpwm_1_interrupts_14_IRQHandler
  - cpuss_interrupts_dw0_11_IRQHandler
  - tcpwm_1_interrupts_9_IRQHandler
  - cpuss_interrupts_cm0_cti_1_IRQHandler
  - tcpwm_1_interrupts_22_IRQHandler
  - cpuss_interrupts_dw0_4_IRQHandler
  - PendSV_Handler
  - NMI_Handler
  - cpuss_interrupts_dw1_12_IRQHandler
  - tcpwm_1_interrupts_12_IRQHandler
  - smif_interrupt_IRQHandler
  - tcpwm_1_interrupts_2_IRQHandler
  - cpuss_interrupts_ipc_13_IRQHandler
  - udb_interrupts_11_IRQHandler
  - tcpwm_1_interrupts_18_IRQHandler
  - tcpwm_0_interrupts_2_IRQHandler
  - cpuss_interrupts_dw0_13_IRQHandler
  - udb_interrupts_2_IRQHandler
  - cpuss_interrupts_dw1_7_IRQHandler
  - ioss_interrupts_gpio_1_IRQHandler
  - ioss_interrupts_gpio_7_IRQHandler
  - scb_5_interrupt_IRQHandler
  - udb_interrupts_6_IRQHandler
  - cpuss_interrupts_fault_1_IRQHandler
  - cpuss_interrupts_ipc_4_IRQHandler
  - cpuss_interrupts_ipc_5_IRQHandler
  - cpuss_interrupts_dw1_10_IRQHandler
  - udb_interrupts_0_IRQHandler
  - tcpwm_1_interrupts_6_IRQHandler
  - scb_4_interrupt_IRQHandler
  - pass_interrupt_dacs_IRQHandler
  - ioss_interrupts_gpio_2_IRQHandler
  - cpuss_interrupts_dw1_9_IRQHandler
  - cpuss_interrupts_dw1_13_IRQHandler
  - scb_2_interrupt_IRQHandler
  - udb_interrupts_5_IRQHandler
  - srss_interrupt_IRQHandler
  - udb_interrupts_12_IRQHandler
  - scb_0_interrupt_IRQHandler
  - csd_interrupt_IRQHandler
  - udb_interrupts_1_IRQHandler
  - profile_interrupt_IRQHandler
  - tcpwm_1_interrupts_1_IRQHandler
  - cpuss_interrupts_ipc_12_IRQHandler
  - tcpwm_1_interrupts_3_IRQHandler
  - tcpwm_0_interrupts_7_IRQHandler
  - cpuss_interrupts_dw1_1_IRQHandler
  - cpuss_interrupts_dw1_0_IRQHandler
  - cpuss_interrupts_dw0_9_IRQHandler
  - tcpwm_1_interrupts_23_IRQHandler
  - udb_interrupts_4_IRQHandler
  - tcpwm_1_interrupts_20_IRQHandler
  - ioss_interrupt_gpio_IRQHandler
  - tcpwm_0_interrupts_1_IRQHandler
  - ioss_interrupts_gpio_8_IRQHandler
  - tcpwm_0_interrupts_6_IRQHandler
  - scb_7_interrupt_IRQHandler
  - tcpwm_1_interrupts_7_IRQHandler
  - cpuss_interrupts_ipc_11_IRQHandler
  - udb_interrupts_13_IRQHandler
  - cpuss_interrupts_dw0_15_IRQHandler
  - udb_interrupts_7_IRQHandler
  - cpuss_interrupts_dw1_6_IRQHandler
  - cpuss_interrupt_crypto_IRQHandler
  - scb_1_interrupt_IRQHandler
  - Default_Handler
  - usb_interrupt_hi_IRQHandler
  - tcpwm_1_interrupts_0_IRQHandler
  - udb_interrupts_9_IRQHandler
  - audioss_interrupt_pdm_IRQHandler
  - srss_interrupt_mcwdt_0_IRQHandler
  - scb_3_interrupt_IRQHandler
  - pass_interrupt_ctbs_IRQHandler
  - udb_interrupts_8_IRQHandler
  - ioss_interrupts_gpio_3_IRQHandler
  - scb_6_interrupt_IRQHandler
  - cpuss_interrupts_cm4_cti_0_IRQHandler
  - cpuss_interrupts_dw1_3_IRQHandler
  - pass_interrupt_sar_IRQHandler
  - ioss_interrupts_gpio_0_IRQHandler
  - ioss_interrupts_gpio_14_IRQHandler
  - tcpwm_0_interrupts_4_IRQHandler
  - udb_interrupts_3_IRQHandler
  - tcpwm_0_interrupts_5_IRQHandler
  - cpuss_interrupts_ipc_15_IRQHandler
  - cpuss_interrupts_cm4_cti_1_IRQHandler
  - scb_8_interrupt_IRQHandler
  - srss_interrupt_mcwdt_1_IRQHandler
  - SVC_Handler
  - cpuss_interrupts_dw1_5_IRQHandler
  - cpuss_interrupts_ipc_1_IRQHandler
  - cpuss_interrupts_dw0_0_IRQHandler
  - ioss_interrupts_gpio_12_IRQHandler
  - cpuss_interrupts_ipc_3_IRQHandler
  - tcpwm_1_interrupts_17_IRQHandler
  - srss_interrupt_backup_IRQHandler
  - bless_interrupt_IRQHandler
  - cpuss_interrupts_ipc_10_IRQHandler
  - cpuss_interrupts_ipc_9_IRQHandler
  - cpuss_interrupts_dw0_14_IRQHandler
  - tcpwm_1_interrupts_4_IRQHandler
  - tcpwm_0_interrupts_3_IRQHandler
  - cpuss_interrupts_dw1_15_IRQHandler
  - ioss_interrupts_gpio_10_IRQHandler
  - udb_interrupts_10_IRQHandler
  - cpuss_interrupts_dw0_8_IRQHandler
  - ioss_interrupts_gpio_11_IRQHandler
  - cpuss_interrupts_ipc_14_IRQHandler
  - ioss_interrupts_gpio_5_IRQHandler
  - ioss_interrupts_gpio_4_IRQHandler
  - tcpwm_1_interrupts_8_IRQHandler
  - cpuss_interrupts_dw1_14_IRQHandler
  - usb_interrupt_med_IRQHandler
  - cpuss_interrupts_dw0_2_IRQHandler
  - tcpwm_1_interrupts_10_IRQHandler
  - cpuss_interrupts_fault_0_IRQHandler
  - cpuss_interrupts_dw0_12_IRQHandler
  - ioss_interrupts_gpio_6_IRQHandler
  - tcpwm_1_interrupts_21_IRQHandler
  - tcpwm_1_interrupts_16_IRQHandler
  - cpuss_interrupts_dw1_4_IRQHandler
  - udb_interrupts_15_IRQHandler
  - cpuss_interrupts_dw1_11_IRQHandler
  - cpuss_interrupts_dw0_6_IRQHandler
  - ioss_interrupt_vdd_IRQHandler
  - audioss_interrupt_i2s_IRQHandler
  - tcpwm_1_interrupts_5_IRQHandler
  - cpuss_interrupts_ipc_2_IRQHandler
  - cpuss_interrupts_dw0_10_IRQHandler
  - tcpwm_1_interrupts_19_IRQHandler
  - cpuss_interrupts_dw0_1_IRQHandler
  - ioss_interrupts_gpio_9_IRQHandler
  - usb_interrupt_lo_IRQHandler
  - cpuss_interrupts_ipc_8_IRQHandler
  - udb_interrupts_14_IRQHandler
  - cpuss_interrupts_dw0_7_IRQHandler
  - cpuss_interrupts_dw1_2_IRQHandler
  - cpuss_interrupts_cm0_cti_0_IRQHandler
  - ioss_interrupts_gpio_13_IRQHandler
  - cpuss_interrupts_dw0_3_IRQHandler
  0x10020391:
  - Fault_Handler
  - HardFault_Handler
  - UsageFault_Handler
  - MemManage_Handler
  - BusFault_Handler
  0x100203ad: Cy_SysIpcPipeIsrCm4
  0x100203b7: Cy_SystemInit
  0x100203b9: SystemCoreClockUpdate
  0x10020431: SystemInit
  0x10020469: Cy_SystemInitFpuEnable
  0x10020491: cycfg_config_init
  0x100204a9: cycfg_config_reservations
  0x100204bd: init_cycfg_all
  0x100204c9: init_cycfg_clocks
  0x10020535: reserve_cycfg_clocks
  0x10020561: reserve_cycfg_dmas
  0x10020571: init_cycfg_peripherals
  0x10020581: reserve_cycfg_peripherals
  0x10020591: init_cycfg_pins
  0x10020685: reserve_cycfg_pins
  0x1002073d: init_cycfg_routing
  0x10020761: cycfg_ClockStartupError
  0x10020765: init_cycfg_system
  0x100209b1: rx_dma_complete
  0x10020a1d: configure_rx_dma
  0x10020b35: Isr_UART
  0x10020b61: json_hexadecimal_digit
  0x10020b91: json_hexadecimal_value
  0x10020bd1: json_skip_whitespace
  0x10020c91: json_skip_c_style_comments
  0x10020d29: json_skip_all_skippables
  0x10020d91: json_get_string_size
  0x10020f71: is_valid_unquoted_key_char
  0x10020fa7: json_get_key_size
  0x1002101d: json_get_number_size
  0x10021309: json_get_value_size
  0x10021541: json_get_object_size
  0x100216bd: json_get_array_size
  0x10021773: json_parse_string
  0x1002198b: json_parse_key
  0x100219f9: json_parse_number
  0x10021b09: json_parse_value
  0x10021d15: json_parse_object
  0x10021e3f: json_parse_array
  0x10021ef7: json_parse_ex
  0x10021fe5: json_parse
  0x10021ffb: handle_error
  0x10022001: main
  0x100220e9: Cy_SysLib_DelayCycles
  0x100220ee: Cy_DelayCycles_loop
  0x100220f6: Cy_DelayCycles_done
  0x100220fb: Cy_SysLib_EnterCriticalSection
  0x10022103: Cy_SysLib_ExitCriticalSection
  0x10022109: _cyhal_get_bit_position
  0x10022241: cyhal_hwmgr_reserve
  0x100222c9: Cy_PDL_Init
  0x100222d5: Cy_BLE_EcoReset
  0x100222f1: Cy_DMA_Descriptor_Init
  0x100224f5: Cy_DMA_Channel_Init
  0x10022611: Cy_Flash_ProcessOpcode
  0x100226e1: Cy_Flash_OperationStatus
  0x10022731: Cy_Flash_InitExt
  0x100227b1: Cy_Flash_Init
  0x100227c1: Cy_GPIO_Pin_Init
  0x10022a2d: Cy_GPIO_Pin_FastInit
  0x10022b05: Cy_IPC_Drv_LockRelease
  0x10022b31: Cy_IPC_Drv_SendMsgWord
  0x10022b51: Cy_IPC_Drv_ReadMsgWord
  0x10022b7d: Cy_IPC_Pipe_Config
  0x10022b91: Cy_IPC_Pipe_EndpointInit
  0x10022c41: Cy_IPC_Pipe_Init
  0x10022cf5: Cy_IPC_Pipe_SendMessage
  0x10022d95: Cy_IPC_Pipe_RegisterCallback
  0x10022dd1: Cy_IPC_Pipe_ExecCallback
  0x10022e75: Cy_IPC_Pipe_ExecuteCallback
  0x10022e95: Cy_IPC_Sema_InitExt
  0x10022f2d: Cy_IPC_Sema_Init
  0x10022f85: Cy_IPC_Sema_Clear
  0x10023009: Cy_IPC_Sema_Status
  0x10023051: Cy_Prot_GetActivePC
  0x10023079: Cy_SCB_UART_Init
  0x10023395: Cy_SysClk_PeriphSetDivider
  0x10023419: Cy_SysClk_PeriphAssignDivider
  0x10023491: Cy_SysClk_PeriphEnableDivider
  0x10023515: Cy_SysClk_PeriphDisableDivider
  0x10023579: Cy_SysClk_ClkSlowSetDivider
  0x10023595: Cy_SysClk_ClkSlowGetDivider
  0x100235ad: Cy_SysClk_ClkBakSetSource
  0x100235cd: Cy_SysClk_ClkTimerSetSource
  0x100235f9: Cy_SysClk_ClkTimerSetDivider
  0x10023611: Cy_SysClk_ClkTimerEnable
  0x10023625: Cy_SysClk_ClkTimerDisable
  0x10023639: Cy_SysClk_ClkLfSetSource
  0x10023659: Cy_SysClk_ClkPeriSetDivider
  0x10023675: Cy_SysClk_ClkPeriGetDivider
  0x10023689: Cy_SysClk_ClkFastSetDivider
  0x100236a5: Cy_SysClk_ClkFastGetDivider
  0x100236bd: Cy_SysClk_ClkHfSetSource
  0x100236fd: Cy_SysClk_ClkHfGetSource
  0x10023721: Cy_SysClk_ClkHfSetDivider
  0x10023761: Cy_SysClk_ClkHfGetDivider
  0x10023785: Cy_SysClk_WcoOkay
  0x10023795: Cy_SysClk_WcoEnable
  0x100237c9: Cy_SysClk_AltHfGetFrequency
  0x100237d5: Cy_SysClk_AltLfGetFrequency
  0x100237d9: Cy_SysClk_IloEnable
  0x100237ed: Cy_SysClk_IloDisable
  0x10023815: Cy_SysClk_IloHibernateOn
  0x10023835: Cy_SysClk_ExtClkGetFrequency
  0x10023841: Cy_SysClk_EcoGetStatus
  0x10023865: Cy_SysClk_EcoGetFrequency
  0x1002387d: Cy_SysClk_ClkPathSetSource
  0x100238d9: Cy_SysClk_ClkPathGetSource
  0x10023915: Cy_SysClk_ClkPathMuxGetFrequency
  0x100239c5: Cy_SysClk_FllIsEnabled
  0x100239d5: Cy_SysClk_FllLocked
  0x100239e5: Cy_SysClk_FllDisable
  0x10023a19: Cy_SysClk_FllManualConfigure
  0x10023b1d: Cy_SysClk_FllGetConfiguration
  0x10023b79: Cy_SysClk_FllEnable
  0x10023c0d: Cy_SysClk_PllIsEnabled
  0x10023c35: Cy_SysClk_PllDisable
  0x10023c81: Cy_SysClk_PllManualConfigure
  0x10023d51: Cy_SysClk_PllGetConfiguration
  0x10023d9d: Cy_SysClk_PllEnable
  0x10023e51: Cy_SysClk_FllGetFrequency
  0x10023ead: Cy_SysClk_PllGetFrequency
  0x10023f59: Cy_SysClk_ClkPathGetFrequency
  0x10023f99: Cy_SysClk_ClkHfGetFrequency
  0x10023fb9: Cy_SysClk_ClkPeriGetFrequency
  0x10023fd3: Cy_SysClk_ClkSlowGetFrequency
  0x10023fed: Cy_SysInt_SetVector
  0x10024025: Cy_SysInt_Init
  0x1002408d: Cy_SysLib_DelayUs
  0x100240a1: Cy_SysLib_ResetBackupDomain
  0x100240c1: Cy_SysLib_GetResetReason
  0x100240f5: Cy_SysLib_ProcessingFault
  0x100240f9: Cy_SysLib_FaultHandler
  0x1002419d: Cy_SysLib_SetWaitStates
  0x1002426d: Cy_SysLib_GetDeviceRevision
  0x10024283: Cy_SysLib_GetDevice
  0x1002429d: SetReadMarginTrimUlp
  0x1002430d: SetWriteAssistTrimLp
  0x10024369: SetWriteAssistTrimUlp
  0x100243b5: SetReadMarginTrimLp
  0x10024425: IsVoltageChangePossible
  0x100244a1: Cy_SysPm_WriteVoltageBitForFlash
  0x1002457d: Cy_SysPm_LdoGetVoltage
  0x1002459d: Cy_SysPm_LdoIsEnabled
  0x100245b1: Cy_SysPm_SystemSetNormalRegulatorCurrent
  0x10024639: Cy_SysPm_SystemIsMinRegulatorCurrentSet
  0x10024661: Cy_SysPm_LdoSetVoltage
  0x10024731: Cy_SysPm_PmicDisableOutput
  0x10024759: Cy_SysPm_PmicUnlock
  0x1002476d: Cy_SysTick_EnableInterrupt
  0x1002477b: Cy_SysTick_SetReload
  0x1002478f: Cy_SysTick_Clear
  0x10024799: Cy_SysTick_GetCountFlag
  0x100247a5: Cy_SysTick_ServiceCallbacks
  0x100247cd: Cy_SysTick_Enable
  0x100247e1: Cy_SysTick_SetClockSource
  0x10024819: Cy_SysTick_Init
  0x10024861: Cy_TrigMux_Connect
  0x10024919: __aeabi_uldivmod
  0x10024949: __udivmoddi4
  0x10024c11:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x10024c15: __libc_init_array
  0x10024c5d: __libc_fini_array
  0x10024c85: malloc
  0x10024c95: sbrk_aligned
  0x10024cd5: _malloc_r
  0x10024dc1: __malloc_lock
  0x10024dcd: __malloc_unlock
  0x10024dd9: _sbrk_r
  0x10024df9: __retarget_lock_acquire_recursive
  0x10024dfb: __retarget_lock_release_recursive
  0x10024dfd: _sbrk
  0x10024e19: _init
  0x10024e25: _fini
  0x10024e30: systemIpcPipeConfigCm4.1
  0x10024e64: CYBSP_CSD_CLK_DIV_obj
  0x10024e68: CYBSP_TRACE_CLK_DIV_obj
  0x10024e6c: peri_0_div_16_15_obj
  0x10024e70: peri_0_div_8_1_obj
  0x10024e74: RxDma_Descriptor_0_config
  0x10024ea4: RxDma_Descriptor_1_config
  0x10024ed4: RxDma_channelConfig
  0x10024ee4: RxDma_obj
  0x10024ee8: KIT_UART_config
  0x10024f28: KIT_UART_obj
  0x10024f2c: CYBSP_CINA_config
  0x10024f60: CYBSP_CINA_obj
  0x10024f64: CYBSP_CINB_config
  0x10024f98: CYBSP_CINB_obj
  0x10024f9c: CYBSP_CMOD_config
  0x10024fd0: CYBSP_CMOD_obj
  0x10024fd4: CYBSP_CSD_BTN0_config
  0x10025008: CYBSP_CSD_BTN0_obj
  0x1002500c: CYBSP_CSD_BTN1_config
  0x10025040: CYBSP_CSD_BTN1_obj
  0x10025044: CYBSP_CSD_SLD0_config
  0x10025078: CYBSP_CSD_SLD0_obj
  0x1002507c: CYBSP_CSD_SLD1_config
  0x100250b0: CYBSP_CSD_SLD1_obj
  0x100250b4: CYBSP_CSD_SLD2_config
  0x100250e8: CYBSP_CSD_SLD2_obj
  0x100250ec: CYBSP_CSD_SLD3_config
  0x10025120: CYBSP_CSD_SLD3_obj
  0x10025124: CYBSP_CSD_SLD4_config
  0x10025158: CYBSP_CSD_SLD4_obj
  0x1002515c: CYBSP_CSD_TX_config
  0x10025190: CYBSP_CSD_TX_obj
  0x10025194: CYBSP_DEBUG_UART_RX_config
  0x100251c8: CYBSP_DEBUG_UART_RX_obj
  0x100251cc: CYBSP_DEBUG_UART_TX_config
  0x10025200: CYBSP_DEBUG_UART_TX_obj
  0x10025204: CYBSP_SWDCK_config
  0x10025238: CYBSP_SWDCK_obj
  0x1002523c: CYBSP_SWDIO_config
  0x10025270: CYBSP_SWDIO_obj
  0x10025274: CYBSP_SWO_config
  0x100252a8: CYBSP_SWO_obj
  0x100252ac: CYBSP_WCO_IN_obj
  0x100252b0: CYBSP_WCO_OUT_obj
  0x100252b4: srss_0_clock_0_fll_0_fllConfig
  0x100252c8: srss_0_clock_0_pathmux_0_obj
  0x100252cc: srss_0_clock_0_pathmux_1_obj
  0x100252d0: srss_0_clock_0_pathmux_2_obj
  0x100252d4: srss_0_clock_0_pathmux_3_obj
  0x100252d8: srss_0_clock_0_pathmux_4_obj
  0x100252dc: srss_0_clock_0_pll_0_pllConfig
  0x10025300: cyhal_block_offsets_can
  0x10025304: cyhal_block_offsets_clock
  0x10025338: cyhal_block_offsets_dma
  0x1002533c: cyhal_block_offsets_dw
  0x10025340: cyhal_block_offsets_gpio
  0x10025360: cyhal_block_offsets_lpcomp
  0x10025364: cyhal_block_offsets_opamp
  0x10025368: cyhal_block_offsets_tcpwm
  0x1002536c: cyhal_block_offsets_tdm
  0x10025370: cyhal_resource_offsets
  0x100253ac: cy_deviceIpBlockCfgPSoC6_01
  0x10025470:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x10025474: __exidx_start
  0x1002547c:
  - __exidx_end
  - __copy_table_start__
  0x10025494:
  - __zero_table_start__
  - __copy_table_end__
  0x1002549c:
  - __etext
  - __zero_table_end__
  0x14000000: __cy_memory_1_start
  0x16000000: __cy_memory_2_start
  0x18000000:
  - __cy_memory_3_start
  - __cy_xip_end
  - __cy_xip_start
  0x90700000: __cy_memory_4_start
