interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: sam3x_pdc_contiguous.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x125a0
symbols:
  0x0:
  - startup_sam3x.c
  - crtstuff.c
  - sysclk.c
  - read.c
  - write.c
  - init.c
  - pdc.c
  - pio.c
  - pio_handler.c
  - pmc.c
  - uart.c
  - usart.c
  - exceptions.c
  - system_sam3x.c
  - syscalls.c
  - pdc_uart_example.c
  - __call_atexit.c
  - memset.c
  - init.c
  - fini.c
  - lock.c
  - atexit.c
  - findfp.c
  - setbuf.c
  - setvbuf.c
  - freer.c
  - stdio.c
  - sbrkr.c
  - fwalk.c
  - writer.c
  - malloc.c
  - __atexit.c
  - mallocr.c
  - fclose.c
  - sysconf.c
  - makebuf.c
  - mlock.c
  - closer.c
  - fflush.c
  - fstatr.c
  - lseekr.c
  - readr.c
  - errno.c
  - crti.o
  - crtn.o
  - impure.c
  - reent.c
  0x2000: __stack_size__
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: deregister_tm_clones
  0x80111: register_tm_clones
  0x80135: __do_global_dtors_aux
  0x8015d: frame_dummy
  0x80181: sysclk_init
  0x801e5: _read
  0x80221: _write
  0x80271: board_init
  0x802f9: pdc_rx_init
  0x80311: pdc_enable_transfer
  0x8031d: pio_set_peripheral
  0x80359: pio_set_input
  0x8038f: pio_set_output
  0x803b5: pio_get_interrupt_status
  0x803b9: pio_get_interrupt_mask
  0x803bd: pio_set_pin_high
  0x803d5: pio_configure_pin
  0x804a5: pio_configure_pin_group
  0x80541: pio_handler_process
  0x80591: PIOA_Handler
  0x805a5: PIOB_Handler
  0x805b9: PIOC_Handler
  0x805cd: PIOD_Handler
  0x805e1: PIOE_Handler
  0x805f5: PIOF_Handler
  0x80609: pmc_switch_mck_to_pllack
  0x80669: pmc_switch_mainck_to_xtal
  0x806bd: pmc_osc_is_ready_mainck
  0x806cd: pmc_disable_pllack
  0x806dd: pmc_is_locked_pllack
  0x806ed: pmc_enable_periph_clk
  0x8070d: uart_init
  0x80741: uart_enable_interrupt
  0x80745: uart_get_status
  0x80749: uart_write
  0x80759: uart_read
  0x8076d: uart_get_pdc_base
  0x80775: usart_write
  0x80789: usart_read
  0x807a1:
  - DACC_Handler
  - DebugMon_Handler
  - DMAC_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - SysTick_Handler
  - USART3_Handler
  - TWI1_Handler
  - PendSV_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - USART0_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - Dummy_Handler
  - TWI0_Handler
  - USART1_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - SVC_Handler
  - TC8_Handler
  - USART2_Handler
  - SDRAMC_Handler
  - SPI1_Handler
  - EMAC_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - UOTGHS_Handler
  - SPI0_Handler
  0x807a5: Reset_Handler
  0x80845: SystemCoreClockUpdate
  0x80959: _sbrk
  0x8098d: _close
  0x80993: _fstat
  0x8099d: _lseek
  0x809a1: usart_serial_getchar
  0x80a45: usart_serial_putchar
  0x80ae1: pwcheck_success
  0x80af5: pwcheck_passed_1
  0x80b05: pwcheck_passed_2
  0x80b15: pwcheck_passed_3
  0x80b25: pwcheck_passed_4
  0x80b35: pwcheck_passed_5
  0x80b45: pwcheck_passed_6
  0x80b55: pwcheck_passed_7
  0x80b65: pwcheck_passed_8
  0x80b75: check_password
  0x80c01: UART_Handler
  0x80c41: main
  0x80d21: register_fini
  0x80d35: memset
  0x80dd5: __libc_init_array
  0x80e25: __libc_fini_array
  0x80e4d: __retarget_lock_init_recursive
  0x80e51: __retarget_lock_close_recursive
  0x80e55: __retarget_lock_acquire_recursive
  0x80e59: __retarget_lock_release_recursive
  0x80e5d: atexit
  0x80e69: stdio_exit_handler
  0x80e81: cleanup_stdio
  0x80ec1: global_stdio_init.part.0
  0x80fb1: __sinit
  0x80fed: __sfp_lock_acquire
  0x80ff9: __sfp_lock_release
  0x81005: setbuf
  0x81015: setvbuf
  0x811b9: _malloc_trim_r
  0x81271: _free_r
  0x81469: __sread
  0x8148d: __swrite
  0x814cd: __sseek
  0x814f1: __sclose
  0x814f9: _sbrk_r
  0x8151d: _fwalk_sglue
  0x81561: _write_r
  0x8158d: malloc
  0x8159d: __register_exitproc
  0x8161d: _malloc_r
  0x81b85: _fclose_r
  0x81c45: sysconf
  0x81c61: __swhatbuf_r
  0x81cc1: __malloc_lock
  0x81ccd: __malloc_unlock
  0x81cd9: _close_r
  0x81cfd: __sflush_r
  0x81e25: _fflush_r
  0x81e79: _fstat_r
  0x81ea1: _lseek_r
  0x81ecd: _read_r
  0x81ef9: __errno
  0x81f05: _init
  0x81f10:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x81f14: __frame_dummy_init_array_entry
  0x81f18: __init_array_end
  0x81f19: _fini
  0x81f24:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x81f28:
  - _etext
  - __TMC_END__
  - __fini_array_end
  - _efixed
  0x20070000: _srelocate
  0x20070001: SystemInit
  0x200700a5: system_init_flash
  0x2007012c: SystemCoreClock
  0x20070130: __atexit_recursive_mutex
  0x20070134: _impure_ptr
  0x20070138: _impure_data
  0x20070258: __sglue
  0x20070264: __malloc_sbrk_base
  0x20070268: __malloc_trim_threshold
  0x20070270: __malloc_av_
  0x20070678:
  - completed.1
  - _sbss
  - _szero
  - _erelocate
  0x2007067c: object.0
  0x20070694: ptr_get
  0x20070698: ptr_put
  0x2007069c: stdio_base
  0x200706a0: gs_interrupt_sources
  0x20070710: heap.0
  0x20070714: g_p_uart_pdc
  0x20070718: g_pdc_uart_packet
  0x20070720: dma_buf
  0x20070728: num_correct
  0x2007072c: __atexit
  0x20070730: __lock___malloc_recursive_mutex
  0x20070734: __lock___atexit_recursive_mutex
  0x20070738: __lock___sfp_recursive_mutex
  0x2007073c: __sf
  0x20070874: __stdio_exit_handler
  0x20070878: __atexit0
  0x20070a08: __malloc_current_mallinfo
  0x20070a30: __malloc_max_total_mem
  0x20070a34: __malloc_max_sbrked_mem
  0x20070a38: __malloc_top_pad
  0x20070a3c: errno
  0x20070a40:
  - _ebss
  - _ezero
  - _sstack
  0x20072a40:
  - _estack
  - _end
  0x20087ffc: __ram_end__
