interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3X_ADC_PDC.ino.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x16b58
symbols:
  0x0:
  - startup_sam3xa.c
  - crtstuff.c
  - ADC_PDC.ino.cpp
  - variant.cpp
  - pio.c
  - pmc.c
  - system_sam3xa.c
  - adc.c
  - uotghs.c
  - WInterrupts.c
  - cortex_handlers.c
  - hooks.c
  - syscalls_sam3.c
  - wiring.c
  - wiring_analog.c
  - wiring_digital.c
  - Reset.cpp
  - RingBuffer.cpp
  - UARTClass.cpp
  - USARTClass.cpp
  - main.cpp
  - watchdog.cpp
  - Print.cpp
  - USBCore.cpp
  - CDC.cpp
  - PluggableUSB.cpp
  - pwmc.c
  - tc.c
  - timetick.c
  - wdt.c
  - uotghs_device.c
  - dacc.c
  - assert.c
  - fiprintf.c
  - init.c
  - memset.c
  - strlen.c
  - syskill.c
  - vfprintf.c
  - wsetup.c
  - __call_atexit.c
  - abort.c
  - atexit.c
  - fflush.c
  - findfp.c
  - fini.c
  - fputwc.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - locale.c
  - makebuf.c
  - mallocr.c
  - memchr-stub.c
  - lib_a-memcpy.o
  - memmove.c
  - mlock.c
  - mallocr.c
  - sbrkr.c
  - signal.c
  - signalr.c
  - stdio.c
  - wbuf.c
  - wcrtomb.c
  - wctomb_r.c
  - writer.c
  - __atexit.c
  - closer.c
  - fclose.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - readr.c
  - _aeabi_uldivmod.o
  - bpabi.c
  - _dvmd_tls.o
  - libgcc2.c
  - libgcc2.c
  - impure.c
  - /home/alejandro/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crti.o
  - /home/alejandro/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crtn.o
  - interrupt_sam_nvic.c
  - reent.c
  - __bss_start__
  - __bss_end__
  - software_init_hook
  - hardware_init_hook
  - __stack
  - free
  - malloc
  - __deregister_frame_info
  - __libc_fini
  - _Jv_RegisterClasses
  - __register_frame_info
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: _Z4plott
  0x80175: loop
  0x801e9: setup
  0x802b5: _Z11serialEventv
  0x802b9: UART_Handler
  0x802c5: _Z12serialEvent1v
  0x802c7: _Z12serialEvent2v
  0x802c9: _Z12serialEvent3v
  0x802cd: USART0_Handler
  0x802d9: USART1_Handler
  0x802e5: USART3_Handler
  0x802f1: init
  0x80419: _GLOBAL__sub_I_g_APinDescription
  0x804ed: _Z14serialEventRunv
  0x80531: PIO_PullUp
  0x8053b: PIO_SetPeripheral
  0x80561: PIO_SetInput
  0x80587: PIO_SetOutput
  0x805ad: PIO_Configure
  0x80611: PIO_GetOutputDataStatus
  0x80625: pmc_enable_upll_clock
  0x80639: pmc_enable_periph_clk
  0x8067d: pmc_disable_periph_clk
  0x806bd: pmc_switch_udpck_to_upllck
  0x806d1: pmc_enable_udpck
  0x806dd: SystemInit
  0x80765: Reset_Handler
  0x807dd: adc_init
  0x80875: adc_set_resolution
  0x80883: adc_configure_trigger
  0x80891: adc_configure_power_save
  0x808a7: adc_configure_timing
  0x808c1: adc_start
  0x808c7: adc_enable_channel
  0x808d1: adc_disable_channel
  0x808db: adc_disable_all_channel
  0x808e3: adc_disable_tag
  0x808ed: adc_stop_sequencer
  0x808f7: adc_disable_channel_differential_input
  0x80911: adc_disable_interrupt
  0x80915: adc_get_status
  0x80919: adc_set_bias_current
  0x8092b: adc_disable_ts
  0x80939: UOTGHS_Handler
  0x80949: PIOA_Handler
  0x80981: PIOB_Handler
  0x809b9: PIOC_Handler
  0x809f1: PIOD_Handler
  0x80a29:
  - __halt
  - DACC_Handler
  - DebugMon_Handler
  - DMAC_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - TWI1_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - TWI0_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - TC8_Handler
  - USART2_Handler
  - EMAC_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - SPI0_Handler
  0x80a2b: SVC_Handler
  0x80a2f: PendSV_Handler
  0x80a33: SysTick_Handler
  0x80a49:
  - __empty
  - yield
  0x80a4b:
  - __false
  - sysTickHook
  0x80a4f:
  - __halt
  - pendSVHook
  - svcHook
  0x80a51: _sbrk
  0x80a6d: link
  0x80a73: _close
  0x80a79: _fstat
  0x80a83: _isatty
  0x80a87: _lseek
  0x80a8b: _read
  0x80a91: _write
  0x80ab5: _exit
  0x80ab7: _kill
  0x80ab9: _getpid
  0x80abf: delay
  0x80adb: mapResolution
  0x80aed: analogOutputInit
  0x80af1: analogWrite
  0x80db1: pinMode
  0x80eb9: digitalWrite
  0x80f29: initiateReset
  0x80f35: cancelReset
  0x80f45: tickReset
  0x80f65:
  - _ZN10RingBufferC1Ev
  - _ZN10RingBufferC2Ev
  0x80f7f: _ZN10RingBuffer10store_charEh
  0x80f9d: _ZN9UARTClasscvbEv
  0x80fa1: _ZN9UARTClass9availableEv
  0x80fb3: _ZN9UARTClass4peekEv
  0x80fcf: _ZN9UARTClass4readEv
  0x80ff9: _ZN9UARTClass5flushEv
  0x81011: _ZN9UARTClass5writeEh
  0x81065: _ZN9UARTClass3endEv
  0x810a1:
  - _ZN9UARTClassC1EP4Uart4IRQnmP10RingBufferS4_
  - _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x810c5: _ZN9UARTClass4initEmm
  0x81135: _ZN9UARTClass5beginEm
  0x8113d: _ZN9UARTClass10IrqHandlerEv
  0x81197: _ZN10USARTClass5beginEm
  0x811a1:
  - _ZN10USARTClassC1EP5Usart4IRQnmP10RingBufferS4_
  - _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x811c5: initVariant
  0x811c9: main
  0x81201:
  - _Z13watchdogSetupv
  - _watchdogDefaultSetup
  0x8120d: _ZN5Print5writeEPKhj
  0x81231: _ZL11USB_SendZlpv
  0x81251: _Z14USBD_Availablem
  0x8127d: _Z9USBD_RecvmPvm
  0x812f9: _Z9USBD_Recvm
  0x8131d: _Z9USBD_SendmPKvm
  0x81369: _Z16USBD_SendControlhPKvm
  0x813a9: _ZL24USB_SendStringDescriptorPKhi
  0x8140d: _Z16USBD_RecvControlPvm
  0x81429: _Z26USBD_ClassInterfaceRequestR8USBSetup
  0x81447: _Z19USBD_SendInterfacesv
  0x81469: _Z24USBD_SendOtherInterfacesv
  0x8148b: _Z10USBD_Flushm
  0x814a1:
  - _ZN10USBDevice_C2Ev
  - _ZN10USBDevice_C1Ev
  0x814c5: _ZN10USBDevice_6attachEv
  0x814e5: _GLOBAL__sub_I_EndPoints
  0x814f1: _ZL7USB_ISRv
  0x81945: _ZN7Serial_9availableEv
  0x8195d: _ZN7Serial_17availableForWriteEv
  0x81965: _ZN7Serial_4peekEv
  0x81985: _ZN7Serial_5writeEh
  0x8199d: _ZN7Serial_4readEv
  0x819e1: _ZN7Serial_5flushEv
  0x819e9: _ZN7Serial_6acceptEv
  0x81a59: _ZN7Serial_5writeEPKhj
  0x81a85: _Z16CDC_GetInterfacePh
  0x81a99: _Z21CDC_GetOtherInterfacePh
  0x81aad: _Z9CDC_SetupR8USBSetup
  0x81b25: _GLOBAL__sub_I_cdc_rx_buffer
  0x81b41: _ZN13PluggableUSB_12getInterfaceEPh
  0x81b69: _ZN13PluggableUSB_13getDescriptorER8USBSetup
  0x81b85: _ZN13PluggableUSB_12getShortNameEPc
  0x81ba1: _ZN13PluggableUSB_5setupER8USBSetup
  0x81bc1: _Z12PluggableUSBv
  0x81be9: FindClockConfiguration
  0x81c65: PWMC_ConfigureChannel
  0x81cc5: PWMC_ConfigureClocks
  0x81d19: PWMC_SetPeriod
  0x81d35: PWMC_SetDutyCycle
  0x81d79: PWMC_EnableChannel
  0x81d85: TC_Configure
  0x81dbd: TC_Start
  0x81de9: TC_SetRA
  0x81df1: TC_SetRB
  0x81df9: TC_SetRC
  0x81e01: TimeTick_Increment
  0x81e11: GetTickCount
  0x81e1d: WDT_Disable
  0x81e25: UDD_SetStack
  0x81e31: UDD_Init
  0x81f01: UDD_Attach
  0x81f51: UDD_InitEP
  0x81f7d: UDD_InitEndpoints
  0x81fb9: UDD_WaitIN
  0x81fc9: UDD_WaitOUT
  0x81fd9: UDD_ClearIN
  0x81ff1: UDD_ClearOUT
  0x82009: UDD_ReceivedSetupInt
  0x82019: UDD_ClearSetupInt
  0x82029: UDD_Send
  0x820b1: UDD_Send8
  0x820d5: UDD_Recv8
  0x820fd: UDD_Recv
  0x82131: UDD_Stall
  0x82145: UDD_FifoByteCount
  0x82159: UDD_ReleaseRX
  0x82181: UDD_ReleaseTX
  0x821a9: UDD_SetAddress
  0x821c9: dacc_reset
  0x821cf: dacc_set_transfer_mode
  0x821e3: dacc_get_interrupt_status
  0x821e7: dacc_write_conversion_data
  0x821eb: dacc_set_channel_selection
  0x82203: dacc_set_power_save
  0x82227: dacc_set_timing
  0x82253: dacc_enable_channel
  0x82265: dacc_get_channel_status
  0x82269: dacc_set_analog_control
  0x82271: __assert_func
  0x822ad: fiprintf
  0x822d5: __libc_init_array
  0x82325: memset
  0x823b9: strlen
  0x82419: kill
  0x82429: __sprint_r.part.0
  0x824a1: _vfiprintf_r
  0x830f5: __sbprintf
  0x83171: __swsetup_r
  0x83235: register_fini
  0x83249: abort
  0x83259: atexit
  0x83265: __sflush_r
  0x833ad: _fflush_r
  0x833d9: _cleanup_r
  0x833e5: __sinit
  0x834d9: __sfp_lock_acquire
  0x834dd: __sfp_lock_release
  0x834e1: __libc_fini_array
  0x83511: _fputwc_r
  0x835d1: _malloc_trim_r
  0x8366d: _free_r
  0x83805: __sfvwrite_r
  0x83b19: _fwalk
  0x83b61: __locale_charset
  0x83b69: __locale_mb_cur_max
  0x83b75: __smakebuf_r
  0x83c55: _malloc_r
  0x8418d: memchr
  0x84221: memcpy
  0x8430d: memmove
  0x843d9: __malloc_lock
  0x843dd: __malloc_unlock
  0x843e1: _realloc_r
  0x847a1: _sbrk_r
  0x847c5: _raise_r
  0x8481d: raise
  0x8482d: _kill_r
  0x84855: _getpid_r
  0x84859: __sread
  0x8487d: __swrite
  0x848b5: __sseek
  0x848d5: __sclose
  0x848dd: __swbuf_r
  0x84985: _wcrtomb_r
  0x849d5: __ascii_wctomb
  0x849f1: _write_r
  0x84a19: __register_exitproc
  0x84ac1: _close_r
  0x84ae5: _fclose_r
  0x84b65: fclose
  0x84b75: _fstat_r
  0x84b9d: _isatty_r
  0x84bc1: _lseek_r
  0x84be9: _read_r
  0x84c11: __aeabi_uldivmod
  0x84c3d: __gnu_ldivmod_helper
  0x84c6d: __gnu_uldivmod_helper
  0x84c9d:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x84ca1: __divdi3
  0x84f41: __udivdi3
  0x851d0: g_APinDescription
  0x85c3c: channelToId.9433
  0x85c84: channelToTC.9432
  0x85ccc: channelToChNo.9430
  0x85d14: channelToAB.9431
  0x85d60: _ZTV9UARTClass
  0x85d90: _ZTV10USARTClass
  0x85dc0: STRING_PRODUCT
  0x85dcc: USB_DeviceDescriptor
  0x85dde: STRING_LANGUAGE
  0x85de2: _ZL18test_packet_buffer
  0x85e17: STRING_MANUFACTURER
  0x85e23: USB_DeviceDescriptorA
  0x85e35: _ZL19USB_DeviceQualifier
  0x85e40: _ZTV7Serial_
  0x85e68: _ZL18_cdcOtherInterface
  0x85eaa: _ZL13_cdcInterface
  0x85f18: __func__.6830
  0x85f2d: __func__.6841
  0x8610b: __func__.6804
  0x86121: __func__.6793
  0x86138: __func__.6792
  0x86199: __func__.6798
  0x861e8: _global_impure_ptr
  0x861ec: blanks.6717
  0x8622c: zeroes.6718
  0x8623d: _init
  0x86248:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x8624c: __frame_dummy_init_array_entry
  0x8625c: __init_array_end
  0x8625d: _fini
  0x86268:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x8626c:
  - __fini_array_end
  - _efixed
  0x86274: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: input
  0x20070030: pwm
  0x20070034: _ZZ4loopE6pwmCnt
  0x20070038: led
  0x2007003c: SystemCoreClock
  0x20070040: _writeResolution
  0x20070044: _ZL5ticks
  0x20070048: EndPoints
  0x20070070: _ZL10breakValue
  0x20070074: _ZL12_usbLineInfo
  0x2007007c: g_interrupt_enabled
  0x20070080: impure_data
  0x200704a8: _impure_ptr
  0x200704ac: lc_ctype_charset
  0x200704cc: __mb_cur_max
  0x200704d0: __malloc_av_
  0x200708d8: __malloc_trim_threshold
  0x200708dc: __malloc_sbrk_base
  0x200708e0: __wctomb
  0x200708e4:
  - completed.7857
  - _sbss
  - _szero
  - _erelocate
  0x200708e8: object.7862
  0x20070900: buf
  0x200710d0: tx_buffer2
  0x20071158: tx_buffer1
  0x200711e0: Serial
  0x20071204: rx_buffer1
  0x2007128c: Serial1
  0x200712b4: Serial2
  0x200712dc: Serial3
  0x20071304: tx_buffer3
  0x2007138c: tx_buffer4
  0x20071414: g_pinStatus
  0x20071464: rx_buffer2
  0x200714ec: rx_buffer3
  0x20071574: rx_buffer4
  0x200715fc: gpf_isr
  0x20071600: callbacksPioA
  0x20071680: callbacksPioB
  0x20071700: callbacksPioC
  0x20071780: callbacksPioD
  0x20071800: heap.6420
  0x20071804: PWMEnabled
  0x20071805: TCChanEnabled
  0x2007180e: _cmark
  0x20071810: _ZL14isEndpointHalt
  0x20071814: _cdcComposite
  0x20071818: _ZL21isRemoteWakeUpEnabled
  0x2007181c: _usbInitialized
  0x20071820: USBDevice
  0x20071824: _usbSetInterface
  0x20071828: _cend
  0x2007182c: _usbConfiguration
  0x20071830: cdc_rx_buffer
  0x20071a38: _ZZN7Serial_6acceptEvE5guard
  0x20071a3c: SerialUSB
  0x20071a50: _ZZ12PluggableUSBvE3obj
  0x20071a58: _ZGVZ12PluggableUSBvE3obj
  0x20071a5c: _dwTickCount
  0x20071a60: ul_recv_fifo_ptr
  0x20071a88: ul_send_fifo_ptr
  0x20071ab0: __malloc_max_total_mem
  0x20071ab4: __malloc_max_sbrked_mem
  0x20071ab8: __malloc_top_pad
  0x20071abc: __malloc_current_mallinfo
  0x20071ae4: errno
  0x20071ae8:
  - _ebss
  - _ezero
  - _end
  0x20088000:
  - __StackTop
  - __StackLimit
  - _estack
