interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: renesas_picohttpparser.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1020034
symbols:
  0x0:
  - startup.c
  - vector_data.c
  - bsp_rom_registers.c
  - crtstuff.c
  - SEGGER_RTT.c
  - SEGGER_RTT_printf.c
  - hal_entry.c
  - picohttpparser.c
  - spi_ep.c
  - main.c
  - r_spi.c
  - r_ioport.c
  - r_dtc.c
  - bsp_clocks.c
  - bsp_common.c
  - bsp_delay.c
  - bsp_group_irq.c
  - bsp_irq.c
  - bsp_register_protection.c
  - system.c
  - board_init.c
  - memcpy-stub.c
  - memset.c
  - crti.o
  - crtn.o
  - hal_data.c
  - pin_data.c
  - libc_a-strlen.o
  - crtstuff.c
  - common_data.c
  - bsp_io.c
  - __Vectors
  - __ospi_device_1_non_retentive_size__
  - __dtcm_data_end
  - XIP_SECONDARY_SLOT_IMAGE
  - OSPI_DEVICE_0_PRV_LENGTH
  - __bl_FLASH_NSC_START
  - __ospi_device_0_non_retentive_size__
  - __OPTION_SETTING_OFS_End
  - __tz_OPTION_SETTING_S
  - __dtcm_bss_start
  - __tz_DTCM_S
  - RAM_NS_BUFFER_BLOCK_LENGTH
  - USE_OPTION_SETTING_NS
  - OPTION_SETTING_START
  - QSPI_FLASH_PRV_LENGTH
  - ITCM_START
  - FLASH_START
  - __itcm_data_end
  - __OPTION_SETTING_NS_Start
  - __bl_FLASH_IMAGE_END
  - __bl_FLASH_IMAGE_LENGTH
  - OPTION_SETTING_LENGTH
  - DTCM_START
  - __tz_DTCM_N
  - __itcm_data_start
  - FLASH_ORIGIN
  - __qspi_non_retentive_size__
  - OSPI_DEVICE_1_LENGTH
  - PROJECT_SECURE_OR_FLAT
  - __RESERVE_NS_RAM
  - __bln_FLASH_IMAGE_LENGTH
  - ITCM_LENGTH
  - __OPTION_SETTING_OFS_Start
  - __tz_ITCM_N
  - __bl_FLASH_NS_IMAGE_START
  - __ROM_Start
  - __ospi_device_0_code_size__
  - __dtcm_data_start
  - __OPTION_SETTING_NS_End
  - DTCM_LENGTH
  - __dtcm_bss_end
  - OPTION_SETTING_SAS_LENGTH
  - __bl_RAM_NS_START
  - RAM_NS_BUFFER_LENGTH
  - OSPI_DEVICE_1_PRV_LENGTH
  - OPTION_SETTING_S_LENGTH
  - __ospi_device_1_code_size__
  - __bl_RAM_NSC_START
  - __bl_XIP_SECONDARY_FLASH_IMAGE_END
  - __bl_FLASH_IMAGE_START
  - __tz_ITCM_S
  - __tz_FLASH_S
  - OSPI_DEVICE_0_LENGTH
  - __qspi_flash_code_size__
  - __bln_FLASH_IMAGE_START
  - __bl_XIP_SECONDARY_FLASH_IMAGE_START
  - SDRAM_LENGTH
  - QSPI_FLASH_LENGTH
  - __bl_FLASH_NS_START
  0x1:
  - __bln_FSP_BOOTABLE_IMAGE
  - __bl_FSP_BOOTABLE_IMAGE
  0x20: ID_CODE_LENGTH
  0x34:
  - OPTION_SETTING_SAS_SIZE
  - __OPTION_SETTING_SAS_Start
  - __OPTION_SETTING_SAS_End
  0x40: g_vector_table
  0x80:
  - __tz_OPTION_SETTING_N
  - OPTION_SETTING_START_NS
  0xc0:
  - __Vectors_Size
  - __Vectors_End
  0x400: g_bsp_rom_registers
  0x43d: deregister_tm_clones
  0x459: register_tm_clones
  0x47d: __do_global_dtors_aux
  0x4a5: frame_dummy
  0x4c9: _WriteNoCheck
  0x501: _WriteBlocking
  0x565: _DoInit
  0x5d1: SEGGER_RTT_WriteNoLock
  0x65d: SEGGER_RTT_Write
  0x691: _StoreChar
  0x6d1: _PrintUnsigned
  0x7c5: SEGGER_RTT_vprintf
  0xb71: SEGGER_RTT_printf
  0xb91: hal_entry
  0xc39: R_BSP_WarmStart
  0xc51: is_complete
  0xcbd: parse_http_version
  0xd25: get_token_to_eol
  0xe59: parse_headers
  0xf61: phr_parse_request
  0x10d1: spi_init
  0x1161: spi_write_and_read
  0x127d: spi_master_callback
  0x1295: spi_slave_callback
  0x12ad: main
  0x12b9: r_spi_call_callback
  0x12f9: R_SPI_Close
  0x13d9: r_spi_write_read_common
  0x159d: R_SPI_Read
  0x15b5: R_SPI_Open
  0x18ed: spi_rxi_isr
  0x198d: spi_txi_isr
  0x1a65: spi_tei_isr
  0x1b4d: spi_eri_isr
  0x1c39: bsp_vbatt_init
  0x1d21: r_ioport_pins_config
  0x1dbd: R_IOPORT_Open
  0x1df1: R_DTC_SoftwareStart
  0x1df5: R_DTC_SoftwareStop
  0x1df9: R_DTC_Disable
  0x1e2d: R_DTC_Reload
  0x1e31: R_DTC_CallbackSet
  0x1e35: r_dtc_length_assert
  0x1e6d: R_DTC_InfoGet
  0x1edd: R_DTC_Close
  0x1f21: r_dtc_prv_enable.isra.0
  0x1f95: R_DTC_Reset
  0x2000: DATA_FLASH_LENGTH
  0x2031: R_DTC_Enable
  0x2051: R_DTC_Reconfigure
  0x20f1: R_DTC_Open
  0x21bd: SystemCoreClockUpdate
  0x21e5: bsp_clock_init
  0x22d1: R_BSP_Init_RTC
  0x22f9: R_FSP_VersionGet
  0x230c: sw_delay_loop
  0x230d: bsp_prv_software_delay_loop
  0x2319: R_BSP_SoftwareDelay
  0x2369: NMI_Handler
  0x23a5: bsp_irq_cfg
  0x23d5: R_BSP_RegisterProtectEnable
  0x2435: R_BSP_RegisterProtectDisable
  0x2489:
  - DebugMon_Handler
  - HardFault_Handler
  - SysTick_Handler
  - PendSV_Handler
  - UsageFault_Handler
  - SecureFault_Handler
  - Default_Handler
  - MemManage_Handler
  - SVC_Handler
  - BusFault_Handler
  0x248d: Reset_Handler
  0x2499: SystemInit
  0x25f1: bsp_init
  0x25f5: memcpy
  0x2611: memset
  0x2620: g_fsp_version_build_string
  0x2664: g_fsp_version_string
  0x266c: g_fsp_version
  0x2671: _init
  0x267d: _fini
  0x2b28: _aInitStr.0
  0x2b3c: _aV2C.0
  0x2c50: __FUNCTION__.3
  0x2c64: __FUNCTION__.4
  0x2c70: g_spi_master_cfg
  0x2c94: g_spi_master_ext_cfg
  0x2ca0: g_transfer0
  0x2cac: g_transfer0_cfg
  0x2cb4: g_transfer0_cfg_extend
  0x2cb8: g_transfer1
  0x2cc4: g_transfer1_cfg
  0x2ccc: g_transfer1_cfg_extend
  0x2cd0: g_spi_slave_cfg
  0x2cf4: g_spi_slave_ext_cfg
  0x2d00: g_transfer2
  0x2d0c: g_transfer2_cfg
  0x2d14: g_transfer2_cfg_extend
  0x2d18: g_transfer3
  0x2d24: g_transfer3_cfg
  0x2d2c: g_transfer3_cfg_extend
  0x2d30: g_bsp_pin_cfg
  0x2d3c: g_bsp_pin_cfg_data
  0x2d7c: g_interrupt_event_link_select
  0x2d9c: g_vbatt_pins_input
  0x2da4: g_transfer_on_dtc
  0x2dd0: g_prcr_masks
  0x2dd8:
  - __EH_FRAME_BEGIN__
  - __usb_descriptor_end_hs
  - __usb_cfg_descriptor_start_fs
  - __usb_descriptor_end_fs
  - __usb_interface_descriptor_start_hs
  - __usb_cfg_descriptor_start_hs
  - __usb_dev_descriptor_start_hs
  - __usb_interface_descriptor_start_fs
  - __usb_dev_descriptor_start_fs
  0x2e00: __FRAME_END__
  0x2e04:
  - __ROM_End
  - __exidx_end
  - __etext
  - __itcm_data_pre_location
  - __exidx_start
  0x2e10:
  - __itcm_data_init_start
  - __itcm_data_init_end
  0x2e50:
  - __qspi_flash_code_addr__
  - sgstubs_pre_location
  - __ospi_device_0_code_addr__
  - __dtcm_data_init_start
  - __ospi_device_1_code_addr__
  - __dtcm_data_pre_location
  - __dtcm_data_init_end
  0x3000:
  - SGSTUBS_LOC
  - _start_sg
  - __tz_FLASH_C
  - _end_sg
  0x8000:
  - __tz_FLASH_N
  - FLASH_NS_IMAGE_START
  0x18000: RAM_LENGTH
  0x80000:
  - FLASH_LENGTH
  - LIMITED_FLASH_LENGTH
  0x1010018:
  - g_bsp_id_codes
  - ID_CODE_START
  - __tz_ID_CODE_N
  - __ID_Code_Start
  - __tz_ID_CODE_S
  0x1010034: __ID_Code_End
  0x4000000: __qspi_region_max_size__
  0x8000000: __ospi_device_0_region_max_size__
  0x10000000: __ospi_device_1_region_max_size__
  0x20000000:
  - gp_dtc_vector_table
  - RAM_START
  - __tz_RAM_S
  0x20000080:
  - g_wait_count
  - __data_start__
  - __Code_In_RAM_End
  - __Code_In_RAM_Start
  0x20000084: g_transfer0_info
  0x20000094: g_transfer1_info
  0x200000a4: g_transfer2_info
  0x200000b4: g_transfer3_info
  0x200000c4:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x200000c8:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x200000cc:
  - g_clock_freq
  - __TMC_END__
  - __data_end__
  - __noinit_start
  0x200000e0:
  - completed.1
  - __bss_start__
  - __noinit_end
  0x200000e4: object.0
  0x200000fc: _acDownBuffer
  0x2000013c: _acUpBuffer
  0x2000093c: _SEGGER_RTT
  0x200009e4: g_slave_rx_buff
  0x200019e4: g_master_rx_buff
  0x200029e4: g_master_tx_buff
  0x200039e4: g_slave_event_flag
  0x200039e5: g_master_event_flag
  0x200039e8: g_ioport_ctrl
  0x200039f0: g_spi_master_ctrl
  0x20003a20: g_transfer0_ctrl
  0x20003a28: g_transfer1_ctrl
  0x20003a30: g_spi_slave_ctrl
  0x20003a60: g_transfer2_ctrl
  0x20003a68: g_transfer3_ctrl
  0x20003a70: dummy_tx.0
  0x20003a74: dummy_rx.1
  0x20003a78: g_dtc_state_initialized.0
  0x20003a7c: g_bsp_group_irq_sources
  0x20003ab0: g_protect_pfswe_counter
  0x20003ab4: gp_renesas_isr_context
  0x20003b34: g_protect_counters
  0x20003b3c: SystemCoreClock
  0x20003b40:
  - g_heap
  - __HeapBase
  - __bss_end__
  0x20003f40:
  - g_main_stack
  - __HeapLimit
  - __StackLimit
  0x20004340:
  - __StackTopAll
  - __RAM_segment_used_end__
  - __StackTop
  - __stack
  0x20004400: __tz_RAM_C
  0x20006000: __tz_RAM_N
  0x20018000:
  - RAM_NS_BUFFER_START
  - RAM_NS_BUFFER_BLOCK_START
  0x40100000:
  - __Data_Flash_End
  - DATA_FLASH_START
  - __tz_DATA_FLASH_N
  - __tz_DATA_FLASH_S
  - __Data_Flash_Start
  0x60000000:
  - __qspi_region_start_address__
  - __qspi_non_retentive_start__
  - QSPI_FLASH_START
  - __tz_QSPI_FLASH_N
  - __qspi_flash_end__
  - __qspi_flash_start__
  - __tz_QSPI_FLASH_S
  - __qspi_non_retentive_end__
  0x64000000: __qspi_region_end_address__
  0x80000000:
  - __tz_OPTION_SETTING_S_N
  - OPTION_SETTING_S_START
  - __tz_OPTION_SETTING_S_S
  - __OPTION_SETTING_S_Start
  - __OPTION_SETTING_S_End
  0x80010000:
  - __tz_SDRAM_S
  - SDRAM_START
  - __tz_SDRAM_N
  - __SDRAM_Start
  - __SDRAM_End
  0x80020000:
  - __tz_OSPI_DEVICE_0_N
  - __ospi_device_0_non_retentive_end__
  - __ospi_device_0_non_retentive_start__
  - __ospi_device_0_region_start_address__
  - OSPI_DEVICE_0_START
  - __ospi_device_0_end__
  - __ospi_device_0_start__
  - __tz_OSPI_DEVICE_0_S
  0x80030000:
  - __tz_OSPI_DEVICE_1_N
  - __ospi_device_1_non_retentive_start__
  - __ospi_device_1_region_start_address__
  - OSPI_DEVICE_1_START
  - __ospi_device_1_non_retentive_end__
  - __ospi_device_1_end__
  - __tz_OSPI_DEVICE_1_S
  - __ospi_device_1_start__
  0x88020000: __ospi_device_0_region_end_address__
  0x90030000: __ospi_device_1_region_end_address__
