interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_10001200:
    base_addr: 0xfffc000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10005000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: NRF52832_uart.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1265c
symbols:
  0x0:
  - _build/nrf52832_xxaa_gcc_startup_nrf52.S.o
  - crtstuff.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/nofp/crt0.o
  - exit.c
  - init.c
  - memset.c
  - _exit.c
  - app_error.c
  - app_error_weak.c
  - app_fifo.c
  - app_uart_fifo.c
  - retarget.c
  - boards.c
  - nrf_drv_common.c
  - nrf_drv_uart.c
  - main.c
  - system_nrf52.c
  - printf.c
  - findfp.c
  - fwalk.c
  - lock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - sbrkr.c
  - stdio.c
  - wbuf.c
  - writer.c
  - wsetup.c
  - closer.c
  - fflush.c
  - lseekr.c
  - makebuf.c
  - lib_a-memchr.o
  - mlock.c
  - nano-mallocr.c
  - readr.c
  - fstatr.c
  - isattyr.c
  - close.c
  - fstat.c
  - isatty.c
  - lseek.c
  - sbrk.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/crti.o
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/crtn.o
  - impure.c
  - crtstuff.c
  - reent.c
  - __isr_vector
  0x401: __do_global_dtors_aux
  0x425: frame_dummy
  0x441:
  - _mainCRTStartup
  - _start
  0x4b5: exit
  0x4dd: __libc_init_array
  0x525: memset
  0x535: _exit
  0x539: app_error_handler_bare
  0x559: app_error_fault_handler
  0x57d: app_fifo_init
  0x59d: app_fifo_put
  0x5c9: app_fifo_get
  0x5f1: uart_event_handler
  0x6bd: app_uart_init
  0x7a1: app_uart_get
  0x7e1: app_uart_put
  0x825: _write
  0x841: _read
  0x855: bsp_board_leds_init
  0x891: nrf_drv_common_irq_enable
  0x8d9: nrf_drv_uart_init
  0xa7d: nrf_drv_uart_tx
  0xbd9: nrf_drv_uart_tx_in_progress
  0xbf1: nrf_drv_uart_rx
  0xe59: nrf_drv_uart_rx_enable
  0xea5: UARTE0_UART0_IRQHandler
  0x1189: uart_error_handle
  0x119d: main
  0x1221: Reset_Handler
  0x1249: NMI_Handler
  0x124b: HardFault_Handler
  0x124d: MemoryManagement_Handler
  0x124f: BusFault_Handler
  0x1251: UsageFault_Handler
  0x1253: SVC_Handler
  0x1255: DebugMon_Handler
  0x1257: PendSV_Handler
  0x1259: SysTick_Handler
  0x125b:
  - TIMER2_IRQHandler
  - RTC0_IRQHandler
  - SWI0_EGU0_IRQHandler
  - SWI2_EGU2_IRQHandler
  - GPIOTE_IRQHandler
  - PWM1_IRQHandler
  - POWER_CLOCK_IRQHandler
  - RADIO_IRQHandler
  - PDM_IRQHandler
  - TEMP_IRQHandler
  - QDEC_IRQHandler
  - TIMER3_IRQHandler
  - FPU_IRQHandler
  - SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler
  - TIMER4_IRQHandler
  - I2S_IRQHandler
  - SWI4_EGU4_IRQHandler
  - TIMER0_IRQHandler
  - TIMER1_IRQHandler
  - PWM2_IRQHandler
  - ECB_IRQHandler
  - SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler
  - Default_Handler
  - SAADC_IRQHandler
  - CCM_AAR_IRQHandler
  - WDT_IRQHandler
  - SWI5_EGU5_IRQHandler
  - RNG_IRQHandler
  - RTC2_IRQHandler
  - PWM0_IRQHandler
  - SWI3_EGU3_IRQHandler
  - RTC1_IRQHandler
  - SWI1_EGU1_IRQHandler
  - SPIM2_SPIS2_SPI2_IRQHandler
  - NFCT_IRQHandler
  - MWU_IRQHandler
  - COMP_LPCOMP_IRQHandler
  0x125d: SystemInit
  0x152d:
  - printf
  - iprintf
  0x155d: std
  0x15a5: _cleanup_r
  0x15b1: __sfmoreglue
  0x15dd: __sfp_lock_acquire
  0x15e9: __sfp_lock_release
  0x15f5: __sinit_lock_acquire
  0x1601: __sinit_lock_release
  0x160d: __sinit
  0x167d: __sfp
  0x1709: _fwalk_reent
  0x1747: __retarget_lock_init_recursive
  0x1749: __retarget_lock_acquire_recursive
  0x174b: __retarget_lock_release_recursive
  0x174d: _malloc_r
  0x1801: __sfputc_r
  0x182b: __sfputs_r
  0x1851:
  - _vfiprintf_r
  - _vfprintf_r
  0x1ab1: _printf_common
  0x1b8d: _printf_i
  0x1dd9: _sbrk_r
  0x1df9: __sread
  0x1e1b: __swrite
  0x1e53: __sseek
  0x1e77: __sclose
  0x1e81: __swbuf_r
  0x1f25: _write_r
  0x1f49: __swsetup_r
  0x2000:
  - Stack_Size
  - Heap_Size
  0x2025: _close_r
  0x2045: __sflush_r
  0x2151: _fflush_r
  0x21c9: _lseek_r
  0x21ed: __swhatbuf_r
  0x2235: __smakebuf_r
  0x22c1: memchr
  0x2361: __malloc_lock
  0x236d: __malloc_unlock
  0x2379: _free_r
  0x2415: _read_r
  0x2439: _fstat_r
  0x245d: _isatty_r
  0x247d: _close
  0x248d: _fstat
  0x249d: _isatty
  0x24ad: _lseek
  0x24bd: _sbrk
  0x24d9: _init
  0x24e5: _fini
  0x24f0: _global_impure_ptr
  0x2544: __sf_fake_stderr
  0x2564: __sf_fake_stdin
  0x2584: __sf_fake_stdout
  0x25d8:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x25dc: __exidx_start
  0x25e4:
  - __exidx_end
  - __etext
  0x20000000:
  - __data_start__
  - _impure_ptr
  0x20000004: impure_data
  0x20000064: app_uart_inst
  0x2000006c: SystemCoreClock
  0x20000070:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20000074:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x20000078:
  - completed.8911
  - __bss_start__
  - __data_end__
  0x2000007c: object.8916
  0x20000094: m_event_handler
  0x20000098: m_rx_fifo
  0x200000a8: m_rx_ovf
  0x200000ac: m_tx_fifo
  0x200000bc: rx_buffer
  0x200000c0: tx_buffer
  0x200000c4: m_cb
  0x200000e4: rx_buf.7255
  0x200001e4: tx_buf.7256
  0x200002e4: __malloc_free_list
  0x200002e8: __malloc_sbrk_start
  0x200002ec: heap_end.4144
  0x200002f0: __lock___atexit_recursive_mutex
  0x200002f1: __lock___arc4random_mutex
  0x200002f2: __lock___env_recursive_mutex
  0x200002f3: __lock___sinit_recursive_mutex
  0x200002f4: __lock___malloc_recursive_mutex
  0x200002f5: __lock___at_quick_exit_mutex
  0x200002f6: __lock___dd_hash_mutex
  0x200002f7: __lock___tz_mutex
  0x200002f8: __lock___sfp_recursive_mutex
  0x200002fc: errno
  0x20000300:
  - __HeapBase
  - end
  - __bss_end__
  - __end__
  0x20002300: __HeapLimit
  0x2000e000: __StackLimit
  0x20010000:
  - __StackTop
  - __stack
