interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3X_usart_dmac_example.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x133e0
symbols:
  0x0:
  - startup_sam3x.c
  - crtstuff.c
  - sysclk.c
  - read.c
  - write.c
  - init.c
  - dmac.c
  - pio.c
  - pio_handler.c
  - pmc.c
  - uart.c
  - usart.c
  - usart_example_dmac.c
  - exceptions.c
  - system_sam3x.c
  - syscalls.c
  - init.c
  - memset.c
  - puts.c
  - setbuf.c
  - setvbuf.c
  - strlen-stub.c
  - __call_atexit.c
  - atexit.c
  - fflush.c
  - findfp.c
  - fini.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - lock.c
  - makebuf.c
  - malloc.c
  - mallocr.c
  - memchr-stub.c
  - lib_a-memcpy.o
  - memmove.c
  - mlock.c
  - mallocr.c
  - sbrkr.c
  - stdio.c
  - writer.c
  - wsetup.c
  - __atexit.c
  - closer.c
  - fclose.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - readr.c
  - impure.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7-m/nofp/crti.o
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7-m/nofp/crtn.o
  - reent.c
  0x2000: __stack_size__
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80135: sysclk_init
  0x8017d: _read
  0x801b9: _write
  0x80211: board_init
  0x802c1: dmac_init
  0x802cb: dmac_set_priority_mode
  0x802d7: dmac_enable
  0x802dd: dmac_enable_interrupt
  0x802e1: dmac_get_status
  0x802e5: dmac_channel_enable
  0x802ed: dmac_channel_disable
  0x802f5: dmac_channel_set_configuration
  0x80301: dmac_channel_single_buf_transfer_init
  0x8032d: pio_set_peripheral
  0x80369: pio_set_input
  0x8039b: pio_set_output
  0x803c1: pio_get_interrupt_status
  0x803c5: pio_get_interrupt_mask
  0x803c9: pio_set_pin_high
  0x803e3: pio_set_pin_low
  0x803fd: pio_configure_pin
  0x804c1: pio_configure_pin_group
  0x80551: pio_handler_process
  0x80599: PIOA_Handler
  0x805a9: PIOB_Handler
  0x805b9: PIOC_Handler
  0x805c9: PIOD_Handler
  0x805d9: PIOE_Handler
  0x805e9: PIOF_Handler
  0x805f9: pmc_switch_mck_to_pllack
  0x80659: pmc_switch_mainck_to_xtal
  0x806ad: pmc_osc_is_ready_mainck
  0x806bd: pmc_disable_pllack
  0x806cd: pmc_is_locked_pllack
  0x806dd: pmc_enable_periph_clk
  0x806fd: uart_init
  0x80733: uart_write
  0x80743: uart_read
  0x80755: usart_set_async_baudrate
  0x807b1: usart_reset
  0x807d9: usart_init_rs232
  0x80821: usart_enable_tx
  0x80827: usart_enable_rx
  0x8082d: usart_write
  0x80841: usart_read
  0x80859: configure_dmac_rx
  0x808b1: usart_serial_getchar
  0x8094d: usart_serial_putchar
  0x809e1: DMAC_Handler
  0x80a41: main
  0x80b31:
  - DACC_Handler
  - DebugMon_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - SysTick_Handler
  - USART3_Handler
  - TWI1_Handler
  - PendSV_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - USART0_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - Dummy_Handler
  - TWI0_Handler
  - USART1_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - SVC_Handler
  - TC8_Handler
  - USART2_Handler
  - SDRAMC_Handler
  - SPI1_Handler
  - EMAC_Handler
  - UART_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - UOTGHS_Handler
  - SPI0_Handler
  0x80b35: Reset_Handler
  0x80bc9: SystemCoreClockUpdate
  0x80ce1: _sbrk
  0x80d15: _close
  0x80d1b: _fstat
  0x80d25: _isatty
  0x80d29: _lseek
  0x80d2d: __libc_init_array
  0x80d75: memset
  0x80e15: _puts_r
  0x80eb1: puts
  0x80ec1: setbuf
  0x80ed1: setvbuf
  0x81071: strlen
  0x810cd: register_fini
  0x810e1: atexit
  0x810ed: __sflush_r
  0x8121d: _fflush_r
  0x81279: std
  0x812c9: _cleanup_r
  0x812d5: __sinit
  0x81331: __sfp_lock_acquire
  0x8133d: __sfp_lock_release
  0x81349: __libc_fini_array
  0x81375: _malloc_trim_r
  0x81415: _free_r
  0x81621: __sfvwrite_r
  0x8190d: _fwalk_reent
  0x81955: __retarget_lock_init_recursive
  0x81959: __retarget_lock_close_recursive
  0x8195d: __retarget_lock_acquire_recursive
  0x81961: __retarget_lock_release_recursive
  0x81965: __swhatbuf_r
  0x819c1: __smakebuf_r
  0x81a55: malloc
  0x81a65: _malloc_r
  0x81fc1: memchr
  0x82041: memcpy
  0x8212d: memmove
  0x82201: __malloc_lock
  0x8220d: __malloc_unlock
  0x82219: _realloc_r
  0x825f9: _sbrk_r
  0x8261d: __sread
  0x82641: __swrite
  0x82681: __sseek
  0x826a1: __sclose
  0x826a9: _write_r
  0x826d5: __swsetup_r
  0x827a5: __register_exitproc
  0x82831: _close_r
  0x82855: _fclose_r
  0x82921: _fstat_r
  0x8294d: _isatty_r
  0x82971: _lseek_r
  0x8299d: _read_r
  0x82a38: _global_impure_ptr
  0x82a41: _init
  0x82a4c:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x82a50: __frame_dummy_init_array_entry
  0x82a54: __init_array_end
  0x82a55: _fini
  0x82a61: __system_init_flash_veneer
  0x82a68:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x82a6c:
  - _etext
  - __fini_array_end
  - _efixed
  0x20070000: _srelocate
  0x20070001: SystemInit
  0x200700a5: system_init_flash
  0x2007012c: SystemCoreClock
  0x20070130: _impure_ptr
  0x20070138: impure_data
  0x20070560: __atexit_recursive_mutex
  0x20070564: __malloc_av_
  0x2007096c: __malloc_sbrk_base
  0x20070970: __malloc_trim_threshold
  0x20070974:
  - completed.8911
  - _sbss
  - _szero
  - _erelocate
  0x20070978: object.8916
  0x20070990: gs_interrupt_sources
  0x20070a00: ul_reg_val.7537
  0x20070a04: gs_puc_buffer
  0x20070a24: heap.5364
  0x20070a28: __malloc_current_mallinfo
  0x20070a50: __malloc_max_sbrked_mem
  0x20070a54: __malloc_max_total_mem
  0x20070a58: __malloc_top_pad
  0x20070a5c: ptr_get
  0x20070a60: ptr_put
  0x20070a64: stdio_base
  0x20070a68: __lock___atexit_recursive_mutex
  0x20070a6c: __lock___arc4random_mutex
  0x20070a70: __lock___env_recursive_mutex
  0x20070a74: __lock___sinit_recursive_mutex
  0x20070a78: __lock___malloc_recursive_mutex
  0x20070a7c: __lock___at_quick_exit_mutex
  0x20070a80: __lock___dd_hash_mutex
  0x20070a84: __lock___tz_mutex
  0x20070a88: __lock___sfp_recursive_mutex
  0x20070a8c: errno
  0x20070a90:
  - _ebss
  - _ezero
  - _sstack
  0x20072a90:
  - _estack
  - _end
  0x20087ffc: __ram_end__
