interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .stack:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0xac4
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: K64F-RIOT-USART.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x126dc
symbols:
  0x0:
  - vectors_cortexm.c
  - vectors.c
  - isr_kinetis.c
  - fcfield.c
  - syscalls.c
  - sched.c
  - thread_arch.c
  - irq_arch.c
  - wdog.c
  - stdio_uart.c
  - pm.c
  - board.c
  - panic.c
  - kernel_init.c
  - thread.c
  - pm.c
  - cpu.c
  - isrpipe.c
  - uart.c
  - mcg.c
  - gpio.c
  - tsrb.c
  - init.c
  - main.c
  - auto_init.c
  - mutex.c
  - cortexm_init.c
  - init.c
  - nano-mallocr.c
  - printf.c
  - puts.c
  - wbuf.c
  - wsetup.c
  - fflush.c
  - findfp.c
  - fwalk.c
  - lock.c
  - makebuf.c
  - memset.c
  - mlock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - stdio.c
  - lib_a-memchr.o
  - impure.c
  - _rom_start_addr
  - _sbackup_bss
  - _rom_offset
  - _backup_ram_len
  - _isr_vectors
  - _backup_ram_start_addr
  - cortex_vector_base
  - _ebackup_data
  - _ebackup_bss
  - _sbackup_data
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400:
  - _flash_sec_offset
  - flash_configuration_field
  - _vectors_length
  0x410: _sfixed
  0x411: _init
  0x413: _fini
  0x415: _sbrk_r
  0x451: _read_r
  0x459: _write_r
  0x461: _close_r
  0x46b: _lseek_r
  0x475: _fstat_r
  0x47f: _isatty_r
  0x491: sched_run
  0x4f5: sched_set_status
  0x575: sched_switch
  0x5a5: sched_task_exit
  0x5e1: thread_stack_init
  0x649: cpu_switch_context_exit
  0x64e: unreachable325
  0x651: thread_yield_higher
  0x661: isr_pendsv
  0x67d: isr_svc
  0x681: context_restore
  0x699: hard_fault_default
  0x6ac: fix_msp
  0x6b2: test_sp
  0x6c0: use_psp
  0x6c4: out
  0x6dd: nmi_default
  0x6ed: mem_manage_default
  0x6fd: bus_fault_default
  0x70d: usage_fault_default
  0x71d: debug_mon_default
  0x72d:
  - dummy_handler_default
  - isr_systick
  0x73d: post_startup
  0x741: reset_handler_default
  0x7ad: hard_fault_handler
  0x935: irq_disable
  0x93d: irq_enable
  0x945: irq_restore
  0x94b: irq_is_in
  0x955: pre_startup
  0x969:
  - isr_uart3
  - isr_cmp1
  - isr_i2c1
  - isr_dma5_dma21
  - isr_portb_portc
  - isr_dac0
  - isr_can0_bus_off
  - isr_enet_transmit
  - isr_dma5
  - isr_lpuart5
  - isr_dma8
  - isr_porta
  - isr_ftm3
  - isr_dma3_dma19
  - isr_can0_wake_up
  - isr_adc0
  - isr_portb
  - isr_ftfe_collision
  - isr_cmp3
  - isr_i2c0
  - isr_pit1
  - isr_dac1
  - isr_spi0
  - isr_dma15_dma31
  - isr_dma6_dma22
  - isr_enet_receive
  - isr_llwu
  - isr_lpuart2
  - isr_i2c3
  - isr_dma0
  - isr_can1_error
  - isr_mcg
  - isr_dma14_dma30
  - isr_i2s0_rx
  - isr_tpm1
  - isr_ftfa
  - isr_dma_error
  - isr_ftfa_collision
  - isr_uart2
  - isr_usbhs
  - isr_uart3_rx_tx
  - isr_enet_1588_timer
  - isr_ftfl_collision
  - isr_dma3
  - isr_dma11_dma27
  - isr_ftfl
  - isr_can0_error
  - isr_tpm0
  - isr_dma2_dma18
  - isr_can0_ored_message_buffer
  - isr_dma2
  - isr_usb0
  - isr_i2c2
  - isr_uart2_rx_tx
  - isr_pit2
  - isr_dma7_dma23
  - isr_dma14
  - isr_cmp0
  - isr_spi2
  - isr_uart0
  - isr_dma9
  - isr_dma7
  - dummy_handler
  - isr_can1_rx_warning
  - isr_ftfe
  - isr_uart1
  - isr_uart0_lon
  - isr_uart4_err
  - isr_usbhsdcd
  - isr_dma10_dma26
  - isr_radio_0
  - isr_swi
  - isr_cmp2
  - isr_dma10
  - isr_spi1
  - isr_lpuart0
  - isr_portd
  - isr_uart1_rx_tx
  - isr_can1_bus_off
  - isr_uart5
  - isr_adc2
  - isr_tpm2
  - isr_mscan_tx
  - isr_rtc
  - isr_ftm0
  - isr_dma11
  - isr_lpuart1
  - isr_dma13_dma29
  - isr_mscan_rx
  - isr_porte
  - isr_mcm
  - isr_pit
  - isr_uart5_err
  - isr_radio_1
  - isr_dma4
  - isr_dma12_dma28
  - isr_dma12
  - isr_can0_rx_warning
  - isr_tsi0
  - isr_adc1
  - isr_i2s0_tx
  - isr_uart4
  - isr_sdhc
  - isr_dma6
  - isr_uart3_err
  - isr_dma15
  - isr_ftm2
  - isr_lptmr0
  - isr_dma0_dma16
  - isr_pit0
  - isr_portc
  - isr_can1_ored_message_buffer
  - isr_rtc_seconds
  - isr_can0_tx_warning
  - isr_cmt
  - isr_dma4_dma20
  - isr_can1_wake_up
  - isr_trng0
  - isr_lpuart4
  - isr_rng
  - isr_uart1_err
  - isr_enet_error
  - isr_can1_tx_warning
  - isr_usbdcd
  - isr_dma1_dma17
  - isr_uart4_rx_tx
  - isr_uart0_err
  - isr_uart5_rx_tx
  - isr_ftm1
  - isr_dma9_dma25
  - isr_dma13
  - isr_uart2_err
  - isr_pdb0
  - isr_dma1
  - isr_lpuart3
  - isr_lvd_lvw
  - isr_pit3
  - isr_dma8_dma24
  - isr_wdog_ewm
  0x96d: wdog_disable
  0x985: stdio_init
  0x99d: stdio_read
  0x9ad: stdio_write
  0x9bf: pm_off
  0x9c9: board_init
  0xa2d: panic_arch
  0xa31: core_panic
  0xa75: main_trampoline
  0xa8d: idle_thread
  0xa95: kernel_init
  0xaed: thread_add_to_list
  0xb1d: thread_create
  0xc11: pm_set_lowest
  0xc15: cpu_init
  0xc39: isrpipe_write_one
  0xc4f: isrpipe_read
  0xc75: uart_init
  0xd31: uart_write
  0xd51: isr_uart0_rx_tx
  0xd85: bit_clear8
  0xda5: kinetis_mcg_set_fll_factor
  0xdb9: kinetis_mcg_enable_osc
  0xdd9: kinetis_mcg_set_mode
  0xf59: kinetis_mcg_init
  0x105d: gpio_init_port
  0x1089: gpio_init
  0x10d5: gpio_set
  0x10ef: _pop
  0x1101: tsrb_get
  0x1127: tsrb_add_one
  0x114d: periph_init
  0x1151: main
  0x1181: auto_init
  0x1185: _mutex_lock
  0x11e5: mutex_unlock
  0x1231: cortexm_init
  0x1271: __libc_init_array
  0x12b9: _malloc_r
  0x136d:
  - printf
  - iprintf
  0x139d: _puts_r
  0x1479: puts
  0x1489: __swbuf_r
  0x152d: __swsetup_r
  0x1609: __sflush_r
  0x1715: _fflush_r
  0x178d: std
  0x17d5: _cleanup_r
  0x17e1: __sfmoreglue
  0x180d: __sfp_lock_acquire
  0x1819: __sfp_lock_release
  0x1825: __sinit_lock_acquire
  0x1831: __sinit_lock_release
  0x183d: __sinit
  0x18ad: __sfp
  0x1939: _fwalk_reent
  0x1977: __retarget_lock_init_recursive
  0x1979: __retarget_lock_acquire_recursive
  0x197b: __retarget_lock_release_recursive
  0x197d: __swhatbuf_r
  0x19c5: __smakebuf_r
  0x1a45: memset
  0x1a55: __malloc_lock
  0x1a61: __malloc_unlock
  0x1a6d: _free_r
  0x1b09: __sfputc_r
  0x1b33: __sfputs_r
  0x1b59:
  - _vfiprintf_r
  - _vfprintf_r
  0x1db9: _printf_common
  0x1e95: _printf_i
  0x20e1: __sread
  0x2103: __swrite
  0x213b: __sseek
  0x215f: __sclose
  0x2171: memchr
  0x2497: assert_crash_message
  0x24f0: uart_config
  0x2510: mcg_mode_routing
  0x25bc: _global_impure_ptr
  0x25c0: __sf_fake_stderr
  0x25e0: __sf_fake_stdin
  0x2600: __sf_fake_stdout
  0x2654:
  - _etext
  - __fini_array_end
  - __fini_array_start
  - __init_array_end
  - _efixed
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x26dc: _sbackup_data_load
  0x40000: _ram_length
  0x100000:
  - _rom_length
  - _fw_rom_length
  0x1fff0000:
  - _ram_start_addr
  - _sstack
  - _sram
  - isr_stack
  0x1fff0200:
  - _srelocate
  - heap_top
  - _estack
  0x1fff0204: stdio_uart_isrpipe
  0x1fff0218: idle_name
  0x1fff021c: main_name
  0x1fff0220: _impure_ptr
  0x1fff0224: impure_data
  0x1fff0284: _tcb_name_offset
  0x1fff0285: max_threads
  0x1fff0288:
  - runqueue_bitcache
  - _sbss
  - _szero
  - _erelocate
  0x1fff028c: sched_active_pid
  0x1fff0290: sched_active_thread
  0x1fff0294: sched_context_switch_request
  0x1fff0298: sched_num_threads
  0x1fff029c: sched_runqueues
  0x1fff02dc: sched_threads
  0x1fff0360: _rx_buf_mem
  0x1fff03a0: crashed
  0x1fff03a4: idle_stack
  0x1fff04a4: main_stack
  0x1fff0aa4: config
  0x1fff0aac: current_mode
  0x1fff0ab0: __malloc_free_list
  0x1fff0ab4: __malloc_sbrk_start
  0x1fff0ab8: __lock___atexit_recursive_mutex
  0x1fff0ab9: __lock___arc4random_mutex
  0x1fff0aba: __lock___env_recursive_mutex
  0x1fff0abb: __lock___sinit_recursive_mutex
  0x1fff0abc: __lock___malloc_recursive_mutex
  0x1fff0abd: __lock___at_quick_exit_mutex
  0x1fff0abe: __lock___dd_hash_mutex
  0x1fff0abf: __lock___tz_mutex
  0x1fff0ac0: __lock___sfp_recursive_mutex
  0x1fff0ac4:
  - _sheap
  - _ebss
  - _ezero
  - __noinit_start
  - __noinit_end
  0x20030000:
  - _eram
  - _eheap
