interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0x76c
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: cat.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1bb68
symbols:
  0x0:
  - startup_MK64F12.S.obj
  - crtstuff.c
  - crt0.o
  - strcpy.c
  - init.c
  - libc_a-strlen.o
  - memset.c
  - errno.c
  - libc_a-memcpy.o
  - malloc.c
  - strncpy.c
  - exit.c
  - atexit.c
  - snprintf.c
  - printf.c
  - nano-vfprintf.c
  - fini.c
  - wbuf.c
  - nano-svfprintf.c
  - fvwrite.c
  - findfp.c
  - fflush.c
  - mallocr.c
  - freer.c
  - memmove.c
  - fwalk.c
  - libc_a-memchr.o
  - wsetup.c
  - __atexit.c
  - reallocr.c
  - nano-vfprintf_i.c
  - mlock.c
  - makebuf.c
  - isattyr.c
  - sbrkr.c
  - stdio.c
  - msizer.c
  - closer.c
  - __call_atexit.c
  - readr.c
  - fstatr.c
  - lseekr.c
  - writer.c
  - close.c
  - fstat.c
  - isatty.c
  - lseek.c
  - read.c
  - write.c
  - _exit.c
  - uart_edma_cat.c
  - cat.c
  - demo.c
  - pin_mux.c
  - clock_config.c
  - fsl_debug_console.c
  - fsl_assert.c
  - fsl_edma.c
  - fsl_dmamux.c
  - fsl_uart_edma.c
  - fsl_uart.c
  - fsl_clock.c
  - system_MK64F12.c
  - fsl_sbrk.c
  - crti.o
  - crtn.o
  - impure.c
  - reent.c
  - __isr_vector
  0x400:
  - STACK_SIZE
  - HEAP_SIZE
  0x441: deregister_tm_clones
  0x45d: register_tm_clones
  0x481: __do_global_dtors_aux
  0x4a9: frame_dummy
  0x4c9: _stack_init
  0x4d1:
  - _mainCRTStartup
  - _start
  0x539: Reset_Handler
  0x599:
  - DebugMon_Handler
  - SPI1_DriverIRQHandler
  - DMA_Error_DriverIRQHandler
  - SDHC_DriverIRQHandler
  - PIT0_IRQHandler
  - CMP2_IRQHandler
  - LLWU_IRQHandler
  - I2S0_Tx_DriverIRQHandler
  - ENET_1588_Timer_DriverIRQHandler
  - I2C2_DriverIRQHandler
  - SWI_IRQHandler
  - ADC0_IRQHandler
  - UsageFault_Handler
  - CMT_IRQHandler
  - DefaultISR
  - UART5_ERR_DriverIRQHandler
  - CMP1_IRQHandler
  - Reserved71_IRQHandler
  - PORTD_IRQHandler
  - PORTB_IRQHandler
  - UART2_ERR_DriverIRQHandler
  - SPI2_DriverIRQHandler
  - ADC1_IRQHandler
  - PIT2_IRQHandler
  - RTC_IRQHandler
  - UART3_ERR_DriverIRQHandler
  - PDB0_IRQHandler
  - FTM1_IRQHandler
  - PIT3_IRQHandler
  - RTC_Seconds_IRQHandler
  - MCG_IRQHandler
  - FTFE_IRQHandler
  - UART0_ERR_DriverIRQHandler
  - Read_Collision_IRQHandler
  - USBDCD_IRQHandler
  - I2S0_Rx_DriverIRQHandler
  - USB0_IRQHandler
  - UART4_ERR_DriverIRQHandler
  - WDOG_EWM_IRQHandler
  - MemManage_Handler
  - UART0_LON_DriverIRQHandler
  - RNG_IRQHandler
  - I2C1_DriverIRQHandler
  - ENET_Receive_DriverIRQHandler
  - DAC0_IRQHandler
  - ENET_Error_DriverIRQHandler
  - SPI0_DriverIRQHandler
  - PIT1_IRQHandler
  - LVD_LVW_IRQHandler
  - FTM0_IRQHandler
  - PORTA_IRQHandler
  - DAC1_IRQHandler
  - MCM_IRQHandler
  - CAN0_DriverIRQHandler
  - FTM3_IRQHandler
  - PORTE_IRQHandler
  - FTM2_IRQHandler
  - LPTMR0_IRQHandler
  - BusFault_Handler
  - UART1_ERR_DriverIRQHandler
  - ENET_Transmit_DriverIRQHandler
  - I2C0_DriverIRQHandler
  - CMP0_IRQHandler
  - PORTC_IRQHandler
  0x59d: NMI_Handler
  0x5a1: HardFault_Handler
  0x5a5: SVC_Handler
  0x5a9: PendSV_Handler
  0x5ad: SysTick_Handler
  0x5b1: DMA0_IRQHandler
  0x5b5: DMA1_IRQHandler
  0x5b9: DMA2_IRQHandler
  0x5bd: DMA3_IRQHandler
  0x5c1: DMA4_IRQHandler
  0x5c5: DMA5_IRQHandler
  0x5c9: DMA6_IRQHandler
  0x5cd: DMA7_IRQHandler
  0x5d1: DMA8_IRQHandler
  0x5d5: DMA9_IRQHandler
  0x5d9: DMA10_IRQHandler
  0x5dd: DMA11_IRQHandler
  0x5e1: DMA12_IRQHandler
  0x5e5: DMA13_IRQHandler
  0x5e9: DMA14_IRQHandler
  0x5ed: DMA15_IRQHandler
  0x5f1: DMA_Error_IRQHandler
  0x5f5: I2C0_IRQHandler
  0x5f9: I2C1_IRQHandler
  0x5fd: SPI0_IRQHandler
  0x601: SPI1_IRQHandler
  0x605: I2S0_Tx_IRQHandler
  0x609: I2S0_Rx_IRQHandler
  0x60d: UART0_LON_IRQHandler
  0x611: UART0_RX_TX_IRQHandler
  0x615: UART0_ERR_IRQHandler
  0x619: UART1_RX_TX_IRQHandler
  0x61d: UART1_ERR_IRQHandler
  0x621: UART2_RX_TX_IRQHandler
  0x625: UART2_ERR_IRQHandler
  0x629: UART3_RX_TX_IRQHandler
  0x62d: UART3_ERR_IRQHandler
  0x631: SPI2_IRQHandler
  0x635: UART4_RX_TX_IRQHandler
  0x639: UART4_ERR_IRQHandler
  0x63d: UART5_RX_TX_IRQHandler
  0x641: UART5_ERR_IRQHandler
  0x645: I2C2_IRQHandler
  0x649: CAN0_ORed_Message_buffer_IRQHandler
  0x64d: CAN0_Bus_Off_IRQHandler
  0x651: CAN0_Error_IRQHandler
  0x655: CAN0_Tx_Warning_IRQHandler
  0x659: CAN0_Rx_Warning_IRQHandler
  0x65d: CAN0_Wake_Up_IRQHandler
  0x661: SDHC_IRQHandler
  0x665: ENET_1588_Timer_IRQHandler
  0x669: ENET_Transmit_IRQHandler
  0x66d: ENET_Receive_IRQHandler
  0x671: ENET_Error_IRQHandler
  0x739: strcpy
  0x7f5: __libc_init_array
  0x881: strlen
  0x959: memset
  0x9fd: __errno
  0xa09: memcpy
  0xb3d: malloc
  0xb4d: free
  0xb5d: strncpy
  0xbc5: exit
  0xbe9: atexit
  0xbf5:
  - _sniprintf_r
  - _snprintf_r
  0xc79:
  - snprintf
  - sniprintf
  0xd09:
  - _printf_r
  - _iprintf_r
  0xd29:
  - printf
  - iprintf
  0xd51: __sfputc_r
  0xd79: __sfputs_r
  0xda9: __sprint_r
  0xdc9:
  - _vfiprintf_r
  - _vfprintf_r
  0x1035:
  - vfiprintf
  - vfprintf
  0x104d: __libc_fini_array
  0x1075: __swbuf_r
  0x10fd: __swbuf
  0x1115: __ssputs_r
  0x11d5: __ssprint_r
  0x12dd:
  - _svfprintf_r
  - _svfiprintf_r
  0x1515: __sfvwrite_r
  0x180d: __fp_lock
  0x1811: stdio_exit_handler
  0x1829: cleanup_stdio
  0x1869: __fp_unlock
  0x186d: global_stdio_init.part.0
  0x193d: __sfp
  0x19e1: __sinit
  0x1a01: __sfp_lock_acquire
  0x1a05: __sfp_lock_release
  0x1a09: __fp_lock_all
  0x1a1d: __fp_unlock_all
  0x1a31: __sflush_r
  0x1b45: _fflush_r
  0x1b7d: fflush
  0x1bc9: sbrk_aligned
  0x1c11: _malloc_r
  0x1d11: _free_r
  0x1dcd: memmove
  0x1ecd: _fwalk_sglue
  0x1f11: memchr
  0x1fb1: __swsetup_r
  0x2075: __register_exitproc
  0x2121: _realloc_r
  0x2185: _printf_common
  0x22a9: _printf_i
  0x252d: __malloc_lock
  0x2531: __malloc_unlock
  0x2535: __smakebuf_r
  0x25f9: __swhatbuf_r
  0x2649: _isatty_r
  0x266d: _sbrk_r
  0x2691: __sread
  0x26b5: __seofread
  0x26b9: __swrite
  0x26f9: __sseek
  0x271d: __sclose
  0x2725: _malloc_usable_size_r
  0x2735: _close_r
  0x2759: __call_exitprocs
  0x281d: _read_r
  0x2849: _fstat_r
  0x2875: _lseek_r
  0x28a1: _write_r
  0x28cd: _close
  0x28dd: _fstat
  0x28ed: _isatty
  0x28fd: _lseek
  0x290d: _read
  0x291d: _write
  0x292d: _exit
  0x2931: DMAMUX_EnableChannel
  0x297d: DMAMUX_SetSource
  0x29d9: UART_UserCallback
  0x2a2d: main
  0x2bd5: get_atcmd_buf
  0x2bed: get_atcmd_buf_size
  0x2c19: get_unsolicited_buf
  0x2c4d: get_unsolicited_buf_size
  0x2c79: to_upper
  0x2ca5: reset_state
  0x2d0d: unsolicited_reset_state
  0x2d51: is_variables_access_possible
  0x2dbd: is_unsolicited_buffer_empty
  0x2df9: pop_unsolicited_cmd
  0x2eb1: get_command_by_fsm
  0x2f21: get_new_line_chars
  0x2f49: start_flush_io_buffer
  0x2fa5: unsolicited_start_flush_io_buffer
  0x3001: start_flush_io_buffer_raw
  0x305d: ack_error
  0x30b5: ack_ok
  0x310d: get_left_buffer_space_by_fsm
  0x3199: get_current_buffer_by_fsm
  0x3225: move_position_by_fsm
  0x32ad: print_nstring_to_buf
  0x3349: print_string_to_buf
  0x3375: read_cmd_char
  0x33e1: get_command_by_index
  0x348d: unsolicited_init
  0x34b5: cat_init
  0x36f9: error_state
  0x375d: prepare_parse_command
  0x37c1: parse_prefix
  0x3849: prepare_search_command
  0x388d: is_valid_cmd_name_char
  0x38e9: is_valid_dec_char
  0x390f: is_valid_hex_char
  0x3941: convert_hex_char_to_value
  0x3971: end_processing_with_error
  0x39ed: end_processing_with_ok
  0x3a69: reset_position
  0x3ae5: get_var_by_fsm
  0x3b5d: print_response_test
  0x3c65: parse_command
  0x3d71: is_command_disable
  0x3e39: get_cmd_state
  0x3ec5: set_cmd_state
  0x3f41: update_command
  0x4069: wait_read_acknowledge
  0x40e1: start_processing_format_test_args
  0x4201: wait_test_acknowledge
  0x4271: search_command
  0x4381: start_processing_format_read_args
  0x44c5: command_found
  0x4581: command_not_found
  0x45b9: parse_int_decimal
  0x477d: parse_uint_decimal
  0x488d: parse_num_hexadecimal
  0x49c1: parse_buffer_hexadecimal
  0x4ad9: parse_buffer_string
  0x4c75: validate_int_range
  0x4d55: validate_uint_range
  0x4e05: parse_write_args
  0x501d: print_format_num
  0x50b1: format_int_decimal
  0x5171: format_uint_decimal
  0x522d: format_num_hexadecimal
  0x5319: format_buffer_hexadecimal
  0x53c5: format_buffer_string
  0x5519: format_info_type
  0x5801: next_format_var_by_fsm
  0x5949: format_read_args
  0x5aed: format_test_args
  0x5b95: parse_command_args
  0x5d21: check_unsolicited_buffers
  0x5d95: process_idle_state
  0x5e05: enable_hold_state
  0x5e4d: hold_exit
  0x5eb5: start_print_cmd_list
  0x5f11: cmd_list_next_cmd
  0x5f55: print_current_cmd_full_name
  0x6001: print_cmd_list
  0x61e9: process_write_loop
  0x6275: process_run_loop
  0x6305: call_cmd_read_by_fsm
  0x63c9: process_read_loop
  0x6505: call_cmd_test_by_fsm
  0x65c9: process_test_loop
  0x6725: process_hold_state
  0x6781: process_io_write_wait
  0x67a7: unsolicited_process_io_write_wait
  0x67cd: process_io_write
  0x6871: unsolicited_process_io_write
  0x6915: unsolicited_events_service
  0x69f9: is_unsolicited_fsm_busy
  0x6a1d: cat_service
  0x6c75: x_write
  0x6c9d: y_write
  0x6cc5: msg_write
  0x6ced: speed_write
  0x6d15: adr_write
  0x6d3d: bytesbuf_write
  0x6d95: go_write
  0x6e29: set_write
  0x6e59: set_read
  0x6e75: test_run
  0x6e99: quit_run
  0x6ec5: print_cmd_list
  0x6ed9: write_char
  0x6f21: read_char
  0x6f69: cat_start
  0x6f89: cat_process
  0x7019: CLOCK_EnableClock
  0x704b: PORT_SetPinMux
  0x7083: BOARD_InitBootPins
  0x7091: BOARD_InitPins
  0x70d5: CLOCK_SetSimSafeDivs
  0x70f5: CLOCK_SetXtal0Freq
  0x7111: CLOCK_CONFIG_SetFllExtRefDiv
  0x7149: BOARD_InitBootClocks
  0x7155: BOARD_BootClockRUN
  0x71b5: DbgConsole_Printf
  0x71e1: DbgConsole_Vprintf
  0x721d: DbgConsole_Putchar
  0x724d: DbgConsole_PrintfPaddingCharacter
  0x728d: DbgConsole_ConvertRadixNumToString
  0x734d: DbgConsole_PrintfFormattedData
  0x772d: fsl_assert_hook
  0x7745: __assert_func
  0x7775: __NVIC_EnableIRQ
  0x77ad: CLOCK_EnableClock
  0x77df: EnableIRQ
  0x7811: DisableGlobalIRQ
  0x7831: EnableGlobalIRQ
  0x7851: EDMA_GetInstance
  0x78a5: EDMA_InstallTCD
  0x7a09: EDMA_Init
  0x7aad: EDMA_GetDefaultConfig
  0x7afd: EDMA_SetTransferConfig
  0x7b75: EDMA_TcdReset
  0x7c05: EDMA_TcdSetTransferConfig
  0x7d65: EDMA_GetInstanceOffset
  0x7dbd: EDMA_CreateHandle
  0x7eb5: EDMA_SetCallback
  0x7ef5: EDMA_TransferWidthMapping
  0x7fd5: EDMA_PrepareTransferConfig
  0x8151: EDMA_PrepareTransfer
  0x820d: EDMA_SubmitTransfer
  0x8529: EDMA_StartTransfer
  0x85e9: EDMA_AbortTransfer
  0x867d: EDMA_HandleIRQ
  0x884d: DMA0_DriverIRQHandler
  0x8869: DMA1_DriverIRQHandler
  0x8885: DMA2_DriverIRQHandler
  0x88a1: DMA3_DriverIRQHandler
  0x88bd: DMA4_DriverIRQHandler
  0x88d9: DMA5_DriverIRQHandler
  0x88f5: DMA6_DriverIRQHandler
  0x8911: DMA7_DriverIRQHandler
  0x892d: DMA8_DriverIRQHandler
  0x8949: DMA9_DriverIRQHandler
  0x8965: DMA10_DriverIRQHandler
  0x8981: DMA11_DriverIRQHandler
  0x899d: DMA12_DriverIRQHandler
  0x89b9: DMA13_DriverIRQHandler
  0x89d5: DMA14_DriverIRQHandler
  0x89f1: DMA15_DriverIRQHandler
  0x8a0d: CLOCK_EnableClock
  0x8a41: DMAMUX_GetInstance
  0x8a95: DMAMUX_Init
  0x8ab9: __NVIC_EnableIRQ
  0x8af1: EnableIRQ
  0x8b23: UART_GetDataRegisterAddress
  0x8b39: UART_EnableTxDMA
  0x8b97: UART_EnableRxDMA
  0x8bf5: UART_SendEDMACallback
  0x8c55: UART_ReceiveEDMACallback
  0x8cc9: UART_TransferCreateHandleEDMA
  0x8dd1: UART_SendEDMA
  0x8edd: UART_ReceiveEDMA
  0x8ff5: UART_TransferAbortReceiveEDMA
  0x9059: UART_TransferEdmaHandleIRQ
  0x90b9: CLOCK_EnableClock
  0x90ed: UART_GetInstance
  0x914d: UART_Init
  0x9461: UART_GetDefaultConfig
  0x94d9: UART_EnableInterrupts
  0x9549: UART_DisableInterrupts
  0x95d9: UART0_DriverIRQHandler
  0x9601: UART0_RX_TX_DriverIRQHandler
  0x9615: UART1_DriverIRQHandler
  0x963d: UART1_RX_TX_DriverIRQHandler
  0x9651: UART2_DriverIRQHandler
  0x9679: UART2_RX_TX_DriverIRQHandler
  0x968d: UART3_DriverIRQHandler
  0x96b5: UART3_RX_TX_DriverIRQHandler
  0x96c9: UART4_DriverIRQHandler
  0x96f1: UART4_RX_TX_DriverIRQHandler
  0x9705: UART5_DriverIRQHandler
  0x972d: UART5_RX_TX_DriverIRQHandler
  0x9741: CLOCK_SetEr32kClock
  0x976d: CLOCK_SetPllFllSelClock
  0x97a1: OSC_SetExtRefClkConfig
  0x97d3: OSC_SetCapLoad
  0x9805: CLOCK_GetMcgExtClkFreq
  0x9895: CLOCK_GetFllExtRefClkFreq
  0x9945: CLOCK_GetInternalRefClkSelectFreq
  0x9991: CLOCK_GetFllRefClkFreq
  0x99c5: CLOCK_GetPll0RefFreq
  0x99d5: CLOCK_GetOscRangeFromFreq
  0x9a11: CLOCK_GetOsc0ErClkFreq
  0x9a65: CLOCK_GetEr32kClkFreq
  0x9ae9: CLOCK_GetPllFllSelClkFreq
  0x9b3d: CLOCK_GetFreq
  0x9c7d: CLOCK_SetSimConfig
  0x9cb1: CLOCK_GetOutClkFreq
  0x9d15: CLOCK_GetFllFreq
  0x9d99: CLOCK_GetInternalRefClkFreq
  0x9dc9: CLOCK_GetFixedFreqClkFreq
  0x9dfd: CLOCK_GetPll0Freq
  0x9e85: CLOCK_SetExternalRefClkConfig
  0x9ef1: CLOCK_SetInternalRefClkConfig
  0x9ff5: CLOCK_EnablePll0
  0xa08d: CLOCK_InitOsc0
  0xa119: CLOCK_SetPbeMode
  0xa1d1: CLOCK_BootToPeeMode
  0xa241: SystemInit
  0xa269: SystemInitHook
  0xa275: _sbrk
  0xafa0: __func__.1
  0xafb4: __func__.0
  0xafcc: __func__.79
  0xafd8: __func__.78
  0xaff0: __func__.74
  0xb00c: __func__.73
  0xb020: __func__.70
  0xb034: __func__.66
  0xb04c: __func__.65
  0xb070: __func__.64
  0xb08c: __func__.63
  0xb098: __func__.62
  0xb0a0: __func__.61
  0xb0c0: __func__.60
  0xb0dc: __func__.59
  0xb0f4: __func__.58
  0xb10c: __func__.57
  0xb11c: __func__.56
  0xb134: __func__.55
  0xb140: __func__.54
  0xb14c: __func__.53
  0xb164: __func__.52
  0xb174: __func__.51
  0xb18c: __func__.50
  0xb1a8: __func__.49
  0xb1c0: __func__.48
  0xb1d0: __func__.47
  0xb1e0: __func__.46
  0xb1f4: __func__.45
  0xb204: __func__.44
  0xb218: __func__.43
  0xb228: __func__.42
  0xb238: __func__.41
  0xb250: __func__.40
  0xb274: __func__.39
  0xb28c: __func__.38
  0xb29c: __func__.37
  0xb2c0: __func__.36
  0xb2d0: __func__.35
  0xb2e4: __func__.34
  0xb2f8: __func__.33
  0xb30c: __func__.32
  0xb324: __func__.31
  0xb340: __func__.30
  0xb354: __func__.29
  0xb368: __func__.28
  0xb37c: __func__.27
  0xb390: __func__.26
  0xb3a4: __func__.25
  0xb3bc: __func__.24
  0xb3d8: __func__.23
  0xb3f0: __func__.22
  0xb404: __func__.21
  0xb41c: __func__.20
  0xb430: __func__.19
  0xb444: __func__.18
  0xb458: __func__.16
  0xb474: __func__.15
  0xb488: __func__.14
  0xb49c: __func__.13
  0xb4a8: __func__.12
  0xb4c0: __func__.11
  0xb4d4: __func__.10
  0xb4e8: __func__.9
  0xb500: __func__.8
  0xb514: __func__.7
  0xb52c: __func__.6
  0xb540: __func__.5
  0xb554: __func__.0
  0xb560: mcgConfig_BOARD_BootClockRUN
  0xb56c: simConfig_BOARD_BootClockRUN
  0xb574: oscConfig_BOARD_BootClockRUN
  0xb57c: s_edmaIRQNumber
  0xb58c: __func__.36
  0xb5a0: __func__.35
  0xb5b0: __func__.34
  0xb5bc: __func__.33
  0xb5d4: __func__.31
  0xb5ec: __func__.22
  0xb5fc: __func__.21
  0xb618: __func__.10
  0xb630: __func__.9
  0xb644: __func__.7
  0xb658: __func__.6
  0xb674: __func__.5
  0xb690: __func__.4
  0xb6a8: __func__.3
  0xb6bc: __func__.2
  0xb6d0: __func__.0
  0xb6e0: __func__.0
  0xb6f4: __func__.9
  0xb70c: __func__.8
  0xb728: __func__.7
  0xb748: __func__.6
  0xb758: __func__.5
  0xb76c: __func__.3
  0xb78c: __func__.0
  0xb7a8: s_uartBases
  0xb7c0: s_uartIRQ
  0xb7c8: s_uartClock
  0xb7e0: __func__.20
  0xb7f4: __func__.17
  0xb800: __func__.16
  0xb818: __func__.9
  0xb830: __func__.8
  0xb848: __func__.7
  0xb860: fllFactorTable.6
  0xb870: __func__.5
  0xb884: __func__.4
  0xb898: __func__.2
  0xb8ac: __func__.1
  0xb8fc: __EH_FRAME_BEGIN__
  0xb8fd: _init
  0xb909: _fini
  0xb914: __exidx_start
  0xb91c:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __DTOR_END__
  - __CTOR_LIST__
  - __CTOR_END__
  - __DTOR_LIST__
  0xb920:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0xb924:
  - __fini_array_end
  - __etext
  - __DATA_ROM
  0xbb68: __DATA_END
  0x100000: text_end
  0x1fff0000:
  - __data_start__
  - __DATA_RAM
  - _impure_ptr
  0x1fff0004: _impure_data
  0x1fff0050: __sglue
  0x1fff005c: g_tipString
  0x1fff00a2: rxBufferEmpty
  0x1fff00a4: crlf.67
  0x1fff00a8: go_vars
  0x1fff00fc: set_vars
  0x1fff0150: cmds
  0x1fff0204: cmd_group
  0x1fff0214: cmd_desc
  0x1fff0218: desc
  0x1fff0230: iface
  0x1fff0238: s_slowIrcFreq
  0x1fff023c: s_fastIrcFreq
  0x1fff0240: SystemCoreClock
  0x1fff0244:
  - completed.1
  - __TMC_END__
  - __START_BSS
  - __bss_start__
  - __data_end__
  0x1fff0248: object.0
  0x1fff0260: __sf
  0x1fff0398: __stdio_exit_handler
  0x1fff039c: __malloc_sbrk_start
  0x1fff03a0: __malloc_free_list
  0x1fff03a4: __atexit0
  0x1fff0430: __atexit
  0x1fff0434: errno
  0x1fff0438: g_uartEdmaHandle
  0x1fff0454: g_uartTxEdmaHandle
  0x1fff046c: g_uartRxEdmaHandle
  0x1fff0484: g_txBuffer
  0x1fff0504: g_rxBuffer
  0x1fff0584: txBufferFull
  0x1fff0585: txOnGoing
  0x1fff0586: rxOnGoing
  0x1fff0588: speed
  0x1fff058c: adr
  0x1fff058e: x
  0x1fff058f: y
  0x1fff0590: bytes_buf
  0x1fff0594: msg
  0x1fff05a4: quit_flag
  0x1fff05a8: buf
  0x1fff0628: io_read_buf
  0x1fff062c: io_write_buf
  0x1fff0630: io_read_len
  0x1fff0634: io_read_ptr
  0x1fff0638: io_write_len
  0x1fff063c: io_write_ptr
  0x1fff0640: at
  0x1fff06bc: s_debugConsole
  0x1fff06d0: s_EDMAHandle
  0x1fff0710: startInstanceNum.11
  0x1fff0714: s_edmaPrivateHandle
  0x1fff0744: s_uartHandle
  0x1fff075c: s_uartIsr
  0x1fff0760: g_xtal0Freq
  0x1fff0764: g_xtal32Freq
  0x1fff0768: heap_end.0
  0x1fff076c:
  - __bss_end__
  - __END_BSS
  0x20000000:
  - __HeapBase
  - end
  - __end__
  0x20000400:
  - __heap_limit
  - __HeapLimit
  0x2002fc00: __StackLimit
  0x20030000:
  - __StackTop
  - __stack
  0xe000ed08: VTOR
