interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: sam3x_uart_scatter.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x10f88
symbols:
  0x0:
  - startup_sam3x.c
  - crtstuff.c
  - sysclk.c
  - init.c
  - dmac.c
  - pio.c
  - pio_handler.c
  - pmc.c
  - usart.c
  - exceptions.c
  - system_sam3x.c
  - usart_example_dmac.c
  - __call_atexit.c
  - init.c
  - fini.c
  - lock.c
  - atexit.c
  - __atexit.c
  - crti.o
  - crtn.o
  0x2000: __stack_size__
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: deregister_tm_clones
  0x80111: register_tm_clones
  0x80135: __do_global_dtors_aux
  0x8015d: frame_dummy
  0x80181: sysclk_init
  0x801e5: board_init
  0x80291: dmac_init
  0x8029b: dmac_set_priority_mode
  0x802a7: dmac_enable
  0x802ad: dmac_enable_interrupt
  0x802b1: dmac_get_status
  0x802b5: dmac_channel_enable
  0x802bd: dmac_channel_disable
  0x802c5: dmac_channel_set_configuration
  0x802d1: dmac_channel_single_buf_transfer_init
  0x802fd: dmac_channel_multi_buf_transfer_init
  0x80311: pio_set_peripheral
  0x8034d: pio_set_input
  0x80383: pio_set_output
  0x803a9: pio_get_interrupt_status
  0x803ad: pio_get_interrupt_mask
  0x803b1: pio_set_pin_high
  0x803c9: pio_set_pin_low
  0x803e1: pio_configure_pin
  0x804b1: pio_configure_pin_group
  0x8054d: pio_handler_process
  0x8059d: PIOA_Handler
  0x805b1: PIOB_Handler
  0x805c5: PIOC_Handler
  0x805d9: PIOD_Handler
  0x805ed: PIOE_Handler
  0x80601: PIOF_Handler
  0x80615: pmc_switch_mck_to_pllack
  0x80675: pmc_switch_mainck_to_xtal
  0x806c9: pmc_osc_is_ready_mainck
  0x806d9: pmc_disable_pllack
  0x806e9: pmc_is_locked_pllack
  0x806f9: pmc_enable_periph_clk
  0x80719: usart_set_async_baudrate
  0x80779: usart_reset
  0x807a1: usart_init_rs232
  0x807e1: usart_enable_tx
  0x807e7: usart_enable_rx
  0x807ed: usart_is_tx_ready
  0x807f5: usart_write
  0x80809:
  - DACC_Handler
  - DebugMon_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - SysTick_Handler
  - USART3_Handler
  - TWI1_Handler
  - PendSV_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - USART0_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - Dummy_Handler
  - TWI0_Handler
  - USART1_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - SVC_Handler
  - TC8_Handler
  - USART2_Handler
  - SDRAMC_Handler
  - SPI1_Handler
  - EMAC_Handler
  - UART_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - UOTGHS_Handler
  - SPI0_Handler
  0x8080d: Reset_Handler
  0x808ad: SystemCoreClockUpdate
  0x809c1: configure_dmac_rx
  0x80a39: pwcheck_success
  0x80a4d: pwcheck_passed_1
  0x80a5d: pwcheck_passed_2
  0x80a6d: pwcheck_passed_3
  0x80a7d: pwcheck_passed_4
  0x80a8d: pwcheck_passed_5
  0x80a9d: pwcheck_passed_6
  0x80aad: pwcheck_passed_7
  0x80abd: pwcheck_passed_8
  0x80acd: check_password_scatter_gather
  0x80b59: DMAC_Handler
  0x80c49: main
  0x80cf9: register_fini
  0x80d0d: __libc_init_array
  0x80d5d: __libc_fini_array
  0x80d85: __retarget_lock_acquire_recursive
  0x80d89: __retarget_lock_release_recursive
  0x80d8d: atexit
  0x80d99: __register_exitproc
  0x80e31: _init
  0x80e3c:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x80e40: __frame_dummy_init_array_entry
  0x80e44: __init_array_end
  0x80e45: _fini
  0x80e50:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x80e54:
  - _etext
  - __TMC_END__
  - __fini_array_end
  - _efixed
  0x20070000: _srelocate
  0x20070001: SystemInit
  0x200700a5: system_init_flash
  0x2007012c: SystemCoreClock
  0x20070130: __atexit_recursive_mutex
  0x20070134:
  - completed.1
  - _sbss
  - _szero
  - _erelocate
  0x20070138: object.0
  0x20070150: gs_interrupt_sources
  0x200701c0:
  - buffer2
  - dma_buf_2
  0x200701c4: pad
  0x200701cc:
  - buffer1
  - dma_buf_1
  0x200701d0: gs_puc_buffer
  0x200701d8: num_correct
  0x200701dc: __atexit
  0x200701e0: __lock___atexit_recursive_mutex
  0x200701e4: __atexit0
  0x20070374:
  - _ebss
  - _ezero
  0x20070378: _sstack
  0x20072378:
  - _estack
  - _end
  0x20087ffc: __ram_end__
