include:
- config.yml

peripherals:
  my_dma_periph:
    class: fuzzware_harness.peripherals.generic_dma.GenericDMAC
    packet_limit: 0x5

    # Example 13: SAM3X (scatter-gather)
    descriptors:
    - addr: 0x400C4044 # and other DMA channels, if used. Offsets: 0x6c, 0x94, 0xbc, 0xe4, 0x10c
      to:
        typedef: sam3x_ll_elem
        fields:
        - offset: 4
          type: pointer
          to:
            type: buffer
        - offset: 0x10
          type: pointer
          to:
            type: sam3x_ll_elem

    known_sizes:
      dma_buf_1:
        min: 4
        max: 4
      dma_buf_2:
        min: 4
        max: 4
