interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_0fe081fc:
    base_addr: 0xfe03000
    permissions: rw-
    size: 0xa000
  dynamically_added_crash_region_2b004b33:
    base_addr: 0x2afff000
    permissions: rw-
    size: 0xa000
  dynamically_added_crash_region_f7ff46b9:
    base_addr: 0xf7fef000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: test.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x13fdc
symbols:
  0x0:
  - startup_efm32g.c
  - crtstuff.c
  - crt0.o
  - sl_board_init.c
  - system_efm32g.c
  - dmadrv.c
  - gpiointerrupt.c
  - uartdrv.c
  - em_cmu.c
  - em_core.c
  - em_dma.c
  - em_emu.c
  - em_gpio.c
  - em_leuart.c
  - em_rtc.c
  - em_system.c
  - sl_device_init_hfxo_s0.c
  - sl_device_init_nvic.c
  - sl_power_manager.c
  - sl_power_manager_hal_s0_s1.c
  - sl_sleeptimer.c
  - sl_sleeptimer_hal_rtc.c
  - sl_device_init_clocks.c
  - sl_event_handler.c
  - sl_uartdrv_init.c
  - uartdrv_app.c
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - exit.c
  - init.c
  - sl_board_control_gpio.c
  - sl_assert.c
  - sl_slist.c
  - sl_syscalls.c
  - em_usart.c
  - sl_device_init_emu_s0.c
  - sl_device_init_lfxo_s0.c
  - sl_system_init.c
  - sl_system_process_action.c
  - app.c
  - sl_board_default_init.c
  - sl_power_manager_handler.c
  - main.c
  - memset.c
  - crti.o
  - crtn.o
  - sl_memory.c
  - dmactrl.c
  - findfp.c
  - __text_application_ram_offset__
  - __Vectors
  - linker_storage_size
  - linker_vectors_begin
  - linker_nvm_size
  0xbc:
  - linker_vectors_end
  - __Vectors_Size
  - linker_code_begin
  - __Vectors_End
  0xbd: deregister_tm_clones
  0xd9: register_tm_clones
  0xfd: __do_global_dtors_aux
  0x125: frame_dummy
  0x149: _stack_init
  0x151:
  - _mainCRTStartup
  - _start
  0x1c5: sl_board_init
  0x1dd: sl_board_preinit
  0x1e9: Reset_Handler
  0x249: SystemMaxCoreClockGet
  0x251: SystemHFClockGet
  0x309: SystemCoreClockGet
  0x329: SystemHFXOClockSet
  0x345: SystemInit
  0x355: SystemLFXOClockGet
  0x361: DmaBasicCallback
  0x37d: StartTransfer
  0x52d: DmaPingPongCallback
  0x579: DMADRV_AllocateChannel
  0x5d9: DMADRV_Init
  0x645: DMADRV_PauseTransfer
  0x689: DMADRV_ResumeTransfer
  0x6cd: DMADRV_TransferActive
  0x71d: GPIOINT_IRQDispatcher
  0x755: GPIOINT_Init
  0x785: GPIOINT_CallbackRegister
  0x7a9: GPIO_EVEN_IRQHandler
  0x7cd: GPIO_ODD_IRQHandler
  0x7f1: CheckParams
  0x815: addHandle
  0x865: GetTailBuffer
  0x899: GPIO_PinOutClear
  0x8dd: GPIO_PinOutSet
  0x921: InitializeDma
  0x94d: EnqueueBuffer
  0x9d1: HwFcGetClearToSendPin
  0xa25: HwFcManageClearToSend
  0xaa5: StartReceiveDma
  0xae9: UARTDRV_ForceTransmit
  0xbd1: UARTDRV_PauseTransmit
  0xc01: UARTDRV_ResumeTransmit
  0xc41: UARTDRV_Receive
  0xc99: ReceiveDmaComplete
  0xd91: UARTDRV_InitLeuart
  0x1051: sl_uartdrv_sleep_on_isr_exit
  0x1089: CMU_DivToLog2
  0x10b5: syncReg
  0x10c9: flashWaitStateControl.isra.0
  0x1105: flashWaitStateMax
  0x1129: CMU_UpdateWaitStates
  0x1149: CMU_ClockDivSet
  0x12e5: CMU_ClockEnable
  0x1365: CMU_ClockSelectGet
  0x13f1: lfClkGet
  0x147d: CMU_ClockFreqGet
  0x15a1: CMU_HFXOInit
  0x15ed: CMU_LFXOInit
  0x164d: CMU_LFXOPrecisionSet
  0x1659: CMU_HFXOPrecisionSet
  0x1665: CMU_OscillatorEnable
  0x16bd: sli_em_cmu_HFClockSelectLFOsc
  0x1711: sli_em_cmu_HFClockSelectHFXO
  0x1739: __NVIC_GetPriority
  0x175d: CORE_NvicIRQDisabled
  0x1791: CORE_IrqIsBlocked
  0x17fd: DMA_Prepare
  0x1881: BUS_RegBitWrite
  0x18a9: DMA_IRQHandler
  0x1931: DMA_ActivateBasic
  0x198d: DMA_ActivatePingPong
  0x1a11: DMA_CfgChannel
  0x1a7d: DMA_CfgDescr
  0x1ad9: DMA_ChannelEnabled
  0x1b01: DMA_ChannelRequestEnable
  0x1b35: DMA_RefreshPingPong
  0x1bdd: DMA_Reset
  0x1c39: DMA_Init
  0x1c9d: getErrataFixEmuE107En
  0x1ccd: emState.part.0
  0x1d35: emState.constprop.0
  0x1d59: EMU_EnterEM2
  0x1db9: EMU_EnterEM3
  0x1e35: GPIO_PinOutSet
  0x1e79: GPIO_PinOutClear
  0x1ebd: GPIO_ExtIntConfig
  0x1f75: GPIO_PinModeSet
  0x2009: LEUART_BaudrateSet
  0x2085: LEUART_Enable
  0x20c1: LEUART_Init
  0x2125: regSync
  0x2139: RTC_CompareSet
  0x2185: RTC_Init
  0x21ad: SYSTEM_ChipRevisionGet
  0x21fd: sl_device_init_hfxo
  0x2229: sl_device_init_nvic
  0x2265: get_lowest_em
  0x2281: power_manager_notify_em_transition
  0x22f5: clock_restore
  0x234d: on_clock_wakeup_timeout
  0x2371: update_em1_requirement
  0x23d9: sl_power_manager_init
  0x2441: sli_power_manager_update_em_requirement
  0x2545: sli_power_manager_get_restore_delay
  0x2579: sli_power_manager_convert_delay_us_to_tick
  0x2599: sl_power_manager_sleep
  0x2791: sl_power_manager_is_latest_wakeup_internal
  0x27b1: sli_power_manager_init_hardware
  0x2801: EMU_EM23PostsleepHook
  0x283d: sli_power_manager_restore_states
  0x288d: sli_power_manager_apply_em
  0x28a8: __heap_size
  0x28c5: sli_power_manager_get_wakeup_process_time_overhead
  0x28e1: sli_power_manager_low_frequency_restore
  0x290d: sli_power_manager_is_high_freq_accuracy_clk_used
  0x2919: update_delta_list
  0x2951: delta_list_insert_timer
  0x29a9: set_comparator_for_next_timer
  0x2a05: create_timer
  0x2a75: delta_list_remove_timer
  0x2aad: sl_sleeptimer_init
  0x2b21: sl_sleeptimer_stop_timer
  0x2b71: sl_sleeptimer_get_remaining_time_of_first_timer
  0x2bd1: sli_sleeptimer_is_power_manager_timer_next_to_expire
  0x2bf9: sl_sleeptimer_get_timer_frequency
  0x2c05: process_timer_irq
  0x2d5d: sl_sleeptimer_is_power_manager_early_restore_timer_latest_to_expire
  0x2d75: sleeptimer_hal_init_timer
  0x2dd9: sleeptimer_hal_get_counter
  0x2dfd: sleeptimer_hal_enable_int
  0x2e2d: sleeptimer_hal_disable_int
  0x2e59: sleeptimer_hal_set_compare
  0x2ec5: sleeptimer_hal_set_int
  0x2ed5: sli_sleeptimer_hal_is_int_status_set
  0x2f09: sleeptimer_hal_get_timer_frequency
  0x2f15: RTC_IRQHandler
  0x2f85: sli_sleeptimer_set_pm_em_requirement
  0x2fb5: sl_device_init_clocks
  0x2ffd: sl_platform_init
  0x3105: sl_uartdrv_set_default
  0x3119: sl_uartdrv_init_instances
  0x3139: pwcheck_success
  0x314d: pwcheck_passed_1
  0x315d: pwcheck_passed_2
  0x316d: pwcheck_passed_3
  0x317d: pwcheck_passed_4
  0x318d: pwcheck_passed_5
  0x319d: pwcheck_passed_6
  0x31ad: pwcheck_passed_7
  0x31bd: pwcheck_passed_8
  0x31cd: check_password
  0x3235: UART_rx_callback
  0x3245: uartdrv_app_init
  0x3279: __aeabi_uldivmod
  0x32a9: __udivmoddi4
  0x355d:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x3561: exit
  0x3585: __libc_init_array
  0x35cd: sl_board_enable_vcom
  0x35df: sl_board_configure_vcom
  0x35e3: assertEFM
  0x35e5: sl_slist_init
  0x35eb: _exit
  0x35ed:
  - TIMER2_IRQHandler
  - DebugMon_Handler
  - USART0_TX_IRQHandler
  - I2C0_IRQHandler
  - HardFault_Handler
  - LEUART1_IRQHandler
  - SysTick_Handler
  - USART1_RX_IRQHandler
  - PendSV_Handler
  - NMI_Handler
  - USART1_TX_IRQHandler
  - MSC_IRQHandler
  - ADC0_IRQHandler
  - UsageFault_Handler
  - LEUART0_IRQHandler
  - UART0_TX_IRQHandler
  - TIMER0_IRQHandler
  - LCD_IRQHandler
  - PCNT2_IRQHandler
  - UART0_RX_IRQHandler
  - LETIMER0_IRQHandler
  - TIMER1_IRQHandler
  - USART2_RX_IRQHandler
  - Default_Handler
  - PCNT0_IRQHandler
  - sl_app_properties
  - PCNT1_IRQHandler
  - ACMP0_IRQHandler
  - USART0_RX_IRQHandler
  - MemManage_Handler
  - SVC_Handler
  - DAC0_IRQHandler
  - CMU_IRQHandler
  - AES_IRQHandler
  - VCMP_IRQHandler
  - BusFault_Handler
  - USART2_TX_IRQHandler
  0x35ef: SystemLFRCOClockGet
  0x35f5: DMADRV_PeripheralMemory
  0x3629: ConfigGpio
  0x3707: EnableTransmitter
  0x373b: EnableReceiver
  0x376f: DisableReceiver
  0x379f: DequeueBuffer.isra.0
  0x37e5: FcApplyState
  0x3841: sli_em_cmu_SetHFLEConfigSystemCoreClock
  0x3843: CORE_EnterCritical
  0x384b: CORE_ExitCritical
  0x3851: CORE_EnterAtomic
  0x385d: CORE_ExitAtomic
  0x3863: EMU_EM23PresleepHook
  0x3865: EMU_EFPEM23PresleepHook
  0x3867: EMU_EFPEM23PostsleepHook
  0x3869: EMU_Save
  0x386d: EMU_Restore
  0x3871: BUS_RegMaskedWrite
  0x388f: LEUART_Sync
  0x389d: LEUART_Tx
  0x38b1: USART_Tx
  0x38bb: sl_device_init_emu
  0x38bf: sl_device_init_lfxo
  0x38e1: sli_power_manager_initiate_restore
  0x38f7: sli_power_manager_save_states
  0x38fb: sli_power_manager_handle_pre_deepsleep_operations
  0x38fd: sli_power_manager_restore_high_freq_accuracy_clk
  0x38ff: sli_power_manager_is_high_freq_accuracy_clk_ready
  0x3903: sli_power_manager_get_default_high_frequency_minimum_offtime
  0x390b: sl_sleeptimer_restart_timer
  0x3949: sl_sleeptimer_get_tick_count
  0x3961: sl_system_init
  0x397b: sl_system_process_action
  0x3991: app_init
  0x3995: app_process_action
  0x3999: sl_board_default_init
  0x399b: sl_driver_init
  0x39a9: sl_service_init
  0x39b7: sl_stack_init
  0x39b9: sl_internal_app_init
  0x39bb: sl_platform_process_action
  0x39bd: sl_service_process_action
  0x39bf: sl_stack_process_action
  0x39c1: sl_internal_app_process_action
  0x39c3: sl_power_manager_is_ok_to_sleep
  0x39cb: sl_power_manager_sleep_on_isr_exit
  0x3a05: main
  0x3a1d: app_is_ok_to_sleep
  0x3a21: app_sleep_on_isr_exit
  0x3a25: uartdrv_app_process_action
  0x3a27: memset
  0x3a40: linker_code_end
  0x3a41: _init
  0x3a4d: _fini
  0x3a58: __code_classification_validator_start__
  0x3a80: __code_classification_validator_end__
  0x3e6c: CSWTCH.53
  0x3e76: CSWTCH.52
  0x3e80: CSWTCH.51
  0x3e89: CSWTCH.56
  0x3e90:
  - __EH_FRAME_BEGIN__
  - __exidx_start
  0x3e98:
  - __exidx_end
  - __copy_table_start__
  0x3ea4:
  - __etext
  - __zero_table_end__
  - __zero_table_start__
  - __copy_table_end__
  0x3fdc:
  - __lma_ramfuncs_end__
  - __lma_ramfuncs_start__
  0x20000:
  - linker_nvm_end
  - linker_storage_end
  - __nvm3Base
  - __main_flash_end__
  - linker_storage_begin
  - linker_nvm_begin
  0x20000000:
  - sl_stack
  - __StackLimit
  0x20001000:
  - __data_start__
  - SystemCoreClock
  - __StackTop
  - __stack
  0x20001004: SystemLFXOClock
  0x20001008: SystemHFXOClock
  0x2000100c: sl_uartdrv_leuart_init_vcom
  0x20001024: sl_uartdrv_leuart_vcom_tx_buffer
  0x200010a4: sl_uartdrv_leuart_vcom_rx_buffer
  0x20001124: sl_uartdrv_leuart_vcom_handle
  0x20001128: hfxo_precision
  0x2000112a: lfxo_precision
  0x2000112c: comp_int_disabled
  0x20001130:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20001134:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x20001138:
  - __TMC_END__
  - __bss_start__
  - __data_end__
  0x20001200: dmaControlBlock
  0x20001300: dma_buf
  0x20001350: object.0
  0x20001368: dmaCallBack
  0x200013c8: chTable
  0x20001468: gpioCallbacks
  0x20001668: uartdrvHandle
  0x20001678: cmuStatus.1
  0x2000167c: wakeup_time_config_overhead_tick
  0x20001680: high_frequency_min_offtime_tick
  0x20001684: clock_wakeup_timer_handle
  0x200016a4: sleeptimer_frequency
  0x200016a8: power_manager_em_transition_event_list
  0x200016ac: cmu_status
  0x200016b0: process_wakeup_overhead_tick
  0x200016b4: hf_x_oscillator_wakeup_time_tc_inital
  0x200016b8: hfxo_wakeup_time_tick
  0x200016bc: max_millisecond_conversion
  0x200016c0: last_delta_update_count
  0x200016c4: timer_head
  0x200016c8: timer_frequency
  0x200016cc: compare_value_32
  0x200016d0: sli_uartdrv_default_handle
  0x200016d4: sl_uartdrv_leuart_vcom_handle_data
  0x20001734: num_correct
  0x20001738: __stdio_exit_handler
  0x2000173c: overflow_counter
  0x2000173e: completed.1
  0x2000173f: initialized
  0x20001740: uartdrvHandleIsInitialized
  0x20001741: hfClock.0
  0x20001742: is_restored_from_hfxo_isr_internal
  0x20001743: is_restored_from_hfxo_isr
  0x20001744: is_actively_waiting_for_clock_restore
  0x20001745: is_hf_x_oscillator_not_preserved
  0x20001746: requirement_on_em1_added
  0x20001747: is_states_saved
  0x20001748: is_sleeping_waiting_for_clock_restore
  0x20001749: waiting_clock_restore_from_em
  0x2000174a: requirement_high_accuracy_hf_clock_counter
  0x2000174b: requirement_em_table
  0x2000174d: current_em
  0x2000174e: is_initialized
  0x2000174f: is_hf_x_oscillator_already_started
  0x20001750: is_hf_x_oscillator_used
  0x20001751: sleep_on_isr_exit
  0x20001752: next_timer_to_expire_is_power_manager
  0x20001753: is_sleeptimer_initialized
  0x20001754: rtc_overflow_count
  0x20001758:
  - sl_heap
  - __HeapBase
  - __vma_ramfuncs_start__
  - __ramfuncs_start__
  - __text_application_ram_start__
  - end
  - __bss_end__
  - __end__
  - __vma_ramfuncs_end__
  - __text_application_ram_end__
  - _end
  - __ramfuncs_end__
  0x20004000:
  - __HeapLimit
  - __ram_end__
