interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_UART_HyperTerminal_DMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1163c
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - stm32f1xx_nucleo.c
  - system_stm32f1xx.c
  - stm32f1xx_hal.c
  - stm32f1xx_hal_cortex.c
  - stm32f1xx_hal_dma.c
  - stm32f1xx_hal_gpio.c
  - stm32f1xx_hal_rcc.c
  - stm32f1xx_hal_uart.c
  - main.c
  - stm32f1xx_hal_msp.c
  - stm32f1xx_it.c
  - init.c
  - memset.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: BSP_LED_Init
  0x800019d: BSP_LED_On
  0x80001b1: BSP_LED_Off
  0x80001c5: BSP_LED_Toggle
  0x80001d5: SystemInit
  0x8000221: HAL_MspInit
  0x8000225: HAL_InitTick
  0x8000269: HAL_Init
  0x800028d: HAL_IncTick
  0x80002a5: HAL_GetTick
  0x80002b1: HAL_Delay
  0x80002d5: HAL_NVIC_SetPriorityGrouping
  0x80002f9: HAL_NVIC_SetPriority
  0x8000361: HAL_NVIC_EnableIRQ
  0x8000379: HAL_SYSTICK_Config
  0x80003a5: HAL_DMA_Init
  0x8000405: HAL_DMA_Start_IT
  0x8000481: HAL_DMA_Abort_IT
  0x8000511: HAL_DMA_IRQHandler
  0x8000639: HAL_GPIO_Init
  0x80007f9: HAL_GPIO_WritePin
  0x8000803: HAL_GPIO_TogglePin
  0x800080d: HAL_RCC_OscConfig
  0x8000b25: HAL_RCC_GetSysClockFreq
  0x8000b99: HAL_RCC_ClockConfig
  0x8000cf9: HAL_RCC_GetPCLK1Freq
  0x8000d19: HAL_RCC_GetPCLK2Freq
  0x8000d39: UART_EndRxTransfer
  0x8000d55: UART_SetConfig
  0x8000e91: HAL_UART_Init
  0x8000eed: HAL_UART_Transmit_DMA
  0x8000f61: HAL_UART_Receive_DMA
  0x8000ff1: UART_DMATransmitCplt
  0x800101d: HAL_UART_TxHalfCpltCallback
  0x800101f: UART_DMATxHalfCplt
  0x8001029: UART_DMAReceiveCplt
  0x8001061: UART_Receive_IT
  0x80010d7: HAL_UART_RxHalfCpltCallback
  0x80010d9: UART_DMARxHalfCplt
  0x80010e3: UART_DMAError
  0x8001131: HAL_UART_IRQHandler
  0x8001271: UART_DMAAbortOnError
  0x8001281: HAL_UART_GetState
  0x800128d: Reset_Handler
  0x8001290: CopyDataInit
  0x8001298: LoopCopyDataInit
  0x80012a6: FillZerobss
  0x80012ac: LoopFillZerobss
  0x80012d4:
  - Infinite_Loop
  - Default_Handler
  0x80012d5:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI15_10_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x80012d7: Error_Handler
  0x80012e9: SystemClock_Config
  0x8001339: main
  0x80013c5: HAL_UART_TxCpltCallback
  0x80013cb: HAL_UART_RxCpltCallback
  0x80013d1: HAL_UART_ErrorCallback
  0x80013d9: HAL_UART_MspInit
  0x80014ed: NMI_Handler
  0x80014ef: HardFault_Handler
  0x80014f1: MemManage_Handler
  0x80014f3: BusFault_Handler
  0x80014f5: UsageFault_Handler
  0x80014f7: SVC_Handler
  0x80014f9: DebugMon_Handler
  0x80014fb: PendSV_Handler
  0x80014fd: SysTick_Handler
  0x8001501: DMA1_Channel5_IRQHandler
  0x800150d: DMA1_Channel4_IRQHandler
  0x8001519: USART1_IRQHandler
  0x8001525: __libc_init_array
  0x800156d: memset
  0x800157c: __EH_FRAME_BEGIN__
  0x800157d: _init
  0x8001589: _fini
  0x8001594:
  - _etext
  - AHBPrescTable
  0x80015a4: APBPrescTable
  0x80015bc:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x80015c0:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x80015c4: _sidata
  0x20000000:
  - _sdata
  - LED_PORT
  0x20000004: BUTTON_PORT
  0x20000008: SystemCoreClock
  0x2000000c: uwTickFreq
  0x20000010: uwTickPrio
  0x20000014: aTxBuffer
  0x20000078:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x2000007c: object.8660
  0x20000094: hdma_tx.6522
  0x200000d8: hdma_rx.6523
  0x2000011c: hdma_tx.6532
  0x20000160: hdma_rx.6533
  0x200001a4: uwTick
  0x200001a8: UartHandle
  0x200001e8: aRxBuffer
  0x200001f4:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
