interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x800328c
    permissions: r-x
    size: 0xd74
  .heap:
    base_addr: 0x80039c8
    permissions: r--
    size: 0x42e38
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x10000000
    file: mtb-example-psoc6-uart-transmit-receive-dma.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x340a0
symbols:
  0x0:
  - psoc6_cm0p_bless.c
  - startup_psoc6_01_cm4.o
  - crtbegin.o
  - system_psoc6_cm4.c
  - cycfg.c
  - cycfg_clocks.c
  - cycfg_dmas.c
  - cycfg_peripherals.c
  - cycfg_pins.c
  - cycfg_routing.c
  - cycfg_system.c
  - UartDma.c
  - main.c
  - cy_syslib_ext.o
  - cyhal_hwmgr.c
  - cy_device.c
  - cy_ble_clk.c
  - cy_dma.c
  - cy_flash.c
  - cy_gpio.c
  - cy_ipc_drv.c
  - cy_ipc_pipe.c
  - cy_ipc_sema.c
  - cy_prot.c
  - cy_scb_uart.c
  - cy_sysclk.c
  - cy_sysint.c
  - cy_syslib.c
  - cy_syspm.c
  - cy_systick.c
  - cy_trigmux.c
  - _aeabi_uldivmod.o
  - _udivmoddi4.o
  - _dvmd_tls.o
  - libc_a-init.o
  - libc_a-fini.o
  - crti.o
  - crtn.o
  - crtend.o
  - cyhal_comp_ctb.c
  - cyhal_gpio.c
  - cyhal_pdmpcm.c
  0x1: __cy_memory_4_row_size
  0x200:
  - __cy_memory_1_row_size
  - __cy_memory_0_row_size
  - __cy_memory_3_row_size
  - __cy_memory_2_row_size
  0x28c: __VectorsSize
  0x400: Heap_Size
  0x1000:
  - Stack_Size
  - STACK_SIZE
  0x8000:
  - __cy_memory_2_length
  - __cy_memory_1_length
  0x20000: FLASH_CM0P_SIZE
  0xe0000: FLASH_CM4_SIZE
  0x100000:
  - __cy_memory_0_length
  - __cy_memory_4_length
  0x8000000: __cy_memory_3_length
  0x8003000:
  - __ram_vectors_start__
  - __ramVectors
  0x800328c:
  - __data_start__
  - __ram_vectors_end__
  - SystemCoreClock
  0x8003290: cy_AhbFreqHz
  0x8003294: cy_Hfclk0FreqHz
  0x8003298: cy_PeriClkFreqHz
  0x800329c: cy_delayFreqKhz
  0x80032a0: cy_delayFreqMhz
  0x80032a4:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x80032a8:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x80032ac: __fini_array_end
  0x80032ad: Cy_Flash_RAMDelay
  0x8003311: Cy_Flash_ResumeIrqHandler
  0x80033a1: Cy_Flash_NotifyHandler
  0x800340d: Cy_Flash_SendCmd
  0x8003575: EnterDeepSleepRam
  0x8003629: __Cy_IPC_Drv_SendMsgWord_veneer
  0x8003631: __Cy_IPC_Sema_Status_veneer
  0x8003639: __Cy_IPC_Sema_Clear_veneer
  0x8003641: __Cy_SysClk_ClkSlowGetFrequency_veneer
  0x8003649: __Cy_IPC_Pipe_SendMessage_veneer
  0x8003651: __Cy_Flash_OperationStatus_veneer
  0x8003659: __Cy_SysLib_ExitCriticalSection_veneer
  0x8003661: __Cy_SysLib_EnterCriticalSection_veneer
  0x8003668:
  - ipcWaitMessageStc.4
  - __TMC_END__
  - __data_end__
  0x800366c: cy_semaData.0
  0x8003678: _cyhal_comp_ctb_config_structs
  0x8003680: _cyhal_gpio_callbacks
  0x80036bc: _cyhal_gpio_source_signals
  0x80036c8: _cyhal_pdm_pcm_config_structs_inst0
  0x80036cc: cy_assertFileName
  0x80036e8: cy_assertLine
  0x80036ec: cy_faultFrame
  0x8003764:
  - completed.1
  - __bss_start__
  0x8003768: object.0
  0x8003780: cy_BleEcoClockFreqHz
  0x8003784: systemIpcPipeEpArray.2
  0x80038e4: systemIpcPipeSysCbArray.0
  0x8003904: RxDma_Descriptor_0
  0x800391c: RxDma_Descriptor_1
  0x8003934: num_correct
  0x8003938: rx_dma_done
  0x8003939: rx_dma_error
  0x800393c:
  - dma_buf_0
  - rx_dma_uart_buffer_a
  0x8003944:
  - rx_dma_uart_buffer_b
  - dma_buf_1
  0x800394c: uart_error
  0x8003950: cyhal_used
  0x8003974: cy_device
  0x8003978: flashContext
  0x8003988: ipcWaitMessage
  0x800398c: semaIndex.2
  0x8003990: semaMask.1
  0x8003994: semaPtr.0
  0x8003998: semaStruct.3
  0x800399c: cy_ipc_pipe_epArray
  0x80039a0: cy_semaIpcStruct
  0x80039a4: cySysClkExtFreq
  0x80039a8: ecoFrequency
  0x80039ac: wasEventSent
  0x80039b0: Cy_SysTick_Callbacks
  0x80039c4: __bss_end__
  0x80039c8:
  - __HeapBase
  - end
  - __end__
  0x8046800:
  - __HeapLimit
  - __StackLimit
  0x8047800:
  - __StackTop
  - __stack
  0x10000000:
  - __cy_m0p_code_start
  - FLASH_CM0P_START
  - cy_m0p_image
  - __cy_memory_0_start
  0x1001b610: __cy_m0p_code_end
  0x10020000:
  - FLASH_CM4_START
  - __Vectors
  0x1002028c:
  - __Vectors_Size
  - __Vectors_End
  0x1002028d: deregister_tm_clones
  0x100202a9: register_tm_clones
  0x100202cd: __do_global_dtors_aux
  0x100202f5: frame_dummy
  0x10020319: Cy_OnResetUser
  0x1002031b: cy_toolchain_init
  0x1002031d: Reset_Handler
  0x1002038d:
  - lpcomp_interrupt_IRQHandler
  - cpuss_interrupts_dw0_5_IRQHandler
  - cpuss_interrupts_ipc_6_IRQHandler
  - DebugMon_Handler
  - tcpwm_1_interrupts_11_IRQHandler
  - cpuss_interrupts_ipc_0_IRQHandler
  - tcpwm_1_interrupts_15_IRQHandler
  - tcpwm_1_interrupts_13_IRQHandler
  - cpuss_interrupts_dw1_8_IRQHandler
  - tcpwm_0_interrupts_0_IRQHandler
  - SysTick_Handler
  - cpuss_interrupt_fm_IRQHandler
  - cpuss_interrupts_ipc_7_IRQHandler
  - tcpwm_1_interrupts_14_IRQHandler
  - cpuss_interrupts_dw0_11_IRQHandler
  - tcpwm_1_interrupts_9_IRQHandler
  - cpuss_interrupts_cm0_cti_1_IRQHandler
  - tcpwm_1_interrupts_22_IRQHandler
  - cpuss_interrupts_dw0_4_IRQHandler
  - PendSV_Handler
  - NMI_Handler
  - cpuss_interrupts_dw1_12_IRQHandler
  - tcpwm_1_interrupts_12_IRQHandler
  - smif_interrupt_IRQHandler
  - tcpwm_1_interrupts_2_IRQHandler
  - cpuss_interrupts_ipc_13_IRQHandler
  - udb_interrupts_11_IRQHandler
  - tcpwm_1_interrupts_18_IRQHandler
  - tcpwm_0_interrupts_2_IRQHandler
  - cpuss_interrupts_dw0_13_IRQHandler
  - udb_interrupts_2_IRQHandler
  - cpuss_interrupts_dw1_7_IRQHandler
  - ioss_interrupts_gpio_1_IRQHandler
  - ioss_interrupts_gpio_7_IRQHandler
  - scb_5_interrupt_IRQHandler
  - udb_interrupts_6_IRQHandler
  - cpuss_interrupts_fault_1_IRQHandler
  - cpuss_interrupts_ipc_4_IRQHandler
  - cpuss_interrupts_ipc_5_IRQHandler
  - cpuss_interrupts_dw1_10_IRQHandler
  - udb_interrupts_0_IRQHandler
  - tcpwm_1_interrupts_6_IRQHandler
  - scb_4_interrupt_IRQHandler
  - pass_interrupt_dacs_IRQHandler
  - ioss_interrupts_gpio_2_IRQHandler
  - cpuss_interrupts_dw1_9_IRQHandler
  - cpuss_interrupts_dw1_13_IRQHandler
  - scb_2_interrupt_IRQHandler
  - udb_interrupts_5_IRQHandler
  - srss_interrupt_IRQHandler
  - udb_interrupts_12_IRQHandler
  - scb_0_interrupt_IRQHandler
  - csd_interrupt_IRQHandler
  - udb_interrupts_1_IRQHandler
  - profile_interrupt_IRQHandler
  - tcpwm_1_interrupts_1_IRQHandler
  - cpuss_interrupts_ipc_12_IRQHandler
  - tcpwm_1_interrupts_3_IRQHandler
  - tcpwm_0_interrupts_7_IRQHandler
  - cpuss_interrupts_dw1_1_IRQHandler
  - cpuss_interrupts_dw1_0_IRQHandler
  - cpuss_interrupts_dw0_9_IRQHandler
  - tcpwm_1_interrupts_23_IRQHandler
  - udb_interrupts_4_IRQHandler
  - tcpwm_1_interrupts_20_IRQHandler
  - ioss_interrupt_gpio_IRQHandler
  - tcpwm_0_interrupts_1_IRQHandler
  - ioss_interrupts_gpio_8_IRQHandler
  - tcpwm_0_interrupts_6_IRQHandler
  - scb_7_interrupt_IRQHandler
  - tcpwm_1_interrupts_7_IRQHandler
  - cpuss_interrupts_ipc_11_IRQHandler
  - udb_interrupts_13_IRQHandler
  - cpuss_interrupts_dw0_15_IRQHandler
  - udb_interrupts_7_IRQHandler
  - cpuss_interrupts_dw1_6_IRQHandler
  - cpuss_interrupt_crypto_IRQHandler
  - scb_1_interrupt_IRQHandler
  - Default_Handler
  - usb_interrupt_hi_IRQHandler
  - tcpwm_1_interrupts_0_IRQHandler
  - udb_interrupts_9_IRQHandler
  - audioss_interrupt_pdm_IRQHandler
  - srss_interrupt_mcwdt_0_IRQHandler
  - scb_3_interrupt_IRQHandler
  - pass_interrupt_ctbs_IRQHandler
  - udb_interrupts_8_IRQHandler
  - ioss_interrupts_gpio_3_IRQHandler
  - scb_6_interrupt_IRQHandler
  - cpuss_interrupts_cm4_cti_0_IRQHandler
  - cpuss_interrupts_dw1_3_IRQHandler
  - pass_interrupt_sar_IRQHandler
  - ioss_interrupts_gpio_0_IRQHandler
  - ioss_interrupts_gpio_14_IRQHandler
  - tcpwm_0_interrupts_4_IRQHandler
  - udb_interrupts_3_IRQHandler
  - tcpwm_0_interrupts_5_IRQHandler
  - cpuss_interrupts_ipc_15_IRQHandler
  - cpuss_interrupts_cm4_cti_1_IRQHandler
  - scb_8_interrupt_IRQHandler
  - srss_interrupt_mcwdt_1_IRQHandler
  - SVC_Handler
  - cpuss_interrupts_dw1_5_IRQHandler
  - cpuss_interrupts_ipc_1_IRQHandler
  - cpuss_interrupts_dw0_0_IRQHandler
  - ioss_interrupts_gpio_12_IRQHandler
  - cpuss_interrupts_ipc_3_IRQHandler
  - tcpwm_1_interrupts_17_IRQHandler
  - srss_interrupt_backup_IRQHandler
  - bless_interrupt_IRQHandler
  - cpuss_interrupts_ipc_10_IRQHandler
  - cpuss_interrupts_ipc_9_IRQHandler
  - cpuss_interrupts_dw0_14_IRQHandler
  - tcpwm_1_interrupts_4_IRQHandler
  - tcpwm_0_interrupts_3_IRQHandler
  - cpuss_interrupts_dw1_15_IRQHandler
  - ioss_interrupts_gpio_10_IRQHandler
  - udb_interrupts_10_IRQHandler
  - cpuss_interrupts_dw0_8_IRQHandler
  - ioss_interrupts_gpio_11_IRQHandler
  - cpuss_interrupts_ipc_14_IRQHandler
  - ioss_interrupts_gpio_5_IRQHandler
  - ioss_interrupts_gpio_4_IRQHandler
  - tcpwm_1_interrupts_8_IRQHandler
  - cpuss_interrupts_dw1_14_IRQHandler
  - usb_interrupt_med_IRQHandler
  - cpuss_interrupts_dw0_2_IRQHandler
  - tcpwm_1_interrupts_10_IRQHandler
  - cpuss_interrupts_fault_0_IRQHandler
  - cpuss_interrupts_dw0_12_IRQHandler
  - ioss_interrupts_gpio_6_IRQHandler
  - tcpwm_1_interrupts_21_IRQHandler
  - tcpwm_1_interrupts_16_IRQHandler
  - cpuss_interrupts_dw1_4_IRQHandler
  - udb_interrupts_15_IRQHandler
  - cpuss_interrupts_dw1_11_IRQHandler
  - cpuss_interrupts_dw0_6_IRQHandler
  - ioss_interrupt_vdd_IRQHandler
  - audioss_interrupt_i2s_IRQHandler
  - tcpwm_1_interrupts_5_IRQHandler
  - cpuss_interrupts_ipc_2_IRQHandler
  - cpuss_interrupts_dw0_10_IRQHandler
  - tcpwm_1_interrupts_19_IRQHandler
  - cpuss_interrupts_dw0_1_IRQHandler
  - ioss_interrupts_gpio_9_IRQHandler
  - usb_interrupt_lo_IRQHandler
  - cpuss_interrupts_ipc_8_IRQHandler
  - udb_interrupts_14_IRQHandler
  - cpuss_interrupts_dw0_7_IRQHandler
  - cpuss_interrupts_dw1_2_IRQHandler
  - cpuss_interrupts_cm0_cti_0_IRQHandler
  - ioss_interrupts_gpio_13_IRQHandler
  - cpuss_interrupts_dw0_3_IRQHandler
  0x10020391:
  - Fault_Handler
  - HardFault_Handler
  - UsageFault_Handler
  - MemManage_Handler
  - BusFault_Handler
  0x100203ad: Cy_SysIpcPipeIsrCm4
  0x100203b7: Cy_SystemInit
  0x100203b9: SystemCoreClockUpdate
  0x10020431: SystemInit
  0x10020469: Cy_SystemInitFpuEnable
  0x10020491: cycfg_config_init
  0x100204a9: cycfg_config_reservations
  0x100204bd: init_cycfg_all
  0x100204c9: init_cycfg_clocks
  0x10020535: reserve_cycfg_clocks
  0x10020561: reserve_cycfg_dmas
  0x10020579: init_cycfg_peripherals
  0x10020591: reserve_cycfg_peripherals
  0x100205a9: init_cycfg_pins
  0x100205fd: reserve_cycfg_pins
  0x100206b5: init_cycfg_routing
  0x10020709: cycfg_ClockStartupError
  0x1002070d: init_cycfg_system
  0x10020959: rx_dma_complete
  0x100209c5: configure_rx_dma
  0x10020add: Isr_UART
  0x10020b09: pwcheck_success
  0x10020b1d: pwcheck_passed_1
  0x10020b2d: pwcheck_passed_2
  0x10020b3d: pwcheck_passed_3
  0x10020b4d: pwcheck_passed_4
  0x10020b5d: pwcheck_passed_5
  0x10020b6d: pwcheck_passed_6
  0x10020b7d: pwcheck_passed_7
  0x10020b8d: pwcheck_passed_8
  0x10020b9d: check_password_scatter_gather
  0x10020c05: handle_error
  0x10020c0d: main
  0x10020cd9: Cy_SysLib_DelayCycles
  0x10020cde: Cy_DelayCycles_loop
  0x10020ce6: Cy_DelayCycles_done
  0x10020ceb: Cy_SysLib_EnterCriticalSection
  0x10020cf3: Cy_SysLib_ExitCriticalSection
  0x10020cf9: _cyhal_get_bit_position
  0x10020e31: cyhal_hwmgr_reserve
  0x10020eb9: Cy_PDL_Init
  0x10020ec5: Cy_BLE_EcoReset
  0x10020ee1: Cy_DMA_Descriptor_Init
  0x100210e5: Cy_DMA_Channel_Init
  0x10021201: Cy_Flash_ProcessOpcode
  0x100212d1: Cy_Flash_OperationStatus
  0x10021321: Cy_Flash_InitExt
  0x100213a1: Cy_Flash_Init
  0x100213b1: Cy_GPIO_Pin_Init
  0x1002161d: Cy_GPIO_Pin_FastInit
  0x100216f5: Cy_IPC_Drv_LockRelease
  0x10021721: Cy_IPC_Drv_SendMsgWord
  0x10021741: Cy_IPC_Drv_ReadMsgWord
  0x1002176d: Cy_IPC_Pipe_Config
  0x10021781: Cy_IPC_Pipe_EndpointInit
  0x10021831: Cy_IPC_Pipe_Init
  0x100218e5: Cy_IPC_Pipe_SendMessage
  0x10021985: Cy_IPC_Pipe_RegisterCallback
  0x100219c1: Cy_IPC_Pipe_ExecCallback
  0x10021a65: Cy_IPC_Pipe_ExecuteCallback
  0x10021a85: Cy_IPC_Sema_InitExt
  0x10021b1d: Cy_IPC_Sema_Init
  0x10021b75: Cy_IPC_Sema_Clear
  0x10021bf9: Cy_IPC_Sema_Status
  0x10021c41: Cy_Prot_GetActivePC
  0x10021c69: Cy_SCB_UART_Init
  0x10021f85: Cy_SysClk_PeriphSetDivider
  0x10022009: Cy_SysClk_PeriphAssignDivider
  0x10022081: Cy_SysClk_PeriphEnableDivider
  0x10022105: Cy_SysClk_PeriphDisableDivider
  0x10022169: Cy_SysClk_ClkSlowSetDivider
  0x10022185: Cy_SysClk_ClkSlowGetDivider
  0x1002219d: Cy_SysClk_ClkBakSetSource
  0x100221bd: Cy_SysClk_ClkTimerSetSource
  0x100221e9: Cy_SysClk_ClkTimerSetDivider
  0x10022201: Cy_SysClk_ClkTimerEnable
  0x10022215: Cy_SysClk_ClkTimerDisable
  0x10022229: Cy_SysClk_ClkLfSetSource
  0x10022249: Cy_SysClk_ClkPeriSetDivider
  0x10022265: Cy_SysClk_ClkPeriGetDivider
  0x10022279: Cy_SysClk_ClkFastSetDivider
  0x10022295: Cy_SysClk_ClkFastGetDivider
  0x100222ad: Cy_SysClk_ClkHfSetSource
  0x100222ed: Cy_SysClk_ClkHfGetSource
  0x10022311: Cy_SysClk_ClkHfSetDivider
  0x10022351: Cy_SysClk_ClkHfGetDivider
  0x10022375: Cy_SysClk_WcoOkay
  0x10022385: Cy_SysClk_WcoEnable
  0x100223b9: Cy_SysClk_AltHfGetFrequency
  0x100223c5: Cy_SysClk_AltLfGetFrequency
  0x100223c9: Cy_SysClk_IloEnable
  0x100223dd: Cy_SysClk_IloDisable
  0x10022405: Cy_SysClk_IloHibernateOn
  0x10022425: Cy_SysClk_ExtClkGetFrequency
  0x10022431: Cy_SysClk_EcoGetStatus
  0x10022455: Cy_SysClk_EcoGetFrequency
  0x1002246d: Cy_SysClk_ClkPathSetSource
  0x100224c9: Cy_SysClk_ClkPathGetSource
  0x10022505: Cy_SysClk_ClkPathMuxGetFrequency
  0x100225b5: Cy_SysClk_FllIsEnabled
  0x100225c5: Cy_SysClk_FllLocked
  0x100225d5: Cy_SysClk_FllDisable
  0x10022609: Cy_SysClk_FllManualConfigure
  0x1002270d: Cy_SysClk_FllGetConfiguration
  0x10022769: Cy_SysClk_FllEnable
  0x100227fd: Cy_SysClk_PllIsEnabled
  0x10022825: Cy_SysClk_PllDisable
  0x10022871: Cy_SysClk_PllManualConfigure
  0x10022941: Cy_SysClk_PllGetConfiguration
  0x1002298d: Cy_SysClk_PllEnable
  0x10022a41: Cy_SysClk_FllGetFrequency
  0x10022a9d: Cy_SysClk_PllGetFrequency
  0x10022b49: Cy_SysClk_ClkPathGetFrequency
  0x10022b89: Cy_SysClk_ClkHfGetFrequency
  0x10022ba9: Cy_SysClk_ClkPeriGetFrequency
  0x10022bc3: Cy_SysClk_ClkSlowGetFrequency
  0x10022bdd: Cy_SysInt_SetVector
  0x10022c15: Cy_SysInt_Init
  0x10022c7d: Cy_SysLib_DelayUs
  0x10022c91: Cy_SysLib_ResetBackupDomain
  0x10022cb1: Cy_SysLib_GetResetReason
  0x10022ce5: Cy_SysLib_ProcessingFault
  0x10022ce9: Cy_SysLib_FaultHandler
  0x10022d8d: Cy_SysLib_SetWaitStates
  0x10022e5d: Cy_SysLib_GetDeviceRevision
  0x10022e73: Cy_SysLib_GetDevice
  0x10022e8d: SetReadMarginTrimUlp
  0x10022efd: SetWriteAssistTrimLp
  0x10022f59: SetWriteAssistTrimUlp
  0x10022fa5: SetReadMarginTrimLp
  0x10023015: IsVoltageChangePossible
  0x10023091: Cy_SysPm_WriteVoltageBitForFlash
  0x1002316d: Cy_SysPm_LdoGetVoltage
  0x1002318d: Cy_SysPm_LdoIsEnabled
  0x100231a1: Cy_SysPm_SystemSetNormalRegulatorCurrent
  0x10023229: Cy_SysPm_SystemIsMinRegulatorCurrentSet
  0x10023251: Cy_SysPm_LdoSetVoltage
  0x10023321: Cy_SysPm_PmicDisableOutput
  0x10023349: Cy_SysPm_PmicUnlock
  0x1002335d: Cy_SysTick_EnableInterrupt
  0x1002336b: Cy_SysTick_SetReload
  0x1002337f: Cy_SysTick_Clear
  0x10023389: Cy_SysTick_GetCountFlag
  0x10023395: Cy_SysTick_ServiceCallbacks
  0x100233bd: Cy_SysTick_Enable
  0x100233d1: Cy_SysTick_SetClockSource
  0x10023409: Cy_SysTick_Init
  0x10023451: Cy_TrigMux_Connect
  0x10023509: __aeabi_uldivmod
  0x10023539: __udivmoddi4
  0x10023801:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x10023805: __libc_init_array
  0x1002384d: __libc_fini_array
  0x10023875: _init
  0x10023881: _fini
  0x1002388c: systemIpcPipeConfigCm4.1
  0x100238c0: CYBSP_CSD_CLK_DIV_obj
  0x100238c4: CYBSP_TRACE_CLK_DIV_obj
  0x100238c8: peri_0_div_16_15_obj
  0x100238cc: peri_0_div_8_1_obj
  0x100238d0: RxDma_Descriptor_0_config
  0x10023900: RxDma_Descriptor_1_config
  0x10023930: RxDma_channelConfig
  0x10023940: RxDma_obj
  0x10023944: TxDma_obj
  0x10023948: CYBSP_BLE_obj
  0x1002394c: KIT_UART_config
  0x1002398c: KIT_UART_obj
  0x10023990: CYBSP_CINA_obj
  0x10023994: CYBSP_CINB_obj
  0x10023998: CYBSP_CMOD_obj
  0x1002399c: CYBSP_CSD_BTN0_obj
  0x100239a0: CYBSP_CSD_BTN1_obj
  0x100239a4: CYBSP_CSD_SLD0_obj
  0x100239a8: CYBSP_CSD_SLD1_obj
  0x100239ac: CYBSP_CSD_SLD2_obj
  0x100239b0: CYBSP_CSD_SLD3_obj
  0x100239b4: CYBSP_CSD_SLD4_obj
  0x100239b8: CYBSP_CSD_TX_obj
  0x100239bc: CYBSP_DEBUG_UART_RX_config
  0x100239f0: CYBSP_DEBUG_UART_RX_obj
  0x100239f4: CYBSP_DEBUG_UART_TX_config
  0x10023a28: CYBSP_DEBUG_UART_TX_obj
  0x10023a2c: CYBSP_SWDCK_config
  0x10023a60: CYBSP_SWDCK_obj
  0x10023a64: CYBSP_SWDIO_config
  0x10023a98: CYBSP_SWDIO_obj
  0x10023a9c: CYBSP_SWO_config
  0x10023ad0: CYBSP_SWO_obj
  0x10023ad4: CYBSP_WCO_IN_obj
  0x10023ad8: CYBSP_WCO_OUT_obj
  0x10023adc: srss_0_clock_0_fll_0_fllConfig
  0x10023af0: srss_0_clock_0_pathmux_0_obj
  0x10023af4: srss_0_clock_0_pathmux_1_obj
  0x10023af8: srss_0_clock_0_pathmux_2_obj
  0x10023afc: srss_0_clock_0_pathmux_3_obj
  0x10023b00: srss_0_clock_0_pathmux_4_obj
  0x10023b04: srss_0_clock_0_pll_0_pllConfig
  0x10023b1c: cyhal_block_offsets_can
  0x10023b20: cyhal_block_offsets_clock
  0x10023b54: cyhal_block_offsets_dma
  0x10023b58: cyhal_block_offsets_dw
  0x10023b5c: cyhal_block_offsets_gpio
  0x10023b7c: cyhal_block_offsets_lpcomp
  0x10023b80: cyhal_block_offsets_opamp
  0x10023b84: cyhal_block_offsets_tcpwm
  0x10023b88: cyhal_block_offsets_tdm
  0x10023b8c: cyhal_resource_offsets
  0x10023bc8: cy_deviceIpBlockCfgPSoC6_01
  0x10023c8c:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x10023c90: __exidx_start
  0x10023c98:
  - __exidx_end
  - __copy_table_start__
  0x10023cb0:
  - __zero_table_start__
  - __copy_table_end__
  0x10023cb8:
  - __etext
  - __zero_table_end__
  0x14000000: __cy_memory_1_start
  0x16000000: __cy_memory_2_start
  0x18000000:
  - __cy_memory_3_start
  - __cy_xip_end
  - __cy_xip_start
  0x90700000: __cy_memory_4_start
