interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-GPIO_INT.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x15154
symbols:
  0x0:
  - startup_sam3xa.c
  - crtstuff.c
  - GPIO_INT.ino.cpp
  - variant.cpp
  - pio.c
  - pmc.c
  - system_sam3xa.c
  - adc.c
  - uotghs.c
  - WInterrupts.c
  - cortex_handlers.c
  - hooks.c
  - syscalls_sam3.c
  - wiring_analog.c
  - wiring_digital.c
  - Reset.cpp
  - RingBuffer.cpp
  - UARTClass.cpp
  - USARTClass.cpp
  - main.cpp
  - watchdog.cpp
  - wiring.c
  - Print.cpp
  - timetick.c
  - wdt.c
  - init.c
  - iprintf.c
  - memset.c
  - strlen.c
  - syskill.c
  - vfprintf.c
  - wsetup.c
  - __call_atexit.c
  - atexit.c
  - fflush.c
  - findfp.c
  - fini.c
  - fputwc.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - locale.c
  - makebuf.c
  - mallocr.c
  - memchr-stub.c
  - lib_a-memcpy.o
  - memmove.c
  - mlock.c
  - mallocr.c
  - sbrkr.c
  - signalr.c
  - stdio.c
  - wbuf.c
  - wcrtomb.c
  - wctomb_r.c
  - writer.c
  - __atexit.c
  - closer.c
  - fclose.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - readr.c
  - _aeabi_uldivmod.o
  - bpabi.c
  - _dvmd_tls.o
  - libgcc2.c
  - libgcc2.c
  - impure.c
  - /home/bo/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crti.o
  - /home/bo/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crtn.o
  - reent.c
  - __bss_start__
  - __bss_end__
  - software_init_hook
  - hardware_init_hook
  - __stack
  - free
  - malloc
  - __deregister_frame_info
  - __libc_fini
  - _Jv_RegisterClasses
  - __register_frame_info
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: _Z5blinkv
  0x8015d: setup
  0x80181: loop
  0x80191: _Z11serialEventv
  0x80195: UART_Handler
  0x801a1: _Z12serialEvent1v
  0x801a3: _Z12serialEvent2v
  0x801a5: _Z12serialEvent3v
  0x801a9: USART0_Handler
  0x801b5: USART1_Handler
  0x801c1: USART3_Handler
  0x801cd: init
  0x802f5: _GLOBAL__sub_I_g_APinDescription
  0x803c9: _Z14serialEventRunv
  0x8040d: PIO_PullUp
  0x80417: PIO_SetPeripheral
  0x8043d: PIO_SetInput
  0x80463: PIO_SetOutput
  0x80489: PIO_Configure
  0x804ed: PIO_GetOutputDataStatus
  0x80501: pmc_enable_periph_clk
  0x80545: pmc_disable_periph_clk
  0x80585: SystemInit
  0x8060d: Reset_Handler
  0x80685: adc_init
  0x8071d: adc_configure_trigger
  0x8072b: adc_configure_timing
  0x80745: adc_disable_channel
  0x8074f: adc_disable_all_channel
  0x80757: adc_disable_interrupt
  0x8075d: UOTGHS_Handler
  0x8076d: attachInterrupt
  0x808b5: PIOA_Handler
  0x808ed: PIOB_Handler
  0x80925: PIOC_Handler
  0x8095d: PIOD_Handler
  0x80995:
  - __halt
  - DACC_Handler
  - DebugMon_Handler
  - DMAC_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - TWI1_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - TWI0_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - TC8_Handler
  - USART2_Handler
  - EMAC_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - SPI0_Handler
  0x80997: SVC_Handler
  0x8099b: PendSV_Handler
  0x8099f: SysTick_Handler
  0x809b5:
  - __false
  - sysTickHook
  0x809b9:
  - __halt
  - pendSVHook
  - svcHook
  0x809bd: _sbrk
  0x809d9: link
  0x809df: _close
  0x809e5: _fstat
  0x809ef: _isatty
  0x809f3: _lseek
  0x809f7: _read
  0x809fd: _write
  0x80a21: _exit
  0x80a31: _kill
  0x80a33: _getpid
  0x80a39: analogOutputInit
  0x80a3d: pinMode
  0x80b45: digitalWrite
  0x80bb5: tickReset
  0x80bd5:
  - _ZN10RingBufferC1Ev
  - _ZN10RingBufferC2Ev
  0x80bef: _ZN10RingBuffer10store_charEh
  0x80c0d: _ZN9UARTClasscvbEv
  0x80c11: _ZN9UARTClass9availableEv
  0x80c23: _ZN9UARTClass4peekEv
  0x80c3f: _ZN9UARTClass4readEv
  0x80c69: _ZN9UARTClass5flushEv
  0x80c81: _ZN9UARTClass5writeEh
  0x80cd5: _ZN9UARTClass3endEv
  0x80d11:
  - _ZN9UARTClassC1EP4Uart4IRQnmP10RingBufferS4_
  - _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80d35: _ZN9UARTClass4initEmm
  0x80da5: _ZN9UARTClass5beginEm
  0x80dad: _ZN9UARTClass10IrqHandlerEv
  0x80df7: _ZN10USARTClass5beginEm
  0x80e01:
  - _ZN10USARTClassC1EP5Usart4IRQnmP10RingBufferS4_
  - _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x80e25: initVariant
  0x80e29: main
  0x80e55:
  - _Z13watchdogSetupv
  - _watchdogDefaultSetup
  0x80e61: delay
  0x80e63: _ZN5Print5writeEPKhj
  0x80e85: TimeTick_Increment
  0x80e95: WDT_Disable
  0x80e9d: __libc_init_array
  0x80eed: iprintf
  0x80f15: memset
  0x80fa9: strlen
  0x81009: kill
  0x81019: __sprint_r.part.0
  0x81091: _vfiprintf_r
  0x81ce5: __sbprintf
  0x81d61: __swsetup_r
  0x81e25: register_fini
  0x81e39: atexit
  0x81e45: __sflush_r
  0x81f8d: _fflush_r
  0x81fb9: _cleanup_r
  0x81fc5: __sinit
  0x820b9: __sfp_lock_acquire
  0x820bd: __sfp_lock_release
  0x820c1: __libc_fini_array
  0x820f1: _fputwc_r
  0x821b1: _malloc_trim_r
  0x8224d: _free_r
  0x823e5: __sfvwrite_r
  0x826f9: _fwalk
  0x82741: __locale_charset
  0x82749: __locale_mb_cur_max
  0x82755: __smakebuf_r
  0x82835: _malloc_r
  0x82d6d: memchr
  0x82e01: memcpy
  0x82eed: memmove
  0x82fb9: __malloc_lock
  0x82fbd: __malloc_unlock
  0x82fc1: _realloc_r
  0x83381: _sbrk_r
  0x833a5: _kill_r
  0x833cd: __sread
  0x833f1: __swrite
  0x83429: __sseek
  0x83449: __sclose
  0x83451: __swbuf_r
  0x834f9: _wcrtomb_r
  0x83549: __ascii_wctomb
  0x83565: _write_r
  0x8358d: __register_exitproc
  0x83635: _close_r
  0x83659: _fclose_r
  0x836d9: fclose
  0x836e9: _fstat_r
  0x83711: _isatty_r
  0x83735: _lseek_r
  0x8375d: _read_r
  0x83785: __aeabi_uldivmod
  0x837b1: __gnu_ldivmod_helper
  0x837e1: __gnu_uldivmod_helper
  0x83811:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x83815: __divdi3
  0x83ab5: __udivdi3
  0x83d44: g_APinDescription
  0x847d0: _ZTV9UARTClass
  0x84800: _ZTV10USARTClass
  0x84834: _global_impure_ptr
  0x84838: blanks.6717
  0x84878: zeroes.6718
  0x84889: _init
  0x84894:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x84898: __frame_dummy_init_array_entry
  0x848a0: __init_array_end
  0x848a1: _fini
  0x848ac:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x848b0:
  - __fini_array_end
  - _efixed
  0x848b8: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: _ZL5ticks
  0x20070038: impure_data
  0x20070460: _impure_ptr
  0x20070464: lc_ctype_charset
  0x20070484: __mb_cur_max
  0x20070488: __malloc_av_
  0x20070890: __malloc_trim_threshold
  0x20070894: __malloc_sbrk_base
  0x20070898: __wctomb
  0x2007089c:
  - completed.7857
  - _sbss
  - _szero
  - _erelocate
  0x200708a0: object.7862
  0x200708b8: state
  0x200708bc: tx_buffer2
  0x20070944: tx_buffer1
  0x200709cc: Serial
  0x200709f0: rx_buffer1
  0x20070a78: Serial1
  0x20070aa0: Serial2
  0x20070ac8: Serial3
  0x20070af0: tx_buffer3
  0x20070b78: tx_buffer4
  0x20070c00: g_pinStatus
  0x20070c50: rx_buffer2
  0x20070cd8: rx_buffer3
  0x20070d60: rx_buffer4
  0x20070de8: gpf_isr
  0x20070dec: enabled.9380
  0x20070df0: callbacksPioA
  0x20070e70: callbacksPioB
  0x20070ef0: callbacksPioC
  0x20070f70: callbacksPioD
  0x20070ff0: heap.6420
  0x20070ff4: _dwTickCount
  0x20070ff8: __malloc_max_total_mem
  0x20070ffc: __malloc_max_sbrked_mem
  0x20071000: __malloc_top_pad
  0x20071004: __malloc_current_mallinfo
  0x2007102c: errno
  0x20071030:
  - _ebss
  - _ezero
  - _end
  0x20088000:
  - __StackTop
  - __StackLimit
  - _estack
