interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_10001200:
    base_addr: 0xfffc000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10005000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: NRF52832_SPI_master.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x11c58
symbols:
  0x0:
  - _build/nrf52832_xxaa_gcc_startup_nrf52.S.o
  - crtstuff.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/nofp/crt0.o
  - exit.c
  - init.c
  - memset.c
  - _exit.c
  - app_error.c
  - app_error_weak.c
  - app_timer.c
  - boards.c
  - nrf_drv_common.c
  - nrf_drv_gpiote.c
  - nrf_drv_spi.c
  - nrf_drv_uart.c
  - main.c
  - system_nrf52.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/crti.o
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7e-m/nofp/crtn.o
  - impure.c
  - crtstuff.c
  - __isr_vector
  0x401: __do_global_dtors_aux
  0x425: frame_dummy
  0x441:
  - _mainCRTStartup
  - _start
  0x4b5: exit
  0x4dd: __libc_init_array
  0x525: memset
  0x535: _exit
  0x539: app_error_handler_bare
  0x559: app_error_fault_handler
  0x57d: RTC1_IRQHandler
  0x63d: SWI0_EGU0_IRQHandler
  0xc89: bsp_board_led_invert
  0xcad: bsp_board_leds_init
  0xce9: nrf_drv_common_irq_enable
  0xd31: GPIOTE_IRQHandler
  0x121d: nrf_drv_spi_init
  0x134d: nrf_drv_spi_transfer
  0x1441: SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler
  0x148d: UARTE0_UART0_IRQHandler
  0x1771: spi_event_handler
  0x177d: main
  0x1895: Reset_Handler
  0x18bd: NMI_Handler
  0x18bf: HardFault_Handler
  0x18c1: MemoryManagement_Handler
  0x18c3: BusFault_Handler
  0x18c5: UsageFault_Handler
  0x18c7: SVC_Handler
  0x18c9: DebugMon_Handler
  0x18cb: PendSV_Handler
  0x18cd: SysTick_Handler
  0x18cf:
  - TIMER2_IRQHandler
  - RTC0_IRQHandler
  - SWI2_EGU2_IRQHandler
  - PWM1_IRQHandler
  - POWER_CLOCK_IRQHandler
  - RADIO_IRQHandler
  - PDM_IRQHandler
  - TEMP_IRQHandler
  - QDEC_IRQHandler
  - TIMER3_IRQHandler
  - FPU_IRQHandler
  - TIMER4_IRQHandler
  - I2S_IRQHandler
  - SWI4_EGU4_IRQHandler
  - TIMER0_IRQHandler
  - TIMER1_IRQHandler
  - PWM2_IRQHandler
  - ECB_IRQHandler
  - SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler
  - Default_Handler
  - SAADC_IRQHandler
  - CCM_AAR_IRQHandler
  - WDT_IRQHandler
  - SWI5_EGU5_IRQHandler
  - RNG_IRQHandler
  - RTC2_IRQHandler
  - PWM0_IRQHandler
  - SWI3_EGU3_IRQHandler
  - SWI1_EGU1_IRQHandler
  - SPIM2_SPIS2_SPI2_IRQHandler
  - NFCT_IRQHandler
  - MWU_IRQHandler
  - COMP_LPCOMP_IRQHandler
  0x18d1: SystemInit
  0x1ba1: _init
  0x1bad: _fini
  0x1bb8: _global_impure_ptr
  0x1bbc: m_board_led_list
  0x1bd0: spi
  0x1bd8:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x1bdc: __exidx_start
  0x1be4:
  - __exidx_end
  - __etext
  0x2000:
  - Stack_Size
  - Heap_Size
  0x20000000:
  - impure_data
  - __data_start__
  0x20000060: m_tx_buf
  0x20000068: SystemCoreClock
  0x2000006c:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20000070:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x20000074: __data_end__
  0x20000078:
  - completed.8911
  - __bss_start__
  0x2000007c: object.8916
  0x20000094: m_evt_schedule_func
  0x20000098: m_op_queue
  0x200000a0: m_rtc1_reset
  0x200000a1: m_rtc1_running
  0x200000a4: m_ticks_elapsed
  0x200000ac: m_ticks_elapsed_q_read_ind
  0x200000ad: m_ticks_elapsed_q_write_ind
  0x200000b0: m_ticks_latest
  0x200000b4: mp_timer_id_head
  0x200000b8: m_cb
  0x20000110: m_cb
  0x20000130: m_cb
  0x20000150: m_rx_buf
  0x20000158: spi_xfer_done
  0x2000015c: __bss_end__
  0x20000160:
  - __HeapBase
  - __end__
  0x20002160: __HeapLimit
  0x2000e000: __StackLimit
  0x20010000:
  - __StackTop
  - __stack
