interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F429_ChibiOS_ADC_slider.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x13dd4
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - _arm_addsubsf3.o
  - _arm_muldivsf3.o
  - _arm_cmpsf2.o
  - _arm_fixsfsi.o
  - _arm_fixunssfsi.o
  - lib_a-memcpy.o
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __flash7_free__
  - __ram6_start__
  - __flash1_free__
  - __flash7_size__
  - __flash4_free__
  - __flash3_free__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __flash3_start__
  - __ram6_noinit__
  - __ram7_clear__
  - __ram7_size__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram3_end__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __flash2_size__
  - __flash4_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __flash6_size__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x1000: __ram5_size__
  0x4000: __ram2_size__
  0x75a3: crt1.c.486f1554
  0x7900: hal.c.6d6ca49f
  0x8e15: hal_st.c.559d3cab
  0xa557: hal_buffers.c.50ca17aa
  0xcaaa: hal_queues.c.b0389240
  0xee16: hal_adc.c.885cbbe8
  0x10000: __ram4_size__
  0x106b6: hal_pal.c.2ab0237c
  0x11de4: hal_serial.c.0cdf020f
  0x137cf: nvic.c.6097072c
  0x15050: stm32_isr.c.3e81b8a6
  0x16789: hal_lld.c.825d5565
  0x1812d: hal_adc_lld.c.4d2c49d4
  0x19a31: stm32_dma.c.01492c8c
  0x1b612: hal_pal_lld.c.3cb6821a
  0x1c000: __ram1_size__
  0x1cccf: hal_st_lld.c.8665f4ba
  0x1e5e1: hal_serial_lld.c.3c739e61
  0x1ff1a: board.c.d1693c07
  0x20000: __ram0_size__
  0x21824: chsys.c.a4673462
  0x230d1: chdebug.c.22fb3730
  0x23d46: chtrace.c.4c34418b
  0x24dd4: chvt.c.7f0e5f68
  0x25ca9: chschd.c.45c095a3
  0x26c04: chthreads.c.e52fe36b
  0x2820d: chtm.c.7fa24ad6
  0x29090: chregistry.c.77f31f24
  0x2a66b: chmtx.c.8b005704
  0x2b5c1: chevents.c.627560a0
  0x2c6ff: chdynamic.c.dd96e3d2
  0x2d5ac: chmemcore.c.7962fb80
  0x2e2d8: chmemheaps.c.a7216f70
  0x2f1a2: chmempools.c.fef221f7
  0x30121: chfactory.c.0792c3b4
  0x31ff0: chcore_v7m.c.d34d31a0
  0x32eb9: chprintf.c.1be96580
  0x3479e: main.c.bc3a7938
  0x100000: __flash0_size__
  0x8000000:
  - _vectors
  - __flash0_start__
  0x80001e0:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x80001e1: _crt0_entry
  0x8000214: msloop
  0x8000222: psloop
  0x8000232: dloop
  0x8000246: bloop
  0x800025c: initloop
  0x8000268: endinitloop
  0x8000270: finiloop
  0x800027c: endfiniloop
  0x80002b9: Reset_Handler
  0x80002bb:
  - Vector58
  - VectorE8
  - Vector9C
  - VectorAC
  - DebugMon_Handler
  - Vector1A0
  - Vector5C
  - Vector11C
  - HardFault_Handler
  - Vector1B8
  - Vector19C
  - Vector8C
  - SysTick_Handler
  - PendSV_Handler
  - Vector168
  - NMI_Handler
  - Vector110
  - Vector1D8
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - Vector160
  - Vector1B0
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - VectorBC
  - Vector190
  - Vector1C4
  - Vector1CC
  - Vector148
  - Vector188
  - Vector198
  - Vector118
  - Vector64
  - VectorCC
  - Vector54
  - Vector98
  - VectorD8
  - Vector138
  - Vector24
  - Vector1AC
  - Vector178
  - Vector1A4
  - VectorD0
  - Vector1B4
  - Vector140
  - VectorE4
  - VectorC0
  - Vector1C0
  - Vector134
  - Vector1D0
  - VectorF0
  - Vector13C
  - Vector100
  - VectorE0
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector180
  - Vector90
  - Vector114
  - Vector164
  - Vector60
  - Vector1C
  - Vector1BC
  - Vector1D4
  - Vector17C
  - Vector48
  - Vector1A8
  - Vector16C
  - VectorD4
  - Vector4C
  - Vector144
  - Vector15C
  - Vector68
  - Vector170
  - Vector104
  - Vector184
  - Vector10C
  - Vector14C
  - BusFault_Handler
  - Vector50
  - Vector1C8
  - Vector194
  - Vector1DC
  - Vector44
  - Vector28
  - VectorB8
  - Vector34
  - VectorA4
  - Vector20
  - Vector18C
  - Vector174
  0x80002be: .stay
  0x80002bf: _unhandled_exception
  0x80002c1: _port_switch
  0x80002d1: _port_thread_start
  0x80002e5: _port_switch_from_isr
  0x80002f0: _port_exit_from_isr
  0x80002f5: __aeabi_frsub
  0x80002fd:
  - __subsf3
  - __aeabi_fsub
  0x8000301:
  - __aeabi_fadd
  - __addsf3
  0x8000461:
  - __aeabi_ui2f
  - __floatunsisf
  0x8000469:
  - __aeabi_i2f
  - __floatsisf
  0x8000485:
  - __floatundisf
  - __aeabi_ul2f
  0x8000495:
  - __floatdisf
  - __aeabi_l2f
  0x8000511:
  - __mulsf3
  - __aeabi_fmul
  0x8000679:
  - __divsf3
  - __aeabi_fdiv
  0x80007b1:
  - __gtsf2
  - __gesf2
  0x80007b9:
  - __lesf2
  - __ltsf2
  0x80007c1:
  - __nesf2
  - __eqsf2
  - __cmpsf2
  0x8000821: __aeabi_cfrcmple
  0x8000829:
  - __aeabi_cfcmple
  - __aeabi_cfcmpeq
  0x8000839: __aeabi_fcmpeq
  0x800084d: __aeabi_fcmplt
  0x8000861: __aeabi_fcmple
  0x8000875: __aeabi_fcmpge
  0x8000889: __aeabi_fcmpgt
  0x800089d:
  - __fixsfsi
  - __aeabi_f2iz
  0x80008e9:
  - __aeabi_f2uiz
  - __fixunssfsi
  0x8000929: memcpy
  0x8000a61: _pal_lld_setgroupmode.constprop.0
  0x8000ae1: chTMStartMeasurementX.constprop.0
  0x8000af1: notify3
  0x8000b01: _port_irq_epilogue
  0x8000b61: chTMStopMeasurementX
  0x8000bb1: trace_next
  0x8000bf1: _trace_switch.part.0
  0x8000c11: _trace_isr_leave
  0x8000c41: _trace_isr_enter
  0x8000c71: chSysHalt
  0x8000ca1: chDbgCheckClassS
  0x8000cc1: chDbgCheckClassI
  0x8000ce1: chCoreAllocAlignedWithOffsetI
  0x8000d31: chCoreAllocAlignedI
  0x8000d41: chSchReadyI
  0x8000d91: chThdDequeueNextI.constprop.0
  0x8000dc1: chThdResumeI
  0x8000df1: _dbg_check_leave_isr
  0x8000e21: _dbg_check_enter_isr
  0x8000e51: _dbg_check_unlock_from_isr
  0x8000e81: _dbg_check_lock_from_isr
  0x8000eb1: wakeup
  0x8000f11: _idle_thread
  0x8000f21: adc_lld_stop_conversion
  0x8000f61: adc_lld_serve_rx_interrupt
  0x8001031: _ctl
  0x8001051: stSetAlarm
  0x8001071: chEvtBroadcastFlagsI.constprop.0
  0x8001101: chSchWakeupS.constprop.0
  0x8001181: chSchGoSleepS
  0x80011e1: chSchGoSleepTimeoutS
  0x8001331: chThdEnqueueTimeoutS
  0x8001361: chprintf
  0x8001791: SVC_Handler
  0x80017b1:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8001841: _dbg_check_unlock
  0x8001861: chSysUnlock.lto_priv.3
  0x8001891: _dbg_check_lock
  0x80018b1: chCoreAllocAlignedWithOffset
  0x8001901: Thd2
  0x8001b51: Thd1
  0x8001bb1: chRegFindThreadByWorkingArea
  0x8001fe1: chThdCreateStatic.constprop.0
  0x8002091: main
  0x8002751: chThdExit
  0x80027b1: oqWriteTimeout
  0x80028c1: _writet
  0x80028d1: _write
  0x80028e1: oqPutTimeout
  0x8002981: _putt
  0x8002991: _put
  0x80029a1: iqReadTimeout
  0x8002ab1: _readt
  0x8002ac1: _read
  0x8002ad1: iqGetTimeout
  0x8002b51: _gett
  0x8002b61: _get
  0x8002b71: __early_init
  0x8002dd1: VectorDC
  0x8002fa1: VectorB0
  0x8003091: Vector158
  0x80030e1: Vector154
  0x8003131: Vector150
  0x8003181: Vector130
  0x80031c1: Vector12C
  0x8003211: Vector128
  0x8003261: Vector124
  0x80032b1: Vector120
  0x80032f1: VectorFC
  0x8003341: Vector84
  0x8003391: Vector80
  0x80033e1: Vector7C
  0x8003421: Vector78
  0x8003471: Vector74
  0x80034c1: Vector70
  0x8003511: Vector6C
  0x8003551: Vector88
  0x80037e1: __init_ram_areas
  0x8003851: __default_exit
  0x8003861: __late_init
  0x8003871: __core_init
  0x8003874:
  - __text_end
  - __rodata_base__
  0x8003944: __func__.6136.lto_priv.0
  0x8003950: __func__.6136.lto_priv.1
  0x800395c: __func__.6136.lto_priv.2
  0x8003968: __func__.6136.lto_priv.3
  0x8003974: __func__.6136.lto_priv.4
  0x8003980: __func__.6136.lto_priv.5
  0x800398c: __func__.6222
  0x8003998: __func__.6337
  0x80039ac: __func__.6538.lto_priv.0
  0x80039b8: __func__.6538.lto_priv.1
  0x80039c4: __func__.7126
  0x80039d0: __func__.7129.lto_priv.0
  0x80039dc: __func__.7129.lto_priv.1
  0x80039e8: __func__.7133.lto_priv.0
  0x80039fc: __func__.7133.lto_priv.1
  0x8003a1c: __func__.7148.lto_priv.0
  0x8003a28: __func__.7148.lto_priv.1
  0x8003a34: __func__.7151.lto_priv.1
  0x8003a40: __func__.7152
  0x8003a4c: __func__.7157
  0x8003a60: __func__.7162
  0x8003a70: __func__.7168
  0x8003a80: __func__.7169
  0x8003a90: __func__.7184
  0x8003a9c: __func__.7229
  0x8003aac: __func__.7529
  0x8003abc: __func__.7895
  0x8003ac8: __func__.7898
  0x8003ad8: __func__.7902
  0x8003ae4: __func__.7903
  0x8003af0: __func__.7904
  0x8003afc: __func__.7905
  0x8003b08: __func__.7909
  0x8003b14: __func__.7910
  0x8003b24: __func__.7914
  0x8003b30: __func__.7919.lto_priv.0
  0x8003b44: __func__.7919.lto_priv.1
  0x8003b50: __func__.7924
  0x8003b5c: __func__.7925
  0x8003b68: __func__.7929
  0x8003b74: __func__.7934
  0x8003b80: __func__.7935
  0x8003b8c: __func__.7936
  0x8003b94: __func__.7939
  0x8003ba0: __func__.7944
  0x8003bac: __func__.7949
  0x8003bb8: __func__.7954.lto_priv.0
  0x8003bc0: __func__.7954.lto_priv.1
  0x8003bcc: __func__.7959
  0x8003bd8: __func__.7964
  0x8003be4: __func__.7969
  0x8003bf0: __func__.7974
  0x8003bfc: __func__.7979
  0x8003c08: __func__.8352
  0x8003c18: __func__.8403
  0x8003c28: _stm32_dma_streams
  0x8003ce8: ch_debug
  0x8003d00: my_conversion_group
  0x8003d2c: ram_areas
  0x8003dac: vmt
  0x8003dd4:
  - __exidx_end
  - __ram3_init_text__
  - __rodata_end__
  - __exidx_start
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  - _textdata_start
  0x8100000: __flash0_end__
  0x10000000:
  - ICSR_PENDSVSET
  - __ram4_start__
  - __ram4_clear__
  - __ram4_init__
  - __ram4_noinit__
  - __ram4_free__
  0x10010000: __ram4_end__
  0x20000000:
  - __ram1_free__
  - __ram1_clear__
  - __ram1_start__
  - __ram1_noinit__
  - __ram0_start__
  - __ram1_init__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - ADCD1
  - __main_thread_stack_end__
  - _bss_start
  - _data_start
  - _data_end
  - __process_stack_end__
  0x20000834: ADCD2
  0x20000868: ADCD3
  0x2000089c: SD3
  0x20000918: ch
  0x200011a0: ch_factory
  0x200011e8: ch_idle_thread_wa
  0x200012c0: ch_memcore
  0x200012c8: default_heap
  0x200012e4: dma
  0x20001368: flag
  0x2000136c: lastvalue
  0x20001370: mean
  0x20001374: sample_buff
  0x200013a0: waThd1
  0x20001568: waThd2
  0x20001830:
  - __ram0_init__
  - __ram0_free__
  - __heap_base__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x2001c000:
  - __ram1_end__
  - __ram2_noinit__
  - __ram2_clear__
  - __ram2_init__
  - __ram2_start__
  - __ram2_free__
  0x20020000:
  - __heap_end__
  - __ram2_end__
  - __ram0_end__
  0x40024000:
  - __ram5_clear__
  - __ram5_noinit__
  - __ram5_free__
  - __ram5_init__
  - __ram5_start__
  0x40025000: __ram5_end__
  0xe000ed04: SCB_ICSR
