interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_ChibiOS_ADC_slider.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x137c4
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - _arm_addsubsf3.o
  - _arm_muldivsf3.o
  - _arm_cmpsf2.o
  - _arm_fixsfsi.o
  - _arm_fixunssfsi.o
  - lib_a-memcpy.o
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __ram4_start__
  - __flash7_free__
  - __ram5_clear__
  - __ram1_free__
  - __ram6_start__
  - __ram5_end__
  - __ram5_noinit__
  - __flash1_free__
  - __ram5_size__
  - __flash7_size__
  - __flash4_free__
  - __ram1_size__
  - __flash3_free__
  - __ram1_clear__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __ram4_size__
  - __ram1_end__
  - __ram4_end__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __ram4_clear__
  - __ram5_free__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __ram2_noinit__
  - __flash3_start__
  - __ram6_noinit__
  - __ram4_init__
  - __ram7_clear__
  - __ram7_size__
  - __ram4_noinit__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram2_clear__
  - __ram3_end__
  - __ram2_size__
  - __ram1_start__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __ram1_noinit__
  - __flash2_size__
  - __flash4_end__
  - __ram2_init__
  - __ram2_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram2_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __ram5_init__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __ram1_init__
  - __ram5_start__
  - __flash6_size__
  - __ram2_free__
  - __ram4_free__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x5000: __ram0_size__
  0x6983: crt1.c.5a17ca93
  0x6ce0: hal.c.ffa1a01d
  0x82d6: hal_st.c.cf1d3cce
  0x9af9: hal_buffers.c.dfc28cf9
  0xc12d: hal_queues.c.5fb4298d
  0xe57a: hal_adc.c.aaa2741f
  0xfefb: hal_pal.c.4d95ed43
  0x11747: hal_serial.c.794bc1e8
  0x13213: nvic.c.73cab202
  0x14b75: stm32_isr.c.6f1c19f1
  0x16414: hal_lld.c.ffd08517
  0x17b82: hal_adc_lld.c.c6c890e9
  0x1938f: stm32_dma.c.1c9850d5
  0x1ad73: hal_pal_lld.c.452bfe5b
  0x1c78a: hal_st_lld.c.3e3d808c
  0x1e039: hal_serial_lld.c.243f7a54
  0x1f92b: board.c.581f340e
  0x20000: __flash0_size__
  0x20f28: chsys.c.582094bf
  0x22719: chdebug.c.ce7033c6
  0x2338e: chtrace.c.25d2c17b
  0x2441c: chvt.c.a2333f99
  0x252fa: chschd.c.5e6bb030
  0x26255: chthreads.c.03b10d68
  0x2785e: chtm.c.24b14fd6
  0x286e1: chregistry.c.aba1168c
  0x29cbc: chmtx.c.1af0e4c0
  0x2ac12: chevents.c.87b5ad10
  0x2bd50: chdynamic.c.1ab8cc0c
  0x2cbfd: chmemcore.c.ee6bd0ed
  0x2d929: chmemheaps.c.0b354387
  0x2e7f3: chmempools.c.c8303399
  0x2f772: chfactory.c.80a29f64
  0x31641: chcore_v7m.c.bdf35e2e
  0x3250a: chprintf.c.474d1c43
  0x33ed0: main.c.dcc336a1
  0x8000000:
  - _vectors
  - __flash0_start__
  0x8000160:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x8000161: _crt0_entry
  0x8000194: msloop
  0x80001a2: psloop
  0x80001b2: dloop
  0x80001c6: bloop
  0x80001dc: initloop
  0x80001e8: endinitloop
  0x80001f0: finiloop
  0x80001fc: endfiniloop
  0x8000239: Reset_Handler
  0x800023b:
  - VectorE8
  - VectorAC
  - DebugMon_Handler
  - Vector11C
  - HardFault_Handler
  - Vector8C
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - Vector110
  - Vector120
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - VectorBC
  - Vector150
  - Vector124
  - Vector148
  - Vector118
  - VectorCC
  - Vector54
  - Vector98
  - VectorD8
  - Vector138
  - Vector24
  - VectorD0
  - Vector140
  - VectorE4
  - VectorC0
  - Vector158
  - Vector130
  - Vector134
  - VectorF0
  - Vector12C
  - Vector13C
  - Vector100
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector90
  - Vector114
  - Vector1C
  - Vector48
  - VectorD4
  - Vector4C
  - Vector144
  - Vector15C
  - Vector88
  - Vector104
  - Vector10C
  - Vector14C
  - BusFault_Handler
  - Vector50
  - Vector154
  - Vector44
  - Vector28
  - VectorB8
  - VectorFC
  - Vector34
  - Vector128
  - VectorA4
  - Vector20
  0x800023e: .stay
  0x800023f: _unhandled_exception
  0x8000241: _port_switch
  0x8000251: _port_thread_start
  0x8000265: _port_switch_from_isr
  0x8000270: _port_exit_from_isr
  0x8000275: __aeabi_frsub
  0x800027d:
  - __subsf3
  - __aeabi_fsub
  0x8000281:
  - __aeabi_fadd
  - __addsf3
  0x80003e1:
  - __aeabi_ui2f
  - __floatunsisf
  0x80003e9:
  - __aeabi_i2f
  - __floatsisf
  0x8000405:
  - __floatundisf
  - __aeabi_ul2f
  0x8000415:
  - __floatdisf
  - __aeabi_l2f
  0x8000491:
  - __mulsf3
  - __aeabi_fmul
  0x80005f9:
  - __divsf3
  - __aeabi_fdiv
  0x8000731:
  - __gtsf2
  - __gesf2
  0x8000739:
  - __lesf2
  - __ltsf2
  0x8000741:
  - __nesf2
  - __eqsf2
  - __cmpsf2
  0x80007a1: __aeabi_cfrcmple
  0x80007a9:
  - __aeabi_cfcmple
  - __aeabi_cfcmpeq
  0x80007b9: __aeabi_fcmpeq
  0x80007cd: __aeabi_fcmplt
  0x80007e1: __aeabi_fcmple
  0x80007f5: __aeabi_fcmpge
  0x8000809: __aeabi_fcmpgt
  0x800081d:
  - __fixsfsi
  - __aeabi_f2iz
  0x8000869:
  - __aeabi_f2uiz
  - __fixunssfsi
  0x80008a9: memcpy
  0x80009a1: _pal_lld_setgroupmode.constprop.0
  0x80009e1: chTMStartMeasurementX.constprop.0
  0x80009f1: notify3
  0x8000a01: _port_irq_epilogue
  0x8000a61: chTMStopMeasurementX
  0x8000ab1: trace_next
  0x8000af1: _trace_switch.part.0
  0x8000b11: _trace_isr_leave
  0x8000b41: _trace_isr_enter
  0x8000b71: chSysHalt
  0x8000ba1: chDbgCheckClassS
  0x8000bc1: chDbgCheckClassI
  0x8000be1: chCoreAllocAlignedWithOffsetI
  0x8000c31: chCoreAllocAlignedI
  0x8000c41: chSchReadyI
  0x8000c91: chThdDequeueNextI.constprop.0
  0x8000cc1: chThdResumeI
  0x8000cf1: _dbg_check_leave_isr
  0x8000d21: _dbg_check_enter_isr
  0x8000d51: _dbg_check_unlock_from_isr
  0x8000d81: _dbg_check_lock_from_isr
  0x8000db1: adc_lld_serve_rx_interrupt
  0x8000eb1: wakeup
  0x8000f11: _idle_thread
  0x8000f21: dmaServeInterrupt
  0x8000f61: _ctl
  0x8000f81: stSetAlarm
  0x8000fa1: chEvtBroadcastFlagsI.constprop.0
  0x8001031: chSchWakeupS.constprop.0
  0x80010b1: chSchGoSleepS
  0x8001111: chSchGoSleepTimeoutS
  0x80012a1: chThdEnqueueTimeoutS
  0x80012d1: chprintf
  0x80016e1: SVC_Handler
  0x8001701:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8001791: _dbg_check_unlock
  0x80017b1: chSysUnlock.lto_priv.3
  0x80017e1: _dbg_check_lock
  0x8001801: chCoreAllocAlignedWithOffset
  0x8001851: Thd2
  0x8001a71: Thd1
  0x8001ad1: chRegFindThreadByWorkingArea
  0x8001f11: chThdCreateStatic.constprop.0
  0x8001fc1: main
  0x80026a1: chThdExit
  0x8002701: oqWriteTimeout
  0x8002811: _writet
  0x8002821: _write
  0x8002831: oqPutTimeout
  0x80028d1: _putt
  0x80028e1: _put
  0x80028f1: iqReadTimeout
  0x8002a11: _readt
  0x8002a21: _read
  0x8002a31: iqGetTimeout
  0x8002ab1: _gett
  0x8002ac1: _get
  0x8002ad1: __early_init
  0x8002b51: VectorDC
  0x8002d21: VectorB0
  0x8002e41: Vector84
  0x8002e71: Vector80
  0x8002ea1: Vector7C
  0x8002ed1: Vector78
  0x8002f01: Vector74
  0x8002f31: Vector70
  0x8002f61: Vector6C
  0x8002f91: VectorE0
  0x8003021: Vector9C
  0x80030a1: Vector68
  0x80030f1: Vector64
  0x8003141: Vector60
  0x8003191: Vector5C
  0x80031e1: Vector58
  0x8003231: __init_ram_areas
  0x80032a1: __default_exit
  0x80032b1: __late_init
  0x80032c1: __core_init
  0x80032c4:
  - __text_end
  - __rodata_base__
  0x8003394: __func__.4292.lto_priv.0
  0x80033a0: __func__.4292.lto_priv.1
  0x80033ac: __func__.5513.lto_priv.0
  0x80033b8: __func__.5513.lto_priv.1
  0x80033c4: __func__.5513.lto_priv.2
  0x80033d0: __func__.5513.lto_priv.3
  0x80033dc: __func__.5513.lto_priv.4
  0x80033e8: __func__.5513.lto_priv.5
  0x80033f4: __func__.5599
  0x8003400: __func__.5714
  0x8003414: __func__.5915.lto_priv.0
  0x8003420: __func__.5915.lto_priv.1
  0x800342c: __func__.6503
  0x8003438: __func__.6506.lto_priv.0
  0x8003444: __func__.6506.lto_priv.1
  0x8003450: __func__.6510.lto_priv.0
  0x8003464: __func__.6510.lto_priv.1
  0x8003484: __func__.6525.lto_priv.0
  0x8003490: __func__.6525.lto_priv.1
  0x800349c: __func__.6528.lto_priv.1
  0x80034a8: __func__.6529
  0x80034b4: __func__.6534
  0x80034c8: __func__.6539
  0x80034d8: __func__.6545
  0x80034e8: __func__.6546
  0x80034f8: __func__.6561
  0x8003504: __func__.6606
  0x8003514: __func__.6906
  0x8003524: __func__.7260
  0x8003530: __func__.7261
  0x800353c: __func__.7263
  0x800354c: __func__.7266
  0x8003558: __func__.7267
  0x8003564: __func__.7269
  0x8003570: __func__.7270
  0x800357c: __func__.7271
  0x8003588: __func__.7273
  0x8003594: __func__.7274
  0x80035a4: __func__.7276
  0x80035b0: __func__.7277
  0x80035bc: __func__.7281.lto_priv.0
  0x80035c8: __func__.7281.lto_priv.1
  0x80035d4: __func__.7284
  0x80035e8: __func__.7285
  0x80035f4: __func__.7286
  0x8003600: __func__.7289
  0x800360c: __func__.7290
  0x8003618: __func__.7291
  0x8003624: __func__.7293
  0x8003630: __func__.7300
  0x800363c: __func__.7301
  0x8003644: __func__.7319
  0x800364c: __func__.7717
  0x800365c: __func__.7768
  0x800366c: _stm32_dma_streams
  0x80036dc: ch_debug
  0x80036f4: my_conversion_group
  0x800371c: ram_areas
  0x800379c: vmt
  0x80037c4:
  - __exidx_end
  - __ram3_init_text__
  - __rodata_end__
  - __exidx_start
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  - _textdata_start
  0x8020000: __flash0_end__
  0x10000000: ICSR_PENDSVSET
  0x20000000:
  - __ram0_start__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - ADCD1
  - __main_thread_stack_end__
  - _bss_start
  - _data_start
  - _data_end
  - __process_stack_end__
  0x20000834: SD3
  0x200008b0: _pal_events
  0x20000930: ch
  0x200011b8: ch_factory
  0x20001200: ch_idle_thread_wa
  0x200012d8: ch_memcore
  0x200012e0: default_heap
  0x200012fc: dma
  0x2000133c: flag
  0x20001340: lastvalue
  0x20001344: mean
  0x20001348: sample_buff
  0x20001370: waThd1
  0x20001538: waThd2
  0x20001800:
  - __ram0_init__
  - __ram0_free__
  - __heap_base__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x20005000:
  - __heap_end__
  - __ram0_end__
  0xe000ed04: SCB_ICSR
