interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x10000000
    permissions: rw-
    size: 0x1250
  dynamically_added_crash_region_10007ff8:
    base_addr: 0x10002000
    permissions: rw-
    size: 0xa000
  dynamically_added_crash_region_20303021:
    base_addr: 0x202fe000
    permissions: rw-
    size: 0xa000
  dynamically_added_crash_region_30203048:
    base_addr: 0x301fe000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x1a000000
    file: periph_uart_sg.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x29078
symbols:
  0x0:
  - cr_startup_lpc18xx.c
  - isup.c
  - mtp2.c
  - mtp3.c
  - ss7.c
  - ss7_sched.c
  - sysinit.c
  - uart.c
  - board.c
  - board_sysinit.c
  - chip_18xx_43xx.c
  - clock_18xx_43xx.c
  - gpdma_18xx_43xx.c
  - gpio_18xx_43xx.c
  - sysinit_18xx_43xx.c
  - uart_18xx_43xx.c
  - ring_buffer.c
  - _cr__main.c
  - memcpy.c
  - memset.c
  - alloc.c
  - fpprintf.c
  - fputs.c
  - initio.c
  - memcmp.c
  - printf.c
  - setvbuf.c
  - strchr.c
  - strlen.c
  - _cr_sbrk.c
  - _deferredlazyseek.c
  - _fdopen.c
  - _fflush.c
  - _frexpl.c
  - _ldexpl.c
  - _writebuf.c
  - fclose.c
  - fflush.c
  - fseek.c
  - ftell.c
  - remove.c
  - _cr_check_heap.c
  - _do_fflush.c
  - division_64.o
  - division_idiv0.o
  - double.c
  - memcpy.o
  - __sys_appexit.c
  - __sys_close.c
  - __sys_flen.c
  - __sys_istty.c
  - __sys_remove.c
  - __sys_seek.c
  - __sys_tmpnam.c
  - __ciob.c
  - __init_alloc.c
  - errno.c
  0x19078: _image_size
  0x10000000:
  - iam_params
  - __base_RamLoc32
  - _end_uninit_RESERVED
  - _start_uninit_RESERVED
  - _data
  - __base_RAM
  0x10000034: ansi_iam_params
  0x10000084: acm_params
  0x1000008c: frj_params
  0x10000098: faa_params
  0x100000a4: far_params
  0x100000b0: anm_params
  0x100000b8: con_params
  0x100000c4: rel_params
  0x100000cc: greset_params
  0x100000d4: cot_params
  0x100000dc: cpg_params
  0x100000e8: cicgroup_params
  0x100000f4: cqr_params
  0x10000100: sus_res_params
  0x1000010c: inr_params
  0x10000114: inf_params
  0x10000124: sam_params
  0x1000012c: empty_params
  0x10000130: messages
  0x10000478: parms
  0x10000ce8: testmessage
  0x10000cf4: net_mng_messages
  0x10000e80: isDMATx
  0x10000e84: GPDMA_LUTPerAddr
  0x10000efc:
  - __ss7_message
  - _bss
  - _edata
  0x10000f00: __ss7_error
  0x10000f04: ss7_notinservice
  0x10000f08: ss7_hangup
  0x10000f0c: ss7_call_null
  0x10000f10: DMADest_Buffer
  0x10000f98: DMADest_Buffer_2
  0x10001018: txring
  0x1000102c: rxring
  0x10001040: dmaChannelNumTx
  0x10001041: dmaChannelNumRx
  0x10001044: channelTC
  0x10001048: channelTCErr
  0x1000104c: SystemCoreClock
  0x10001050: audio_usb_pll_freq
  0x10001058: ChannelHandlerArray
  0x10001060: ABsyncSts
  0x10001064: __Ciob
  0x10001244: __end_of_heap
  0x10001248: __heaps
  0x1000124c: errno
  0x10001250:
  - _noinit
  - _ebss
  - _end_noinit
  - _pvHeapStart
  0x10008000:
  - __top_RAM
  - __top_RamLoc32
  - _vStackTop
  0x10080000:
  - __base_RAM2
  - __base_RamLoc40
  0x1008a000:
  - __top_RAM2
  - __top_RamLoc40
  0x1a000000:
  - __vectors_start__
  - __base_Flash
  - _image_start
  - __base_MFlashA512
  - g_pfnVectors
  0x1a000114:
  - __section_table_start
  - __data_section_table
  0x1a000150:
  - __data_section_table_end
  - __bss_section_table
  0x1a000178:
  - __bss_section_table_end
  - __section_table_end
  0x1a000179: data_init
  0x1a0001bd: bss_init
  0x1a0001f5: NMI_Handler
  0x1a0001fd: HardFault_Handler
  0x1a000205: MemManage_Handler
  0x1a00020d: BusFault_Handler
  0x1a000215: UsageFault_Handler
  0x1a00021d: SVC_Handler
  0x1a000225: DebugMon_Handler
  0x1a00022d: PendSV_Handler
  0x1a000235: SysTick_Handler
  0x1a00023d:
  - TIMER2_IRQHandler
  - RIT_IRQHandler
  - I2C0_IRQHandler
  - SDIO_IRQHandler
  - ATIMER_IRQHandler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - GPIO5_IRQHandler
  - CAN1_IRQHandler
  - USB1_IRQHandler
  - I2S0_IRQHandler
  - TIMER3_IRQHandler
  - SGPIO_IRQHandler
  - ADC0_IRQHandler
  - GPIO6_IRQHandler
  - IntDefaultHandler
  - GPIO1_IRQHandler
  - SSP0_IRQHandler
  - ADC1_IRQHandler
  - FLASHEEPROM_IRQHandler
  - RTC_IRQHandler
  - TIMER0_IRQHandler
  - LCD_IRQHandler
  - TIMER1_IRQHandler
  - UART2_IRQHandler
  - GPIO2_IRQHandler
  - I2S1_IRQHandler
  - SSP1_IRQHandler
  - USB0_IRQHandler
  - GPIO3_IRQHandler
  - SCT_IRQHandler
  - WDT_IRQHandler
  - GPIO7_IRQHandler
  - SPIFI_IRQHandler
  - QEI_IRQHandler
  - ETH_IRQHandler
  - CAN0_IRQHandler
  - GINT0_IRQHandler
  - DAC_IRQHandler
  - GPIO0_IRQHandler
  - EVRT_IRQHandler
  - UART3_IRQHandler
  - MCPWM_IRQHandler
  - GINT1_IRQHandler
  - GPIO4_IRQHandler
  0x1a000245: ResetISR
  0x1a00031d: safe_copy_string
  0x1a000375: message2str
  0x1a000859: isup_timer2str
  0x1a0009bd: char2digit
  0x1a000b35: digit2char
  0x1a000bdd: isup_dump_buffer
  0x1a000c35: isup_get_number
  0x1a000ccb: isup_put_generic
  0x1a000d15: isup_put_number
  0x1a000dfd: nature_of_connection_ind_transmit
  0x1a000e65: nature_of_connection_ind_receive
  0x1a000ee5: nature_of_connection_ind_dump
  0x1a000fb5: forward_call_ind_transmit
  0x1a001045: forward_call_ind_receive
  0x1a001061: forward_call_ind_dump
  0x1a001311: calling_party_cat_receive
  0x1a001335: calling_party_cat_transmit
  0x1a001359: calling_party_cat_dump
  0x1a001449: user_service_info_receive
  0x1a001463: user_service_info_transmit
  0x1a001493: transmission_medium_reqs_transmit
  0x1a0014c5: transmission_medium_reqs_receive
  0x1a0014ed: transmission_medium_reqs_dump
  0x1a001575: called_party_num_dump
  0x1a00161d: called_party_num_receive
  0x1a001667: called_party_num_transmit
  0x1a0016bf: backward_call_ind_receive
  0x1a001703: backward_call_ind_transmit
  0x1a001759: backward_call_ind_dump
  0x1a0018b5: opt_backward_call_ind_receive
  0x1a0018d1: opt_backward_call_ind_dump
  0x1a00195d: opt_forward_call_ind_dump
  0x1a001a11: opt_forward_call_ind_transmit
  0x1a001a63: opt_forward_call_ind_receive
  0x1a001a9d: cause_receive
  0x1a001ae5: cause_transmit
  0x1a001b39: cause_dump
  0x1a00209d: range_and_status_dump
  0x1a0020c9: range_and_status_receive
  0x1a002169: range_and_status_transmit
  0x1a00224d: calling_party_num_dump
  0x1a002329: calling_party_num_receive
  0x1a00239b: calling_party_num_transmit
  0x1a002465: connected_num_dump
  0x1a002525: connected_num_receive
  0x1a002597: connected_num_transmit
  0x1a002639: originating_line_information_dump
  0x1a002965: originating_line_information_receive
  0x1a00298b: originating_line_information_transmit
  0x1a0029d3: carrier_identification_dump
  0x1a0029ed: carrier_identification_receive
  0x1a002a07: carrier_identification_transmit
  0x1a002a39: jip_dump
  0x1a002a81: jip_receive
  0x1a002aa9: jip_transmit
  0x1a002ae3: hop_counter_dump
  0x1a002afd: hop_counter_receive
  0x1a002b17: hop_counter_transmit
  0x1a002b37: charge_number_receive
  0x1a002b99: charge_number_dump
  0x1a002c25: charge_number_transmit
  0x1a002c85: continuity_ind_transmit
  0x1a002cb7: continuity_ind_receive
  0x1a002cf1: continuity_ind_dump
  0x1a002d35: circuit_group_supervision_dump
  0x1a002dad: circuit_group_supervision_receive
  0x1a002dd5: circuit_group_supervision_transmit
  0x1a002e01: event_info_dump
  0x1a002ea1: event_info_receive
  0x1a002ec5: event_info_transmit
  0x1a002ee9: redirection_info_dump
  0x1a0030c5: redirection_info_receive
  0x1a003127: redirection_info_transmit
  0x1a003199: generic_name_receive
  0x1a0031f9: generic_name_dump
  0x1a0032b1: generic_name_transmit
  0x1a003335: generic_address_dump
  0x1a003425: generic_address_receive
  0x1a0034a9: generic_address_transmit
  0x1a003539: generic_digits_dump
  0x1a0035c1: generic_digits_receive
  0x1a00360f: generic_digits_transmit
  0x1a0036e5: original_called_num_dump
  0x1a0037a5: original_called_num_receive
  0x1a003817: original_called_num_transmit
  0x1a0038a1: echo_control_info_dump
  0x1a003a49: parameter_compat_info_dump
  0x1a003a65: propagation_delay_cntr_dump
  0x1a003a99: circuit_state_ind_dump
  0x1a003c2d: circuit_state_ind_transmit
  0x1a003c79: tns_dump
  0x1a003cf9: tns_transmit
  0x1a003d13: tns_receive
  0x1a003d2d: generic_notification_ind_dump
  0x1a0040d5: generic_notification_ind_transmit
  0x1a0040ef: generic_notification_ind_receive
  0x1a004109: lspi_transmit
  0x1a00414f: lspi_receive
  0x1a0041b1: lspi_dump
  0x1a004241: call_ref_dump
  0x1a0042f9: call_ref_transmit
  0x1a0043d7: call_ref_receive
  0x1a004481: facility_ind_dump
  0x1a0044ad: facility_ind_receive
  0x1a0044c7: facility_ind_transmit
  0x1a0044e9: redirecting_number_dump
  0x1a0045c5: redirecting_number_receive
  0x1a004637: redirecting_number_transmit
  0x1a0046c1: redirect_counter_dump
  0x1a0046f1: redirect_counter_receive
  0x1a00471b: redirect_counter_transmit
  0x1a004755: inr_ind_dump
  0x1a004815: inr_ind_receive
  0x1a004843: inr_ind_transmit
  0x1a004875: inf_ind_dump
  0x1a00496d: inf_ind_receive
  0x1a0049af: inf_ind_transmit
  0x1a0049df: access_transport_dump
  0x1a0049f9: access_transport_receive
  0x1a004a13: access_transport_transmit
  0x1a004a2d: suspend_resume_ind_dump
  0x1a004a71: suspend_resume_ind_receive
  0x1a004a99: suspend_resume_ind_transmit
  0x1a004ac5: subs_num_dump
  0x1a004b11: subs_num_receive
  0x1a004b47: subs_num_transmit
  0x1a004b81: cug_interlock_code_dump
  0x1a004c29: cug_interlock_code_receive
  0x1a004cd1: cug_interlock_code_transmit
  0x1a004d81: param2str
  0x1a004de1: init_isup_call
  0x1a004e39: __isup_new_call
  0x1a004eb1: isup_find_call
  0x1a004f2d: isup_free_call
  0x1a004fc1: do_parm
  0x1a0051b9: dump_parm
  0x1a005355: isup_send_message
  0x1a0057d9: isup_dump
  0x1a005b95: isup_check_status
  0x1a005bd9: isup_handle_unexpected
  0x1a005c99: isup_receive
  0x1a00796d: isup_event_iam
  0x1a007dc5: isup_rel
  0x1a007edd: isup_inr
  0x1a007f81: isup_inf
  0x1a008009: isup_rsc
  0x1a008099: isup_timer_expiry
  0x1a0086a1: isup_stop_timer
  0x1a008751: isup_stop_all_timers
  0x1a0087a1: isup_start_timer
  0x1a0088e9: isup_free_call_if_clear
  0x1a00894d: isup_free_all_calls
  0x1a008999: isup_clear_callflags
  0x1a008a1d: len_buf
  0x1a008a51: linkstate2str
  0x1a008ae1: lssu_type
  0x1a008af7: flush_bufs
  0x1a008b63: reset_mtp
  0x1a008bb5: mtp2_request_retransmission
  0x1a008bf9: mtp2_queue_su
  0x1a008c59: mtp2_retransmit
  0x1a008cc9: t7_expiry
  0x1a008d0d: mtp2_msu
  0x1a008d7d: mtp2_lssu
  0x1a008da7: mtp2_fisu
  0x1a008dd1: update_txbuf
  0x1a008eb5: fisu_rx
  0x1a008f91: t1_expiry
  0x1a008fad: t2_expiry
  0x1a008fc9: t3_expiry
  0x1a008fe5: t4_expiry
  0x1a009025: to_idle
  0x1a00906d: mtp2_setstate
  0x1a00947d: lssu_rx
  0x1a009651: msu_rx
  0x1a00978d: mtp2_new
  0x1a009885: mtp2_dump
  0x1a009ba1: mtp2_receive
  0x1a009c95: userpart2str
  0x1a009cfd: ss7_ni2str
  0x1a009d55: get_routinglabel
  0x1a009e19: get_userpart
  0x1a009e35: get_ni
  0x1a009e4f: get_priority
  0x1a009e6f: set_routinglabel
  0x1a009f51: set_h0
  0x1a009f81: get_h0
  0x1a009f9d: set_h1
  0x1a009fcb: get_h1
  0x1a009fe5: link_available
  0x1a00a13f: rl_to_link
  0x1a00a207: mtp3_setstate_mtp2link
  0x1a00a25d: net_mng_message2str
  0x1a00a2d1: net_mng_dump
  0x1a00a36d: std_test_send
  0x1a00a4e9: q707_t1_expiry
  0x1a00a569: ss7_linkset_up_event
  0x1a00a58f: linkset_up_expired
  0x1a00a5b9: available_links
  0x1a00a6a5: ss7_check
  0x1a00aaa1: mtp3_stop_all_timers_except_cocb
  0x1a00ab51: mtp3_timer_q707_t2_expiry
  0x1a00ab91: mtp3_move_buffer
  0x1a00ad07: mtp3_transmit_buffer
  0x1a00ad97: mtp3_free_co
  0x1a00adfd: mtp3_cancel_changeover
  0x1a00aeb9: mtp3_check
  0x1a00b03d: mtp3_init
  0x1a00b0e3: mtp3_restart
  0x1a00b199: mtp3_t3_expired
  0x1a00b1fd: mtp3_changeback
  0x1a00b2d1: mtp3_cancel_changeback
  0x1a00b381: mtp3_t1_expired
  0x1a00b3d9: mtp3_timed_changeover
  0x1a00b499: mtp3_changeover
  0x1a00b589: mtp3_prepare_changeover
  0x1a00b601: mtp3_t19_expiry
  0x1a00b641: mtp3_t21_expiry
  0x1a00b691: mtp3_t22_expired
  0x1a00b71d: mtp3_t23_expired
  0x1a00b7a9: pc2int
  0x1a00b7f5: mtp3_t10_expired
  0x1a00b871: mtp3_forced_reroute
  0x1a00b9dd: mtp3_destroy_route
  0x1a00ba81: mtp3_t6_expired
  0x1a00bac5: mtp3_controlled_reroute
  0x1a00bbd9: mtp3_add_set_route
  0x1a00bcbd: netmng_adjpc_sls_to_mtp2
  0x1a00bd3d: net_mng_receive
  0x1a00c8a5: mtp3_t2_expired
  0x1a00c95d: mtp3_t5_expired
  0x1a00c9b9: mtp3_t4_expired
  0x1a00ca95: mtp3_t14_expired
  0x1a00cae5: mtp3_t14_expired_2nd
  0x1a00cb35: mtp3_t13_expired
  0x1a00cb85: mtp3_t13_expired_2nd
  0x1a00cbbd: mtp3_t12_expired
  0x1a00cc0d: mtp3_t12_expired_2nd
  0x1a00cc51: net_mng_send
  0x1a00d41d: mtp3_link_failed
  0x1a00d4f1: std_test_receive
  0x1a00d7e5: mtp3_to_buffer
  0x1a00d83d: mtp3_transmit
  0x1a00d911: mtp3_dump
  0x1a00da61: mtp3_receive
  0x1a00dc25: mtp3_event_link_down
  0x1a00dc4d: mtp3_timer2str
  0x1a00dd3d: mtp3_add_link_adjsps
  0x1a00ddad: mtp3_new_adjsp
  0x1a00de45: mtp3_add_adj_sp
  0x1a00decf: mtp3_destroy_all_routes
  0x1a00df05: ss7_message
  0x1a00df85: ss7_error
  0x1a00e005: ss7_dump_buf
  0x1a00e135: ss7_dump_msg
  0x1a00e1e5: ss7_msg_new
  0x1a00e1f9: ss7_msg_userpart
  0x1a00e20f: ss7_msg_userpart_len
  0x1a00e231: ss7_next_empty_event
  0x1a00e28d: ss7_set_adjpc
  0x1a00e2af: ss7_add_link
  0x1a00e36b: ss7_new
  0x1a00e411: ss7_destroy
  0x1a00e4d1: ss7_pc_to_str
  0x1a00e51d: ss7_schedule_event
  0x1a00e537: ss7_schedule_del
  0x1a00e54d: SystemInit
  0x1a00e571: NVIC_EnableIRQ
  0x1a00e5a1: NVIC_DisableIRQ
  0x1a00e5d5: NVIC_SetPriority
  0x1a00e629: Chip_UART_TXEnable
  0x1a00e641: Chip_UART_SetupFIFOS
  0x1a00e65b: Chip_UART_ConfigData
  0x1a00e675: App_DMA_Init
  0x1a00e69d: App_DMA_DeInit
  0x1a00e6d1: App_DMA_Test
  0x1a00e7ae: wfimark
  0x1a00e821: DMA_IRQHandler
  0x1a00e885: UART0_IRQHandler
  0x1a00e8a5: main
  0x1a00e8ec: exit_main
  0x1a00e8fd: Chip_SCU_PinMuxSet
  0x1a00e92d: Chip_ENET_RMIIEnable
  0x1a00e955: Chip_GPIO_SetPinState
  0x1a00e98b: Chip_GPIO_SetPinDIROutput
  0x1a00e9c7: Chip_UART_TXEnable
  0x1a00e9df: Chip_UART_SendByte
  0x1a00e9fb: Chip_UART_ConfigData
  0x1a00ea15: Chip_UART_ReadLineStatus
  0x1a00ea2b: __sys_write
  0x1a00ea63: Board_UART_Init
  0x1a00ea89: Board_Debug_Init
  0x1a00eab9: Board_UARTPutChar
  0x1a00eaed: Board_LED_Init
  0x1a00eb4d: Board_Init
  0x1a00eb71: Chip_SCU_PinMuxSet
  0x1a00eba1: Chip_SCU_SetPinMuxing
  0x1a00ebed: Chip_CREG_SetFlashAcceleration
  0x1a00ec41: Board_SetupMuxing
  0x1a00ec55: Board_SetupClocking
  0x1a00ecd5: Board_SystemInit
  0x1a00ece5: SystemCoreClockUpdate
  0x1a00ecfd: ABS
  0x1a00ed1d: pll_calc_divs
  0x1a00ee41: pll_get_frac
  0x1a00efb7: Chip_Clock_GetDivRate
  0x1a00eff9: Chip_Clock_FindBaseClock
  0x1a00f085: Chip_Clock_EnableCrystal
  0x1a00f0f5: Chip_Clock_CalcMainPLLValue
  0x1a00f1cd: Chip_Clock_GetMainPLLHz
  0x1a00f289: Chip_Clock_GetDividerSource
  0x1a00f2c9: Chip_Clock_GetDividerDivisor
  0x1a00f2fd: Chip_Clock_GetClockInputHz
  0x1a00f43d: Chip_Clock_GetBaseClocktHz
  0x1a00f461: Chip_Clock_SetBaseClock
  0x1a00f4fd: Chip_Clock_GetBaseClock
  0x1a00f549: Chip_Clock_EnableOpts
  0x1a00f5c5: Chip_Clock_Disable
  0x1a00f625: Chip_Clock_GetRate
  0x1a00f6ad: configDMAMux
  0x1a00f8a9: makeCtrlWord
  0x1a00f9f1: setupChannel
  0x1a00faad: Chip_GPDMA_Init
  0x1a00fb19: Chip_GPDMA_Stop
  0x1a00fb81: Chip_GPDMA_Interrupt
  0x1a00fbed: Chip_GPDMA_InitChannelCfg
  0x1a00fcf1: Chip_GPDMA_IntGetStatus
  0x1a00fdad: Chip_GPDMA_ClearIntPending
  0x1a00fdeb: Chip_GPDMA_ChannelCmd
  0x1a00fe31: Chip_GPDMA_PrepareDescriptor
  0x1a00fef5: Chip_GPDMA_SGTransfer
  0x1a00ffc3: Chip_GPIO_Init
  0x1a00ffd5: Chip_Clock_DisableMainPLL
  0x1a00fff1: Chip_Clock_SetupMainPLL
  0x1a010031: Chip_Clock_MainPLLLocked
  0x1a010055: Chip_SetupCoreClock
  0x1a0101b1: RingBuffer_IsEmpty
  0x1a0101d9: Chip_UART_TXDisable
  0x1a0101f1: Chip_UART_SendByte
  0x1a01020d: Chip_UART_ReadByte
  0x1a010225: Chip_UART_IntDisable
  0x1a010247: Chip_UART_ReadIntIDReg
  0x1a01025d: Chip_UART_SetupFIFOS
  0x1a010277: Chip_UART_ConfigData
  0x1a010291: Chip_UART_EnableDivisorAccess
  0x1a0102af: Chip_UART_DisableDivisorAccess
  0x1a0102cd: Chip_UART_SetDivisorLatches
  0x1a0102f3: Chip_UART_ReadLineStatus
  0x1a010309: Chip_UART_SetAutoBaudReg
  0x1a010329: Chip_UART_GetIndex
  0x1a010395: Chip_UART_ABIntHandler
  0x1a010401: Chip_UART_Init
  0x1a010485: Chip_UART_DeInit
  0x1a0104b5: Chip_UART_SetBaud
  0x1a010521: Chip_UART_RXIntHandlerRB
  0x1a01055d: Chip_UART_TXIntHandlerRB
  0x1a0105b1: Chip_UART_IRQRBHandler
  0x1a0105fd: Chip_UART_SetBaudFDR
  0x1a01077d: RingBuffer_GetCount
  0x1a01079d: RingBuffer_IsFull
  0x1a0107c3: RingBuffer_IsEmpty
  0x1a0107eb: RingBuffer_Insert
  0x1a010847: RingBuffer_Pop
  0x1a0108a3: __main
  0x1a0108b1: memcpy
  0x1a0108b5: memset
  0x1a0108b9: malloc
  0x1a010981: free
  0x1a0109b1: calloc
  0x1a010a01: _Csys_alloc
  0x1a010a21: fp_round
  0x1a010a6d: pr_dec.constprop.0
  0x1a010a91: sprintf
  0x1a010b01: fp_display
  0x1a0114ad: snprintf
  0x1a011525: vsnprintf
  0x1a01158d: fputs
  0x1a0115b9: _initio
  0x1a011631: memcmp
  0x1a011675: __vfprintf
  0x1a0121e5: setvbuf
  0x1a012223: strchr
  0x1a01223b: strlen
  0x1a012289: _sbrk
  0x1a0122c5: _deferredlazyseek
  0x1a012305: __flsbuf
  0x1a01242b: _fdopen
  0x1a012493: _fflush
  0x1a0124e5: _frexpl
  0x1a012541: _ldexpl
  0x1a012589: _Cwritebuf
  0x1a0125f5: fclose
  0x1a01264d: fflush
  0x1a012689: fseek
  0x1a012781: ftell
  0x1a0127c5: remove
  0x1a0127d9: __check_heap_overflow
  0x1a0127f1: _do_fflush
  0x1a012831: __aeabi_uldivmod
  0x1a012835: __bhs_ldivmod1
  0x1a012850: ldiv32
  0x1a012858: ldiv_return
  0x1a01286e: ldiv_sign
  0x1a012880: ldiv64
  0x1a012908: ldiv_res01
  0x1a01291e: ldiv_divzero
  0x1a01292a: udiv6432
  0x1a012932: udiv6432_loop1
  0x1a012946: udiv6432_entry
  0x1a012948: udiv6432_loop
  0x1a0129a5: __aeabi_idiv0
  0x1a0129a9: __aeabi_dmul
  0x1a012aa5: __aeabi_ddiv
  0x1a012bd9: __aeabi_dsub
  0x1a012d8d: __aeabi_dadd
  0x1a012ea5: __aeabi_d2iz
  0x1a012ee7: __bhs_ui2d
  0x1a012f2d: __aeabi_i2d
  0x1a012f3d: __aeabi_dcmpeq
  0x1a012f6d: __aeabi_dcmplt
  0x1a012fc3: __aeabi_dcmple
  0x1a013017: __aeabi_dcmpge
  0x1a013071: __aeabi_memcpy
  0x1a01307b:
  - __aeabi_memcpy4
  - __aeabi_memcpy8
  0x1a01307e: copy4
  0x1a013094: copy1
  0x1a0130a5: __aeabi_lowlevel_memset
  0x1a0130b8: __bhs_memset4
  0x1a0130ba: memset4
  0x1a0130c6: memset1
  0x1a0130ca: memset1a
  0x1a0130d7:
  - __exit
  - __sys_appexit
  0x1a0130d9: __sys_close
  0x1a0130df: __sys_flen
  0x1a0130e5: __sys_istty
  0x1a0130eb: __sys_remove
  0x1a0130f1: __sys_seek
  0x1a0130f7: __sys_tmpnam
  0x1a017fbc: ExtRateIn
  0x1a017fc0: OscRateIn
  0x1a017fc4: gpioLEDBits
  0x1a017fcc: InitClkStates
  0x1a017fd8: pinmuxing
  0x1a01800c: periph_to_base
  0x1a018068: GPDMA_LUTPerBurst
  0x1a018088: GPDMA_LUTPerWid
  0x1a0180a8: InitClkStates
  0x1a0180e4: UART_PClock
  0x1a0180ec: UART_BClock
  0x1a0180f4: __num_Ciob_streams
  0x1a01817c:
  - __exidx_end
  - _etext
  - __exidx_start
  0x1a019078: _image_end
  0x1a080000:
  - __top_MFlashA512
  - __top_Flash
  0x1b000000:
  - __base_Flash2
  - __base_MFlashB512
  0x1b080000:
  - __top_Flash2
  - __top_MFlashB512
  0x20000000:
  - __base_RamAHB32
  - __base_RAM3
  0x20008000:
  - __top_RamAHB32
  - __base_RamAHB16
  - __base_RAM4
  - __top_RAM3
  0x2000c000:
  - __base_RamAHB_ETB16
  - __top_RAM4
  - __base_RAM5
  - __top_RamAHB16
  0x20010000:
  - __top_RamAHB_ETB16
  - __top_RAM5
