interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: uart2echo_LP_CC1311P3_nortos_gcc.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x68000
symbols:
  0x0:
  - startup_cc13x1_cc26x1_gcc.c
  - resetVectors
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - main_nortos.c
  - uart2echo.c
  - ti_drivers_config.c
  - GPIO.c
  - GPIOCC26XX.c
  - PowerCC26X2.c
  - PowerCC26X2_calibrateRCOSC.c
  - UART2.c
  - UART2CC26X2.c
  - GPIOCC26X2.c
  - PowerCC26X2_calibrateRCOSC_helpers.c
  - PowerCC26X2_helpers.c
  - List.c
  - RingBuf.c
  - UDMACC26XX.c
  - NoRTOS.c
  - SemaphoreP_nortos.c
  - ClockPTimer_nortos.c
  - QueueP_nortos.c
  - HwiPCC26XX_nortos.c
  - PowerCC26X2_nortos.c
  - TimerPCC26XX_nortos.c
  - SwiP_nortos.c
  - cpu.c
  - interrupt.c
  - osc.c
  - prcm.c
  - setup.c
  - sys_ctrl.c
  - aux_sysif.c
  - chipinfo.c
  - memcpy-stub.c
  - memset.c
  - ti_devices_config.c
  - UDMACC26XX_uart0TxAltControlTableEntry_is_placed
  - UDMACC26XX_dmaSpi0RxControlTableEntry_is_placed
  - _resetVecs_base_address
  - UDMACC26XX_dmaUart0RxControlTableEntry_is_placed
  - UDMACC26XX_dmaGPT0APriControlTableEntry_is_placed
  - UDMACC26XX_uart0RxControlTableEntry_is_placed
  - UDMACC26XX_dmaADCPriControlTableEntry_is_placed
  - UDMACC26XX_dmaADCAltControlTableEntry_is_placed
  - UDMACC26XX_uart0TxControlTableEntry_is_placed
  - UDMACC26XX_dmaSpi0RxAltControlTableEntry_is_placed
  - UDMACC26XX_dmaSpi0TxControlTableEntry_is_placed
  - UDMACC26XX_dmaUart0TxControlTableEntry_is_placed
  - UDMACC26XX_dmaSpi0TxAltControlTableEntry_is_placed
  - UDMACC26XX_uart0RxAltControlTableEntry_is_placed
  - UDMACC26XX_dmaGPT0AAltControlTableEntry_is_placed
  0x41: __aeabi_uldivmod
  0x71: __udivmoddi4
  0x331:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x335: main
  0x349: pwcheck_success
  0x359: pwcheck_passed_1
  0x369: pwcheck_passed_2
  0x379: pwcheck_passed_3
  0x389: pwcheck_passed_4
  0x399: pwcheck_passed_5
  0x3a9: pwcheck_passed_6
  0x3b9: pwcheck_passed_7
  0x3c9: pwcheck_passed_8
  0x3d9: check_password
  0x400: STACKSIZE
  0x441: mainThread
  0x4e5: Board_shutDownExtFlash
  0x5a5: Board_initHook
  0x5a9: Board_init
  0x5bd: GPIO_resetConfig
  0x5f9: GPIO_disableInt
  0x611: GPIO_setConfig
  0x691: GPIO_setConfigAndMux
  0x719: GPIO_write
  0x72d: emptyClockFunc
  0x731: nopResourceHandler
  0x735: configureRFCoreClocks
  0x739: switchToTCXO
  0x7b9: configureXOSCHF
  0x8e5: oscillatorISR
  0xa11: Power_disablePolicy
  0xa25: Power_enablePolicy
  0xa35: Power_getConstraintMask
  0xa41: Power_getTransitionLatency
  0xa5d: Power_idleFunc
  0xa75: Power_init
  0xbdd: Power_registerNotify
  0xc01: Power_releaseConstraint
  0xc35: Power_releaseDependency
  0xcf5: Power_setConstraint
  0xd25: Power_setDependency
  0xdf1: Power_sleep
  0xfb9: PowerCC26XX_calibrate
  0xfd1: PowerCC26X2_initiateCalibration
  0x1045: PowerCC26X2_auxISR
  0x1331: PowerCC26X2_calibrate
  0x1471: PowerCC26X2_RCOSC_clockFunc
  0x14bd: UART2_Params_init
  0x14d9: UART2_rxEnable
  0x151d: UART2_readTimeout
  0x16e1: UART2_readFull
  0x1731: UART2_read
  0x1755: UART2_writeTimeoutBlocking
  0x18c9: UART2_writeTimeoutNonblocking
  0x19ed: UART2_writeTimeout
  0x1a05: UART2_write
  0x1a19: UART2CC26X2_eventCallback
  0x1a1d: UART2CC26X2_postNotifyFxn
  0x1b55: UART2_open
  0x1e51: UART2Support_disableTx
  0x1e5d: UART2Support_dmaStartTx
  0x1f41: UART2Support_dmaStopRx
  0x1fb5: UART2Support_dmaStartRx
  0x2000: HEAPSIZE
  0x20b9: UART2Support_dmaStopTx
  0x2145: UART2CC26X2_hwiIntFxn
  0x2401: UART2Support_enableInts
  0x242d: UART2Support_enableRx
  0x2439: UART2Support_enableTx
  0x2445: UART2Support_powerSetConstraint
  0x246d: UART2Support_sendData
  0x24a9: UART2Support_txDone
  0x24b9: GPIO_hwiIntFxn
  0x2505: GPIO_init
  0x263d: PowerCC26X2_updateSubSecInc
  0x26c1: PowerCC26X2_readCtrim
  0x26d1: PowerCC26X2_readCtrimFract
  0x26e1: PowerCC26X2_readRtrim
  0x26f1: PowerCC26X2_writeCtrim
  0x2719: PowerCC26X2_writeCtrimFract
  0x2741: PowerCC26X2_writeCtrimFractEn
  0x2769: PowerCC26X2_writeRtrim
  0x2791: PowerCC26X2_setTdcClkSrc24M
  0x27cd: PowerCC26X2_setAclkRefSrc
  0x2811: PowerCC26X2_oscCtlClearXtal
  0x2821: PowerCC26X2_prcmEnableCacheRetention
  0x2831: PowerCC26X2_oschfSwitchToRcosc
  0x2835: PowerCC26X2_oscClockSourceGet
  0x2841: PowerCC26X2_oscDisableQualifiers
  0x287d: PowerCC26X2_oschfTrySwitchToXosc
  0x2885: PowerCC26X2_enableTCXOQual
  0x28a5: PowerCC26X2_disableTCXOQual
  0x28c5: PowerCC26X2_turnOnXosc
  0x28c9: PowerCC26X2_switchToTCXO
  0x28d9: PowerCC26X2_sysCtrlStandby
  0x28e5: PowerCC26X2_sysCtrlIdle
  0x28e9: PowerCC26X2_setPeriphDeepSleepEnable
  0x28f5: PowerCC26X2_sysCtrlGetResetSource
  0x2901: PowerCC26X2_setSubSecIncToXoscLf
  0x2931: PowerCC26X2_sysCtrlUpdateVoltageRegulator
  0x293d: List_put
  0x2969: RingBuf_construct
  0x297d: RingBuf_getConsume
  0x29ad: RingBuf_getCount
  0x29b1: RingBuf_getPointer
  0x29d9: RingBuf_put
  0x2a21: RingBuf_putAdvance
  0x2a5d: RingBuf_putPointer
  0x2a91: UDMACC26XX_hwiIntFxn
  0x2a9d: UDMACC26XX_open
  0x2b09: NoRTOS_start
  0x2b0d: clkFxn
  0x2b11: SemaphoreP_constructBinary
  0x2b4d: SemaphoreP_pend
  0x2c49: SemaphoreP_post
  0x2c8d: ClockP_doTick
  0x2c99: ClockP_startup.part.0
  0x2d1d: ClockP_workFuncDynamic
  0x2e6d: ClockP_Params_init
  0x2e7d: ClockP_startup
  0x2e8d: ClockP_getTicksUntilInterrupt
  0x2ebd: ClockP_add
  0x2ed9: ClockP_destruct
  0x2ef5: ClockP_start
  0x2f8d: ClockP_construct
  0x2fe5: ClockP_stop
  0x2fed: ClockP_setTimeout
  0x2ff1: ClockP_isActive
  0x2ff5: ClockP_getCpuFreq
  0x3005: ClockP_getSystemTickPeriod
  0x3011: QueueP_init
  0x3019: QueueP_empty
  0x3025: QueueP_get
  0x3041: QueueP_head
  0x3045: QueueP_next
  0x3049: QueueP_put
  0x3069: QueueP_remove
  0x3079: HwiP_dispatch
  0x3095: HwiP_enable
  0x3099: HwiP_disable
  0x30a9: HwiP_restore
  0x30b1: HwiP_interruptsEnabled
  0x30c1: HwiP_construct
  0x3151: HwiP_Params_init
  0x3165: HwiP_post
  0x3171: HwiP_inISR
  0x3185: PowerCC26XX_standbyPolicy
  0x3275: PowerCC26XX_schedulerDisable
  0x3285: PowerCC26XX_schedulerRestore
  0x3291: TimerP_dynamicStub
  0x32ad: TimerP_Params_init
  0x32bd: TimerP_construct
  0x33c1: TimerP_getMaxTicks
  0x33e9: TimerP_setNextTick
  0x3439: TimerP_getCurrentTick
  0x346d: resetISR
  0x347d: nmiISR
  0x3481: faultISR
  0x3485: busFaultHandler
  0x3489: defaultHandler
  0x348d: localProgramStart
  0x3505: _fini
  0x3509: SwiP_Params_init
  0x3519: SwiP_construct
  0x361d: SwiP_disable
  0x3639: SwiP_dispatch
  0x370d: SwiP_handleHwi
  0x3725: SwiP_post
  0x3795: SwiP_restore
  0x37dd: NOROM_CPUcpsid
  0x37e5: NOROM_CPUprimask
  0x37ed: NOROM_CPUcpsie
  0x37f4: CPUdel68
  0x37f5: NOROM_CPUdelay
  0x37fd: NOROM_IntRegister
  0x3835: NOROM_OSCHF_TurnOnXosc
  0x3859: NOROM_OSCHF_AttemptToSwitchToXosc
  0x38f1: NOROM_OSCHF_SwitchToRcOscTurnOffXosc
  0x3961: NOROM_OSC_HPOSCRelativeFrequencyOffsetGet
  0x39a1: NOROM_PRCMPowerDomainsAllOff
  0x3a2d: NOROM_PRCMPowerDomainsAllOn
  0x3a81: TrimAfterColdResetWakeupFromShutDown
  0x3b91: NOROM_SetupTrimDevice
  0x3c75: NOROM_SysCtrlIdle
  0x3cad: NOROM_SysCtrlStandby
  0x3dbd: NOROM_AUXSYSIFOpModeChange
  0x3dfd: NOROM_ThisLibraryIsFor_CC13x1_CC26x1_HaltIfViolated
  0x3e15: memcpy
  0x3e31: memset
  0x3e40:
  - __init_array_end
  - __init_array_start
  0x3e58: GPIO_config
  0x3e68: GPIO_pinLowerBound
  0x3e69: GPIO_pinUpperBound
  0x3e6c: PowerCC26X2_config
  0x3e80: UART2_config
  0x3e88: UART2_count
  0x3e8c: UDMACC26XX_config
  0x3e94: uart2CC26X2HWAttrs
  0x3eec: udmaCC26XXHWAttrs
  0x3ef4: resourceDB
  0x3f40: UART2_defaultParams
  0x3f64: dataLength
  0x3f68: parityType
  0x3f70: rxFifoThreshold
  0x3f78: stopBits
  0x3f7c: txFifoThreshold
  0x3f84: SwiP_defaultParams
  0x3f94: g_OpMode_to_order
  0x3f98: g_Order_to_OpMode
  0x3f9c: __data_load__
  0x41ac: __exidx_start
  0x41b4: __exidx_end
  0x57fa8: __ccfg
  0x20000000: g_pfnRAMVectors
  0x20000400: UDMACC26XX_CONFIG_BASE
  0x20000410:
  - dmaUart0RxControlTableEntry
  - DMA_UART0_RX_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000420:
  - dmaUart0TxControlTableEntry
  - DMA_UART0_TX_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000430:
  - __data_start__
  - gpioPinConfigs
  - DMA_SPI0_RX_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000440: DMA_SPI0_TX_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000470: DMA_ADC_PRI_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000490: DMA_GPT0A_PRI_CONTROL_TABLE_ENTRY_ADDRESS
  0x200004ac: PowerCC26X2_module
  0x20000610: DMA_UART0_RX_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000620:
  - PowerCC26X2_rtcSubSecInc
  - DMA_UART0_TX_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  0x20000624: SemaphoreP_defaultParams
  0x2000062c: ClockP_tickPeriod
  0x20000630:
  - DMA_SPI0_RX_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  - HwiP_swiPIntNum
  0x20000634: TimerP_defaultParams
  0x20000640:
  - input
  - DMA_SPI0_TX_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  - __bss_start__
  - dma_buf
  - __data_end__
  0x20000648: num_correct
  0x2000064c: uart2RxRingBuffer0
  0x2000066c: uart2TxRingBuffer0
  0x20000670: DMA_ADC_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  0x2000068c: gpioHwi
  0x20000690: DMA_GPT0A_ALT_CONTROL_TABLE_ENTRY_ADDRESS
  0x200006a8: initCalled
  0x200006a9: SemaphoreP_initialized
  0x200006aa: doEnablePolicy
  0x200006ab: pendInProgress
  0x200006ac: ClockP_defaultParams
  0x200006b8: ClockP_initialized
  0x200006c0: ClockP_module
  0x20000768: HwiP_dispatchTable
  0x20000840: PowerCC26X2_swiKey
  0x20000844: TimerP_handle
  0x20000848: TimerP_hwiStruct
  0x20000864: TimerP_initialized
  0x20000868: SwiP_currentTrigger
  0x2000086c: SwiP_hwiStruct
  0x20000888: SwiP_initialized
  0x2000088c: SwiP_lockState
  0x20000890: SwiP_readyList
  0x200008b0: SwiP_readyMask
  0x200008b4: SwiP_schedulerRunning
  0x200008b8: _hposcCoeffs
  0x200008c8: oscHfGlobals
  0x200008dc: uart2CC26X2Objects
  0x20000a4c: gpioCallbackFunctions
  0x20000ac8: udmaCC26XXObject
  0x20000ae8: gpioUserArgs
  0x20000b64:
  - end
  - __bss_end__
  - __end
  - __heap_start__
  - _end
  0x20002b64:
  - __HeapLimit
  - __heap_end__
  0x20002b68:
  - __stack
  - _stack
  0x20002f68:
  - __stack_end
  - _stack_end
