interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: L1521_ChibiOS_SPI.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12664
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __ram4_start__
  - __flash7_free__
  - __ram5_clear__
  - __ram1_free__
  - __ram6_start__
  - __ram5_end__
  - __ram5_noinit__
  - __flash1_free__
  - __ram5_size__
  - __flash7_size__
  - __flash4_free__
  - __ram1_size__
  - __flash3_free__
  - __ram1_clear__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __ram4_size__
  - __ram1_end__
  - __ram4_end__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __ram4_clear__
  - __ram5_free__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __ram2_noinit__
  - __flash3_start__
  - __ram6_noinit__
  - __ram4_init__
  - __ram7_clear__
  - __ram7_size__
  - __ram4_noinit__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram2_clear__
  - __ram3_end__
  - __ram2_size__
  - __ram1_start__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __ram1_noinit__
  - __flash2_size__
  - __flash4_end__
  - __ram2_init__
  - __ram2_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram2_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __ram5_init__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __ram1_init__
  - __ram5_start__
  - __flash6_size__
  - __ram2_free__
  - __ram4_free__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x4000: __ram0_size__
  0x4c79: crt1.c.acf8d079
  0x4ff7: hal.c.8cd40742
  0x6092: hal_st.c.06c8685b
  0x735a: hal_buffers.c.dfd5e94a
  0x943e: hal_pal.c.5f80244c
  0xa697: hal_spi.c.bab27ac0
  0xbc14: nvic.c.f1dd4b50
  0xd01b: stm32_isr.c.91489da2
  0xe36b: hal_lld.c.c9a18343
  0xf5b8: stm32_dma.c.74578dee
  0x10a79: hal_pal_lld.c.c0d8993e
  0x11ddc: hal_spi_lld.c.869bc410
  0x1326b: hal_st_lld.c.e620cc64
  0x1460f: board.c.528b3dc7
  0x158a3: chsys.c.828fd42c
  0x170c1: chdebug.c.718612b5
  0x17d57: chtrace.c.0ca5b67c
  0x18e06: chvt.c.2690ea72
  0x19d05: chschd.c.c46d5609
  0x1ac81: chthreads.c.d2154bad
  0x1c2ab: chtm.c.6e37493a
  0x1d14f: chregistry.c.5a41d942
  0x1e74b: chmtx.c.f3339ec2
  0x1f6c2: chdynamic.c.c1ae3c67
  0x20000: __flash0_size__
  0x20590: chmemcore.c.f979ee21
  0x212dd: chmemheaps.c.9adf0cd5
  0x221c8: chmempools.c.c5a64656
  0x23168: chfactory.c.e64b3cdf
  0x25058: chcore_v7m.c.b795117e
  0x25f42: main.c.9c80d322
  0x8000000:
  - _vectors
  - __flash0_start__
  0x8000140:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x8000141: _crt0_entry
  0x8000174: msloop
  0x8000182: psloop
  0x8000192: dloop
  0x80001a6: bloop
  0x80001bc: initloop
  0x80001c8: endinitloop
  0x80001d0: finiloop
  0x80001dc: endfiniloop
  0x8000219: Reset_Handler
  0x800021b:
  - VectorE8
  - VectorAC
  - DebugMon_Handler
  - Vector11C
  - HardFault_Handler
  - Vector8C
  - SysTick_Handler
  - VectorDC
  - PendSV_Handler
  - NMI_Handler
  - Vector110
  - Vector120
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - VectorBC
  - Vector124
  - Vector118
  - VectorCC
  - Vector54
  - Vector98
  - VectorD8
  - Vector138
  - Vector24
  - VectorD0
  - VectorE4
  - VectorC0
  - Vector130
  - Vector134
  - VectorF0
  - Vector12C
  - Vector13C
  - Vector100
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector90
  - Vector114
  - Vector1C
  - Vector48
  - VectorD4
  - Vector4C
  - Vector88
  - Vector104
  - Vector10C
  - BusFault_Handler
  - Vector50
  - Vector44
  - Vector28
  - VectorB8
  - VectorFC
  - Vector34
  - Vector128
  - VectorA4
  - Vector20
  0x800021e: .stay
  0x800021f: _unhandled_exception
  0x8000221: _port_switch
  0x8000231: _port_thread_start
  0x8000245: _port_switch_from_isr
  0x8000250: _port_exit_from_isr
  0x8000261: _pal_lld_setgroupmode.constprop.0
  0x8000341: chTMStartMeasurementX.constprop.0
  0x8000351: _port_irq_epilogue
  0x80003b1: chTMStopMeasurementX
  0x8000401: trace_next
  0x8000441: _trace_switch.part.0
  0x8000461: _trace_isr_leave
  0x8000491: _trace_isr_enter
  0x80004c1: chSysHalt
  0x80004f1: spi_lld_serve_tx_interrupt
  0x8000511: chDbgCheckClassS
  0x8000531: chDbgCheckClassI
  0x8000551: dmaStreamAllocI.constprop.0
  0x8000621: chCoreAllocAlignedWithOffsetI
  0x8000671: chCoreAllocAlignedI
  0x8000681: chSchReadyI
  0x80006d1: _dbg_check_leave_isr
  0x8000701: _dbg_check_enter_isr
  0x8000731: _dbg_check_unlock_from_isr
  0x8000761: _dbg_check_lock_from_isr
  0x8000791: wakeup
  0x80007f1: _idle_thread
  0x8000801: spi_lld_serve_rx_interrupt
  0x80008d1: dmaServeInterrupt
  0x8000911: stSetAlarm
  0x8000931: spi_lld_start.constprop.0
  0x8000a01: chSchWakeupS.constprop.0
  0x8000a81: chSchGoSleepS
  0x8000ae1: SVC_Handler
  0x8000b01:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8000b91: _dbg_check_unlock
  0x8000bb1: chSysUnlock.lto_priv.1
  0x8000be1: _dbg_check_lock
  0x8000c01: spiSelect.constprop.0
  0x8000c61: spiUnselect.constprop.0
  0x8000cc1: spiExchange.constprop.0
  0x8000d81: chCoreAllocAlignedWithOffset
  0x8000dd1: chMtxUnlock
  0x8000ea1: chMtxLock
  0x8000fc1: spi_thread_1
  0x8001081: spi_thread_2
  0x8001141: chRegFindThreadByWorkingArea
  0x8001361: chThdCreateStatic.constprop.0
  0x8001411: main
  0x8001a21: chThdExit
  0x8001a81: __early_init
  0x8001c81: VectorB0
  0x8001da1: Vector84
  0x8001dd1: Vector80
  0x8001e01: Vector7C
  0x8001e31: Vector78
  0x8001e61: Vector74
  0x8001e91: Vector70
  0x8001ec1: Vector6C
  0x8001ef1: VectorE0
  0x8001f81: Vector9C
  0x8002001: Vector68
  0x8002051: Vector64
  0x80020a1: Vector60
  0x80020f1: Vector5C
  0x8002141: Vector58
  0x8002191: __init_ram_areas
  0x8002201: __default_exit
  0x8002211: __late_init
  0x8002221: __core_init
  0x8002224:
  - __text_end
  - __rodata_base__
  0x80022b8: __func__.4292.lto_priv.0
  0x80022c4: __func__.4292.lto_priv.1
  0x80022d0: __func__.5560.lto_priv.0
  0x80022dc: __func__.5560.lto_priv.1
  0x80022e8: __func__.5560.lto_priv.2
  0x80022f4: __func__.5560.lto_priv.3
  0x8002300: __func__.5560.lto_priv.4
  0x800230c: __func__.5646
  0x8002318: __func__.5962
  0x8002324: __func__.6550
  0x8002330: __func__.6553.lto_priv.0
  0x800233c: __func__.6553.lto_priv.1
  0x8002348: __func__.6557.lto_priv.0
  0x800235c: __func__.6557.lto_priv.1
  0x800237c: __func__.6572.lto_priv.0
  0x8002388: __func__.6572.lto_priv.1
  0x8002394: __func__.6575
  0x80023a0: __func__.6576
  0x80023ac: __func__.6581
  0x80023c0: __func__.6586
  0x80023d0: __func__.6593
  0x80023e0: __func__.6608
  0x80023ec: __func__.6647
  0x8002404: __func__.6653
  0x8002414: __func__.6953
  0x8002424: __func__.7243
  0x8002430: __func__.7244
  0x800243c: __func__.7246
  0x800244c: __func__.7249
  0x8002458: __func__.7250
  0x8002464: __func__.7252
  0x8002470: __func__.7253
  0x800247c: __func__.7254
  0x8002488: __func__.7256
  0x8002494: __func__.7258.lto_priv.0
  0x80024a0: __func__.7258.lto_priv.1
  0x80024b0: __func__.7259
  0x80024bc: __func__.7260
  0x80024c8: __func__.7262
  0x80024d4: __func__.7264.lto_priv.0
  0x80024e0: __func__.7264.lto_priv.1
  0x80024ec: __func__.7268
  0x80024f8: __func__.7269
  0x8002504: __func__.7272
  0x8002510: __func__.7274
  0x800251c: __func__.7276
  0x8002528: __func__.7306
  0x8002534: _stm32_dma_streams
  0x80025a4: ch_debug
  0x80025bc: hs_spicfg
  0x80025d0: ls_spicfg
  0x80025e4: ram_areas
  0x8002664:
  - __exidx_end
  - __ram3_init_text__
  - __rodata_end__
  - __exidx_start
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  - _textdata_start
  0x8020000: __flash0_end__
  0x10000000: ICSR_PENDSVSET
  0x20000000:
  - __ram0_start__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - SPID1
  - __main_thread_stack_end__
  - _bss_start
  - _data_start
  - _data_end
  - __process_stack_end__
  0x20000830: SPID2
  0x20000860: _pal_events
  0x200008e0: auxRead
  0x200008e4: ch
  0x2000116c: ch_factory
  0x200011b8: ch_idle_thread_wa
  0x20001290: ch_memcore
  0x20001298: default_heap
  0x200012b4: dma
  0x200012f4: i
  0x200012f8: rxbuf
  0x200014f8: spi_thread_1_wa
  0x200016c0: spi_thread_2_wa
  0x20001888: txbuf
  0x20001a88:
  - __ram0_init__
  - __ram0_free__
  - __heap_base__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x20004000:
  - __heap_end__
  - __ram0_end__
  0xe000ed04: SCB_ICSR
