interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x1fff0000
    permissions: rw-
    size: 0x134
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: uart_example.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x14970
symbols:
  0x0:
  - startup_MK64F12.S.obj
  - crt0.o
  - libc_a-strlen.o
  - crtstuff.c
  - uart_edma_transfer.c
  - pin_mux.c
  - clock_config.c
  - fsl_debug_console.c
  - fsl_assert.c
  - fsl_edma.c
  - fsl_dmamux.c
  - fsl_uart_edma.c
  - fsl_uart.c
  - fsl_clock.c
  - system_MK64F12.c
  - exit.c
  - init.c
  - memcpy-stub.c
  - memset.c
  - _exit.c
  - crti.o
  - crtn.o
  - findfp.c
  - __isr_vector
  0x400:
  - STACK_SIZE
  - HEAP_SIZE
  0x411: _stack_init
  0x419:
  - _mainCRTStartup
  - _start
  0x48d: Reset_Handler
  0x4ed:
  - DebugMon_Handler
  - SPI1_DriverIRQHandler
  - DMA_Error_DriverIRQHandler
  - SDHC_DriverIRQHandler
  - PIT0_IRQHandler
  - CMP2_IRQHandler
  - LLWU_IRQHandler
  - I2S0_Tx_DriverIRQHandler
  - ENET_1588_Timer_DriverIRQHandler
  - I2C2_DriverIRQHandler
  - SWI_IRQHandler
  - ADC0_IRQHandler
  - UsageFault_Handler
  - CMT_IRQHandler
  - DefaultISR
  - UART5_ERR_DriverIRQHandler
  - CMP1_IRQHandler
  - Reserved71_IRQHandler
  - PORTD_IRQHandler
  - PORTB_IRQHandler
  - UART2_ERR_DriverIRQHandler
  - SPI2_DriverIRQHandler
  - ADC1_IRQHandler
  - PIT2_IRQHandler
  - RTC_IRQHandler
  - UART3_ERR_DriverIRQHandler
  - PDB0_IRQHandler
  - FTM1_IRQHandler
  - PIT3_IRQHandler
  - RTC_Seconds_IRQHandler
  - MCG_IRQHandler
  - FTFE_IRQHandler
  - UART0_ERR_DriverIRQHandler
  - Read_Collision_IRQHandler
  - USBDCD_IRQHandler
  - I2S0_Rx_DriverIRQHandler
  - USB0_IRQHandler
  - UART4_ERR_DriverIRQHandler
  - WDOG_EWM_IRQHandler
  - MemManage_Handler
  - UART0_LON_DriverIRQHandler
  - RNG_IRQHandler
  - I2C1_DriverIRQHandler
  - ENET_Receive_DriverIRQHandler
  - DAC0_IRQHandler
  - ENET_Error_DriverIRQHandler
  - SPI0_DriverIRQHandler
  - PIT1_IRQHandler
  - LVD_LVW_IRQHandler
  - FTM0_IRQHandler
  - PORTA_IRQHandler
  - DAC1_IRQHandler
  - MCM_IRQHandler
  - CAN0_DriverIRQHandler
  - FTM3_IRQHandler
  - PORTE_IRQHandler
  - FTM2_IRQHandler
  - LPTMR0_IRQHandler
  - BusFault_Handler
  - UART1_ERR_DriverIRQHandler
  - ENET_Transmit_DriverIRQHandler
  - I2C0_DriverIRQHandler
  - CMP0_IRQHandler
  - PORTC_IRQHandler
  0x4f1: NMI_Handler
  0x4f5: HardFault_Handler
  0x4f9: SVC_Handler
  0x4fd: PendSV_Handler
  0x501: SysTick_Handler
  0x505: DMA0_IRQHandler
  0x509: DMA1_IRQHandler
  0x50d: DMA2_IRQHandler
  0x511: DMA3_IRQHandler
  0x515: DMA4_IRQHandler
  0x519: DMA5_IRQHandler
  0x51d: DMA6_IRQHandler
  0x521: DMA7_IRQHandler
  0x525: DMA8_IRQHandler
  0x529: DMA9_IRQHandler
  0x52d: DMA10_IRQHandler
  0x531: DMA11_IRQHandler
  0x535: DMA12_IRQHandler
  0x539: DMA13_IRQHandler
  0x53d: DMA14_IRQHandler
  0x541: DMA15_IRQHandler
  0x545: DMA_Error_IRQHandler
  0x549: I2C0_IRQHandler
  0x54d: I2C1_IRQHandler
  0x551: SPI0_IRQHandler
  0x555: SPI1_IRQHandler
  0x559: I2S0_Tx_IRQHandler
  0x55d: I2S0_Rx_IRQHandler
  0x561: UART0_LON_IRQHandler
  0x565: UART0_RX_TX_IRQHandler
  0x569: UART0_ERR_IRQHandler
  0x56d: UART1_RX_TX_IRQHandler
  0x571: UART1_ERR_IRQHandler
  0x575: UART2_RX_TX_IRQHandler
  0x579: UART2_ERR_IRQHandler
  0x57d: UART3_RX_TX_IRQHandler
  0x581: UART3_ERR_IRQHandler
  0x585: SPI2_IRQHandler
  0x589: UART4_RX_TX_IRQHandler
  0x58d: UART4_ERR_IRQHandler
  0x591: UART5_RX_TX_IRQHandler
  0x595: UART5_ERR_IRQHandler
  0x599: I2C2_IRQHandler
  0x59d: CAN0_ORed_Message_buffer_IRQHandler
  0x5a1: CAN0_Bus_Off_IRQHandler
  0x5a5: CAN0_Error_IRQHandler
  0x5a9: CAN0_Tx_Warning_IRQHandler
  0x5ad: CAN0_Rx_Warning_IRQHandler
  0x5b1: CAN0_Wake_Up_IRQHandler
  0x5b5: SDHC_IRQHandler
  0x5b9: ENET_1588_Timer_IRQHandler
  0x5bd: ENET_Transmit_IRQHandler
  0x5c1: ENET_Receive_IRQHandler
  0x5c5: ENET_Error_IRQHandler
  0x68d: strlen
  0x69d: deregister_tm_clones
  0x6b9: register_tm_clones
  0x6dd: __do_global_dtors_aux
  0x705: frame_dummy
  0x729: DMAMUX_EnableChannel
  0x775: DMAMUX_SetSource
  0x7d1: pwcheck_success
  0x7ed: pwcheck_passed_1
  0x809: pwcheck_passed_2
  0x825: pwcheck_passed_3
  0x841: pwcheck_passed_4
  0x85d: pwcheck_passed_5
  0x879: pwcheck_passed_6
  0x895: pwcheck_passed_7
  0x8b1: pwcheck_passed_8
  0x8cd: check_password
  0x969: UART_UserCallback
  0x98d: main
  0xa99: CLOCK_EnableClock
  0xacd: PORT_SetPinMux
  0xb07: BOARD_InitBootPins
  0xb15: BOARD_InitPins
  0xb59: CLOCK_SetSimSafeDivs
  0xb79: CLOCK_SetXtal0Freq
  0xb99: CLOCK_CONFIG_SetFllExtRefDiv
  0xbd5: BOARD_InitBootClocks
  0xbe1: BOARD_BootClockRUN
  0xc41: DbgConsole_Printf
  0xc6d: DbgConsole_Vprintf
  0xca9: DbgConsole_Putchar
  0xcd9: DbgConsole_PrintfPaddingCharacter
  0xd19: DbgConsole_ConvertRadixNumToString
  0xddd: DbgConsole_PrintfFormattedData
  0x11bd: fsl_assert_hook
  0x11d9: __assert_func
  0x1209: __NVIC_EnableIRQ
  0x1245: CLOCK_EnableClock
  0x1279: EnableIRQ
  0x12ab: DisableGlobalIRQ
  0x12cd: EnableGlobalIRQ
  0x12ed: EDMA_GetInstance
  0x1341: EDMA_InstallTCD
  0x14a5: EDMA_Init
  0x1549: EDMA_GetDefaultConfig
  0x1599: EDMA_SetTransferConfig
  0x1611: EDMA_TcdReset
  0x16a1: EDMA_TcdSetTransferConfig
  0x1801: EDMA_GetInstanceOffset
  0x1859: EDMA_CreateHandle
  0x1951: EDMA_SetCallback
  0x1991: EDMA_TransferWidthMapping
  0x1a71: EDMA_PrepareTransferConfig
  0x1bed: EDMA_PrepareTransfer
  0x1ca9: EDMA_SubmitTransfer
  0x1fc5: EDMA_StartTransfer
  0x2085: EDMA_AbortTransfer
  0x211d: EDMA_HandleIRQ
  0x22ed: DMA0_DriverIRQHandler
  0x2309: DMA1_DriverIRQHandler
  0x2325: DMA2_DriverIRQHandler
  0x2341: DMA3_DriverIRQHandler
  0x235d: DMA4_DriverIRQHandler
  0x2379: DMA5_DriverIRQHandler
  0x2395: DMA6_DriverIRQHandler
  0x23b1: DMA7_DriverIRQHandler
  0x23cd: DMA8_DriverIRQHandler
  0x23e9: DMA9_DriverIRQHandler
  0x2405: DMA10_DriverIRQHandler
  0x2421: DMA11_DriverIRQHandler
  0x243d: DMA12_DriverIRQHandler
  0x2459: DMA13_DriverIRQHandler
  0x2475: DMA14_DriverIRQHandler
  0x2491: DMA15_DriverIRQHandler
  0x24ad: CLOCK_EnableClock
  0x24e1: DMAMUX_GetInstance
  0x2535: DMAMUX_Init
  0x2559: __NVIC_EnableIRQ
  0x2595: EnableIRQ
  0x25c7: UART_GetDataRegisterAddress
  0x25df: UART_EnableTxDMA
  0x263f: UART_EnableRxDMA
  0x26a1: UART_SendEDMACallback
  0x2701: UART_ReceiveEDMACallback
  0x2775: UART_TransferCreateHandleEDMA
  0x287d: UART_SendEDMA
  0x2989: UART_ReceiveEDMA
  0x2aa1: UART_TransferAbortReceiveEDMA
  0x2b05: UART_TransferEdmaHandleIRQ
  0x2b65: CLOCK_EnableClock
  0x2b99: UART_GetInstance
  0x2bf9: UART_Init
  0x2f0d: UART_GetDefaultConfig
  0x2f85: UART_EnableInterrupts
  0x2ff5: UART_DisableInterrupts
  0x3085: UART0_DriverIRQHandler
  0x30ad: UART0_RX_TX_DriverIRQHandler
  0x30c1: UART1_DriverIRQHandler
  0x30e9: UART1_RX_TX_DriverIRQHandler
  0x30fd: UART2_DriverIRQHandler
  0x3125: UART2_RX_TX_DriverIRQHandler
  0x3139: UART3_DriverIRQHandler
  0x3161: UART3_RX_TX_DriverIRQHandler
  0x3175: UART4_DriverIRQHandler
  0x319d: UART4_RX_TX_DriverIRQHandler
  0x31b1: UART5_DriverIRQHandler
  0x31d9: UART5_RX_TX_DriverIRQHandler
  0x31ed: CLOCK_SetEr32kClock
  0x321d: CLOCK_SetPllFllSelClock
  0x3255: OSC_SetExtRefClkConfig
  0x3289: OSC_SetCapLoad
  0x32bd: CLOCK_GetMcgExtClkFreq
  0x334d: CLOCK_GetFllExtRefClkFreq
  0x33fd: CLOCK_GetInternalRefClkSelectFreq
  0x3449: CLOCK_GetFllRefClkFreq
  0x347d: CLOCK_GetPll0RefFreq
  0x348d: CLOCK_GetOscRangeFromFreq
  0x34c9: CLOCK_GetOsc0ErClkFreq
  0x351d: CLOCK_GetEr32kClkFreq
  0x35a1: CLOCK_GetPllFllSelClkFreq
  0x35f5: CLOCK_GetFreq
  0x3735: CLOCK_SetSimConfig
  0x3769: CLOCK_GetOutClkFreq
  0x37cd: CLOCK_GetFllFreq
  0x3851: CLOCK_GetInternalRefClkFreq
  0x3881: CLOCK_GetFixedFreqClkFreq
  0x38b5: CLOCK_GetPll0Freq
  0x393d: CLOCK_SetExternalRefClkConfig
  0x39a9: CLOCK_SetInternalRefClkConfig
  0x3aad: CLOCK_EnablePll0
  0x3b45: CLOCK_InitOsc0
  0x3bd1: CLOCK_SetPbeMode
  0x3c89: CLOCK_BootToPeeMode
  0x3cf9: SystemInit
  0x3d35: SystemInitHook
  0x3d45: exit
  0x3d69: __libc_init_array
  0x3db1: memcpy
  0x3dcd: memset
  0x3ddd: _exit
  0x45b0: __func__.1
  0x45c4: __func__.0
  0x45dc: mcgConfig_BOARD_BootClockRUN
  0x45e8: simConfig_BOARD_BootClockRUN
  0x45f0: oscConfig_BOARD_BootClockRUN
  0x45f8: s_edmaIRQNumber
  0x4608: __func__.36
  0x461c: __func__.35
  0x462c: __func__.34
  0x4638: __func__.33
  0x4650: __func__.31
  0x4668: __func__.22
  0x4678: __func__.21
  0x4694: __func__.10
  0x46ac: __func__.9
  0x46c0: __func__.7
  0x46d4: __func__.6
  0x46f0: __func__.5
  0x470c: __func__.4
  0x4724: __func__.3
  0x4738: __func__.2
  0x474c: __func__.0
  0x475c: __func__.0
  0x4770: __func__.9
  0x4788: __func__.8
  0x47a4: __func__.7
  0x47c4: __func__.6
  0x47d4: __func__.5
  0x47e8: __func__.3
  0x4808: __func__.0
  0x4824: s_uartBases
  0x483c: s_uartIRQ
  0x4844: s_uartClock
  0x485c: __func__.20
  0x4870: __func__.17
  0x487c: __func__.16
  0x4894: __func__.9
  0x48ac: __func__.8
  0x48c4: __func__.7
  0x48dc: fllFactorTable.6
  0x48ec: __func__.5
  0x4900: __func__.4
  0x4914: __func__.2
  0x4928: __func__.1
  0x493c: __EH_FRAME_BEGIN__
  0x493d: _init
  0x4949: _fini
  0x4954: __exidx_start
  0x495c:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __DTOR_END__
  - __CTOR_LIST__
  - __CTOR_END__
  - __DTOR_LIST__
  0x4960:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x4964:
  - __etext
  - __DATA_ROM
  0x4970: __DATA_END
  0x100000: text_end
  0x1fff0000:
  - s_slowIrcFreq
  - __data_start__
  - __DATA_RAM
  0x1fff0004: s_fastIrcFreq
  0x1fff0008: SystemCoreClock
  0x1fff000c:
  - completed.1
  - __TMC_END__
  - __START_BSS
  - __bss_start__
  - __data_end__
  0x1fff0010: object.0
  0x1fff0028: num_correct
  0x1fff002c: g_uartEdmaHandle
  0x1fff0048: g_uartTxEdmaHandle
  0x1fff0060: g_uartRxEdmaHandle
  0x1fff0078: dma_buf
  0x1fff0080: transfer_complete
  0x1fff0084: s_debugConsole
  0x1fff0098: s_EDMAHandle
  0x1fff00d8: startInstanceNum.11
  0x1fff00dc: s_edmaPrivateHandle
  0x1fff010c: s_uartHandle
  0x1fff0124: s_uartIsr
  0x1fff0128: g_xtal0Freq
  0x1fff012c: g_xtal32Freq
  0x1fff0130: __stdio_exit_handler
  0x1fff0134:
  - __bss_end__
  - __END_BSS
  0x20000000:
  - __HeapBase
  - end
  - __end__
  0x20000400:
  - __heap_limit
  - __HeapLimit
  0x2002fc00: __StackLimit
  0x20030000:
  - __StackTop
  - __stack
  0xe000ed08: VTOR
