interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: nuc123_uart_example.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x121a8
symbols:
  0x0:
  - startup_NUC123.o
  - crtstuff.c
  - crt0.o
  - main.c
  - clk.c
  - pdma.c
  - retarget.c
  - sys.c
  - uart.c
  - _syscalls.c
  - system_NUC123.c
  - _thumb1_case_uqi.o
  - _udivsi3.o
  - _dvmd_tls.o
  - exit.c
  - init.c
  - printf.c
  - nano-vfprintf.c
  - wbuf.c
  - wsetup.c
  - putchar.c
  - nano-vfprintf_i.c
  - puts.c
  - fflush.c
  - memchr-stub.c
  - findfp.c
  - stdio.c
  - readr.c
  - writer.c
  - errno.c
  - fwalk.c
  - memset.c
  - freer.c
  - lock.c
  - makebuf.c
  - putc.c
  - closer.c
  - mallocr.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - mlock.c
  - sbrkr.c
  - _thumb1_case_shi.o
  - sbrk.c
  - _exit.c
  - crti.o
  - crtn.o
  - crtstuff.c
  - impure.c
  - __Vectors
  0xc0:
  - __Vectors_Size
  - __Vectors_End
  0xc1: deregister_tm_clones
  0xe1: register_tm_clones
  0x100: Heap_Size
  0x109: __do_global_dtors_aux
  0x135: frame_dummy
  0x159: _stack_init
  0x165:
  - _mainCRTStartup
  - _start
  0x1d9: pwcheck_success
  0x1e9: pwcheck_passed_1
  0x1f9: pwcheck_passed_2
  0x209: pwcheck_passed_3
  0x219: pwcheck_passed_4
  0x229: pwcheck_passed_5
  0x239: pwcheck_passed_6
  0x249: pwcheck_passed_7
  0x259: pwcheck_passed_8
  0x269: check_password
  0x2dd: ClearBuf
  0x2eb: BuildSrcPattern
  0x315: PDMA_UART_RxTest
  0x351: PDMA_Callback
  0x3a5: PDMA_IRQHandler
  0x3bd: PDMA_UART
  0x400: Stack_Size
  0x479: SYS_Init
  0x509: UART0_Init
  0x525: main
  0x571: CLK_SetModuleClock
  0x629: CLK_EnableXtalRC
  0x639: CLK_EnableModuleClock
  0x655: CLK_WaitClockReady
  0x679: CLK_SetHCLK
  0x6c5: CLK_EnablePLL
  0x879: CLK_SetCoreClock
  0x8f9: PDMA_Open
  0x909: PDMA_Close
  0x915: PDMA_SetTransferCnt
  0x94d: PDMA_SetTransferAddr
  0x96d: PDMA_SetTransferMode
  0xabd: PDMA_Trigger
  0xad5: PDMA_EnableInt
  0xae9: PDMA_DisableInt
  0xafd: Hard_Fault_Handler
  0xb6d: HardFault_Handler
  0xb8d: _write
  0xbc5: _read
  0xbdd: SYS_ResetModule
  0xbfd: CLK_GetPLLClockFreq
  0xc5d: UART_DisableInt
  0xc81: UART_EnableInt
  0xca5: UART_Open
  0xd35: _close
  0xd45: _fstat
  0xd55: _isatty
  0xd63: _lseek
  0xd75: Reset_Handler
  0xd9d:
  - GPCDF_IRQHandler
  - I2C0_IRQHandler
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - PS2_IRQHandler
  - CAN1_IRQHandler
  - UART0_IRQHandler
  - USBD_IRQHandler
  - SPI1_IRQHandler
  - TMR0_IRQHandler
  - ACMP_IRQHandler
  - I2S_IRQHandler
  - RTC_IRQHandler
  - PWRWU_IRQHandler
  - EINT1_IRQHandler
  - PWMA_IRQHandler
  - Default_Handler
  - ADC_IRQHandler
  - TMR2_IRQHandler
  - BOD_IRQHandler
  - SPI2_IRQHandler
  - WDT_IRQHandler
  - SVC_Handler
  - SC012_IRQHandler
  - GPAB_IRQHandler
  - EINT0_IRQHandler
  - CAN0_IRQHandler
  - TMR3_IRQHandler
  - SPI0_IRQHandler
  - SPI3_IRQHandler
  - TMR1_IRQHandler
  0xda1: SH_DoCommand
  0xda9: SystemCoreClockUpdate
  0xe59: SystemInit
  0xe5d: __gnu_thumb1_case_uqi
  0xe70: .udivsi3_skip_div0_test
  0xe71:
  - __udivsi3
  - __aeabi_uidiv
  0xf7d: __aeabi_uidivmod
  0xf85:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0xf89: exit
  0xfb1: __libc_init_array
  0xff9:
  - printf
  - iprintf
  0x1019: __sfputc_r
  0x1043: __sfputs_r
  0x1069:
  - _vfiprintf_r
  - _vfprintf_r
  0x12a1: __swbuf_r
  0x1325: __swsetup_r
  0x13e1: putchar
  0x13f5: _printf_common
  0x14d5: _printf_i
  0x16ed: _puts_r
  0x1799: puts
  0x17ad: __sflush_r
  0x18b9: _fflush_r
  0x190f: memchr
  0x1925: std
  0x1991: stdio_exit_handler
  0x19ad: cleanup_stdio
  0x19e9: global_stdio_init.part.0
  0x1a25: __sfp_lock_acquire
  0x1a35: __sfp_lock_release
  0x1a45: __sinit
  0x1a75: __sread
  0x1a9d: __swrite
  0x1ad5: __sseek
  0x1b01: __sclose
  0x1b0d: _read_r
  0x1b35: _write_r
  0x1b5d: __errno
  0x1b69: _fwalk_sglue
  0x1ba1: memset
  0x1bb1: _free_r
  0x1c45: __retarget_lock_init_recursive
  0x1c47: __retarget_lock_acquire_recursive
  0x1c49: __retarget_lock_release_recursive
  0x1c4d: __swhatbuf_r
  0x1ca1: __smakebuf_r
  0x1d23: _putc_r
  0x1d91: _close_r
  0x1db5: sbrk_aligned
  0x1df9: _malloc_r
  0x1ef9: _fstat_r
  0x1f1d: _isatty_r
  0x1f41: _lseek_r
  0x1f69: __malloc_lock
  0x1f79: __malloc_unlock
  0x1f89: _sbrk_r
  0x1fad: __gnu_thumb1_case_shi
  0x1fc1: _sbrk
  0x1fdd: _exit
  0x1fe1: _init
  0x1fed: _fini
  0x2108:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x210c: __exidx_start
  0x2114:
  - __exidx_end
  - __etext
  0x20000000:
  - __data_start__
  - UART_TEST_LENGTH
  0x20000004: gau32ClkSrcTbl
  0x20000024: PllClock
  0x20000028: CyclesPerUs
  0x2000002c: SystemCoreClock
  0x20000030: _impure_ptr
  0x20000034: _impure_data
  0x20000080: __sglue
  0x2000008c:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20000090:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x20000094:
  - completed.1
  - __TMC_END__
  - __bss_start__
  - __data_end__
  0x20000098: object.0
  0x200000b0: IsTestOver
  0x200000b4: IntCnt
  0x200000b8:
  - dma_buf
  - DestArray
  0x200000c0: SrcArray
  0x200000c8: num_correct
  0x200000cc: errno
  0x200000d0: __sf
  0x20000208: __stdio_exit_handler
  0x2000020c: __lock___malloc_recursive_mutex
  0x2000020d: __lock___sfp_recursive_mutex
  0x20000210: __malloc_sbrk_start
  0x20000214: __malloc_free_list
  0x20000218: heap_end.0
  0x2000021c: __bss_end__
  0x20000220:
  - __HeapBase
  - end
  - __end__
  0x20000320: __HeapLimit
  0x20004c00: __StackLimit
  0x20005000:
  - __StackTop
  - __stack
