interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103-RIOT-USART.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12228
symbols:
  0x0:
  - vectors_cortexm.c
  - vectors.c
  - syscalls.c
  - sched.c
  - thread_arch.c
  - irq_arch.c
  - stdio_uart.c
  - pm.c
  - uart.c
  - board.c
  - panic.c
  - kernel_init.c
  - thread.c
  - isrpipe.c
  - gpio.c
  - pm.c
  - stmclk.c
  - stmclk_common.c
  - cpu_init.c
  - cpu_common.c
  - tsrb.c
  - init.c
  - main.c
  - auto_init.c
  - mutex.c
  - cortexm_init.c
  - init.c
  - nano-mallocr.c
  - printf.c
  - puts.c
  - wbuf.c
  - wsetup.c
  - fflush.c
  - findfp.c
  - fwalk.c
  - lock.c
  - makebuf.c
  - memset.c
  - mlock.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - stdio.c
  - memchr-stub.c
  - impure.c
  - _sbackup_bss
  - _rom_offset
  - _backup_ram_len
  - ccmram_length
  - _backup_ram_start_addr
  - _ebackup_data
  - _ebackup_bss
  - _sbackup_data
  0x5000: _ram_length
  0x20000:
  - _rom_length
  - _fw_rom_length
  0x8000000:
  - _rom_start_addr
  - _sfixed
  - _isr_vectors
  - cortex_vector_base
  0x8000040: vector_cpu
  0x80000ed:
  - isr_pvd
  - isr_usb_lp_can1_rx0
  - isr_dma1_channel4
  - isr_exti
  - isr_tim7
  - isr_tim5
  - isr_i2c1_ev
  - isr_tim1_brk
  - isr_dma1_channel5
  - isr_tim4
  - isr_dma1_channel2
  - isr_adc3
  - isr_can1_sce
  - isr_dma1_channel7
  - isr_usb_hp_can1_tx
  - isr_tim1_up
  - isr_tim2
  - isr_sdio
  - isr_spi2
  - isr_tim1_trg_com
  - isr_dma1_channel1
  - dummy_handler
  - isr_adc1_2
  - isr_can1_rx1
  - isr_fsmc
  - isr_spi1
  - isr_tim6
  - isr_rcc
  - isr_flash
  - isr_uart5
  - isr_rtc
  - isr_tim1_cc
  - isr_usbwakeup
  - isr_dma2_channel1
  - isr_uart4
  - isr_tim8_brk
  - isr_i2c2_er
  - isr_dma2_channel4_5
  - isr_dma1_channel6
  - isr_spi3
  - isr_tim3
  - isr_tim8_up
  - isr_tim8_cc
  - isr_i2c2_ev
  - isr_dma2_channel2
  - isr_dma2_channel3
  - isr_rtc_alarm
  - isr_tamper
  - isr_dma1_channel3
  - isr_tim8_trg_com
  - isr_i2c1_er
  - isr_wwdg
  0x80000f1: _init
  0x80000f3: _fini
  0x80000f5: _sbrk_r
  0x8000131: _read_r
  0x8000139: _write_r
  0x8000141: _close_r
  0x800014b: _lseek_r
  0x8000155: _fstat_r
  0x800015f: _isatty_r
  0x800016d: sched_run
  0x80001d1: sched_set_status
  0x8000251: sched_switch
  0x8000281: sched_task_exit
  0x80002bd: thread_stack_init
  0x8000325: cpu_switch_context_exit
  0x800032a: unreachable329
  0x800032d: thread_yield_higher
  0x800033d: isr_pendsv
  0x8000359: isr_svc
  0x800035d: context_restore
  0x8000375: hard_fault_default
  0x8000388: fix_msp
  0x800038e: test_sp
  0x800039c: use_psp
  0x80003a0: out
  0x80003b9: nmi_default
  0x80003c9: mem_manage_default
  0x80003d9: bus_fault_default
  0x80003e9: usage_fault_default
  0x80003f9: debug_mon_default
  0x8000409:
  - dummy_handler_default
  - isr_systick
  0x8000419: pre_startup
  0x800041b: post_startup
  0x800041d: reset_handler_default
  0x8000489: hard_fault_handler
  0x8000611: irq_disable
  0x8000619: irq_enable
  0x8000621: irq_restore
  0x8000627: irq_is_in
  0x8000631: stdio_init
  0x8000649: stdio_read
  0x8000659: stdio_write
  0x800066b: pm_off
  0x800066d: uart_enable_clock
  0x800069d: irq_handler
  0x80006e5: uart_init
  0x80007a5: uart_write
  0x80007e5: isr_usart2
  0x80007eb: isr_usart1
  0x80007f1: isr_usart3
  0x80007f7: board_init
  0x80007fb: panic_arch
  0x80007fd: core_panic
  0x8000841: main_trampoline
  0x8000859: idle_thread
  0x8000861: kernel_init
  0x80008b9: thread_add_to_list
  0x80008e9: thread_create
  0x80009e1: isrpipe_write_one
  0x80009f7: isrpipe_read
  0x8000a1d: gpio_init
  0x8000ab1: gpio_init_af
  0x8000af5: gpio_set
  0x8000b09: pm_set_lowest
  0x8000b21: pm_block
  0x8000b51: stmclk_init_sysclk
  0x8000bd1: stmclk_enable_hsi
  0x8000be9: stmclk_disable_hsi
  0x8000c01: cpu_init
  0x8000ca1: periph_apb_clk
  0x8000cb9: periph_clk_en
  0x8000ce9: _pop
  0x8000cfb: tsrb_get
  0x8000d21: tsrb_add_one
  0x8000d47: periph_init
  0x8000d49: main
  0x8000d79: auto_init
  0x8000d7d: _mutex_lock
  0x8000ddd: mutex_unlock
  0x8000e29: cortexm_init
  0x8000e69: __libc_init_array
  0x8000eb1: _malloc_r
  0x8000f65:
  - printf
  - iprintf
  0x8000f95: _puts_r
  0x8001071: puts
  0x8001081: __swbuf_r
  0x8001125: __swsetup_r
  0x8001201: __sflush_r
  0x800130d: _fflush_r
  0x8001385: std
  0x80013cd: _cleanup_r
  0x80013d9: __sfmoreglue
  0x8001405: __sfp_lock_acquire
  0x8001411: __sfp_lock_release
  0x800141d: __sinit_lock_acquire
  0x8001429: __sinit_lock_release
  0x8001435: __sinit
  0x80014a5: __sfp
  0x8001531: _fwalk_reent
  0x800156f: __retarget_lock_init_recursive
  0x8001571: __retarget_lock_acquire_recursive
  0x8001573: __retarget_lock_release_recursive
  0x8001575: __swhatbuf_r
  0x80015bd: __smakebuf_r
  0x800163d: memset
  0x800164d: __malloc_lock
  0x8001659: __malloc_unlock
  0x8001665: _free_r
  0x80016fd: __sfputc_r
  0x8001727: __sfputs_r
  0x800174d:
  - _vfiprintf_r
  - _vfprintf_r
  0x80019ad: _printf_common
  0x8001a8d: _printf_i
  0x8001cd9: __sread
  0x8001cfb: __swrite
  0x8001d33: __sseek
  0x8001d57: __sclose
  0x8001d5f: memchr
  0x8001fd4: uart_config
  0x800203e: assert_crash_message
  0x8002104: _global_impure_ptr
  0x8002108: __sf_fake_stderr
  0x8002128: __sf_fake_stdin
  0x8002148: __sf_fake_stdout
  0x800219c:
  - _etext
  - __fini_array_end
  - __fini_array_start
  - __init_array_end
  - _efixed
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x8002228: _sbackup_data_load
  0x20000000:
  - _ram_start_addr
  - _sstack
  - _sram
  - isr_stack
  0x20000200:
  - _srelocate
  - heap_top
  - _estack
  0x20000204: stdio_uart_isrpipe
  0x20000218: idle_name
  0x2000021c: main_name
  0x20000220: pm_blocker
  0x20000224: _impure_ptr
  0x20000228: impure_data
  0x20000288: _tcb_name_offset
  0x20000289: max_threads
  0x2000028c:
  - runqueue_bitcache
  - _sbss
  - _szero
  - _erelocate
  0x20000290: sched_active_pid
  0x20000294: sched_active_thread
  0x20000298: sched_context_switch_request
  0x2000029c: sched_num_threads
  0x200002a0: sched_runqueues
  0x200002e0: sched_threads
  0x20000364: _rx_buf_mem
  0x200003a4: isr_ctx
  0x200003c8: crashed
  0x200003cc: idle_stack
  0x200004cc: main_stack
  0x20000acc: __malloc_free_list
  0x20000ad0: __malloc_sbrk_start
  0x20000ad4: __lock___atexit_recursive_mutex
  0x20000ad5: __lock___arc4random_mutex
  0x20000ad6: __lock___env_recursive_mutex
  0x20000ad7: __lock___sinit_recursive_mutex
  0x20000ad8: __lock___malloc_recursive_mutex
  0x20000ad9: __lock___at_quick_exit_mutex
  0x20000ada: __lock___dd_hash_mutex
  0x20000adb: __lock___tz_mutex
  0x20000adc: __lock___sfp_recursive_mutex
  0x20000ae0:
  - _sheap
  - _ebss
  - _ezero
  - __noinit_start
  - __noinit_end
  0x20005000:
  - _eram
  - _eheap
