handlers:
  # Skip executing the idle hook
  default_idle_hook:
  printf:

exit_at:
  mbed_error:
  mbed_die:
  __assert_func:

interrupt_triggers:
  # Disable default interrupt trigger
  trigger: {}
  # Set interrupt trigger on idle loop
  idle:
    addr: default_idle_hook
    fuzz_mode: round_robin
  # Trigger interrupt at WFI instructions
  spiWrite1:
    addr: wfimark1
    fuzz_mode: fuzzed
  spiWrite2:
    addr: wfimark2
    fuzz_mode: fuzzed
  spiRead1:
    addr: wfimark3
    fuzz_mode: fuzzed
  spiRead2:
    addr: wfimark4
    fuzz_mode: fuzzed
