interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x10000000
    permissions: rw-
    size: 0x6f4
  dynamically_added_crash_region_10007ff8:
    base_addr: 0x10002000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x1a000000
    file: periph_uart.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x138e4
symbols:
  0x0:
  - cr_startup_lpc18xx.c
  - sysinit.c
  - uart.c
  - board.c
  - board_sysinit.c
  - chip_18xx_43xx.c
  - clock_18xx_43xx.c
  - gpdma_18xx_43xx.c
  - gpio_18xx_43xx.c
  - ring_buffer.c
  - sysinit_18xx_43xx.c
  - uart_18xx_43xx.c
  - _cr__main.c
  - memcpy.c
  - memset.c
  - initio.c
  - setvbuf.c
  - _fdopen.c
  - fclose.c
  - fflush.c
  - fseek.c
  - ftell.c
  - remove.c
  - strlen.c
  - _do_fflush.c
  - _fflush.c
  - _writebuf.c
  - alloc.c
  - _deferredlazyseek.c
  - division_64.o
  - division_idiv0.o
  - memcpy.o
  - __sys_close.c
  - __sys_flen.c
  - __sys_istty.c
  - __sys_remove.c
  - __sys_seek.c
  - __sys_tmpnam.c
  - __ciob.c
  - errno.c
  0x38e4: _image_size
  0x10000000:
  - uartABStart
  - __base_RamLoc32
  - _end_uninit_RESERVED
  - _start_uninit_RESERVED
  - _data
  - __base_RAM
  0x10000030: uartABComplete
  0x10000054: uartPolling_menu1
  0x10000070: uartPolling_menu2
  0x1000008c: uartPolling_menu3
  0x100000a4: uartPolling_menu4
  0x10000110: uartPolling_menu5
  0x1000015c: uart_interrupt_menu
  0x100001c8: uart_interrupt_menu1
  0x100001e4: uart_interrupt_menu2
  0x10000200: uart_interrupt_menu3
  0x1000021c: uart_interrupt_menu4
  0x10000235: isDMATx
  0x10000238: GPDMA_LUTPerAddr
  0x100002b0:
  - _bss
  - num_correct
  - _edata
  0x100002b4: txring
  0x100002c8: rxring
  0x100002dc:
  - dma_buf
  - receiveBuffer
  0x100002ec: rxbuff
  0x100003ec: txbuff
  0x100004ec: dmaChannelNumTx
  0x100004ed: dmaChannelNumRx
  0x100004f0: channelTC
  0x100004f4: channelTCErr
  0x100004f8: SystemCoreClock
  0x100004fc: audio_usb_pll_freq
  0x10000504: ChannelHandlerArray
  0x1000050c: ABsyncSts
  0x10000510: errno
  0x10000514: __Ciob
  0x100006f4:
  - _noinit
  - _ebss
  - _end_noinit
  - _pvHeapStart
  0x10008000:
  - __top_RAM
  - __top_RamLoc32
  - _vStackTop
  0x10080000:
  - __base_RAM2
  - __base_RamLoc40
  0x1008a000:
  - __top_RAM2
  - __top_RamLoc40
  0x1a000000:
  - __vectors_start__
  - __base_Flash
  - _image_start
  - __base_MFlashA512
  - g_pfnVectors
  0x1a000114:
  - __section_table_start
  - __data_section_table
  0x1a000150:
  - __data_section_table_end
  - __bss_section_table
  0x1a000178:
  - __bss_section_table_end
  - __section_table_end
  0x1a000179: data_init
  0x1a0001bd: bss_init
  0x1a0001f5: NMI_Handler
  0x1a0001fd: HardFault_Handler
  0x1a000205: MemManage_Handler
  0x1a00020d: BusFault_Handler
  0x1a000215: UsageFault_Handler
  0x1a00021d: SVC_Handler
  0x1a000225: DebugMon_Handler
  0x1a00022d: PendSV_Handler
  0x1a000235: SysTick_Handler
  0x1a00023d:
  - TIMER2_IRQHandler
  - RIT_IRQHandler
  - I2C0_IRQHandler
  - SDIO_IRQHandler
  - ATIMER_IRQHandler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - GPIO5_IRQHandler
  - CAN1_IRQHandler
  - USB1_IRQHandler
  - I2S0_IRQHandler
  - TIMER3_IRQHandler
  - SGPIO_IRQHandler
  - ADC0_IRQHandler
  - GPIO6_IRQHandler
  - IntDefaultHandler
  - GPIO1_IRQHandler
  - SSP0_IRQHandler
  - ADC1_IRQHandler
  - FLASHEEPROM_IRQHandler
  - RTC_IRQHandler
  - TIMER0_IRQHandler
  - LCD_IRQHandler
  - TIMER1_IRQHandler
  - UART2_IRQHandler
  - GPIO2_IRQHandler
  - I2S1_IRQHandler
  - SSP1_IRQHandler
  - USB0_IRQHandler
  - GPIO3_IRQHandler
  - SCT_IRQHandler
  - WDT_IRQHandler
  - GPIO7_IRQHandler
  - SPIFI_IRQHandler
  - QEI_IRQHandler
  - ETH_IRQHandler
  - CAN0_IRQHandler
  - GINT0_IRQHandler
  - DAC_IRQHandler
  - GPIO0_IRQHandler
  - EVRT_IRQHandler
  - UART3_IRQHandler
  - MCPWM_IRQHandler
  - GINT1_IRQHandler
  - GPIO4_IRQHandler
  0x1a000245: ResetISR
  0x1a00031d: SystemInit
  0x1a000341: NVIC_EnableIRQ
  0x1a000371: NVIC_DisableIRQ
  0x1a0003a5: NVIC_SetPriority
  0x1a0003f9: Chip_UART_IntEnable
  0x1a000419: Chip_UART_IntDisable
  0x1a00043b: Chip_UART_SetupFIFOS
  0x1a000455: pwcheck_success
  0x1a000471: pwcheck_passed_1
  0x1a00048d: pwcheck_passed_2
  0x1a0004a9: pwcheck_passed_3
  0x1a0004c5: pwcheck_passed_4
  0x1a0004e1: pwcheck_passed_5
  0x1a0004fd: pwcheck_passed_6
  0x1a000519: pwcheck_passed_7
  0x1a000535: pwcheck_passed_8
  0x1a000551: check_password
  0x1a0005ed: App_DMA_Init
  0x1a000615: App_DMA_DeInit
  0x1a000649: App_DMA_Test
  0x1a0006c1: Print_Menu_Interrupt
  0x1a0006ed: App_Interrupt_Init
  0x1a00073d: App_Interrupt_DeInit
  0x1a000759: App_Interrupt_Test
  0x1a000819: Print_Menu_Polling
  0x1a000851: DMA_IRQHandler
  0x1a0008b5: UART0_IRQHandler
  0x1a0008d5: main
  0x1a000a39: Chip_SCU_PinMuxSet
  0x1a000a69: Chip_ENET_RMIIEnable
  0x1a000a91: Chip_GPIO_SetPinState
  0x1a000ac7: Chip_GPIO_SetPinDIROutput
  0x1a000b03: Chip_UART_TXEnable
  0x1a000b1b: Chip_UART_SendByte
  0x1a000b37: Chip_UART_ConfigData
  0x1a000b51: Chip_UART_ReadLineStatus
  0x1a000b67: __sys_write
  0x1a000b9f: Board_UART_Init
  0x1a000bc5: Board_Debug_Init
  0x1a000bf5: Board_UARTPutChar
  0x1a000c29: Board_LED_Init
  0x1a000c89: Board_Init
  0x1a000cad: Chip_SCU_PinMuxSet
  0x1a000cdd: Chip_SCU_SetPinMuxing
  0x1a000d29: Chip_CREG_SetFlashAcceleration
  0x1a000d7d: Board_SetupMuxing
  0x1a000d91: Board_SetupClocking
  0x1a000e11: Board_SystemInit
  0x1a000e21: SystemCoreClockUpdate
  0x1a000e39: ABS
  0x1a000e59: pll_calc_divs
  0x1a000f7d: pll_get_frac
  0x1a0010f3: Chip_Clock_GetDivRate
  0x1a001135: Chip_Clock_FindBaseClock
  0x1a0011c1: Chip_Clock_EnableCrystal
  0x1a001231: Chip_Clock_CalcMainPLLValue
  0x1a001309: Chip_Clock_GetMainPLLHz
  0x1a0013c5: Chip_Clock_GetDividerSource
  0x1a001405: Chip_Clock_GetDividerDivisor
  0x1a001439: Chip_Clock_GetClockInputHz
  0x1a001579: Chip_Clock_GetBaseClocktHz
  0x1a00159d: Chip_Clock_SetBaseClock
  0x1a001639: Chip_Clock_GetBaseClock
  0x1a001685: Chip_Clock_EnableOpts
  0x1a001701: Chip_Clock_Disable
  0x1a001761: Chip_Clock_GetRate
  0x1a0017e9: configDMAMux
  0x1a0019e5: makeCtrlWord
  0x1a001b2d: setupChannel
  0x1a001be9: Chip_GPDMA_Init
  0x1a001c55: Chip_GPDMA_Stop
  0x1a001cbd: Chip_GPDMA_Interrupt
  0x1a001d29: Chip_GPDMA_InitChannelCfg
  0x1a001e2d: Chip_GPDMA_IntGetStatus
  0x1a001ee9: Chip_GPDMA_ClearIntPending
  0x1a001f27: Chip_GPDMA_ChannelCmd
  0x1a001f6d: Chip_GPDMA_Transfer
  0x1a002061: Chip_GPDMA_GetFreeChannel
  0x1a0020b9: Chip_GPIO_Init
  0x1a0020cb: RingBuffer_GetCount
  0x1a0020eb: RingBuffer_GetFree
  0x1a002109: RingBuffer_IsFull
  0x1a00212f: RingBuffer_IsEmpty
  0x1a002157: RingBuffer_Init
  0x1a002191: RingBuffer_Insert
  0x1a0021ed: RingBuffer_InsertMult
  0x1a00230f: RingBuffer_Pop
  0x1a00236b: RingBuffer_PopMult
  0x1a00248d: Chip_Clock_DisableMainPLL
  0x1a0024a9: Chip_Clock_SetupMainPLL
  0x1a0024e9: Chip_Clock_MainPLLLocked
  0x1a00250d: Chip_SetupCoreClock
  0x1a002669: RingBuffer_IsEmpty
  0x1a002691: Chip_UART_TXDisable
  0x1a0026a9: Chip_UART_SendByte
  0x1a0026c5: Chip_UART_ReadByte
  0x1a0026dd: Chip_UART_IntEnable
  0x1a0026fd: Chip_UART_IntDisable
  0x1a00271f: Chip_UART_ReadIntIDReg
  0x1a002735: Chip_UART_SetupFIFOS
  0x1a00274f: Chip_UART_ConfigData
  0x1a002769: Chip_UART_EnableDivisorAccess
  0x1a002787: Chip_UART_DisableDivisorAccess
  0x1a0027a5: Chip_UART_SetDivisorLatches
  0x1a0027cb: Chip_UART_ReadLineStatus
  0x1a0027e1: Chip_UART_SetAutoBaudReg
  0x1a002801: Chip_UART_GetIndex
  0x1a00286d: Chip_UART_ABIntHandler
  0x1a0028d9: Chip_UART_Init
  0x1a00295d: Chip_UART_DeInit
  0x1a00298d: Chip_UART_Send
  0x1a0029dd: Chip_UART_CheckBusy
  0x1a002a01: Chip_UART_SendBlocking
  0x1a002a4b: Chip_UART_Read
  0x1a002a9d: Chip_UART_RXIntHandlerRB
  0x1a002ad9: Chip_UART_TXIntHandlerRB
  0x1a002b2d: Chip_UART_SendRB
  0x1a002b8d: Chip_UART_ReadRB
  0x1a002baf: Chip_UART_IRQRBHandler
  0x1a002bf9: Chip_UART_SetBaudFDR
  0x1a002d79: Chip_UART_GetABEOStatus
  0x1a002d95: Chip_UART_ABCmd
  0x1a002e15: __main
  0x1a002e23: memcpy
  0x1a002e27: memset
  0x1a002e2d: _initio
  0x1a002ea5: setvbuf
  0x1a002ee3: _fdopen
  0x1a002f4b: fclose
  0x1a002fa5: fflush
  0x1a002fe1: fseek
  0x1a0030d9: ftell
  0x1a00311d: remove
  0x1a003131: strlen
  0x1a00317f: _do_fflush
  0x1a0031bf: _fflush
  0x1a003211: _Cwritebuf
  0x1a00327d: free
  0x1a0032ad: _deferredlazyseek
  0x1a0032ed: __aeabi_uldivmod
  0x1a0032f1: __bhs_ldivmod1
  0x1a00330c: ldiv32
  0x1a003314: ldiv_return
  0x1a00332a: ldiv_sign
  0x1a00333c: ldiv64
  0x1a0033c4: ldiv_res01
  0x1a0033da: ldiv_divzero
  0x1a0033e6: udiv6432
  0x1a0033ee: udiv6432_loop1
  0x1a003402: udiv6432_entry
  0x1a003404: udiv6432_loop
  0x1a003461: __aeabi_idiv0
  0x1a003463: __aeabi_memcpy
  0x1a00346d:
  - __aeabi_memcpy4
  - __aeabi_memcpy8
  0x1a003470: copy4
  0x1a003486: copy1
  0x1a003497: __aeabi_lowlevel_memset
  0x1a0034aa: __bhs_memset4
  0x1a0034ac: memset4
  0x1a0034b8: memset1
  0x1a0034bc: memset1a
  0x1a0034c9: __sys_close
  0x1a0034cf: __sys_flen
  0x1a0034d5: __sys_istty
  0x1a0034db: __sys_remove
  0x1a0034e1: __sys_seek
  0x1a0034e7: __sys_tmpnam
  0x1a0034ec: ExtRateIn
  0x1a0034f0: OscRateIn
  0x1a0034f4: gpioLEDBits
  0x1a0034fc: InitClkStates
  0x1a003508: pinmuxing
  0x1a00353c: periph_to_base
  0x1a0035a0: GPDMA_LUTPerBurst
  0x1a0035c0: GPDMA_LUTPerWid
  0x1a0035e0: InitClkStates
  0x1a00361c: UART_PClock
  0x1a003624: UART_BClock
  0x1a003630: __num_Ciob_streams
  0x1a003634:
  - __exidx_end
  - _etext
  - __exidx_start
  0x1a0038e4: _image_end
  0x1a080000:
  - __top_MFlashA512
  - __top_Flash
  0x1b000000:
  - __base_Flash2
  - __base_MFlashB512
  0x1b080000:
  - __top_Flash2
  - __top_MFlashB512
  0x20000000:
  - __base_RamAHB32
  - __base_RAM3
  0x20008000:
  - __top_RamAHB32
  - __base_RamAHB16
  - __base_RAM4
  - __top_RAM3
  0x2000c000:
  - __base_RamAHB_ETB16
  - __top_RAM4
  - __base_RAM5
  - __top_RamAHB16
  0x20010000:
  - __top_RamAHB_ETB16
  - __top_RAM5
