interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: GPS-Receiver.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x19984
symbols:
  0x0:
  - startup/startup_stm32f103xb.o
  - crtstuff.c
  - _arm_addsubdf3.o
  - _arm_muldivdf3.o
  - _arm_cmpdf2.o
  - _arm_unorddf2.o
  - _arm_fixdfsi.o
  - lib_a-memcpy.o
  - _arm_fixunsdfsi.o
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - stm32f1xx_ll_gpio.c
  - stm32f1xx_ll_rcc.c
  - stm32f1xx_ll_usart.c
  - stm32f1xx_ll_utils.c
  - afl_call.c
  - gps.c
  - main.c
  - stm32f1xx_it.c
  - syscalls.c
  - system_stm32f1xx.c
  - errno.c
  - init.c
  - memset.c
  - sprintf.c
  - strlen-stub.c
  - strncmp.c
  - strtod.c
  - vfprintf.c
  - __call_atexit.c
  - atexit.c
  - dtoa.c
  - fini.c
  - mallocr.c
  - gdtoa-gethex.c
  - gdtoa-hexnan.c
  - localeconv.c
  - lock.c
  - mallocr.c
  - mbtowc_r.c
  - memchr-stub.c
  - mlock.c
  - mprec.c
  - s_frexp.c
  - sbrkr.c
  - strncpy.c
  - vfprintf.c
  - wctomb_r.c
  - __atexit.c
  - mallocr.c
  - memmove.c
  - mallocr.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  - impure.c
  - locale.c
  - ctype_.c
  - reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000111: __do_global_dtors_aux
  0x8000135: frame_dummy
  0x8000151: __aeabi_drsub
  0x8000159:
  - __aeabi_dsub
  - __subdf3
  0x800015d:
  - __adddf3
  - __aeabi_dadd
  0x80003d5:
  - __aeabi_ui2d
  - __floatunsidf
  0x80003f5:
  - __floatsidf
  - __aeabi_i2d
  0x8000419:
  - __extendsfdf2
  - __aeabi_f2d
  0x800045d:
  - __aeabi_ul2d
  - __floatundidf
  0x800046d:
  - __floatdidf
  - __aeabi_l2d
  0x80004c9:
  - __aeabi_dmul
  - __muldf3
  0x800071d:
  - __aeabi_ddiv
  - __divdf3
  0x80008ed:
  - __gtdf2
  - __gedf2
  0x80008f5:
  - __ltdf2
  - __ledf2
  0x80008fd:
  - __cmpdf2
  - __eqdf2
  - __nedf2
  0x8000979: __aeabi_cdrcmple
  0x8000989:
  - __aeabi_cdcmple
  - __aeabi_cdcmpeq
  0x8000999: __aeabi_dcmpeq
  0x80009ad: __aeabi_dcmplt
  0x80009c1: __aeabi_dcmple
  0x80009d5: __aeabi_dcmpge
  0x80009e9: __aeabi_dcmpgt
  0x80009fd:
  - __aeabi_dcmpun
  - __unorddf2
  0x8000a29:
  - __fixdfsi
  - __aeabi_d2iz
  0x8000a79: memcpy
  0x8000b65:
  - __fixunsdfsi
  - __aeabi_d2uiz
  0x8000ba5: __aeabi_uldivmod
  0x8000bd5: __udivmoddi4
  0x8000ea5:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x8000ea9: LL_GPIO_SetPinMode
  0x8000f09: LL_GPIO_SetPinSpeed
  0x8000f69: LL_GPIO_SetPinOutputType
  0x8000fc9: LL_GPIO_SetPinPull
  0x800100b: LL_GPIO_Init
  0x80010cd: LL_RCC_GetSysClkSource
  0x80010e5: LL_RCC_GetAHBPrescaler
  0x80010fd: LL_RCC_GetAPB1Prescaler
  0x8001115: LL_RCC_GetAPB2Prescaler
  0x800112d: LL_RCC_PLL_GetMainSource
  0x8001145: LL_RCC_PLL_GetMultiplicator
  0x800115d: LL_RCC_PLL_GetPrediv
  0x8001179: LL_RCC_GetSystemClocksFreq
  0x80011c5: RCC_GetSystemClockFreq
  0x8001209: RCC_GetHCLKClockFreq
  0x8001235: RCC_GetPCLK1ClockFreq
  0x800125d: RCC_GetPCLK2ClockFreq
  0x8001285: RCC_PLL_GetFreqDomain_SYS
  0x80012e5: LL_USART_IsEnabled
  0x800130b: LL_USART_SetStopBitsLength
  0x800132f: LL_USART_SetHWFlowCtrl
  0x8001355: LL_USART_SetBaudRate
  0x8001411: LL_USART_Init
  0x80014d1: LL_InitTick
  0x8001505: LL_Init1msTick
  0x8001521: LL_SetSystemCoreClock
  0x800153d: aflCall
  0x8001545: startForkserver
  0x8001575: parse_number
  0x8001607: parse_float_number
  0x800164d: parse_lat_long
  0x80016ed: parse_term
  0x8001c25: check_crc
  0x8001d25: copy_from_tmp_memory
  0x8001e9b: gps_init
  0x8001eb9: gps_process
  0x8002035: NVIC_SetPriorityGrouping
  0x800207d: NVIC_GetPriorityGrouping
  0x8002099: NVIC_EnableIRQ
  0x80020c9: NVIC_SetPriority
  0x800211d: NVIC_EncodePriority
  0x8002181: LL_DMA_EnableChannel
  0x80021bd: LL_DMA_SetDataTransferDirection
  0x8002205: LL_DMA_SetMode
  0x8002249: LL_DMA_SetPeriphIncMode
  0x800228d: LL_DMA_SetMemoryIncMode
  0x80022d1: LL_DMA_SetPeriphSize
  0x8002315: LL_DMA_SetMemorySize
  0x8002359: LL_DMA_SetChannelPriorityLevel
  0x800239d: LL_DMA_SetDataLength
  0x80023e1: LL_DMA_SetMemoryAddress
  0x8002411: LL_DMA_SetPeriphAddress
  0x8002441: LL_DMA_EnableIT_TC
  0x800247d: LL_DMA_EnableIT_HT
  0x80024b9: LL_RCC_HSE_Enable
  0x80024d5: LL_RCC_HSE_IsReady
  0x80024f9: LL_RCC_SetSysClkSource
  0x8002521: LL_RCC_GetSysClkSource
  0x8002539: LL_RCC_SetAHBPrescaler
  0x8002561: LL_RCC_SetAPB1Prescaler
  0x8002589: LL_RCC_SetAPB2Prescaler
  0x80025b1: LL_RCC_PLL_Enable
  0x80025cd: LL_RCC_PLL_IsReady
  0x80025f1: LL_RCC_PLL_ConfigDomain_SYS
  0x8002621: LL_AHB1_GRP1_EnableClock
  0x8002651: LL_APB1_GRP1_EnableClock
  0x8002681: LL_APB2_GRP1_EnableClock
  0x80026b1: LL_FLASH_SetLatency
  0x80026d9: LL_FLASH_GetLatency
  0x80026f1: LL_SYSTICK_SetClkSource
  0x8002729: LL_USART_Enable
  0x8002747: LL_USART_ConfigAsyncMode
  0x8002771: LL_USART_IsActiveFlag_IDLE
  0x8002795: LL_USART_IsActiveFlag_TC
  0x80027b9: LL_USART_IsActiveFlag_TXE
  0x80027dd: LL_USART_ClearFlag_IDLE
  0x80027ff: LL_USART_EnableIT_IDLE
  0x800281d: LL_USART_IsEnabledIT_IDLE
  0x8002841: LL_USART_EnableDMAReq_RX
  0x800285f: LL_USART_TransmitData8
  0x800287b: LL_GPIO_SetPinMode
  0x80028db: LL_GPIO_ReadInputPort
  0x80028f1: main
  0x80029ed: UserButton_Init
  0x8002a0d: LL_Init
  0x8002af5: usart_rx_check
  0x8002b0d: usart_process_data
  0x8002b61: usart_send_string
  0x8002b81: usart_init
  0x8002ce9: DMA1_Channel5_IRQHandler
  0x8002cf5: USART1_IRQHandler
  0x8002d25: SystemClock_Config
  0x8002da9: NMI_Handler
  0x8002db5: HardFault_Handler
  0x8002dbb: MemManage_Handler
  0x8002dc1: BusFault_Handler
  0x8002dc7: UsageFault_Handler
  0x8002dcd: SVC_Handler
  0x8002dd9: DebugMon_Handler
  0x8002de5: PendSV_Handler
  0x8002df1: SysTick_Handler
  0x8002dfd: _sbrk
  0x8002e55: SystemInit
  0x8002ebd: Reset_Handler
  0x8002ec0: CopyDataInit
  0x8002ec8: LoopCopyDataInit
  0x8002ed6: FillZerobss
  0x8002edc: LoopFillZerobss
  0x8002f04:
  - Infinite_Loop
  - Default_Handler
  0x8002f05:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - DMA1_Channel4_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI15_10_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x8002f09: __errno
  0x8002f15: __libc_init_array
  0x8002f5d: memset
  0x8002ff1: sprintf
  0x8003035: strlen
  0x8003091: strncmp
  0x8003125: sulp
  0x8003169: _strtod_l
  0x800408d: strtod
  0x80040b1: _svfprintf_r
  0x8005ab5: register_fini
  0x8005ac9: atexit
  0x8005ad5: quorem
  0x8005bf9: _dtoa_r
  0x8006a29: __libc_fini_array
  0x8006a5d: _malloc_trim_r
  0x8006afd: _free_r
  0x8006ce5: rshift
  0x8006d95: __gethex
  0x80072b5: __match
  0x80072e5: __hexnan
  0x8007485: __localeconv_l
  0x8007489: _localeconv_r
  0x80074a5: __retarget_lock_acquire_recursive
  0x80074a9: __retarget_lock_release_recursive
  0x80074ad: _malloc_r
  0x80079d1: __ascii_mbtowc
  0x80079fd: memchr
  0x8007a89: __malloc_lock
  0x8007a95: __malloc_unlock
  0x8007aa1: _Balloc
  0x8007aed: _Bfree
  0x8007b01: __multadd
  0x8007b85: __s2b
  0x8007c1d: __hi0bits
  0x8007c5d: __lo0bits
  0x8007cbd: __i2b
  0x8007cd1: __multiply
  0x8007e1d: __pow5mult
  0x8007ebd: __lshift
  0x8007f71: __mcmp
  0x8007fa9: __mdiff
  0x80080a9: __ulp
  0x80080ed: __b2d
  0x80081ad: __d2b
  0x800825d: __ratio
  0x80082b5: __copybits
  0x80082fd: __any_on
  0x8008351: frexp
  0x80083b5: _sbrk_r
  0x80083d9: strncpy
  0x800843d: __ssprint_r
  0x8008531: __ascii_wctomb
  0x8008549: __register_exitproc
  0x8008609: _calloc_r
  0x8008675: memmove
  0x8008739: _realloc_r
  0x8008aac: __EH_FRAME_BEGIN__
  0x8008aad: _init
  0x8008ab9: _fini
  0x8008ac4: _etext
  0x8008b08: CHANNEL_OFFSET_TAB
  0x8008bb8: AHBPrescTable
  0x8008bc8: APBPrescTable
  0x8008bd0: _global_impure_ptr
  0x8008be4: fpi.6172
  0x8008bf8: fpinan.6208
  0x8008c10: tinytens
  0x8008c7c: blanks.7315
  0x8008c8c: zeroes.7316
  0x8008cac: __hexdig
  0x8008dc0: __mprec_bigtens
  0x8008de8: __mprec_tens
  0x8008eb0: p05.6092
  0x8008ebc: _ctype_
  0x8008fc0: __exidx_start
  0x8008fc8:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  0x8008fcc: __frame_dummy_init_array_entry
  0x8008fd0:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x8008fd4:
  - __fini_array_end
  - _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: _impure_ptr
  0x20000008: impure_data
  0x20000430: __atexit_recursive_mutex
  0x20000434: __global_locale
  0x200005a0: __malloc_av_
  0x200009a8: __malloc_sbrk_base
  0x200009ac: __malloc_trim_threshold
  0x200009b0:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x200009b4: object.8660
  0x200009cc: noHyperCall
  0x200009d0: printflag
  0x200009d4: printflag
  0x200009d8: usart_rx_dma_buffer
  0x20000a18: textout
  0x20000a58: aux
  0x20000a5c: flag
  0x20000a60: __env
  0x20000a64: heap_end.5959
  0x20000a68: __malloc_current_mallinfo
  0x20000a90: __malloc_max_sbrked_mem
  0x20000a94: __malloc_max_total_mem
  0x20000a98: __malloc_top_pad
  0x20000aa0: hgps
  0x20000b50: __lock___atexit_recursive_mutex
  0x20000b54: __lock___arc4random_mutex
  0x20000b58: __lock___env_recursive_mutex
  0x20000b5c: __lock___sinit_recursive_mutex
  0x20000b60: __lock___malloc_recursive_mutex
  0x20000b64: __lock___at_quick_exit_mutex
  0x20000b68: __lock___dd_hash_mutex
  0x20000b6c: __lock___tz_mutex
  0x20000b70: __lock___sfp_recursive_mutex
  0x20000b74: errno
  0x20000b78:
  - _ebss
  - end
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
