include:
- config.yml

peripherals:
  my_dma_periph:
    class: fuzzware_harness.peripherals.generic_dma.GenericDMAC
    packet_limit: 16

    descriptors:
    - addr: 0x40001504 # RADIO PACKETPTR
      to:
        type: buffer
      known_values:
        - rx_buf

    known_sizes:
      # frame contains 1 byte PHY header and up to 127 bytes of payload
      rx_buf:
        min: 1
        max: 128
