interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: L1521_ChibiOS_UART.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x125c8
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __ram4_start__
  - __flash7_free__
  - __ram5_clear__
  - __ram1_free__
  - __ram6_start__
  - __ram5_end__
  - __ram5_noinit__
  - __flash1_free__
  - __ram5_size__
  - __flash7_size__
  - __flash4_free__
  - __ram1_size__
  - __flash3_free__
  - __ram1_clear__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __ram4_size__
  - __ram1_end__
  - __ram4_end__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __ram4_clear__
  - __ram5_free__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __ram2_noinit__
  - __flash3_start__
  - __ram6_noinit__
  - __ram4_init__
  - __ram7_clear__
  - __ram7_size__
  - __ram4_noinit__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram2_clear__
  - __ram3_end__
  - __ram2_size__
  - __ram1_start__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __ram1_noinit__
  - __flash2_size__
  - __flash4_end__
  - __ram2_init__
  - __ram2_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram2_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __ram5_init__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __ram1_init__
  - __ram5_start__
  - __flash6_size__
  - __ram2_free__
  - __ram4_free__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x4000: __ram0_size__
  0x49a5: crt1.c.67ace7a6
  0x4d23: hal.c.5a8294d5
  0x5dae: hal_st.c.11374873
  0x7066: hal_buffers.c.181550e2
  0x913a: hal_pal.c.781ed2ba
  0xa480: hal_uart.c.6e30783a
  0xb838: nvic.c.b06c69a3
  0xcc2f: stm32_isr.c.86bb4141
  0xdf6f: hal_lld.c.76766a24
  0xf1ac: stm32_dma.c.da023686
  0x1065d: hal_pal_lld.c.5a639ec8
  0x11aa1: hal_st_lld.c.b0a7c007
  0x12e35: hal_uart_lld.c.269e9e55
  0x14279: board.c.ece87582
  0x155e2: chsys.c.c3ae5893
  0x16e00: chdebug.c.241a4528
  0x17a96: chtrace.c.a6b272f5
  0x18b45: chvt.c.ad94433f
  0x19a44: chschd.c.d1b2dbaa
  0x1a9c0: chthreads.c.0e446262
  0x1bfea: chtm.c.190caf82
  0x1ce8e: chregistry.c.baac8904
  0x1e48a: chmtx.c.260c0b33
  0x1f401: chdynamic.c.67eb95d7
  0x20000: __flash0_size__
  0x202cf: chmemcore.c.0de5bd68
  0x2101c: chmemheaps.c.000ba8d5
  0x21f07: chmempools.c.7e1dfa10
  0x22ea7: chfactory.c.43883e81
  0x24d97: chcore_v7m.c.8dfa9b64
  0x25c81: main.c.d30db6ed
  0x8000000:
  - _vectors
  - __flash0_start__
  0x8000140:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x8000141: _crt0_entry
  0x8000174: msloop
  0x8000182: psloop
  0x8000192: dloop
  0x80001a6: bloop
  0x80001bc: initloop
  0x80001c8: endinitloop
  0x80001d0: finiloop
  0x80001dc: endfiniloop
  0x8000219: Reset_Handler
  0x800021b:
  - VectorE8
  - VectorAC
  - DebugMon_Handler
  - Vector11C
  - HardFault_Handler
  - Vector8C
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - Vector110
  - Vector120
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - VectorBC
  - Vector124
  - Vector118
  - VectorCC
  - Vector54
  - Vector98
  - Vector138
  - Vector24
  - VectorD0
  - VectorE4
  - VectorC0
  - Vector130
  - Vector134
  - VectorF0
  - Vector12C
  - Vector13C
  - Vector100
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector90
  - Vector114
  - Vector1C
  - Vector48
  - Vector4C
  - Vector88
  - Vector104
  - Vector10C
  - BusFault_Handler
  - Vector50
  - Vector44
  - Vector28
  - VectorB8
  - VectorFC
  - Vector34
  - Vector128
  - VectorA4
  - Vector20
  0x800021e: .stay
  0x800021f: _unhandled_exception
  0x8000221: _port_switch
  0x8000231: _port_thread_start
  0x8000245: _port_switch_from_isr
  0x8000250: _port_exit_from_isr
  0x8000261: uart_lld_start_send.constprop.0
  0x80002a1: _pal_lld_setgroupmode.constprop.0
  0x8000331: chTMStartMeasurementX.constprop.0
  0x8000341: rxend
  0x8000351: ledoff
  0x8000361: rxerr
  0x8000371: txend1
  0x8000381: _port_irq_epilogue
  0x80003e1: chTMStopMeasurementX
  0x8000431: trace_next
  0x8000471: _trace_switch.part.0
  0x8000491: _trace_isr_leave
  0x80004c1: _trace_isr_enter
  0x80004f1: chSysHalt
  0x8000521: uart_lld_serve_tx_end_irq
  0x8000571: chDbgCheckClassS
  0x8000591: chDbgCheckClassI
  0x80005b1: dmaStreamAllocI.constprop.0
  0x8000681: chCoreAllocAlignedWithOffsetI
  0x80006d1: chCoreAllocAlignedI
  0x80006e1: chSchReadyI
  0x8000731: _dbg_check_leave_isr
  0x8000761: _dbg_check_enter_isr
  0x8000791: _dbg_check_unlock_from_isr
  0x80007c1: _dbg_check_lock_from_isr
  0x80007f1: wakeup
  0x8000851: _idle_thread
  0x8000861: serve_usart_irq
  0x80008e1: uart_lld_serve_rx_end_irq
  0x8000971: dmaServeInterrupt
  0x80009b1: stSetAlarm
  0x80009d1: chVTDoResetI
  0x8000a81: chVTDoSetI
  0x8000b41: rxchar
  0x8000b91: txend2
  0x8000be1: restart
  0x8000c31: chSchGoSleepS
  0x8000c91: SVC_Handler
  0x8000cb1:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8000d41: _dbg_check_unlock
  0x8000d61: chSysUnlock.lto_priv.0
  0x8000d91: _dbg_check_lock
  0x8000db1: main
  0x80018c1: chCoreAllocAlignedWithOffset
  0x8001911: chThdExit
  0x8001971: __early_init
  0x8001b71: VectorDC
  0x8001ba1: VectorD8
  0x8001bd1: VectorD4
  0x8001c01: VectorB0
  0x8001d21: Vector84
  0x8001d51: Vector80
  0x8001d81: Vector7C
  0x8001db1: Vector78
  0x8001de1: Vector74
  0x8001e11: Vector70
  0x8001e41: Vector6C
  0x8001e71: VectorE0
  0x8001f01: Vector9C
  0x8001f81: Vector68
  0x8001fd1: Vector64
  0x8002021: Vector60
  0x8002071: Vector5C
  0x80020c1: Vector58
  0x8002111: __init_ram_areas
  0x8002181: __default_exit
  0x8002191: __late_init
  0x80021a1: __core_init
  0x80021a4:
  - __text_end
  - __rodata_base__
  0x8002230: __func__.4292.lto_priv.0
  0x800223c: __func__.4292.lto_priv.1
  0x8002248: __func__.5560.lto_priv.0
  0x8002254: __func__.5560.lto_priv.1
  0x8002260: __func__.5560.lto_priv.2
  0x800226c: __func__.5560.lto_priv.3
  0x8002278: __func__.5560.lto_priv.4
  0x8002284: __func__.5646
  0x8002290: __func__.5962
  0x800229c: __func__.6550
  0x80022a8: __func__.6553.lto_priv.0
  0x80022b4: __func__.6553.lto_priv.1
  0x80022c0: __func__.6557.lto_priv.0
  0x80022d4: __func__.6557.lto_priv.1
  0x80022f4: __func__.6562
  0x8002304: __func__.6572.lto_priv.0
  0x8002310: __func__.6572.lto_priv.1
  0x800231c: __func__.6575
  0x8002328: __func__.6576
  0x8002334: __func__.6586
  0x8002344: __func__.6593
  0x8002354: __func__.6608
  0x8002360: __func__.6953
  0x8002370: __func__.7233
  0x800237c: __func__.7234
  0x8002388: __func__.7236
  0x8002398: __func__.7239
  0x80023a4: __func__.7240
  0x80023b0: __func__.7242
  0x80023bc: __func__.7243
  0x80023c8: __func__.7244
  0x80023d4: __func__.7246
  0x80023e0: __func__.7249
  0x80023ec: __func__.7250.lto_priv.0
  0x80023fc: __func__.7250.lto_priv.1
  0x8002408: __func__.7254.lto_priv.0
  0x8002414: __func__.7254.lto_priv.1
  0x8002420: __func__.7256
  0x8002430: __func__.7258
  0x800243c: __func__.7259
  0x8002448: __func__.7262
  0x8002454: __func__.7264
  0x8002460: __func__.7266
  0x800246c: __func__.7267
  0x8002478: __func__.7271
  0x8002484: __func__.7275
  0x8002490: __func__.7282
  0x80024a0: _stm32_dma_streams
  0x8002510: ch_debug
  0x8002528: ram_areas
  0x80025a8:
  - __exidx_end
  - __rodata_end__
  - __exidx_start
  - _textdata_start
  0x80025c8:
  - __ram3_init_text__
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  0x8020000: __flash0_end__
  0x10000000: ICSR_PENDSVSET
  0x20000000:
  - __ram0_start__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - uart_cfg_1
  - __main_thread_stack_end__
  - _data_start
  - __process_stack_end__
  0x20000820:
  - UARTD1
  - _bss_start
  - _data_end
  0x2000083c: UARTD2
  0x20000858: UARTD3
  0x20000874: _pal_events
  0x200008f4: ch
  0x2000117c: ch_factory
  0x200011c8: ch_idle_thread_wa
  0x200012a0: ch_memcore
  0x200012a8: default_heap
  0x200012c4: dma
  0x20001304: vt1
  0x20001318: vt2
  0x2000132c:
  - __ram0_init__
  - __ram0_free__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x20001330: __heap_base__
  0x20004000:
  - __heap_end__
  - __ram0_end__
  0xe000ed04: SCB_ICSR
