interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: sam3x_uart_contiguous.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12818
symbols:
  0x0:
  - startup_sam3x.c
  - crtstuff.c
  - sysclk.c
  - read.c
  - write.c
  - init.c
  - dmac.c
  - pio.c
  - pio_handler.c
  - pmc.c
  - uart.c
  - usart.c
  - exceptions.c
  - system_sam3x.c
  - syscalls.c
  - usart_example_dmac.c
  - __call_atexit.c
  - memset.c
  - init.c
  - fini.c
  - lock.c
  - atexit.c
  - findfp.c
  - setbuf.c
  - setvbuf.c
  - freer.c
  - stdio.c
  - sbrkr.c
  - fwalk.c
  - writer.c
  - malloc.c
  - __atexit.c
  - mallocr.c
  - fclose.c
  - sysconf.c
  - makebuf.c
  - mlock.c
  - closer.c
  - fflush.c
  - fstatr.c
  - lseekr.c
  - readr.c
  - errno.c
  - crti.o
  - crtn.o
  - impure.c
  - reent.c
  0x2000: __stack_size__
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: deregister_tm_clones
  0x80111: register_tm_clones
  0x80135: __do_global_dtors_aux
  0x8015d: frame_dummy
  0x80181: sysclk_init
  0x801e5: _read
  0x80221: _write
  0x80271: board_init
  0x8031d: dmac_init
  0x80327: dmac_set_priority_mode
  0x80333: dmac_enable
  0x80339: dmac_enable_interrupt
  0x8033d: dmac_get_status
  0x80341: dmac_channel_enable
  0x80349: dmac_channel_disable
  0x80351: dmac_channel_set_configuration
  0x8035d: dmac_channel_single_buf_transfer_init
  0x80389: pio_set_peripheral
  0x803c5: pio_set_input
  0x803fb: pio_set_output
  0x80421: pio_get_interrupt_status
  0x80425: pio_get_interrupt_mask
  0x80429: pio_set_pin_high
  0x80441: pio_set_pin_low
  0x80459: pio_configure_pin
  0x80529: pio_configure_pin_group
  0x805c5: pio_handler_process
  0x80615: PIOA_Handler
  0x80629: PIOB_Handler
  0x8063d: PIOC_Handler
  0x80651: PIOD_Handler
  0x80665: PIOE_Handler
  0x80679: PIOF_Handler
  0x8068d: pmc_switch_mck_to_pllack
  0x806ed: pmc_switch_mainck_to_xtal
  0x80741: pmc_osc_is_ready_mainck
  0x80751: pmc_disable_pllack
  0x80761: pmc_is_locked_pllack
  0x80771: pmc_enable_periph_clk
  0x80791: uart_init
  0x807c5: uart_write
  0x807d5: uart_read
  0x807e7: usart_set_async_baudrate
  0x80845: usart_reset
  0x8086d: usart_init_rs232
  0x808ad: usart_enable_tx
  0x808b3: usart_enable_rx
  0x808b9: usart_is_tx_ready
  0x808c1: usart_write
  0x808d5: usart_read
  0x808ed:
  - DACC_Handler
  - DebugMon_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - SysTick_Handler
  - USART3_Handler
  - TWI1_Handler
  - PendSV_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - USART0_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - Dummy_Handler
  - TWI0_Handler
  - USART1_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - SVC_Handler
  - TC8_Handler
  - USART2_Handler
  - SDRAMC_Handler
  - SPI1_Handler
  - EMAC_Handler
  - UART_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - UOTGHS_Handler
  - SPI0_Handler
  0x808f1: Reset_Handler
  0x80991: SystemCoreClockUpdate
  0x80aa5: _sbrk
  0x80ad9: _close
  0x80adf: _fstat
  0x80ae9: _lseek
  0x80aed: configure_dmac_rx
  0x80b55: usart_serial_getchar
  0x80bf9: usart_serial_putchar
  0x80c95: pwcheck_success
  0x80ca9: pwcheck_passed_1
  0x80cb9: pwcheck_passed_2
  0x80cc9: pwcheck_passed_3
  0x80cd9: pwcheck_passed_4
  0x80ce9: pwcheck_passed_5
  0x80cf9: pwcheck_passed_6
  0x80d09: pwcheck_passed_7
  0x80d19: pwcheck_passed_8
  0x80d29: check_password
  0x80db5: DMAC_Handler
  0x80e6d: main
  0x80f81: register_fini
  0x80f95: memset
  0x81035: __libc_init_array
  0x81085: __libc_fini_array
  0x810ad: __retarget_lock_init_recursive
  0x810b1: __retarget_lock_close_recursive
  0x810b5: __retarget_lock_acquire_recursive
  0x810b9: __retarget_lock_release_recursive
  0x810bd: atexit
  0x810c9: stdio_exit_handler
  0x810e1: cleanup_stdio
  0x81121: global_stdio_init.part.0
  0x81211: __sinit
  0x8124d: __sfp_lock_acquire
  0x81259: __sfp_lock_release
  0x81265: setbuf
  0x81275: setvbuf
  0x81419: _malloc_trim_r
  0x814d1: _free_r
  0x816c9: __sread
  0x816ed: __swrite
  0x8172d: __sseek
  0x81751: __sclose
  0x81759: _sbrk_r
  0x8177d: _fwalk_sglue
  0x817c1: _write_r
  0x817ed: malloc
  0x817fd: __register_exitproc
  0x8187d: _malloc_r
  0x81de5: _fclose_r
  0x81ea5: sysconf
  0x81ec1: __swhatbuf_r
  0x81f21: __malloc_lock
  0x81f2d: __malloc_unlock
  0x81f39: _close_r
  0x81f5d: __sflush_r
  0x82085: _fflush_r
  0x820d9: _fstat_r
  0x82101: _lseek_r
  0x8212d: _read_r
  0x82159: __errno
  0x8217d: _init
  0x82188:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x8218c: __frame_dummy_init_array_entry
  0x82190: __init_array_end
  0x82191: _fini
  0x8219c:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x821a0:
  - _etext
  - __TMC_END__
  - __fini_array_end
  - _efixed
  0x20070000: _srelocate
  0x20070001: SystemInit
  0x200700a5: system_init_flash
  0x2007012c: SystemCoreClock
  0x20070130: __atexit_recursive_mutex
  0x20070134: _impure_ptr
  0x20070138: _impure_data
  0x20070258: __sglue
  0x20070264: __malloc_sbrk_base
  0x20070268: __malloc_trim_threshold
  0x20070270: __malloc_av_
  0x20070678:
  - completed.1
  - _sbss
  - _szero
  - _erelocate
  0x2007067c: object.0
  0x20070694: ptr_get
  0x20070698: ptr_put
  0x2007069c: stdio_base
  0x200706a0: gs_interrupt_sources
  0x20070710: heap.0
  0x20070714:
  - gs_puc_buffer
  - dma_buf
  0x2007071c: num_correct
  0x20070720: __atexit
  0x20070724: __lock___malloc_recursive_mutex
  0x20070728: __lock___atexit_recursive_mutex
  0x2007072c: __lock___sfp_recursive_mutex
  0x20070730: __sf
  0x20070868: __stdio_exit_handler
  0x2007086c: __atexit0
  0x200709fc: __malloc_current_mallinfo
  0x20070a24: __malloc_max_total_mem
  0x20070a28: __malloc_max_sbrked_mem
  0x20070a2c: __malloc_top_pad
  0x20070a30: errno
  0x20070a34:
  - _ebss
  - _ezero
  0x20070a38: _sstack
  0x20072a38:
  - _estack
  - _end
  0x20087ffc: __ram_end__
