include:
- config.yml

peripherals:
  my_dma_periph:
    class: fuzzware_harness.peripherals.generic_dma.GenericDMAC
    packet_limit: 1
    # 400c4000 is the dma controller
    descriptors:
    - addr: 0x400c4040 # channel 0 DMAC_DADDR
      to:
        type: buffer 
      known_values:
        - dma_buf
    known_sizes:
      dma_buf:
        min: 0x8
        max: 0x8
