include:
- config.yml

peripherals:
  my_dma_periph:
    class: fuzzware_harness.peripherals.generic_dma.GenericDMAC
    packet_limit: 1
    descriptors:
    - addr: 0x40020078 # DMA_CMAR6
      to:
        type: buffer 
      known_values: 
        - dma_buf
    known_sizes:
      dma_buf:
        min: 0x8
        max: 0x8
