interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_00000000:
    base_addr: 0x0
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: Modbus.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1316c
symbols:
  0x0:
  - startup/startup_stm32f303xe.o
  - crtstuff.c
  - lib_a-memcpy.o
  - stm32f3xx_hal.c
  - stm32f3xx_hal_cortex.c
  - stm32f3xx_ll_rcc.c
  - cmsis_os.c
  - list.c
  - queue.c
  - tasks.c
  - port.c
  - heap_4.c
  - afl_call.c
  - main.c
  - modbus_rtu.c
  - stm32f3xx_it.c
  - system_stm32f3xx.c
  - init.c
  - memset.c
  - __call_atexit.c
  - atexit.c
  - fini.c
  - lock.c
  - __atexit.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crtn.o
  - impure.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x80001a1: __do_global_dtors_aux
  0x80001c5: frame_dummy
  0x80001e1: memcpy
  0x8000315: HAL_IncTick
  0x8000339: HAL_SYSTICK_IRQHandler
  0x8000345: HAL_SYSTICK_Callback
  0x8000351: LL_RCC_HSI_IsReady
  0x8000375: LL_RCC_LSE_IsReady
  0x8000399: LL_RCC_GetSysClkSource
  0x80003b1: LL_RCC_GetAHBPrescaler
  0x80003c9: LL_RCC_GetAPB1Prescaler
  0x80003e1: LL_RCC_GetAPB2Prescaler
  0x80003f9: LL_RCC_GetUSARTClockSource
  0x8000425: LL_RCC_PLL_GetMainSource
  0x800043d: LL_RCC_PLL_GetMultiplicator
  0x8000455: LL_RCC_PLL_GetPrediv
  0x800046d: LL_RCC_GetUSARTClockFreq
  0x80005dd: RCC_GetSystemClockFreq
  0x8000621: RCC_GetHCLKClockFreq
  0x800064d: RCC_GetPCLK1ClockFreq
  0x8000675: RCC_GetPCLK2ClockFreq
  0x800069d: RCC_PLL_GetFreqDomain_SYS
  0x8000719: osSystickHandler
  0x800072f: vListInitialise
  0x800076d: vListInitialiseItem
  0x8000785: vListInsertEnd
  0x80007cb: vListInsert
  0x800083b: uxListRemove
  0x800088d: xQueueGenericReset
  0x800095d: xQueueGenericCreate
  0x80009cf: prvInitialiseNewQueue
  0x8000a15: xQueueGiveFromISR
  0x8000b29: xQueueGenericReceive
  0x8000d4d: prvCopyDataFromQueue
  0x8000d99: prvUnlockQueue
  0x8000e3d: prvIsQueueEmpty
  0x8000e69: xTaskCreate
  0x8000eeb: prvInitialiseNewTask
  0x8000ff9: prvAddNewTaskToReadyList
  0x80010d5: vTaskStartScheduler
  0x8001161: vTaskSuspendAll
  0x800117d: xTaskResumeAll
  0x80012b5: xTaskIncrementTick
  0x800142d: vTaskSwitchContext
  0x80014e1: vTaskPlaceOnEventList
  0x8001529: xTaskRemoveFromEventList
  0x80015ed: vTaskSetTimeOutState
  0x8001631: xTaskCheckForTimeOut
  0x80016ed: vTaskMissedYield
  0x8001705: prvIdleTask
  0x8001735: prvInitialiseTaskLists
  0x80017b5: prvCheckTasksWaitingTermination
  0x800182d: prvDeleteTCB
  0x800184d: prvResetNextTaskUnblockTime
  0x8001895: xTaskGetSchedulerState
  0x80018d1: vTaskPriorityInherit
  0x80019bd: pvTaskIncrementMutexHeldCount
  0x80019e5: prvAddCurrentTaskToDelayedList
  0x8001ab1: pxPortInitialiseStack
  0x8001b09: prvTaskExitError
  0x8001b51: SVC_Handler
  0x8001b70: pxCurrentTCBConst2
  0x8001b79: prvPortStartFirstTask
  0x8001b99: xPortStartScheduler
  0x8001c55: vPortEnterCritical
  0x8001cb1: vPortExitCritical
  0x8001d01: PendSV_Handler
  0x8001d40: pxCurrentTCBConst
  0x8001d49: xPortSysTickHandler
  0x8001d89: vPortSetupTimerInterrupt
  0x8001dbd: vPortValidateInterruptPriority
  0x8001e35: pvPortMalloc
  0x8001fb9: vPortFree
  0x8002069: prvHeapInit
  0x800212d: prvInsertBlockIntoFreeList
  0x80021dd: aflCall
  0x80021e5: startForkserver
  0x8002215: main
  0x8002231: NVIC_EnableIRQ
  0x8002261: NVIC_SetPriority
  0x80022b5: modbusSlaveStartTread
  0x80022e1: modbusSlaveHandler
  0x8002335: modbusSlaveHardwareInit
  0x8002551: DMA1_Channel4_IRQHandler
  0x800257d: DMA1_Channel5_IRQHandler
  0x80025d1: USART1_IRQHandler
  0x8002651: modbusSlaveStartReceiving
  0x8002691: modbusSlaveStartTransmitting
  0x80026bd: modbusSlaveCheckFrameSize
  0x80026dd: modbusSlaveCheckID
  0x80026fd: modbusSlaveCheckCRC
  0x800275d: modbusSlaveGetCRC
  0x80027d9: modbusSlaveErrorSet
  0x8002809: modbusSlaveParseFrame
  0x80029f9: SysTick_Handler
  0x8002a0d: SystemInit
  0x8002a91: Reset_Handler
  0x8002a98: CopyDataInit
  0x8002aa0: LoopCopyDataInit
  0x8002aae: FillZerobss
  0x8002ab4: LoopFillZerobss
  0x8002ac6: LoopForever
  0x8002ae0:
  - Infinite_Loop
  - Default_Handler
  0x8002ae1:
  - RTC_Alarm_IRQHandler
  - TIM8_TRG_COM_IRQHandler
  - TIM8_CC_IRQHandler
  - DebugMon_Handler
  - SPI4_IRQHandler
  - TIM1_CC_IRQHandler
  - HardFault_Handler
  - USB_HP_IRQHandler
  - PVD_IRQHandler
  - TAMP_STAMP_IRQHandler
  - NMI_Handler
  - EXTI3_IRQHandler
  - I2C3_ER_IRQHandler
  - USB_HP_CAN_TX_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - FPU_IRQHandler
  - TIM1_UP_TIM16_IRQHandler
  - UsageFault_Handler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - CAN_SCE_IRQHandler
  - TIM6_DAC_IRQHandler
  - TIM8_UP_IRQHandler
  - DMA2_Channel2_IRQHandler
  - TIM20_TRG_COM_IRQHandler
  - USART3_IRQHandler
  - DMA1_Channel7_IRQHandler
  - UART5_IRQHandler
  - ADC3_IRQHandler
  - TIM4_IRQHandler
  - CAN_RX1_IRQHandler
  - DMA2_Channel1_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - UART4_IRQHandler
  - DMA2_Channel4_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM20_UP_IRQHandler
  - DMA1_Channel1_IRQHandler
  - USBWakeUp_RMP_IRQHandler
  - EXTI15_10_IRQHandler
  - TIM7_IRQHandler
  - I2C3_EV_IRQHandler
  - EXTI9_5_IRQHandler
  - RTC_WKUP_IRQHandler
  - SPI2_IRQHandler
  - USB_LP_CAN_RX0_IRQHandler
  - MemManage_Handler
  - DMA2_Channel5_IRQHandler
  - USB_LP_IRQHandler
  - EXTI4_IRQHandler
  - TIM1_TRG_COM_TIM17_IRQHandler
  - DMA1_Channel3_IRQHandler
  - ADC4_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - COMP7_IRQHandler
  - COMP1_2_3_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - COMP4_5_6_IRQHandler
  - TIM20_BRK_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - TIM8_BRK_IRQHandler
  - FLASH_IRQHandler
  - TIM20_CC_IRQHandler
  - BusFault_Handler
  - SPI3_IRQHandler
  - I2C1_ER_IRQHandler
  - FMC_IRQHandler
  - USBWakeUp_IRQHandler
  - DMA2_Channel3_IRQHandler
  - EXTI2_TSC_IRQHandler
  - TIM1_BRK_TIM15_IRQHandler
  0x8002ae5: __libc_init_array
  0x8002b2d: memset
  0x8002bc1: register_fini
  0x8002bd5: atexit
  0x8002be1: __libc_fini_array
  0x8002c15: __retarget_lock_acquire_recursive
  0x8002c19: __retarget_lock_release_recursive
  0x8002c1d: __register_exitproc
  0x8002cdc: __EH_FRAME_BEGIN__
  0x8002cdd: _init
  0x8002ce9: _fini
  0x8002cf4: _etext
  0x8002d08: AHBPrescTable
  0x8002d18: APBPrescTable
  0x8002d20: _global_impure_ptr
  0x8002d24:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8002d28: __frame_dummy_init_array_entry
  0x8002d2c:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x8002d30:
  - __fini_array_end
  - _sidata
  0x800316c: _siccmram
  0x10000000:
  - _eccmram
  - _sccmram
  0x20000000:
  - _sdata
  - uwTickPrio
  0x20000004: uwTickFreq
  0x20000008: uxCriticalNesting
  0x2000000c: SystemCoreClock
  0x20000010: impure_data
  0x20000438: __atexit_recursive_mutex
  0x2000043c:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x20000440: object.8660
  0x20000458: pxCurrentTCB
  0x2000045c: pxReadyTasksLists
  0x200004e8: xDelayedTaskList1
  0x200004fc: xDelayedTaskList2
  0x20000510: pxDelayedTaskList
  0x20000514: pxOverflowDelayedTaskList
  0x20000518: xPendingReadyList
  0x2000052c: xTasksWaitingTermination
  0x20000540: uxDeletedTasksWaitingCleanUp
  0x20000544: xSuspendedTaskList
  0x20000558: uxCurrentNumberOfTasks
  0x2000055c: xTickCount
  0x20000560: uxTopReadyPriority
  0x20000564: xSchedulerRunning
  0x20000568: uxPendedTicks
  0x2000056c: xYieldPending
  0x20000570: xNumOfOverflows
  0x20000574: uxTaskNumber
  0x20000578: xNextTaskUnblockTime
  0x2000057c: xIdleTaskHandle
  0x20000580: uxSchedulerSuspended
  0x20000584: ucMaxSysCallPriority
  0x20000588: ulMaxPRIGROUPValue
  0x2000058c: ucHeap
  0x2000418c: xStart
  0x20004194: pxEnd
  0x20004198: xFreeBytesRemaining
  0x2000419c: xMinimumEverFreeBytesRemaining
  0x200041a0: xBlockAllocatedBit
  0x200041a4: noHyperCall
  0x200041a8: modbusRxTxBuffer
  0x200042a8: modbusRxCount
  0x200042aa: modbusSlaveFrameReadyFlag
  0x200042ac: xFrameReadySemaphore
  0x200042b0: xModbusSlaveTask
  0x200042b4: aux
  0x200042b8: uwTick
  0x200042bc: modbusMemory
  0x200044bc: __lock___atexit_recursive_mutex
  0x200044c0: __lock___arc4random_mutex
  0x200044c4: __lock___env_recursive_mutex
  0x200044c8: __lock___sinit_recursive_mutex
  0x200044cc: __lock___malloc_recursive_mutex
  0x200044d0: __lock___at_quick_exit_mutex
  0x200044d4: __lock___dd_hash_mutex
  0x200044d8: __lock___tz_mutex
  0x200044dc: __lock___sfp_recursive_mutex
  0x200044e0:
  - _ebss
  - end
  - __bss_end__
  0x20010000: _estack
  0xf1e0f85f: BootRAM
