interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_10000130:
    base_addr: 0xfffb000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10005000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: uart_example.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x129d8
symbols:
  0x0:
  - gcc_startup_nrf52.S.o
  - crtstuff.c
  - crt0.o
  - boards.c
  - app_error.c
  - app_error_weak.c
  - app_fifo.c
  - app_uart_fifo.c
  - app_util_platform.c
  - retarget.c
  - nrf_drv_uart.c
  - nrfx_prs.c
  - nrfx_uart.c
  - nrfx_uarte.c
  - main.c
  - system_nrf52.c
  - exit.c
  - init.c
  - printf.c
  - nano-vfprintf.c
  - wbuf.c
  - wsetup.c
  - nano-vfprintf_i.c
  - fflush.c
  - libc_a-memchr.o
  - findfp.c
  - stdio.c
  - readr.c
  - writer.c
  - fwalk.c
  - memset.c
  - freer.c
  - lock.c
  - makebuf.c
  - closer.c
  - mallocr.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - mlock.c
  - sbrkr.c
  - close.c
  - fstat.c
  - isatty.c
  - lseek.c
  - sbrk.c
  - _exit.c
  - crti.o
  - crtn.o
  - libc_a-strlen.o
  - crtstuff.c
  - impure.c
  - reent.c
  - __isr_vector
  0x80: DataInitFlashUsed
  0x201: deregister_tm_clones
  0x21d: register_tm_clones
  0x241: __do_global_dtors_aux
  0x269: frame_dummy
  0x28d: _stack_init
  0x295:
  - _mainCRTStartup
  - _start
  0x309: Reset_Handler
  0x331: NMI_Handler
  0x333: HardFault_Handler
  0x335: MemoryManagement_Handler
  0x337: BusFault_Handler
  0x339: UsageFault_Handler
  0x33b: SVC_Handler
  0x33d: DebugMon_Handler
  0x33f: PendSV_Handler
  0x341: SysTick_Handler
  0x343:
  - TIMER2_IRQHandler
  - RTC0_IRQHandler
  - SWI0_EGU0_IRQHandler
  - SWI2_EGU2_IRQHandler
  - GPIOTE_IRQHandler
  - PWM1_IRQHandler
  - POWER_CLOCK_IRQHandler
  - RADIO_IRQHandler
  - PDM_IRQHandler
  - TEMP_IRQHandler
  - QDEC_IRQHandler
  - TIMER3_IRQHandler
  - FPU_IRQHandler
  - SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQHandler
  - TIMER4_IRQHandler
  - I2S_IRQHandler
  - SWI4_EGU4_IRQHandler
  - TIMER0_IRQHandler
  - TIMER1_IRQHandler
  - PWM2_IRQHandler
  - ECB_IRQHandler
  - SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1_IRQHandler
  - Default_Handler
  - SAADC_IRQHandler
  - CCM_AAR_IRQHandler
  - WDT_IRQHandler
  - SWI5_EGU5_IRQHandler
  - RNG_IRQHandler
  - RTC2_IRQHandler
  - PWM0_IRQHandler
  - SWI3_EGU3_IRQHandler
  - RTC1_IRQHandler
  - SWI1_EGU1_IRQHandler
  - SPIM2_SPIS2_SPI2_IRQHandler
  - NFCT_IRQHandler
  - MWU_IRQHandler
  - COMP_LPCOMP_IRQHandler
  0x345: bsp_board_init
  0x3a1: app_error_handler_bare
  0x3c1: app_error_fault_handler
  0x3f1: app_fifo_init
  0x411: app_fifo_put
  0x441: app_fifo_get
  0x46d: uart_event_handler
  0x58d: app_uart_init
  0x675: app_uart_get
  0x6cd: app_uart_put
  0x741: app_util_critical_region_enter
  0x751: app_util_critical_region_exit
  0x765: _write
  0x781: _read
  0x795: uarte_evt_handler
  0x7c9: uart_evt_handler
  0x7fd: nrf_drv_uart_init
  0x871: UARTE0_UART0_IRQHandler
  0x87d: nrfx_prs_acquire
  0x8b9: nrfx_uart_0_irq_handler
  0xa89: nrfx_uart_init
  0xc25: nrfx_uart_tx
  0xcfd: nrfx_uart_tx_in_progress
  0xd15: nrfx_uart_rx
  0xe61: nrfx_uarte_0_irq_handler
  0xfd1: nrfx_uarte_init
  0x11a1: nrfx_uarte_tx
  0x124d: nrfx_uarte_tx_in_progress
  0x1269: nrfx_uarte_rx
  0x13ad: uart_error_handle
  0x13c1: pwcheck_success
  0x13d5: pwcheck_passed_1
  0x13e5: pwcheck_passed_2
  0x13f5: pwcheck_passed_3
  0x1405: pwcheck_passed_4
  0x1415: pwcheck_passed_5
  0x1425: pwcheck_passed_6
  0x1435: pwcheck_passed_7
  0x1445: pwcheck_passed_8
  0x1455: check_password
  0x14bd: main
  0x1551: SystemInit
  0x18c5: exit
  0x18e9: __libc_init_array
  0x1931:
  - printf
  - iprintf
  0x1955: __sfputc_r
  0x1983: __sfputs_r
  0x19a9:
  - _vfiprintf_r
  - _vfprintf_r
  0x1bd9: __swbuf_r
  0x1c55: __swsetup_r
  0x1d01: _printf_common
  0x1ddd: _printf_i
  0x2000:
  - Stack_Size
  - Heap_Size
  0x2019: __sflush_r
  0x2121: _fflush_r
  0x2171: memchr
  0x2211: std
  0x227d: stdio_exit_handler
  0x2295: cleanup_stdio
  0x22d5: global_stdio_init.part.0
  0x2311: __sfp_lock_acquire
  0x231d: __sfp_lock_release
  0x2329: __sinit
  0x2359: __sread
  0x237b: __swrite
  0x23b3: __sseek
  0x23d7: __sclose
  0x23e1: _read_r
  0x2405: _write_r
  0x2429: _fwalk_sglue
  0x2465: memset
  0x2475: _free_r
  0x2509: __retarget_lock_init_recursive
  0x250b: __retarget_lock_acquire_recursive
  0x250d: __retarget_lock_release_recursive
  0x250f: __swhatbuf_r
  0x255b: __smakebuf_r
  0x25d5: _close_r
  0x25f5: sbrk_aligned
  0x2639: _malloc_r
  0x2739: _fstat_r
  0x275d: _isatty_r
  0x277d: _lseek_r
  0x27a1: __malloc_lock
  0x27ad: __malloc_unlock
  0x27b9: _sbrk_r
  0x27d9: _close
  0x27e9: _fstat
  0x27f9: _isatty
  0x2809: _lseek
  0x2819: _sbrk
  0x2835: _exit
  0x2839: _init
  0x2845: _fini
  0x28d8: __EH_FRAME_BEGIN__
  0x2950: __FRAME_END__
  0x2954: __exidx_start
  0x295c:
  - __exidx_end
  - __etext
  - CodeFlashUsed
  0x29dc: TotalFlashUsed
  0x20000000:
  - app_uart_inst
  - __data_start__
  0x20000014: SystemCoreClock
  0x20000018: _impure_ptr
  0x2000001c: _impure_data
  0x20000068: __sglue
  0x20000074:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20000078:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x2000007c:
  - __TMC_END__
  - __data_end__
  0x20000080:
  - completed.1
  - __bss_start__
  0x20000084: object.0
  0x2000009c: m_tx_fifo
  0x200000ac: m_rx_fifo
  0x200000bc: m_rx_ovf
  0x200000c0: rx_buffer
  0x200000c4: tx_buffer
  0x200000c8: m_event_handler
  0x200000cc: m_in_critical_region
  0x200000d0: nrf_drv_uart_use_easy_dma
  0x200000d4: m_contexts
  0x200000d8: m_handlers
  0x200000dc: m_prs_box_4
  0x200000e8: m_cb
  0x20000118: m_cb
  0x2000013c: tx_buf.0
  0x20000144: rx_buf.1
  0x2000014c: dma_buf
  0x20000154: num_correct
  0x20000158: __sf
  0x20000290: __stdio_exit_handler
  0x20000294: __lock___malloc_recursive_mutex
  0x20000295: __lock___sfp_recursive_mutex
  0x20000298: errno
  0x2000029c: __malloc_sbrk_start
  0x200002a0: __malloc_free_list
  0x200002a4: heap_end.0
  0x200002a8:
  - __HeapBase
  - end
  - __bss_end__
  - __end__
  0x200022a8: __HeapLimit
  0x2000e000: __StackLimit
  0x20010000:
  - __StackTop
  - __stack
