interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_I2C_TwoBoards_ComDMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x11e08
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - stm32f1xx_nucleo.c
  - system_stm32f1xx.c
  - stm32f1xx_hal.c
  - stm32f1xx_hal_cortex.c
  - stm32f1xx_hal_dma.c
  - stm32f1xx_hal_gpio.c
  - stm32f1xx_hal_i2c.c
  - stm32f1xx_hal_rcc.c
  - main.c
  - stm32f1xx_hal_msp.c
  - stm32f1xx_it.c
  - init.c
  - memset.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: BSP_LED_Init
  0x800019d: BSP_LED_Toggle
  0x80001ad: SystemInit
  0x80001f9: HAL_MspInit
  0x80001fd: HAL_InitTick
  0x8000241: HAL_Init
  0x8000265: HAL_IncTick
  0x800027d: HAL_GetTick
  0x8000289: HAL_Delay
  0x8000291: HAL_NVIC_SetPriorityGrouping
  0x80002b5: HAL_NVIC_SetPriority
  0x800031d: HAL_NVIC_EnableIRQ
  0x8000335: HAL_SYSTICK_Config
  0x8000361: HAL_DMA_Init
  0x80003c1: HAL_DMA_Start_IT
  0x800043d: HAL_DMA_Abort_IT
  0x80004cd: HAL_DMA_IRQHandler
  0x80005f5: HAL_GPIO_Init
  0x80007b5: HAL_GPIO_WritePin
  0x80007bf: HAL_GPIO_TogglePin
  0x80007c9: HAL_I2C_Init
  0x80008c9: HAL_I2C_Slave_Transmit_DMA
  0x80009ad: HAL_I2C_Slave_Receive_DMA
  0x8000a91: HAL_I2C_MasterTxCpltCallback
  0x8000a93: HAL_I2C_MasterRxCpltCallback
  0x8000a95: HAL_I2C_AddrCallback
  0x8000a97: HAL_I2C_ListenCpltCallback
  0x8000a99: HAL_I2C_MemTxCpltCallback
  0x8000a9b: HAL_I2C_MemRxCpltCallback
  0x8000a9d: I2C_DMAError
  0x8000ac7: I2C_DMAXferCplt
  0x8000b47: HAL_I2C_AbortCpltCallback
  0x8000b49: I2C_ITError
  0x8000c71: HAL_I2C_EV_IRQHandler
  0x8001341: HAL_I2C_ER_IRQHandler
  0x800147d: I2C_DMAAbort
  0x80014c9: HAL_I2C_GetState
  0x80014d1: HAL_RCC_OscConfig
  0x80017e9: HAL_RCC_GetSysClockFreq
  0x800185d: HAL_RCC_ClockConfig
  0x80019bd: HAL_RCC_GetPCLK1Freq
  0x80019dd: Reset_Handler
  0x80019e0: CopyDataInit
  0x80019e8: LoopCopyDataInit
  0x80019f6: FillZerobss
  0x80019fc: LoopFillZerobss
  0x8001a24:
  - Infinite_Loop
  - Default_Handler
  0x8001a25:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - DMA1_Channel4_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI15_10_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - DMA1_Channel5_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - USBWakeUp_IRQHandler
  0x8001a27: Error_Handler
  0x8001a39: SystemClock_Config
  0x8001a89: main
  0x8001b35: HAL_I2C_SlaveTxCpltCallback
  0x8001b3b: HAL_I2C_SlaveRxCpltCallback
  0x8001b41: HAL_I2C_ErrorCallback
  0x8001b49: HAL_I2C_MspInit
  0x8001c79: NMI_Handler
  0x8001c7b: HardFault_Handler
  0x8001c7d: MemManage_Handler
  0x8001c7f: BusFault_Handler
  0x8001c81: UsageFault_Handler
  0x8001c83: SVC_Handler
  0x8001c85: DebugMon_Handler
  0x8001c87: PendSV_Handler
  0x8001c89: SysTick_Handler
  0x8001c8d: I2C1_EV_IRQHandler
  0x8001c99: I2C1_ER_IRQHandler
  0x8001ca5: DMA1_Channel7_IRQHandler
  0x8001cb1: DMA1_Channel6_IRQHandler
  0x8001cbd: __libc_init_array
  0x8001d05: memset
  0x8001d14: __EH_FRAME_BEGIN__
  0x8001d15: _init
  0x8001d21: _fini
  0x8001d2c:
  - _etext
  - AHBPrescTable
  0x8001d3c: APBPrescTable
  0x8001d54:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8001d58:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8001d5c: _sidata
  0x20000000:
  - _sdata
  - LED_PORT
  0x20000004: BUTTON_PORT
  0x20000008: SystemCoreClock
  0x2000000c: uwTickFreq
  0x20000010: uwTickPrio
  0x20000014: aTxBuffer
  0x200000ac:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x200000b0: object.8660
  0x200000c8: hdma_tx.6747
  0x2000010c: hdma_rx.6748
  0x20000150: hdma_tx.6756
  0x20000194: hdma_rx.6757
  0x200001d8: uwTick
  0x200001dc: aRxBuffer
  0x20000274: I2cHandle
  0x200002c8:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
