interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_I2C_TwoBoards_MasterTx_SlaveRx_DMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x10884
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - system_stm32f1xx.c
  - stm32f1xx_ll_rcc.c
  - stm32f1xx_ll_utils.c
  - main.c
  - stm32f1xx_it.c
  - init.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: SystemInit
  0x8000199: RCC_GetHCLKClockFreq
  0x80001b1: RCC_GetPCLK1ClockFreq
  0x80001c9: RCC_GetPCLK2ClockFreq
  0x80001e1: RCC_PLL_GetFreqDomain_SYS
  0x8000215: RCC_GetSystemClockFreq
  0x8000231: LL_RCC_GetSystemClocksFreq
  0x8000251: LL_Init1msTick
  0x800026d: LL_mDelay
  0x8000281: LL_SetSystemCoreClock
  0x800028d: Reset_Handler
  0x8000290: CopyDataInit
  0x8000298: LoopCopyDataInit
  0x80002a6: FillZerobss
  0x80002ac: LoopFillZerobss
  0x80002d4:
  - Infinite_Loop
  - Default_Handler
  0x80002d5:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - DMA1_Channel4_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - DMA1_Channel5_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x80002d9: LL_APB2_GRP1_EnableClock
  0x80002f5: LL_GPIO_SetPinMode
  0x8000325: Configure_DMA
  0x8000409: Configure_I2C_Master
  0x8000585: Activate_I2C_Master
  0x8000595: LED_Init
  0x80005b1: LED_Blinking
  0x80005d1: UserButton_Init
  0x800063d: Handle_I2C_Master
  0x80006b5: SystemClock_Config
  0x8000745: main
  0x8000771: UserButton_Callback
  0x800077d: DMA1_Transfer_Complete_Callback
  0x8000789: DMA1_Transfer_Error_Callback
  0x80007a1: NMI_Handler
  0x80007a3: HardFault_Handler
  0x80007a5: MemManage_Handler
  0x80007a7: BusFault_Handler
  0x80007a9: UsageFault_Handler
  0x80007ab: SVC_Handler
  0x80007ad: DebugMon_Handler
  0x80007af: PendSV_Handler
  0x80007b1: SysTick_Handler
  0x80007b5: EXTI15_10_IRQHandler
  0x80007cd: DMA1_Channel6_IRQHandler
  0x80007f1: __libc_init_array
  0x8000838: __EH_FRAME_BEGIN__
  0x8000839: _init
  0x8000845: _fini
  0x8000850:
  - _etext
  - AHBPrescTable
  0x8000860: APBPrescTable
  0x8000868:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x800086c:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8000870: _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: ubNbDataToTransmit
  0x20000008: pTransmitBuffer
  0x2000000c: ubNbDataToReceive
  0x2000000d: aLedOn
  0x20000014:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x20000018: object.8660
  0x20000030: aReceiveBuffer
  0x20000037: ubMasterTransferComplete
  0x20000038: ubButtonPress
  0x20000039: ubSlaveTransferComplete
  0x2000003c:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
