interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_ADC_SingleConversion_TriggerTimer_DMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x107cc
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - system_stm32f1xx.c
  - stm32f1xx_ll_utils.c
  - main.c
  - stm32f1xx_it.c
  - init.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: SystemInit
  0x8000199: LL_Init1msTick
  0x80001b5: LL_mDelay
  0x80001c9: LL_SetSystemCoreClock
  0x80001d5: Reset_Handler
  0x80001d8: CopyDataInit
  0x80001e0: LoopCopyDataInit
  0x80001ee: FillZerobss
  0x80001f4: LoopFillZerobss
  0x800021c:
  - Infinite_Loop
  - Default_Handler
  0x800021d:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - DMA1_Channel4_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - DMA1_Channel5_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x8000221: LL_APB2_GRP1_EnableClock
  0x800023d: LL_GPIO_SetPinMode
  0x800026d: Configure_DMA
  0x80002f5: Configure_TIM_TimeBase_ADC_trigger
  0x8000379: Configure_ADC
  0x800045d: Activate_ADC
  0x8000499: LED_Init
  0x80004b5: LED_Blinking
  0x80004d5: UserButton_Init
  0x8000551: SystemClock_Config
  0x80005e1: main
  0x8000619: UserButton_Callback
  0x8000649: AdcDmaTransferComplete_Callback
  0x800068d: AdcDmaTransferHalf_Callback
  0x80006d1: AdcDmaTransferError_Callback
  0x80006db: NMI_Handler
  0x80006dd: HardFault_Handler
  0x80006df: MemManage_Handler
  0x80006e1: BusFault_Handler
  0x80006e3: UsageFault_Handler
  0x80006e5: SVC_Handler
  0x80006e7: DebugMon_Handler
  0x80006e9: PendSV_Handler
  0x80006eb: SysTick_Handler
  0x80006ed: EXTI15_10_IRQHandler
  0x8000709: DMA1_Channel1_IRQHandler
  0x8000745: __libc_init_array
  0x800078c: __EH_FRAME_BEGIN__
  0x800078d: _init
  0x8000799: _fini
  0x80007a4:
  - _etext
  - AHBPrescTable
  0x80007b4: APBPrescTable
  0x80007bc:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x80007c0:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x80007c4: _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: ubDmaTransferStatus
  0x20000008:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x2000000c: object.8660
  0x20000024: aADCxConvertedData_Voltage_mVolt
  0x200000a4: aADCxConvertedData
  0x20000124:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
