interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_USART_SyncCommunication_FullDuplex_DMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x10bb0
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - system_stm32f1xx.c
  - stm32f1xx_ll_utils.c
  - main.c
  - stm32f1xx_it.c
  - init.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: SystemInit
  0x8000199: LL_Init1msTick
  0x80001b5: LL_mDelay
  0x80001c9: LL_SetSystemCoreClock
  0x80001d5: Reset_Handler
  0x80001d8: CopyDataInit
  0x80001e0: LoopCopyDataInit
  0x80001ee: FillZerobss
  0x80001f4: LoopFillZerobss
  0x800021c:
  - Infinite_Loop
  - Default_Handler
  0x800021d:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x8000221: LL_APB2_GRP1_EnableClock
  0x800023d: LL_GPIO_SetPinMode
  0x800026d: LL_DMA_ConfigAddresses.constprop.6
  0x8000291: LL_DMA_DisableChannel.constprop.9
  0x80002b1: LL_GPIO_SetPinOutputType.constprop.15
  0x80002d3: LL_GPIO_SetPinSpeed.constprop.16
  0x8000301: Configure_USART1_DMA
  0x80003e5: Configure_SPI1_DMA
  0x80004cd: Configure_USART1
  0x80005f5: Configure_SPI1
  0x8000711: Activate_SPI1
  0x800073d: StartTransfers
  0x8000771: LED_Init
  0x800078d: LED_Blinking
  0x80007a9: UserButton_Init
  0x8000815: Buffercmp8
  0x8000839: WaitAndCheckEndOfTransfer
  0x80008b5: SystemClock_Config
  0x8000945: main
  0x800097d: UserButton_Callback
  0x8000989: USART1_DMA1_TransmitComplete_Callback
  0x8000995: SPI1_DMA1_TransmitComplete_Callback
  0x80009a1: USART1_DMA1_ReceiveComplete_Callback
  0x80009ad: SPI1_DMA1_ReceiveComplete_Callback
  0x80009b9: USART_TransferError_Callback
  0x80009cf: SPI_TransferError_Callback
  0x80009e5: NMI_Handler
  0x80009e7: HardFault_Handler
  0x80009e9: MemManage_Handler
  0x80009eb: BusFault_Handler
  0x80009ed: UsageFault_Handler
  0x80009ef: SVC_Handler
  0x80009f1: DebugMon_Handler
  0x80009f3: PendSV_Handler
  0x80009f5: SysTick_Handler
  0x80009f9: EXTI15_10_IRQHandler
  0x8000a11: DMA1_Channel4_IRQHandler
  0x8000a35: DMA1_Channel5_IRQHandler
  0x8000a59: DMA1_Channel3_IRQHandler
  0x8000a7d: DMA1_Channel2_IRQHandler
  0x8000a9d: __libc_init_array
  0x8000ae4: __EH_FRAME_BEGIN__
  0x8000ae5: _init
  0x8000af1: _fini
  0x8000afc:
  - CHANNEL_OFFSET_TAB
  - _etext
  0x8000b04:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8000b08:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8000b0c: _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: aUSART1TxBuffer
  0x20000052: ubUSART1NbDataToTransmit
  0x20000053: ubUSART1NbDataToReceive
  0x20000054: aSPI1TxBuffer
  0x200000a2: ubSPI1NbDataToTransmit
  0x200000a3: ubSPI1NbDataToReceive
  0x200000a4:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x200000a8: object.8660
  0x200000c0: ubUSART1TransmissionComplete
  0x200000c1: ubSPI1TransmissionComplete
  0x200000c2: ubUSART1ReceptionComplete
  0x200000c3: ubSPI1ReceptionComplete
  0x200000c4: ubButtonPress
  0x200000c5: aUSART1RxBuffer
  0x20000113: aSPI1RxBuffer
  0x20000164:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
