interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_UART_TwoBoards_ComDMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x11918
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - stm32f1xx_nucleo.c
  - system_stm32f1xx.c
  - stm32f1xx_hal.c
  - stm32f1xx_hal_cortex.c
  - stm32f1xx_hal_dma.c
  - stm32f1xx_hal_gpio.c
  - stm32f1xx_hal_rcc.c
  - stm32f1xx_hal_uart.c
  - main.c
  - stm32f1xx_hal_msp.c
  - stm32f1xx_it.c
  - init.c
  - memset.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: BSP_LED_Init
  0x800019d: BSP_LED_On
  0x80001b1: BSP_LED_Off
  0x80001c5: BSP_LED_Toggle
  0x80001d5: BSP_PB_Init
  0x8000249: SystemInit
  0x8000295: HAL_MspInit
  0x8000299: HAL_InitTick
  0x80002dd: HAL_Init
  0x8000301: HAL_IncTick
  0x8000319: HAL_GetTick
  0x8000325: HAL_Delay
  0x800032d: HAL_NVIC_SetPriorityGrouping
  0x8000351: HAL_NVIC_SetPriority
  0x80003b9: HAL_NVIC_EnableIRQ
  0x80003d1: HAL_NVIC_DisableIRQ
  0x80003ed: HAL_SYSTICK_Config
  0x8000419: HAL_DMA_Init
  0x8000479: HAL_DMA_DeInit
  0x80004cd: HAL_DMA_Start_IT
  0x8000549: HAL_DMA_Abort_IT
  0x80005d9: HAL_DMA_IRQHandler
  0x8000701: HAL_GPIO_Init
  0x80008c1: HAL_GPIO_DeInit
  0x80009a1: HAL_GPIO_WritePin
  0x80009ab: HAL_GPIO_TogglePin
  0x80009b5: HAL_GPIO_EXTI_IRQHandler
  0x80009cd: HAL_RCC_OscConfig
  0x8000ce5: HAL_RCC_GetSysClockFreq
  0x8000d59: HAL_RCC_ClockConfig
  0x8000eb9: HAL_RCC_GetPCLK1Freq
  0x8000ed9: HAL_RCC_GetPCLK2Freq
  0x8000ef9: UART_EndRxTransfer
  0x8000f15: UART_SetConfig
  0x8001051: HAL_UART_Init
  0x80010ad: HAL_UART_DeInit
  0x80010d5: HAL_UART_Transmit_DMA
  0x8001149: HAL_UART_Receive_DMA
  0x80011d9: UART_DMATransmitCplt
  0x8001205: HAL_UART_TxHalfCpltCallback
  0x8001207: UART_DMATxHalfCplt
  0x8001211: UART_DMAReceiveCplt
  0x8001249: UART_Receive_IT
  0x80012bf: HAL_UART_RxHalfCpltCallback
  0x80012c1: UART_DMARxHalfCplt
  0x80012cb: UART_DMAError
  0x8001319: HAL_UART_IRQHandler
  0x8001459: UART_DMAAbortOnError
  0x8001469: Reset_Handler
  0x800146c: CopyDataInit
  0x8001474: LoopCopyDataInit
  0x8001482: FillZerobss
  0x8001488: LoopFillZerobss
  0x80014b0:
  - Infinite_Loop
  - Default_Handler
  0x80014b1:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x80014b3: Error_Handler
  0x80014cb: SystemClock_Config
  0x800151d: main
  0x80015ed: HAL_UART_TxCpltCallback
  0x80015f9: HAL_UART_RxCpltCallback
  0x8001605: HAL_UART_ErrorCallback
  0x800160d: HAL_GPIO_EXTI_Callback
  0x8001621: HAL_UART_MspInit
  0x8001735: HAL_UART_MspDeInit
  0x8001789: NMI_Handler
  0x800178b: HardFault_Handler
  0x800178d: MemManage_Handler
  0x800178f: BusFault_Handler
  0x8001791: UsageFault_Handler
  0x8001793: SVC_Handler
  0x8001795: DebugMon_Handler
  0x8001797: PendSV_Handler
  0x8001799: SysTick_Handler
  0x800179d: DMA1_Channel5_IRQHandler
  0x80017a9: DMA1_Channel4_IRQHandler
  0x80017b5: USART1_IRQHandler
  0x80017c1: EXTI15_10_IRQHandler
  0x80017c9: __libc_init_array
  0x8001811: memset
  0x8001820: __EH_FRAME_BEGIN__
  0x8001821: _init
  0x800182d: _fini
  0x8001838:
  - _etext
  - AHBPrescTable
  0x8001848: APBPrescTable
  0x8001860:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8001864:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8001868: _sidata
  0x20000000:
  - _sdata
  - LED_PORT
  0x20000004: BUTTON_PORT
  0x20000008: SystemCoreClock
  0x2000000c: uwTickFreq
  0x20000010: uwTickPrio
  0x20000014: aTxBuffer
  0x200000b0:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x200000b4: object.8660
  0x200000cc: UserButtonStatus
  0x200000d0: UartReady
  0x200000d4: hdma_tx.6522
  0x20000118: hdma_rx.6523
  0x2000015c: uwTick
  0x20000160: UartHandle
  0x200001a0: aRxBuffer
  0x2000023c:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
