interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: ARDUINO-SAM3-Serial.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x151bc
symbols:
  0x0:
  - startup_sam3xa.c
  - crtstuff.c
  - Serial.ino.cpp
  - variant.cpp
  - pio.c
  - pmc.c
  - system_sam3xa.c
  - adc.c
  - uotghs.c
  - WInterrupts.c
  - cortex_handlers.c
  - hooks.c
  - syscalls_sam3.c
  - wiring_analog.c
  - wiring_digital.c
  - Print.cpp
  - Reset.cpp
  - RingBuffer.cpp
  - Stream.cpp
  - UARTClass.cpp
  - USARTClass.cpp
  - main.cpp
  - watchdog.cpp
  - wiring.c
  - timetick.c
  - wdt.c
  - init.c
  - iprintf.c
  - malloc.c
  - mallocr.c
  - lib_a-memcpy.o
  - memmove.c
  - memset.c
  - mlock.c
  - mallocr.c
  - sbrkr.c
  - strlen.c
  - syskill.c
  - vfprintf.c
  - wsetup.c
  - __call_atexit.c
  - atexit.c
  - fflush.c
  - findfp.c
  - fini.c
  - fputwc.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - locale.c
  - makebuf.c
  - memchr-stub.c
  - signalr.c
  - stdio.c
  - wbuf.c
  - wcrtomb.c
  - wctomb_r.c
  - writer.c
  - __atexit.c
  - closer.c
  - fclose.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - readr.c
  - _aeabi_uldivmod.o
  - bpabi.c
  - _dvmd_tls.o
  - libgcc2.c
  - libgcc2.c
  - impure.c
  - /home/bo/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crti.o
  - /home/bo/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/armv7-m/crtn.o
  - reent.c
  - __bss_start__
  - __bss_end__
  - software_init_hook
  - hardware_init_hook
  - __stack
  - __deregister_frame_info
  - __libc_fini
  - _Jv_RegisterClasses
  - __register_frame_info
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: setup
  0x80159: loop
  0x801a1: _Z11serialEventv
  0x801a5: UART_Handler
  0x801b1: _Z12serialEvent1v
  0x801b3: _Z12serialEvent2v
  0x801b5: _Z12serialEvent3v
  0x801b9: USART0_Handler
  0x801c5: USART1_Handler
  0x801d1: USART3_Handler
  0x801dd: init
  0x80305: _GLOBAL__sub_I_g_APinDescription
  0x803d9: _Z14serialEventRunv
  0x8041d: PIO_PullUp
  0x80427: PIO_SetPeripheral
  0x8044d: PIO_SetInput
  0x80473: PIO_SetOutput
  0x80499: PIO_Configure
  0x804fd: PIO_GetOutputDataStatus
  0x80511: pmc_enable_periph_clk
  0x80555: pmc_disable_periph_clk
  0x80595: SystemInit
  0x8061d: Reset_Handler
  0x80695: adc_init
  0x8072d: adc_configure_trigger
  0x8073b: adc_configure_timing
  0x80755: adc_disable_channel
  0x8075f: adc_disable_all_channel
  0x80767: adc_disable_interrupt
  0x8076d: UOTGHS_Handler
  0x8077d: PIOA_Handler
  0x807b5: PIOB_Handler
  0x807ed: PIOC_Handler
  0x80825: PIOD_Handler
  0x8085d:
  - __halt
  - DACC_Handler
  - DebugMon_Handler
  - DMAC_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - TWI1_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - TWI0_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - TC8_Handler
  - USART2_Handler
  - EMAC_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - SPI0_Handler
  0x8085f: SVC_Handler
  0x80863: PendSV_Handler
  0x80867: SysTick_Handler
  0x8087d:
  - __false
  - sysTickHook
  0x80881:
  - __halt
  - pendSVHook
  - svcHook
  0x80885: _sbrk
  0x808a1: link
  0x808a7: _close
  0x808ad: _fstat
  0x808b7: _isatty
  0x808bb: _lseek
  0x808bf: _read
  0x808c5: _write
  0x808e9: _exit
  0x808f9: _kill
  0x808fb: _getpid
  0x80901: analogOutputInit
  0x80905: pinMode
  0x80a0d: digitalWrite
  0x80a7d: _ZN5Print5writeEPKhj
  0x80a9f: _ZN5Print5writeEPKc
  0x80abd: _ZN5Print5printEc
  0x80ac7: _ZN5Print11printNumberEmh
  0x80b05: _ZN5Print5printEli
  0x80b41: _ZN5Print5printEii
  0x80b45: tickReset
  0x80b65:
  - _ZN10RingBufferC1Ev
  - _ZN10RingBufferC2Ev
  0x80b7f: _ZN10RingBuffer10store_charEh
  0x80b9d: _ZN6Stream9timedPeekEv
  0x80bc9: _ZN6Stream13peekNextDigitE13LookaheadModeb
  0x80c1d: _ZN6Stream8parseIntE13LookaheadModec
  0x80c75: _ZN9UARTClasscvbEv
  0x80c79: _ZN9UARTClass9availableEv
  0x80c8b: _ZN9UARTClass4peekEv
  0x80ca7: _ZN9UARTClass4readEv
  0x80cd1: _ZN9UARTClass5flushEv
  0x80ce9: _ZN9UARTClass5writeEh
  0x80d3d: _ZN9UARTClass3endEv
  0x80d79:
  - _ZN9UARTClassC1EP4Uart4IRQnmP10RingBufferS4_
  - _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x80d9d: _ZN9UARTClass4initEmm
  0x80e0d: _ZN9UARTClass5beginEm
  0x80e15: _ZN9UARTClass10IrqHandlerEv
  0x80e5f: _ZN10USARTClass5beginEm
  0x80e69:
  - _ZN10USARTClassC1EP5Usart4IRQnmP10RingBufferS4_
  - _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x80e8d: initVariant
  0x80e91: main
  0x80ebd:
  - _Z13watchdogSetupv
  - _watchdogDefaultSetup
  0x80ec9: millis
  0x80ecd: delay
  0x80ed1: TimeTick_Increment
  0x80ee1: GetTickCount
  0x80eed: WDT_Disable
  0x80ef5: __libc_init_array
  0x80f45: iprintf
  0x80f6d: malloc
  0x80f7d: _malloc_r
  0x814b5: memcpy
  0x815a1: memmove
  0x8166d: memset
  0x81701: __malloc_lock
  0x81705: __malloc_unlock
  0x81709: _realloc_r
  0x81ac9: _sbrk_r
  0x81aed: strlen
  0x81b4d: kill
  0x81b5d: __sprint_r.part.0
  0x81bd5: _vfiprintf_r
  0x82829: __sbprintf
  0x828a5: __swsetup_r
  0x82969: register_fini
  0x8297d: atexit
  0x82989: __sflush_r
  0x82ad1: _fflush_r
  0x82afd: _cleanup_r
  0x82b09: __sinit
  0x82bfd: __sfp_lock_acquire
  0x82c01: __sfp_lock_release
  0x82c05: __libc_fini_array
  0x82c35: _fputwc_r
  0x82cf5: _malloc_trim_r
  0x82d91: _free_r
  0x82f29: __sfvwrite_r
  0x8323d: _fwalk
  0x83285: __locale_charset
  0x8328d: __locale_mb_cur_max
  0x83299: __smakebuf_r
  0x83379: memchr
  0x8340d: _kill_r
  0x83435: __sread
  0x83459: __swrite
  0x83491: __sseek
  0x834b1: __sclose
  0x834b9: __swbuf_r
  0x83561: _wcrtomb_r
  0x835b1: __ascii_wctomb
  0x835cd: _write_r
  0x835f5: __register_exitproc
  0x8369d: _close_r
  0x836c1: _fclose_r
  0x83741: fclose
  0x83751: _fstat_r
  0x83779: _isatty_r
  0x8379d: _lseek_r
  0x837c5: _read_r
  0x837ed: __aeabi_uldivmod
  0x83819: __gnu_ldivmod_helper
  0x83849: __gnu_uldivmod_helper
  0x83879:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x8387d: __divdi3
  0x83b1d: __udivdi3
  0x83dac: g_APinDescription
  0x84838: _ZTV9UARTClass
  0x84868: _ZTV10USARTClass
  0x8489c: _global_impure_ptr
  0x848a0: blanks.6717
  0x848e0: zeroes.6718
  0x848f1: _init
  0x848fc:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x84900: __frame_dummy_init_array_entry
  0x84908: __init_array_end
  0x84909: _fini
  0x84914:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x84918:
  - __fini_array_end
  - _efixed
  0x84920: _etext
  0x20070000: _srelocate
  0x20070001: banzai
  0x2007002c: SystemCoreClock
  0x20070030: _ZL5ticks
  0x20070038: impure_data
  0x20070460: _impure_ptr
  0x20070464: __malloc_av_
  0x2007086c: __malloc_trim_threshold
  0x20070870: __malloc_sbrk_base
  0x20070874: lc_ctype_charset
  0x20070894: __mb_cur_max
  0x20070898: __wctomb
  0x2007089c:
  - completed.7857
  - _sbss
  - _szero
  - _erelocate
  0x200708a0: object.7862
  0x200708b8: tx_buffer2
  0x20070940: tx_buffer1
  0x200709c8: Serial
  0x200709ec: rx_buffer1
  0x20070a74: Serial1
  0x20070a9c: Serial2
  0x20070ac4: Serial3
  0x20070aec: tx_buffer3
  0x20070b74: tx_buffer4
  0x20070bfc: g_pinStatus
  0x20070c4c: rx_buffer2
  0x20070cd4: rx_buffer3
  0x20070d5c: rx_buffer4
  0x20070de4: gpf_isr
  0x20070de8: callbacksPioA
  0x20070e68: callbacksPioB
  0x20070ee8: callbacksPioC
  0x20070f68: callbacksPioD
  0x20070fe8: heap.6420
  0x20070fec: _dwTickCount
  0x20070ff0: __malloc_max_total_mem
  0x20070ff4: __malloc_max_sbrked_mem
  0x20070ff8: __malloc_top_pad
  0x20070ffc: __malloc_current_mallinfo
  0x20071024: errno
  0x20071028:
  - _ebss
  - _ezero
  - _end
  0x20088000:
  - __StackTop
  - __StackLimit
  - _estack
