interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_ChibiOS_UART.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x120e4
symbols:
  0x0:
  - build/obj/vectors.o
  - build/obj/crt0_v7m.o
  - build/obj/chcoreasm_v7m.o
  - __flash1_end__
  - __flash6_free__
  - __flash6_start__
  - __ram4_start__
  - __flash7_free__
  - __ram5_clear__
  - __ram1_free__
  - __ram6_start__
  - __ram5_end__
  - __ram5_noinit__
  - __flash1_free__
  - __ram5_size__
  - __flash7_size__
  - __flash4_free__
  - __ram1_size__
  - __flash3_free__
  - __ram1_clear__
  - __flash2_start__
  - __flash4_start__
  - __ram7_free__
  - __ram4_size__
  - __ram1_end__
  - __ram4_end__
  - __flash5_end__
  - __flash2_free__
  - __flash2_end__
  - __flash4_size__
  - __flash5_free__
  - __flash5_start__
  - __ram4_clear__
  - __ram5_free__
  - __flash6_end__
  - __ram3_clear__
  - __ram6_end__
  - __ram6_init__
  - __ram7_init__
  - __ram6_free__
  - __ram2_noinit__
  - __flash3_start__
  - __ram6_noinit__
  - __ram4_init__
  - __ram7_clear__
  - __ram7_size__
  - __ram4_noinit__
  - __ram7_start__
  - __ram6_clear__
  - __flash3_end__
  - __ram3_size__
  - __ram2_clear__
  - __ram3_end__
  - __ram2_size__
  - __ram1_start__
  - __flash3_size__
  - __ram6_size__
  - __flash5_size__
  - __ram3_free__
  - __flash3_init__
  - __flash6_init__
  - __ram1_noinit__
  - __flash2_size__
  - __flash4_end__
  - __ram2_init__
  - __ram2_end__
  - __ram3_noinit__
  - __flash7_start__
  - __ram2_start__
  - __ram7_end__
  - __flash5_init__
  - __flash1_start__
  - __ram5_init__
  - __flash7_init__
  - __flash1_size__
  - __ram3_init__
  - __ram1_init__
  - __ram5_start__
  - __flash6_size__
  - __ram2_free__
  - __ram4_free__
  - __ram7_noinit__
  - __flash2_init__
  - __flash4_init__
  - __ram3_start__
  - __flash1_init__
  - __flash7_end__
  0x400:
  - __main_stack_size__
  - __process_stack_size__
  0x4480: crt1.c.4c2233fd
  0x47dd: hal.c.ecfc2d5e
  0x5000: __ram0_size__
  0x5895: hal_st.c.67f64f9e
  0x6b7a: hal_buffers.c.cf5ee2ef
  0x8c7b: hal_pal.c.93a1fa44
  0x9ee7: hal_uart.c.874b58d4
  0xb2cc: nvic.c.2ecc06b5
  0xc6f0: stm32_isr.c.13df472e
  0xd8ee: hal_lld.c.74113ad0
  0xeb1e: stm32_dma.c.6e2e77ed
  0xffc4: hal_pal_lld.c.8af9dd06
  0x11267: hal_st_lld.c.928be097
  0x125d8: hal_uart_lld.c.23b8c2fd
  0x13a11: board.c.53dd3c97
  0x14ad0: chsys.c.889f7c54
  0x162c1: chdebug.c.42c994fc
  0x16f36: chtrace.c.e6312999
  0x17fc4: chvt.c.d33472cd
  0x18ea2: chschd.c.ff8954e7
  0x19dfd: chthreads.c.5c5d36f5
  0x1b406: chtm.c.ac61778f
  0x1c289: chregistry.c.de15179d
  0x1d864: chmtx.c.b5d6bd66
  0x1e7ba: chdynamic.c.8133e5db
  0x1f667: chmemcore.c.95acfe16
  0x20000: __flash0_size__
  0x20393: chmemheaps.c.b6c60cd3
  0x2125d: chmempools.c.f12ead9a
  0x221dc: chfactory.c.b9677356
  0x240ab: chcore_v7m.c.adf4d9bf
  0x24f74: main.c.32d9c066
  0x8000000:
  - _vectors
  - __flash0_start__
  0x8000160:
  - __fini_array_end
  - __text_base
  - __fini_array_start
  - __init_array_end
  - __init_array_start
  0x8000161: _crt0_entry
  0x8000194: msloop
  0x80001a2: psloop
  0x80001b2: dloop
  0x80001c6: bloop
  0x80001dc: initloop
  0x80001e8: endinitloop
  0x80001f0: finiloop
  0x80001fc: endfiniloop
  0x8000239: Reset_Handler
  0x800023b:
  - Vector58
  - VectorE8
  - Vector9C
  - VectorAC
  - DebugMon_Handler
  - Vector5C
  - Vector11C
  - HardFault_Handler
  - Vector8C
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - Vector110
  - Vector120
  - VectorC8
  - Vector94
  - VectorA8
  - VectorB4
  - UsageFault_Handler
  - VectorEC
  - Vector40
  - VectorF8
  - Vector108
  - VectorBC
  - Vector150
  - Vector124
  - Vector148
  - Vector118
  - Vector64
  - VectorCC
  - Vector54
  - Vector98
  - Vector138
  - Vector24
  - VectorD0
  - Vector140
  - VectorE4
  - VectorC0
  - Vector158
  - Vector130
  - Vector134
  - VectorF0
  - Vector12C
  - Vector13C
  - Vector100
  - VectorE0
  - VectorF4
  - MemManage_Handler
  - VectorA0
  - VectorC4
  - Vector90
  - Vector114
  - Vector60
  - Vector1C
  - Vector48
  - Vector4C
  - Vector144
  - Vector15C
  - Vector68
  - Vector88
  - Vector104
  - Vector10C
  - Vector14C
  - BusFault_Handler
  - Vector50
  - Vector154
  - Vector44
  - Vector28
  - VectorB8
  - VectorFC
  - Vector34
  - Vector128
  - VectorA4
  - Vector20
  0x800023e: .stay
  0x800023f: _unhandled_exception
  0x8000241: _port_switch
  0x8000251: _port_thread_start
  0x8000265: _port_switch_from_isr
  0x8000270: _port_exit_from_isr
  0x8000281: uart_lld_start_send.constprop.0
  0x80002c1: chTMStartMeasurementX.constprop.0
  0x80002d1: rxend
  0x80002e1: ledoff
  0x80002f1: rxerr
  0x8000301: txend1
  0x8000311: _port_irq_epilogue
  0x8000371: chTMStopMeasurementX
  0x80003c1: trace_next
  0x8000401: _trace_switch.part.0
  0x8000421: _trace_isr_leave
  0x8000451: _trace_isr_enter
  0x8000481: chSysHalt
  0x80004b1: uart_lld_serve_tx_end_irq
  0x8000501: chDbgCheckClassS
  0x8000521: chDbgCheckClassI
  0x8000541: dmaStreamAllocI.constprop.0
  0x8000611: chCoreAllocAlignedWithOffsetI
  0x8000661: chCoreAllocAlignedI
  0x8000671: chSchReadyI
  0x80006c1: _dbg_check_leave_isr
  0x80006f1: _dbg_check_enter_isr
  0x8000721: _dbg_check_unlock_from_isr
  0x8000751: _dbg_check_lock_from_isr
  0x8000781: wakeup
  0x80007e1: _idle_thread
  0x80007f1: serve_usart_irq
  0x8000871: uart_lld_serve_rx_end_irq
  0x8000901: dmaServeInterrupt
  0x8000941: stSetAlarm
  0x8000961: chVTDoResetI
  0x8000a11: chVTDoSetI
  0x8000ad1: rxchar
  0x8000b21: txend2
  0x8000b71: restart
  0x8000bc1: chSchGoSleepS
  0x8000c21: SVC_Handler
  0x8000c41:
  - chSchDoRescheduleAhead
  - chSchDoReschedule
  0x8000cd1: _dbg_check_unlock
  0x8000cf1: chSysUnlock.lto_priv.0
  0x8000d21: _dbg_check_lock
  0x8000d41: main
  0x8001851: chCoreAllocAlignedWithOffset
  0x80018a1: chThdExit
  0x8001901: __early_init
  0x8001981: VectorDC
  0x80019b1: VectorD8
  0x80019e1: VectorD4
  0x8001a11: VectorB0
  0x8001b31: Vector84
  0x8001b61: Vector80
  0x8001b91: Vector7C
  0x8001bc1: Vector78
  0x8001bf1: Vector74
  0x8001c21: Vector70
  0x8001c51: Vector6C
  0x8001c81: __init_ram_areas
  0x8001cf1: __default_exit
  0x8001d01: __late_init
  0x8001d11: __core_init
  0x8001d14:
  - __text_end
  - __rodata_base__
  0x8001da0: __func__.4292.lto_priv.0
  0x8001dac: __func__.4292.lto_priv.1
  0x8001db8: __func__.5513.lto_priv.0
  0x8001dc4: __func__.5513.lto_priv.1
  0x8001dd0: __func__.5513.lto_priv.2
  0x8001ddc: __func__.5513.lto_priv.3
  0x8001de8: __func__.5513.lto_priv.4
  0x8001df4: __func__.5599
  0x8001e00: __func__.5915
  0x8001e0c: __func__.6503
  0x8001e18: __func__.6506.lto_priv.0
  0x8001e24: __func__.6506.lto_priv.1
  0x8001e30: __func__.6510.lto_priv.0
  0x8001e44: __func__.6510.lto_priv.1
  0x8001e64: __func__.6515
  0x8001e74: __func__.6525.lto_priv.0
  0x8001e80: __func__.6525.lto_priv.1
  0x8001e8c: __func__.6528
  0x8001e98: __func__.6529
  0x8001ea4: __func__.6539
  0x8001eb4: __func__.6546
  0x8001ec4: __func__.6561
  0x8001ed0: __func__.6906
  0x8001ee0: __func__.7160
  0x8001eec: __func__.7163
  0x8001efc: __func__.7167
  0x8001f08: __func__.7169
  0x8001f14: __func__.7170
  0x8001f20: __func__.7173
  0x8001f2c: __func__.7177.lto_priv.0
  0x8001f3c: __func__.7177.lto_priv.1
  0x8001f48: __func__.7181
  0x8001f54: __func__.7183
  0x8001f64: __func__.7185
  0x8001f70: __func__.7189
  0x8001f7c: __func__.7193
  0x8001f88: __func__.7194
  0x8001f94: __func__.7198
  0x8001fa0: __func__.7202
  0x8001fac: __func__.7209
  0x8001fbc: _stm32_dma_streams
  0x800202c: ch_debug
  0x8002044: ram_areas
  0x80020c4:
  - __exidx_end
  - __rodata_end__
  - __exidx_start
  - _textdata_start
  0x80020e4:
  - __ram3_init_text__
  - __ram0_init_text__
  - __ram1_init_text__
  - __ram5_init_text__
  - __ram6_init_text__
  - __flash0_init__
  - __flash0_free__
  - __ram2_init_text__
  - __ram4_init_text__
  - __ram7_init_text__
  0x8020000: __flash0_end__
  0x10000000: ICSR_PENDSVSET
  0x20000000:
  - __ram0_start__
  - __main_stack_base__
  0x20000400:
  - __process_stack_base__
  - __main_stack_end__
  - __main_thread_stack_base__
  0x20000800:
  - uart_cfg_1
  - __main_thread_stack_end__
  - _data_start
  - __process_stack_end__
  0x20000820:
  - UARTD1
  - _bss_start
  - _data_end
  0x2000083c: UARTD2
  0x20000858: UARTD3
  0x20000874: ch
  0x200010fc: ch_factory
  0x20001148: ch_idle_thread_wa
  0x20001220: ch_memcore
  0x20001228: default_heap
  0x20001244: dma
  0x20001284: vt1
  0x20001298: vt2
  0x200012ac:
  - __ram0_init__
  - __ram0_free__
  - _bss_end
  - __ram0_clear__
  - __ram0_noinit__
  0x200012b0: __heap_base__
  0x20005000:
  - __heap_end__
  - __ram0_end__
  0xe000ed04: SCB_ICSR
