handlers:
  # Skip executing the idle hook
  default_idle_hook:
  printf:

exit_at:
  mbed_error:
  mbed_die:
  __assert_func:

interrupt_triggers:
  #addr: 2
  # Set interrupt trigger on idle loop
  trigger:
    addr: default_idle_hook
    fuzz_mode: fuzzed
    # overwrite default interrupt trigger
    every_nth_tick: None
  # Trigger DMA interrupt at WFI instructions
  spiWrite1:
    addr: wfimark1
    irq: 16
  spiWrite2:
    addr: wfimark2
    irq: 16
  spiRead1:
    addr: wfimark3
    irq: 16
  spiRead2:
    addr: wfimark4
    irq: 16

# set execution limit to keep speed reasonable
limits:
  interrupts: 100
