debug: 0
eval-targets:
- targets
exp_name: 03-realworld
individual_num_runs: 1
num_cores: 50
out_dir: output
out_file: results_experiment_03.yml
runtime: 0:01:00
runtime_flexibility: 10
strategy_mapping:
  automatic-generic-dma: config.yml
  no-dma: config.yml
use_python_modeling: false
