interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_00000008:
    base_addr: 0x0
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: Soldering-Station.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1ea14
symbols:
  0x0:
  - startup/startup_stm32f103xb.o
  - crtstuff.c
  - _arm_addsubdf3.o
  - _arm_muldivdf3.o
  - _arm_cmpdf2.o
  - _arm_unorddf2.o
  - _arm_fixunsdfsi.o
  - _arm_truncdfsf2.o
  - _arm_addsubsf3.o
  - _arm_fixunssfsi.o
  - lib_a-strcmp.o
  - lib_a-strlen.o
  - stm32f1xx_hal.c
  - stm32f1xx_hal_adc.c
  - stm32f1xx_hal_adc_ex.c
  - stm32f1xx_hal_cortex.c
  - stm32f1xx_hal_dma.c
  - stm32f1xx_hal_gpio.c
  - stm32f1xx_hal_rcc.c
  - stm32f1xx_hal_rcc_ex.c
  - stm32f1xx_hal_spi.c
  - stm32f1xx_hal_spi_ex.c
  - stm32f1xx_hal_tim.c
  - stm32f1xx_hal_tim_ex.c
  - stm32f1xx_hal_uart.c
  - adc_global.c
  - buzzer.c
  - rotary_encoder.c
  - tempsensors.c
  - calibration_screen.c
  - debug_screen.c
  - gui.c
  - main_screen.c
  - oled.c
  - screen.c
  - settings_screen.c
  - splash.c
  - widgets.c
  - ssd1306.c
  - ugui.c
  - afl_call.c
  - iron.c
  - main.c
  - pid.c
  - settings.c
  - stm32f1xx_hal_msp.c
  - stm32f1xx_it.c
  - system_stm32f1xx.c
  - w_log.c
  - e_log.c
  - s_matherr.c
  - s_nan.c
  - errno.c
  - init.c
  - malloc.c
  - nano-mallocr.c
  - nano-mallocr.c
  - sbrkr.c
  - sprintf.c
  - strcpy.c
  - mlock.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - memchr-stub.c
  - memcpy-stub.c
  - memmove.c
  - nano-mallocr.c
  - nano-mallocr.c
  - sbrk.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  - s_lib_ver.c
  - impure.c
  - reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000111: __do_global_dtors_aux
  0x8000135: frame_dummy
  0x8000151: __aeabi_drsub
  0x8000159:
  - __aeabi_dsub
  - __subdf3
  0x800015d:
  - __adddf3
  - __aeabi_dadd
  0x80003d5:
  - __aeabi_ui2d
  - __floatunsidf
  0x80003f5:
  - __floatsidf
  - __aeabi_i2d
  0x8000419:
  - __extendsfdf2
  - __aeabi_f2d
  0x800045d:
  - __aeabi_ul2d
  - __floatundidf
  0x800046d:
  - __floatdidf
  - __aeabi_l2d
  0x80004c9:
  - __aeabi_dmul
  - __muldf3
  0x800071d:
  - __aeabi_ddiv
  - __divdf3
  0x80008ed:
  - __gtdf2
  - __gedf2
  0x80008f5:
  - __ltdf2
  - __ledf2
  0x80008fd:
  - __cmpdf2
  - __eqdf2
  - __nedf2
  0x8000979: __aeabi_cdrcmple
  0x8000989:
  - __aeabi_cdcmple
  - __aeabi_cdcmpeq
  0x8000999: __aeabi_dcmpeq
  0x80009ad: __aeabi_dcmplt
  0x80009c1: __aeabi_dcmple
  0x80009d5: __aeabi_dcmpge
  0x80009e9: __aeabi_dcmpgt
  0x80009fd:
  - __aeabi_dcmpun
  - __unorddf2
  0x8000a29:
  - __fixunsdfsi
  - __aeabi_d2uiz
  0x8000a69:
  - __aeabi_d2f
  - __truncdfsf2
  0x8000b09: __aeabi_frsub
  0x8000b11:
  - __subsf3
  - __aeabi_fsub
  0x8000b15:
  - __aeabi_fadd
  - __addsf3
  0x8000c75:
  - __aeabi_ui2f
  - __floatunsisf
  0x8000c7d:
  - __aeabi_i2f
  - __floatsisf
  0x8000c99:
  - __floatundisf
  - __aeabi_ul2f
  0x8000ca9:
  - __floatdisf
  - __aeabi_l2f
  0x8000d25:
  - __aeabi_f2uiz
  - __fixunssfsi
  0x8000d65: strcmp
  0x8000d79: strlen
  0x8000d89: HAL_InitTick
  0x8000db1: HAL_Init
  0x8000dd5: HAL_IncTick
  0x8000de5: HAL_GetTick
  0x8000df1: HAL_Delay
  0x8000df9: ADC_DMAConvCplt
  0x8000e4b: ADC_DMAHalfConvCplt
  0x8000e55: HAL_ADC_ErrorCallback
  0x8000e57: ADC_DMAError
  0x8000e71: HAL_ADC_ConfigChannel
  0x800102d: ADC_Enable
  0x80010ad: HAL_ADC_Start
  0x8001199: ADC_ConversionStop_Disable
  0x80011e5: HAL_ADC_Init
  0x8001321: HAL_ADCEx_Calibration_Start
  0x800140d: HAL_ADCEx_MultiModeStart_DMA
  0x8001501: HAL_ADCEx_MultiModeConfigChannel
  0x8001559: HAL_NVIC_SetPriorityGrouping
  0x800157d: HAL_NVIC_SetPriority
  0x80015e5: HAL_NVIC_EnableIRQ
  0x80015fd: HAL_SYSTICK_Config
  0x8001629: HAL_SYSTICK_CLKSourceConfig
  0x8001649: HAL_SYSTICK_Callback
  0x800164b: HAL_SYSTICK_IRQHandler
  0x8001653: DMA_SetConfig
  0x8001675: HAL_DMA_Init
  0x80016c7: HAL_DMA_Start_IT
  0x8001721: HAL_DMA_IRQHandler
  0x8001989: HAL_GPIO_Init
  0x8001b5d: HAL_GPIO_ReadPin
  0x8001b6b: HAL_GPIO_WritePin
  0x8001b77: HAL_GPIO_TogglePin
  0x8001b81: HAL_GPIO_EXTI_IRQHandler
  0x8001b9d: HAL_RCC_OscConfig
  0x8002181: HAL_RCC_GetSysClockFreq
  0x800220d: HAL_RCC_ClockConfig
  0x80023e1: HAL_RCC_GetHCLKFreq
  0x80023ed: HAL_RCC_GetPCLK1Freq
  0x8002419: HAL_RCC_GetPCLK2Freq
  0x8002445: HAL_RCCEx_PeriphCLKConfig
  0x800257d: HAL_RCCEx_GetPeriphCLKFreq
  0x80026a5: SPI_WaitOnFlagUntilTimeout
  0x8002783: HAL_SPI_Transmit
  0x8002941: HAL_SPI_Init
  0x80029c9: TIM_OC1_SetConfig
  0x8002a25: TIM_OC3_SetConfig
  0x8002a89: TIM_OC4_SetConfig
  0x8002ad1: TIM_TI1_ConfigInputStage
  0x8002af5: TIM_TI2_ConfigInputStage
  0x8002b1b: TIM_ITRx_SetConfig
  0x8002b2b: TIM_ETR_SetConfig
  0x8002b41: HAL_TIM_Base_Start_IT
  0x8002b59: HAL_TIM_PWM_MspInit
  0x8002b5b: HAL_TIM_ConfigClockSource
  0x8002c63: HAL_TIM_OC_DelayElapsedCallback
  0x8002c65: HAL_TIM_IC_CaptureCallback
  0x8002c67: HAL_TIM_PWM_PulseFinishedCallback
  0x8002c69: HAL_TIM_TriggerCallback
  0x8002c6b: HAL_TIM_IRQHandler
  0x8002de5: TIM_Base_SetConfig
  0x8002e51: HAL_TIM_Base_Init
  0x8002e83: HAL_TIM_PWM_Init
  0x8002eb5: TIM_OC2_SetConfig
  0x8002f19: HAL_TIM_PWM_ConfigChannel
  0x8002ff5: TIM_CCxChannelCmd
  0x8003011: HAL_TIM_PWM_Start
  0x8003041: HAL_TIM_PWM_Stop
  0x80030a1: HAL_TIMEx_MasterConfigSynchronization
  0x80030f3: HAL_TIMEx_CommutationCallback
  0x80030f5: HAL_TIMEx_BreakCallback
  0x80030f9: UART_SetConfig
  0x80032a5: HAL_UART_Init
  0x8003301: MX_ADC1_Init
  0x8003399: MX_ADC2_Init
  0x8003419: buzzer_init
  0x8003429: buzzer_short_beep
  0x8003451: tempReachedCall
  0x8003459: buzzer_long_beep
  0x8003481: buzzer_alarm_start
  0x800348d: buzzer_alarm_stop
  0x80034a9: handle_buzzer
  0x8003519: RE_Init
  0x8003549: RE_Get
  0x80035b1: RE_Process
  0x80036b9: readColdJunctionSensorTemp_mC
  0x8003801: setCurrentTip
  0x8003835: getCurrentTip
  0x8003841: map
  0x8003861: adc2Human
  0x80038d5: readTipTemperatureCompensated
  0x80038f5: human2adc
  0x80039c1: tempReached
  0x80039e1: getMeasuredTemp
  0x80039e9: setMeasuredTemp
  0x80039f5: cancelAction
  0x80039f9: waitProcessInput
  0x8003a11: processCalibration
  0x8003b51: setCalState
  0x8003c01: okAction
  0x8003c51: inputCalibration_screen_init
  0x8003c69: waitCalibration_screen_init
  0x8003c81: waitOnExit
  0x8003cd9: waitOnEnter
  0x8003d55: calibration_screen_setup
  0x8003fc9: debug_screen_getADC1_1
  0x8003fdd: debug_screen2_getDebugSetpoint
  0x8003fe5: cancelDebug2
  0x8003fe9: debug_screen_getOutput
  0x8004001: debug_screen_getError
  0x8004019: debug_screen_getD
  0x8004031: debug_screen_getI
  0x8004049: debug_screen_getP
  0x8004061: debug_screen_init
  0x8004079: saveDebug2
  0x8004083: debug_screen2_setCalcAt400
  0x8004091: debug_screen2_getCalcAt400
  0x800409b: debug_screen2_setCalcAt300
  0x80040a9: debug_screen2_getCalcAt300
  0x80040b3: debug_screen2_setCalcAt200
  0x80040c1: debug_screen2_getCalcAt200
  0x80040c9: debug_screen2_setDebugSetpoint
  0x80040dd: debug_screen2_on_exit
  0x8004111: debug_screen2_on_enter
  0x8004169: setPWM_tim
  0x800416d: debug_screen_setup
  0x80042c5: debug_screen2_setup
  0x80044a9: guiInit
  0x80044e9: getTip
  0x80044fd: boostOn
  0x800450d: setMode
  0x8004521: setTemp
  0x8004535: getTemp
  0x8004549: getMode
  0x800455d: setTip
  0x8004581: main_screenUpdate
  0x800460d: tempProcessInput
  0x800465d: main_screen_getAmbTemp
  0x800467d: main_screen_getIronPower
  0x8004691: main_screen_getIronTemp
  0x80046a9: main_screen_init
  0x80046d9: main_screen_setup
  0x80049b1: oled_addScreen
  0x8004a01: oled_draw
  0x8004a19: oled_update
  0x8004a2d: oled_init
  0x8004a4d: oled_processInput
  0x8004aa9: screen_addWidget
  0x8004ae5: default_screenProcessInput
  0x8004b39: default_screenDraw
  0x8004b53: default_screenUpdate
  0x8004b73: default_init
  0x8004bc9: getTipStr
  0x8004bd1: cancelTip
  0x8004bd5: getMaxPower
  0x8004c01: getBoostTime
  0x8004c15: setBoostTime
  0x8004c29: getBoostTemp
  0x8004c3d: setBoostTemp
  0x8004c51: cancelBoost
  0x8004c65: cancelSleep
  0x8004c81: setSleepTime
  0x8004c95: getSleepTime
  0x8004ca9: setStandByTime
  0x8004cbd: getStandByTime
  0x8004cd1: setSleepTemp
  0x8004ce5: getSleepTemp
  0x8004cf9: getKp
  0x8004d29: getKi
  0x8004d59: getKd
  0x8004d89: setTipStr
  0x8004d99: edit_iron_screen_init
  0x8004df9: delTip
  0x8004e6d: saveTip
  0x8004ee5: saveSleep
  0x8004f05: saveBoost
  0x8004f21: savePower
  0x8004f49: saveContrast
  0x8004f65: savePID
  0x8004f95: edit_iron_tip_screen_init
  0x8004fe9: cancelPower
  0x8005011: setMaxPower
  0x800503d: cancelPID
  0x8005071: setKd
  0x80050a9: setKi
  0x80050e1: setKp
  0x8005119: cancelContrast
  0x800512d: setContrast_
  0x8005141: getContrast_
  0x8005155: settings_screen_init
  0x800517d: settings_screen_setup
  0x8005f0d: splash_draw
  0x8005f21: splash_init
  0x8005f49: splash_processInput
  0x8005f69: splash_setup
  0x8005f89: insertDot
  0x8005fb7: comboBoxDraw
  0x80060d5: extractDisplayPartFromWidget
  0x80060f5: default_widgetUpdate
  0x800615d: extractEditablePartFromWidget
  0x8006175: extractSelectablePartFromWidget
  0x80061a5: default_widgetDraw
  0x8006365: default_widgetProcessInput
  0x80066b1: widgetDefaultsInit
  0x80067b5: comboItemToIndex
  0x80067cf: comboBoxProcessInput
  0x8006891: comboAddItem
  0x80068c9: write_data
  0x8006915: write_cmd
  0x8006969: pset
  0x80069b9: update_display
  0x80069ed: setContrast
  0x8006a09: getContrast
  0x8006a15: ssd1306_init
  0x8006ae1: UG_Init
  0x8006b5d: UG_FontSelect
  0x8006b79: UG_FillFrame
  0x8006be5: UG_FillScreen
  0x8006c0d: UG_DrawPixel
  0x8006c1d: UG_DrawLine
  0x8006d25: UG_DrawFrame
  0x8006d6d: UG_SetForecolor
  0x8006d79: UG_SetBackcolor
  0x8006d85: UG_GetXDim
  0x8006d95: UG_GetYDim
  0x8006da5: UG_FontSetHSpace
  0x8006db5: UG_FontSetVSpace
  0x8006dc5: _UG_PutChar
  0x8007121: UG_PutChar
  0x800713d: UG_PutString
  0x80071d1: _UG_PutText
  0x8007325: _UG_ProcessTouchData
  0x80073e5: _UG_UpdateObjects
  0x800743d: _UG_HandleEvents
  0x8007499: _UG_DrawObjectFrame
  0x80075c5: UG_DrawBMP
  0x8007645: _UG_WindowDrawTitle
  0x800772d: _UG_WindowUpdate
  0x800780d: UG_Update
  0x80078cd: aflCall
  0x80078d1: startForkserver
  0x80078ed: temperatureReached
  0x800790d: setDebugSetPoint
  0x8007919: setDebugMode
  0x8007925: turnIronOn
  0x800793d: turnIronOff
  0x8007955: getIronOn
  0x8007961: applyBoostSettings
  0x8007975: applySleepSettings
  0x800798d: setCurrentTemperature
  0x80079c1: setSetTemperature
  0x80079e5: addSetTemperatureReachedCallback
  0x8007a19: setCurrentMode
  0x8007a71: getCurrentMode
  0x8007a7d: getSetTemperature
  0x8007a89: handleIron
  0x8007ca5: ironInit
  0x8007cc5: getCurrentPower
  0x8007cd1: MX_GPIO_Init
  0x8007d99: MX_DMA_Init
  0x8007dcd: HAL_TIM_PeriodElapsedCallback
  0x8007ded: HAL_ADC_ConvHalfCpltCallback
  0x8007e29: HAL_ADC_ConvCpltCallback
  0x8007f31: HAL_GPIO_EXTI_Callback
  0x8007f4d: _Error_Handler
  0x8007f51: MX_SPI1_Init
  0x8007fa1: MX_TIM4_Init
  0x800803d: MX_USART3_UART_Init
  0x8008079: MX_TIM3_Init
  0x80080ed: SystemClock_Config
  0x8008185: main
  0x8008385: getError
  0x8008391: setupPID
  0x80083e1: setupPIDFromStruct
  0x8008421: resetPID
  0x8008435: calculatePID
  0x80085a9: getPID_D
  0x80085c5: getPID_P
  0x80085e1: getPID_I
  0x80085fd: getOutput
  0x8008619: saveSettings
  0x8008621: resetSettings
  0x8008801: restoreSettings
  0x8008835: HAL_MspInit
  0x80088c5: HAL_ADC_MspInit
  0x8008981: HAL_SPI_MspInit
  0x80089c9: HAL_TIM_Base_MspInit
  0x8008a39: HAL_TIM_MspPostInit
  0x8008a69: HAL_UART_MspInit
  0x8008ac5: NMI_Handler
  0x8008ac7: HardFault_Handler
  0x8008ac9: MemManage_Handler
  0x8008acb: BusFault_Handler
  0x8008acd: UsageFault_Handler
  0x8008acf: SVC_Handler
  0x8008ad1: DebugMon_Handler
  0x8008ad3: PendSV_Handler
  0x8008ad5: SysTick_Handler
  0x8008ae1: EXTI0_IRQHandler
  0x8008aeb: EXTI1_IRQHandler
  0x8008af5: EXTI9_5_IRQHandler
  0x8008b05: DMA1_Channel1_IRQHandler
  0x8008b15: TIM3_IRQHandler
  0x8008b25: TIM4_IRQHandler
  0x8008b35: SystemInit
  0x8008b81: Reset_Handler
  0x8008b84: CopyDataInit
  0x8008b8c: LoopCopyDataInit
  0x8008b9a: FillZerobss
  0x8008ba0: LoopFillZerobss
  0x8008bc8:
  - Infinite_Loop
  - Default_Handler
  0x8008bc9:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - DMA1_Channel4_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - EXTI15_10_IRQHandler
  - SPI2_IRQHandler
  - DMA1_Channel5_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x8008bcd: log
  0x8008cc9: __ieee754_log
  0x800905d: matherr
  0x8009061: nan
  0x800906d: __errno
  0x8009079: __libc_init_array
  0x80090c1: malloc
  0x80090d1: _free_r
  0x8009169: _malloc_r
  0x800921d: _sbrk_r
  0x800923d:
  - sprintf
  - siprintf
  0x800927d: strcpy
  0x800928d: __malloc_lock
  0x800928f: __malloc_unlock
  0x8009291: __ssputs_r
  0x8009345:
  - _svfprintf_r
  - _svfiprintf_r
  0x8009535: _printf_common
  0x8009621: _printf_i
  0x8009845: memchr
  0x8009861: memcpy
  0x8009877: memmove
  0x80098a9: _realloc_r
  0x80098f5: _malloc_usable_size_r
  0x8009905: _sbrk
  0x8009920: __EH_FRAME_BEGIN__
  0x8009921: _init
  0x800992d: _fini
  0x8009938: _etext
  0x8009960: state_temps
  0x8009968: therm
  0x800998c: pal_button_pressed
  0x80099bc: pal_button_released
  0x80099ec: pal_checkbox_pressed
  0x8009a1c: pal_checkbox_released
  0x8009a4c: pal_window
  0x8009a7c: FONT_16X26
  0x8009a90: FONT_8X14
  0x8009aa4: FONT_6X8
  0x8009ab8: font_16x26
  0x800ceb8: font_8x14
  0x800dcb8: font_6x8
  0x800e4d0: AHBPrescTable
  0x800e4e0: APBPrescTable
  0x800e768:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x800e76c:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x800e770: _sidata
  0x20000000:
  - buzzer_state
  - _sdata
  0x20000004: hasIron
  0x20000008: modestr
  0x20000018: str
  0x2000002c: MAX_POWER
  0x20000030: logo
  0x2000022e: m_contrast
  0x20000230: currentSetTemperature
  0x20000232: user_currentSetTemperature
  0x20000234: activity
  0x20000238: SystemCoreClock
  0x2000023c: __fdlib_version
  0x20000240: _impure_ptr
  0x20000244: impure_data
  0x200002a4: _edata
  0x200002a8:
  - completed.8655
  - _sbss
  - __bss_start__
  0x200002ac: object.8660
  0x200002c4: uwTick
  0x200002c8: uCRCErrorWorkaroundCheck
  0x200002ca: iron_temp_adc_avg
  0x200002cc: iron_temp_measure_state
  0x200002d0: last_time
  0x200002d4: long_press_time.7257
  0x200002d8: rIndex.7841
  0x200002dc: rollingAverage.7840
  0x200002ec: currentTipData
  0x200002f0: last_value.7857
  0x200002f8: current_state
  0x200002f9: tempReady
  0x200002fa: measuredTemp
  0x200002fc: measured_temps
  0x20000304: adcAtTemp
  0x2000030c: adcCal
  0x20000314: waitStr
  0x20000318: waitTemp
  0x2000031c: cancelButton
  0x20000320: waitWidget
  0x20000324: calWaitScreen
  0x20000328: calInputScreen
  0x2000032c: tempSetBackup
  0x2000032e: ironModeBackup
  0x20000330: cal_pid
  0x20000360: debugSetPoint
  0x20000368: cal_pid
  0x20000398: m_tip
  0x2000039a: m_mode
  0x2000039c: m_temp
  0x200003a0: ironTempLabelWidget
  0x200003a4: ironTempWidget
  0x200003a8: noIronWidget
  0x200003ac: temp
  0x200003b0: tipsWidget
  0x200003b4: tipstr
  0x200003dc: screens
  0x200003e0: current_screen
  0x200003e4: BTIME
  0x200003e6: BTEMP
  0x200003e8: SLEEPTIME
  0x200003ea: STANDBYTIME
  0x200003ec: SLEEPTEMP
  0x200003ee: KP
  0x200003f0: KI
  0x200003f2: KD
  0x200003f4: tipCombo
  0x200003f8: addNewTipComboItem
  0x200003fc: CONTRAST
  0x20000400: delTipButton
  0x20000404: combo
  0x20000408: bmp
  0x20000414: splash_time
  0x20000418: m_hspi
  0x2000041c: buffer
  0x2000081c: gui
  0x20000820: msg.5238
  0x20000828: noHyperCall
  0x2000082c: temperatureReachedCallbacks
  0x20000830: debugSetPoint
  0x20000832: debugMode
  0x20000834: ironPWMTimer
  0x20000838: isIronOn
  0x2000083a: tempSetPoint
  0x2000083c: temperatureReachedFlag
  0x20000840: lastSetTemperatureTime
  0x20000844: setTemperatureChanged
  0x20000848: currentModeTimer
  0x2000084c: currentMode
  0x2000084d: currentIronPower
  0x20000850: pwmStoppedSince
  0x20000854: rindex.9461
  0x20000858: ironTempADCRollingAverage.9460
  0x2000086c: doOnce.9462
  0x2000086d: startOfNoActivity
  0x20000870: startOfNoActivityTime
  0x20000874: dma
  0x20000878: adc
  0x20000880: pre_error
  0x20000888: integral
  0x20000890: max
  0x20000898: min
  0x200008a0: Kp
  0x200008a8: Kd
  0x200008b0: Ki
  0x200008b8: minI
  0x200008c0: maxI
  0x200008c8: mset
  0x200008d0: mpv
  0x200008d8: p
  0x200008e0: i
  0x200008e8: d
  0x200008f0: currentOutput
  0x200008f8: __malloc_free_list
  0x200008fc: __malloc_sbrk_start
  0x20000900: heap_end.4102
  0x20000904: adc_measures
  0x20000958: currentPID
  0x20000988: currentSleepSettings
  0x20000990: currentBoostSettings
  0x20000998: systemSettings
  0x20000c30: temp
  0x20000c34: huart3
  0x20000c74: hadc2
  0x20000ca4: hiwdg
  0x20000cb4: RE1_Data
  0x20000cdc: hadc1
  0x20000d0c: sConfigOC
  0x20000d28: hdma_adc1
  0x20000d60: temp_measure_tim3
  0x20000d9c: hspi1
  0x20000df4: pwm_tim4
  0x20000e30: lastTime
  0x20000e34: errno
  0x20000e38:
  - _ebss
  - end
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
