debug: 0
eval-targets:
- dice-unit
exp_name: dice-unit
individual_num_runs: 1
num_cores: 50
out_dir: output
out_file: results_dice_unit.yml
runtime: 0:01:00
runtime_flexibility: 10
strategy_mapping:
  automatic-generic-dma: config.yml
use_python_modeling: false
