debug: 0
eval-targets:
- p2im-targets
exp_name: 05-false-positive
individual_num_runs: 1
num_cores: 50
out_dir: output
out_file: results_p2im_unit.yml
runtime: 0:01:00
runtime_flexibility: 10
strategy_mapping:
  automatic-generic-dma: config.yml
use_python_modeling: false
