interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x10000000
    permissions: rw-
    size: 0x214
  dynamically_added_crash_region_10007ff8:
    base_addr: 0x10002000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x1a000000
    file: LPC1837_PDMA_memory.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x14ec0
symbols:
  0x0:
  - cr_startup_lpc18xx.c
  - dma_timertrig.c
  - sysinit.c
  - board.c
  - board_sysinit.c
  - chip_18xx_43xx.c
  - clock_18xx_43xx.c
  - gpdma_18xx_43xx.c
  - gpio_18xx_43xx.c
  - sysinit_18xx_43xx.c
  - timer_18xx_43xx.c
  - uart_18xx_43xx.c
  - _cr__main.c
  - memset.c
  - fpprintf.c
  - initio.c
  - printf.c
  - setvbuf.c
  - strlen.c
  - _deferredlazyseek.c
  - _fdopen.c
  - _fflush.c
  - _frexpl.c
  - _ldexpl.c
  - _writebuf.c
  - alloc.c
  - fclose.c
  - fflush.c
  - fseek.c
  - ftell.c
  - remove.c
  - _cr_sbrk.c
  - _do_fflush.c
  - _cr_check_heap.c
  - division_64.o
  - division_idiv0.o
  - double.c
  - memcpy.o
  - __sys_appexit.c
  - __sys_close.c
  - __sys_flen.c
  - __sys_istty.c
  - __sys_remove.c
  - __sys_seek.c
  - __sys_tmpnam.c
  - _hugeval.c
  - _pvHeapLimit
  0x10000000:
  - GPDMA_LUTPerAddr
  - __base_RamLoc32
  - _end_uninit_RESERVED
  - _data
  - __base_RAM
  0x10000078:
  - source
  - _bss
  - _edata
  0x10000088: dest
  0x10000098: dmaXfers
  0x1000009c: compPass
  0x100000a0: dmaCh
  0x100000a4: seed.8653
  0x100000a8: On.8671
  0x100000ac: audio_usb_pll_freq
  0x100000b4: ChannelHandlerArray
  0x100000bc: _extra
  0x100000c0: __Ciob
  0x10000200: errno
  0x10000204: __heaps
  0x10000208: __end_of_heap
  0x1000020c: isDmaTxfCompleted
  0x10000210: SystemCoreClock
  0x10000214:
  - _noinit
  - _ebss
  - _end_noinit
  - _pvHeapStart
  0x10008000:
  - __top_RAM
  - __top_RamLoc32
  - _vStackTop
  0x10080000:
  - __base_RAM2
  - __base_RamLoc40
  0x1008a000:
  - __top_RAM2
  - __top_RamLoc40
  0x1a000000:
  - __vectors_start__
  - __base_Flash
  - __base_MFlashA512
  - g_pfnVectors
  0x1a000114:
  - __section_table_start
  - __data_section_table
  0x1a000150:
  - __data_section_table_end
  - __bss_section_table
  0x1a000178:
  - __bss_section_table_end
  - __section_table_end
  0x1a000179: data_init
  0x1a0001bd: bss_init
  0x1a0001f5: NMI_Handler
  0x1a0001fd: HardFault_Handler
  0x1a000205: MemManage_Handler
  0x1a00020d: BusFault_Handler
  0x1a000215: UsageFault_Handler
  0x1a00021d: SVC_Handler
  0x1a000225: DebugMon_Handler
  0x1a00022d: PendSV_Handler
  0x1a000235: SysTick_Handler
  0x1a00023d:
  - TIMER2_IRQHandler
  - RIT_IRQHandler
  - FLASH_EEPROM_IRQHandler
  - I2C0_IRQHandler
  - SDIO_IRQHandler
  - ATIMER_IRQHandler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - GPIO5_IRQHandler
  - CAN1_IRQHandler
  - USB1_IRQHandler
  - I2S0_IRQHandler
  - TIMER3_IRQHandler
  - UART0_IRQHandler
  - SGPIO_IRQHandler
  - ADC0_IRQHandler
  - GPIO6_IRQHandler
  - IntDefaultHandler
  - GPIO1_IRQHandler
  - SSP0_IRQHandler
  - ADC1_IRQHandler
  - RTC_IRQHandler
  - LCD_IRQHandler
  - TIMER1_IRQHandler
  - UART2_IRQHandler
  - GPIO2_IRQHandler
  - I2S1_IRQHandler
  - SSP1_IRQHandler
  - USB0_IRQHandler
  - GPIO3_IRQHandler
  - SCT_IRQHandler
  - WDT_IRQHandler
  - GPIO7_IRQHandler
  - SPIFI_IRQHandler
  - QEI_IRQHandler
  - ETH_IRQHandler
  - CAN0_IRQHandler
  - GINT0_IRQHandler
  - DAC_IRQHandler
  - GPIO0_IRQHandler
  - EVRT_IRQHandler
  - UART3_IRQHandler
  - MCPWM_IRQHandler
  - GINT1_IRQHandler
  - GPIO4_IRQHandler
  0x1a000245: ResetISR
  0x1a000319: NVIC_EnableIRQ
  0x1a000349: NVIC_ClearPendingIRQ
  0x1a00037d: Chip_SCU_PinMuxSet
  0x1a0003ad: Chip_RGU_TriggerReset
  0x1a0003e5: Chip_RGU_InReset
  0x1a000425: Chip_TIMER_MatchPending
  0x1a000459: Chip_TIMER_ClearMatch
  0x1a000481: Chip_TIMER_Enable
  0x1a0004a1: Chip_TIMER_PrescaleSet
  0x1a0004bd: Chip_TIMER_SetMatch
  0x1a0004e5: Chip_TIMER_MatchEnableInt
  0x1a000519: Chip_TIMER_ResetOnMatchEnable
  0x1a00054d: Chip_TIMER_TIMER_SetCountClockSrc
  0x1a000575: setupTimerCapInput
  0x1a000589: setupTimerTrigger
  0x1a0005f1: setupDMATrigger
  0x1a000641: fillSourceBuff
  0x1a000689: checkSourceDestData
  0x1a0006d1: DMA_IRQHandler
  0x1a0006f9: TIMER0_IRQHandler
  0x1a000739: main
  0x1a0007c1: SystemInit
  0x1a0007e5: Chip_SCU_PinMuxSet
  0x1a000815: Chip_ENET_RMIIEnable
  0x1a00083d: Chip_GPIO_SetPinState
  0x1a000875: Chip_GPIO_GetPinState
  0x1a0008a9: Chip_GPIO_SetPinDIROutput
  0x1a0008e5: Chip_UART_TXEnable
  0x1a0008fd: Chip_UART_SendByte
  0x1a000919: Chip_UART_ConfigData
  0x1a000935: Chip_UART_ReadLineStatus
  0x1a00094d: __sys_write
  0x1a000985: Board_UART_Init
  0x1a0009a9: Board_Debug_Init
  0x1a0009d9: Board_UARTPutChar
  0x1a000a0d: Board_LED_Init
  0x1a000a69: Board_LED_Set
  0x1a000ab1: Board_LED_Test
  0x1a000af9: Board_LED_Toggle
  0x1a000b35: Board_Init
  0x1a000b59: Chip_SCU_PinMuxSet
  0x1a000b89: Chip_SCU_SetPinMuxing
  0x1a000bd5: Chip_CREG_SetFlashAcceleration
  0x1a000c29: Board_SetupMuxing
  0x1a000c3d: Board_SetupClocking
  0x1a000cd9: Board_SystemInit
  0x1a000ce9: SystemCoreClockUpdate
  0x1a000d01: ABS
  0x1a000d21: pll_calc_divs
  0x1a000e45: pll_get_frac
  0x1a000fc5: Chip_Clock_GetDivRate
  0x1a001005: Chip_Clock_FindBaseClock
  0x1a001091: Chip_Clock_EnableCrystal
  0x1a0010fd: Chip_Clock_CalcMainPLLValue
  0x1a0011d5: Chip_Clock_GetMainPLLHz
  0x1a001295: Chip_Clock_GetDividerSource
  0x1a0012d5: Chip_Clock_GetDividerDivisor
  0x1a001309: Chip_Clock_GetClockInputHz
  0x1a001449: Chip_Clock_GetBaseClocktHz
  0x1a00146d: Chip_Clock_SetBaseClock
  0x1a001509: Chip_Clock_GetBaseClock
  0x1a001555: Chip_Clock_EnableOpts
  0x1a0015d1: Chip_Clock_Enable
  0x1a001631: Chip_Clock_GetRate
  0x1a0016b9: configDMAMux
  0x1a0018b5: makeCtrlWord
  0x1a0019d9: setupChannel
  0x1a001a71: Chip_GPDMA_Init
  0x1a001add: Chip_GPDMA_InitChannelCfg
  0x1a001bbd: Chip_GPDMA_IntGetStatus
  0x1a001c79: Chip_GPDMA_ChannelCmd
  0x1a001cc1: Chip_GPDMA_Transfer
  0x1a001db5: Chip_GPDMA_GetFreeChannel
  0x1a001e0d: Chip_GPIO_Init
  0x1a001e21: Chip_Clock_DisableMainPLL
  0x1a001e3d: Chip_Clock_SetupMainPLL
  0x1a001e81: Chip_Clock_MainPLLLocked
  0x1a001ea5: Chip_SetupCoreClock
  0x1a001fed: Chip_TIMER_GetClockIndex
  0x1a00203d: Chip_TIMER_Init
  0x1a00205d: Chip_TIMER_Reset
  0x1a002099: Chip_UART_TXDisable
  0x1a0020b1: Chip_UART_SetupFIFOS
  0x1a0020cd: Chip_UART_ConfigData
  0x1a0020e9: Chip_UART_EnableDivisorAccess
  0x1a002109: Chip_UART_DisableDivisorAccess
  0x1a002129: Chip_UART_SetDivisorLatches
  0x1a002151: Chip_UART_GetIndex
  0x1a0021ad: Chip_UART_Init
  0x1a002231: Chip_UART_SetBaudFDR
  0x1a0023a1: __main
  0x1a0023b5: memset
  0x1a0023b9: fp_round
  0x1a002405: pr_dec.constprop.1
  0x1a00242d: sprintf
  0x1a002499: fp_display
  0x1a002d85: vsnprintf
  0x1a002de1: printf
  0x1a002e35: _initio
  0x1a002ed9: __vfprintf
  0x1a003c01: setvbuf
  0x1a003c41: strlen
  0x1a003c8b: _deferredlazyseek
  0x1a003ccf: __flsbuf
  0x1a003e0f: _fdopen
  0x1a003e79: _fflush
  0x1a003ed1: _frexpl
  0x1a003f2d: _ldexpl
  0x1a003f79: _Cwritebuf
  0x1a003fe1: malloc
  0x1a0040a9: free
  0x1a0040d9: _Csys_alloc
  0x1a0040f9: fclose
  0x1a004165: fflush
  0x1a004195: fseek
  0x1a0042a5: ftell
  0x1a0042f1: remove
  0x1a004305: _sbrk
  0x1a004345: _do_fflush
  0x1a004389: __check_heap_overflow
  0x1a0043a1: __aeabi_uldivmod
  0x1a0043a5: __bhs_ldivmod1
  0x1a0043c0: ldiv32
  0x1a0043c8: ldiv_return
  0x1a0043de: ldiv_sign
  0x1a0043f0: ldiv64
  0x1a004478: ldiv_res01
  0x1a00448e: ldiv_divzero
  0x1a00449a: udiv6432
  0x1a0044a2: udiv6432_loop1
  0x1a0044b6: udiv6432_entry
  0x1a0044b8: udiv6432_loop
  0x1a004515: __aeabi_idiv0
  0x1a004519: __aeabi_dmul
  0x1a004629: __aeabi_ddiv
  0x1a004761: __aeabi_dsub
  0x1a004901: __aeabi_dadd
  0x1a004a0d: __aeabi_d2iz
  0x1a004a4d: __bhs_ui2d
  0x1a004a93: __aeabi_i2d
  0x1a004aa3: __aeabi_dcmpeq
  0x1a004acf: __aeabi_dcmplt
  0x1a004b23: __aeabi_dcmple
  0x1a004b77: __aeabi_dcmpge
  0x1a004bcb: __aeabi_lowlevel_memset
  0x1a004bde: __bhs_memset4
  0x1a004be0: memset4
  0x1a004bec: memset1
  0x1a004bf0: memset1a
  0x1a004bfd:
  - __exit
  - __sys_appexit
  0x1a004bff: __sys_close
  0x1a004c05: __sys_flen
  0x1a004c0b: __sys_istty
  0x1a004c11: __sys_remove
  0x1a004c17: __sys_seek
  0x1a004c1d: __sys_tmpnam
  0x1a004c74: ExtRateIn
  0x1a004c78: OscRateIn
  0x1a004c7c: gpioLEDBits
  0x1a004c84: InitClkStates
  0x1a004c90: pinmuxing
  0x1a004cc4: periph_to_base
  0x1a004d2c: GPDMA_LUTPerBurst
  0x1a004d4c: GPDMA_LUTPerWid
  0x1a004d6c: InitClkStates
  0x1a004da8: UART_PClock
  0x1a004db0: UART_BClock
  0x1a004e40: __huge_vall
  0x1a004e48:
  - __exidx_end
  - _etext
  - __exidx_start
  0x1a080000:
  - __top_MFlashA512
  - __top_Flash
  0x1b000000:
  - __base_Flash2
  - __base_MFlashB512
  0x1b080000:
  - __top_Flash2
  - __top_MFlashB512
  0x20000000:
  - __base_RamAHB32
  - __base_RAM3
  0x20008000:
  - __top_RamAHB32
  - __base_RamAHB16
  - __base_RAM4
  - __top_RAM3
  0x2000c000:
  - __base_RamAHB_ETB16
  - __top_RAM4
  - __base_RAM5
  - __top_RamAHB16
  0x20010000:
  - __top_RamAHB_ETB16
  - __top_RAM5
  0x53ff73a2: __valid_user_code_checksum
