interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_SPI_FullDuplex_ComDMA.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1142c
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - stm32f1xx_nucleo.c
  - system_stm32f1xx.c
  - stm32f1xx_hal.c
  - stm32f1xx_hal_cortex.c
  - stm32f1xx_hal_dma.c
  - stm32f1xx_hal_gpio.c
  - stm32f1xx_hal_rcc.c
  - stm32f1xx_hal_spi.c
  - stm32f1xx_hal_spi_ex.c
  - main.c
  - stm32f1xx_hal_msp.c
  - stm32f1xx_it.c
  - init.c
  - memset.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: BSP_LED_Init
  0x800019d: BSP_LED_On
  0x80001b1: BSP_LED_Off
  0x80001c5: BSP_LED_Toggle
  0x80001d9: SystemInit
  0x8000225: HAL_MspInit
  0x8000229: HAL_InitTick
  0x800026d: HAL_Init
  0x8000291: HAL_IncTick
  0x80002a9: HAL_GetTick
  0x80002b5: HAL_Delay
  0x80002bd: HAL_NVIC_SetPriorityGrouping
  0x80002e1: HAL_NVIC_SetPriority
  0x8000349: HAL_NVIC_EnableIRQ
  0x8000361: HAL_SYSTICK_Config
  0x800038d: HAL_DMA_Init
  0x80003ed: HAL_DMA_Start_IT
  0x8000469: HAL_DMA_IRQHandler
  0x8000591: HAL_GPIO_Init
  0x8000751: HAL_GPIO_WritePin
  0x800075b: HAL_GPIO_TogglePin
  0x8000765: HAL_RCC_OscConfig
  0x8000a7d: HAL_RCC_GetSysClockFreq
  0x8000af1: HAL_RCC_ClockConfig
  0x8000c51: SPI_WaitFlagStateUntilTimeout
  0x8000cdd: SPI_CheckFlag_BSY
  0x8000cfd: HAL_SPI_TransmitReceive_DMA
  0x8000e09: HAL_SPI_RxCpltCallback
  0x8000e0b: HAL_SPI_RxHalfCpltCallback
  0x8000e0d: SPI_DMAHalfReceiveCplt
  0x8000e17: HAL_SPI_TxRxHalfCpltCallback
  0x8000e19: SPI_DMAHalfTransmitReceiveCplt
  0x8000e23: SPI_DMAError
  0x8000e45: SPI_DMAReceiveCplt
  0x8000f0b: SPI_DMATransmitReceiveCplt
  0x8000fc9: HAL_SPI_Init
  0x8001045: SPI_ISCRCErrorValid
  0x8001049: Reset_Handler
  0x800104c: CopyDataInit
  0x8001054: LoopCopyDataInit
  0x8001062: FillZerobss
  0x8001068: LoopFillZerobss
  0x8001090:
  - Infinite_Loop
  - Default_Handler
  0x8001091:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI15_10_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - I2C1_ER_IRQHandler
  - USBWakeUp_IRQHandler
  0x8001093: Error_Handler
  0x80010ab: SystemClock_Config
  0x80010fd: main
  0x8001199: HAL_SPI_TxRxCpltCallback
  0x80011ad: HAL_SPI_ErrorCallback
  0x80011b9: HAL_SPI_MspInit
  0x80012d9: NMI_Handler
  0x80012db: HardFault_Handler
  0x80012dd: MemManage_Handler
  0x80012df: BusFault_Handler
  0x80012e1: UsageFault_Handler
  0x80012e3: SVC_Handler
  0x80012e5: DebugMon_Handler
  0x80012e7: PendSV_Handler
  0x80012e9: SysTick_Handler
  0x80012ed: DMA1_Channel4_IRQHandler
  0x80012f9: DMA1_Channel5_IRQHandler
  0x8001305: __libc_init_array
  0x800134d: memset
  0x800135c: __EH_FRAME_BEGIN__
  0x800135d: _init
  0x8001369: _fini
  0x8001374:
  - _etext
  - AHBPrescTable
  0x8001384: APBPrescTable
  0x800139c:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x80013a0:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x80013a4: _sidata
  0x20000000:
  - _sdata
  - SpixTimeout
  0x20000004: LED_PORT
  0x20000008: BUTTON_PORT
  0x2000000c: SystemCoreClock
  0x20000010: uwTickFreq
  0x20000014: uwTickPrio
  0x20000018: aTxBuffer
  0x20000088:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x2000008c: object.8660
  0x200000a4: uCRCErrorWorkaroundCheck
  0x200000a8: wTransferState
  0x200000ac: hdma_tx
  0x200000f0: hdma_rx
  0x20000134: uwTick
  0x20000138: SpiHandle
  0x20000190: aRxBuffer
  0x20000200:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
