interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: MIDI-Synthesizer.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12f20
symbols:
  0x0:
  - startup/startup_stm32.o
  - crtstuff.c
  - stm32f4xx_dma.c
  - stm32f4xx_gpio.c
  - stm32f4xx_rcc.c
  - stm32f4xx_tim.c
  - stm32f4xx_usart.c
  - mm_midiccrouter.c
  - mm_midimsg.c
  - mm_midimsgbuilder.c
  - mm_midirouter.c
  - mm_midirouter_standard.c
  - afl_call.c
  - leds.c
  - main.c
  - midi_lowlevel.c
  - stm32f4xx_it.c
  - syscalls.c
  - system_stm32f4xx.c
  - errno.c
  - init.c
  - malloc.c
  - mallocr.c
  - memset.c
  - mlock.c
  - sbrkr.c
  - __call_atexit.c
  - atexit.c
  - fini.c
  - mallocr.c
  - lock.c
  - __atexit.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7e-m/crtn.o
  - impure.c
  - reent.c
  - _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x80001ad: __do_global_dtors_aux
  0x80001d1: frame_dummy
  0x80001ed: DMA_Init
  0x8000299: DMA_StructInit
  0x8000305: DMA_Cmd
  0x800033b: DMA_GetCmdStatus
  0x8000369: DMA_GetFlagStatus
  0x80003dd: DMA_ClearFlag
  0x8000439: DMA_GetITStatus
  0x80004e5: DMA_ClearITPendingBit
  0x8000541: GPIO_Init
  0x800065b: GPIO_SetBits
  0x8000677: GPIO_ResetBits
  0x8000693: GPIO_ToggleBits
  0x80006b5: GPIO_PinAFConfig
  0x8000745: RCC_GetClocksFreq
  0x8000895: RCC_AHB1PeriphClockCmd
  0x80008d1: RCC_APB1PeriphClockCmd
  0x800090d: TIM_TimeBaseInit
  0x80009e1: TIM_Cmd
  0x8000a1f: TIM_ITConfig
  0x8000a65: TIM_ClearITPendingBit
  0x8000a85: USART_Init
  0x8000bf9: USART_Cmd
  0x8000c37: USART_ReceiveData
  0x8000c55: USART_DMACmd
  0x8000c9b: USART_GetITStatus
  0x8000d4f: MIDI_CC_CB_Router_route
  0x8000d8f: MIDI_CC_CB_Router_init
  0x8000dc3: MIDIMsg_numDataBytes
  0x8000e93: MIDIMsgBuilder_init
  0x8000ec1: MIDIMsgBuilder_append_byte
  0x8000eff: MIDIMsgBuilder_update
  0x8000fc9: MIDI_Router_handleMsg
  0x8001241: MIDI_Router_addCB
  0x80013cd: MIDI_Router_init
  0x8001409: MIDI_Router_Standard_init
  0x8001465: aflCall
  0x800146d: startForkserver
  0x800149d: LEDs_Init
  0x80014dd: LEDs_redSet
  0x80014f5: LEDs_redReset
  0x800150d: LEDs_greenToggle
  0x8001525: LEDs_greenSet
  0x800153d: LEDs_greenReset
  0x8001555: MIDI_note_on_do
  0x8001597: MIDI_note_off_do
  0x80015d9: main
  0x8001631: do_stuff_with_msg
  0x800164d: MIDI_process_byte
  0x80016a1: NVIC_EnableIRQ
  0x80016d1: NVIC_ClearPendingIRQ
  0x8001705: USART2_Enable_Rx
  0x8001819: Timer_setup
  0x8001869: MIDI_process_buffer
  0x80018e9: DMA1_Stream5_IRQHandler
  0x8001935: TIM2_IRQHandler
  0x8001959: MIDI_low_level_setup_nolib
  0x8001969: NVIC_ClearPendingIRQ
  0x800199d: NMI_Handler
  0x80019a9: HardFault_Handler
  0x80019af: MemManage_Handler
  0x80019b5: BusFault_Handler
  0x80019bb: UsageFault_Handler
  0x80019c1: SVC_Handler
  0x80019cd: DebugMon_Handler
  0x80019d9: PendSV_Handler
  0x80019e5: SysTick_Handler
  0x80019f1: UART5_IRQHandler
  0x8001a55: _sbrk
  0x8001aad: SystemInit
  0x8001b09: SetSysClock
  0x8001c31: Reset_Handler
  0x8001c3e: CopyDataInit
  0x8001c44: LoopCopyDataInit
  0x8001c52: FillZerobss
  0x8001c56: LoopFillZerobss
  0x8001c66: LoopForever
  0x8001c80:
  - Infinite_Loop
  - Default_Handler
  0x8001c81:
  - RTC_Alarm_IRQHandler
  - HASH_RNG_IRQHandler
  - EXTI2_IRQHandler
  - TIM8_CC_IRQHandler
  - UART8_IRQHandler
  - SPI4_IRQHandler
  - TIM1_CC_IRQHandler
  - DMA2_Stream5_IRQHandler
  - PVD_IRQHandler
  - SDIO_IRQHandler
  - TAMP_STAMP_IRQHandler
  - CAN2_RX1_IRQHandler
  - EXTI3_IRQHandler
  - TIM8_TRG_COM_TIM14_IRQHandler
  - TIM1_UP_TIM10_IRQHandler
  - TIM8_UP_TIM13_IRQHandler
  - I2C3_ER_IRQHandler
  - LCD_TFT_IRQHandler
  - EXTI0_IRQHandler
  - I2C2_EV_IRQHandler
  - DMA1_Stream2_IRQHandler
  - CAN1_RX0_IRQHandler
  - FPU_IRQHandler
  - OTG_HS_WKUP_IRQHandler
  - CAN2_SCE_IRQHandler
  - DMA2_Stream2_IRQHandler
  - SPI1_IRQHandler
  - TIM6_DAC_IRQHandler
  - TIM1_BRK_TIM9_IRQHandler
  - DCMI_IRQHandler
  - CAN2_RX0_IRQHandler
  - DMA2_Stream3_IRQHandler
  - USART6_IRQHandler
  - USART3_IRQHandler
  - CRYP_IRQHandler
  - CAN1_RX1_IRQHandler
  - DMA2_Stream0_IRQHandler
  - TIM4_IRQHandler
  - I2C1_EV_IRQHandler
  - DMA1_Stream6_IRQHandler
  - DMA1_Stream1_IRQHandler
  - UART4_IRQHandler
  - LCD_TFT_1_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM8_BRK_TIM12_IRQHandler
  - EXTI15_10_IRQHandler
  - ADC_IRQHandler
  - DMA1_Stream7_IRQHandler
  - SPI5_IRQHandler
  - TIM7_IRQHandler
  - CAN2_TX_IRQHandler
  - TIM5_IRQHandler
  - DMA2_Stream7_IRQHandler
  - I2C3_EV_IRQHandler
  - EXTI9_5_IRQHandler
  - RTC_WKUP_IRQHandler
  - ETH_WKUP_IRQHandler
  - SPI2_IRQHandler
  - OTG_HS_EP1_IN_IRQHandler
  - DMA1_Stream0_IRQHandler
  - CAN1_TX_IRQHandler
  - EXTI4_IRQHandler
  - ETH_IRQHandler
  - OTG_HS_EP1_OUT_IRQHandler
  - WWDG_IRQHandler
  - SPI6_IRQHandler
  - OTG_FS_WKUP_IRQHandler
  - TIM1_TRG_COM_TIM11_IRQHandler
  - OTG_HS_IRQHandler
  - DMA2D_IRQHandler
  - EXTI1_IRQHandler
  - UART7_IRQHandler
  - USART2_IRQHandler
  - I2C2_ER_IRQHandler
  - DMA2_Stream1_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - DMA2_Stream4_IRQHandler
  - USART1_IRQHandler
  - OTG_FS_IRQHandler
  - SPI3_IRQHandler
  - DMA1_Stream4_IRQHandler
  - I2C1_ER_IRQHandler
  - FMC_IRQHandler
  - DMA2_Stream6_IRQHandler
  - SAI1_IRQHandler
  - DMA1_Stream3_IRQHandler
  0x8001c85: __errno
  0x8001c91: __libc_init_array
  0x8001cd9: malloc
  0x8001ce9: _malloc_r
  0x8002231: memset
  0x80022c5: __malloc_lock
  0x80022d1: __malloc_unlock
  0x80022dd: _sbrk_r
  0x8002301: register_fini
  0x8002315: atexit
  0x8002321: __libc_fini_array
  0x8002355: _malloc_trim_r
  0x80023f5: _free_r
  0x80025dd: __retarget_lock_acquire_recursive
  0x80025e1: __retarget_lock_release_recursive
  0x80025e5: __register_exitproc
  0x80026a4: __EH_FRAME_BEGIN__
  0x80026a5: _init
  0x80026b1: _fini
  0x80026bc:
  - _etext
  - _global_impure_ptr
  0x80026c0:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x80026c4: __frame_dummy_init_array_entry
  0x80026c8:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  - __init_array_end
  0x80026cc:
  - __fini_array_end
  - _sidata
  0x20000000:
  - APBAHBPrescTable
  - _sdata
  0x20000010: _impure_ptr
  0x20000018: impure_data
  0x20000440: __malloc_av_
  0x20000848: __malloc_sbrk_base
  0x2000084c: __malloc_trim_threshold
  0x20000850: __atexit_recursive_mutex
  0x20000854:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x20000858: object.8660
  0x20000870: noHyperCall
  0x20000874: lastState
  0x20000878: midiMsgBuilder
  0x20000994: midiRouter
  0x20004d1c: MIDIlastIndex
  0x20004d20: MIDITimeToProcessBuffer
  0x20004d24: __env
  0x20004d28: heap_end.5959
  0x20004d2c: __malloc_current_mallinfo
  0x20004d54: __malloc_max_sbrked_mem
  0x20004d58: __malloc_max_total_mem
  0x20004d5c: __malloc_top_pad
  0x20004d60: LEDs_GPIO_InitStruct
  0x20004d68: canary1
  0x20004de8: midiBuffer
  0x20004df0: canary2
  0x20004e70: __lock___atexit_recursive_mutex
  0x20004e74: __lock___arc4random_mutex
  0x20004e78: __lock___env_recursive_mutex
  0x20004e7c: __lock___sinit_recursive_mutex
  0x20004e80: __lock___malloc_recursive_mutex
  0x20004e84: __lock___at_quick_exit_mutex
  0x20004e88: __lock___dd_hash_mutex
  0x20004e8c: __lock___tz_mutex
  0x20004e90: __lock___sfp_recursive_mutex
  0x20004e94: errno
  0x20004e98:
  - _ebss
  - end
  - __bss_end__
  0x20030000: _estack
