interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_0fe081fc:
    base_addr: 0xfe03000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: test.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x14eb0
symbols:
  0x0:
  - startup_efm32g.c
  - crtstuff.c
  - crt0.o
  - sl_board_init.c
  - sl_memory.c
  - system_efm32g.c
  - dmadrv.c
  - gpiointerrupt.c
  - uartdrv.c
  - em_cmu.c
  - em_core.c
  - em_dma.c
  - em_emu.c
  - em_gpio.c
  - em_leuart.c
  - em_rtc.c
  - em_system.c
  - sl_device_init_hfxo_s0.c
  - sl_device_init_nvic.c
  - sl_power_manager.c
  - sl_power_manager_hal_s0_s1.c
  - sl_sleeptimer.c
  - sl_sleeptimer_hal_rtc.c
  - sl_device_init_clocks.c
  - sl_event_handler.c
  - sl_uartdrv_init.c
  - uartdrv_app.c
  - _arm_addsubdf3.o
  - _arm_fixunsdfsi.o
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - exit.c
  - init.c
  - malloc.c
  - mallocr.c
  - mlock.c
  - sbrkr.c
  - s_fmin.c
  - s_fpclassify.c
  - _arm_cmpdf2.o
  - sl_board_control_gpio.c
  - sl_assert.c
  - sl_slist.c
  - sl_syscalls.c
  - em_usart.c
  - sl_device_init_emu_s0.c
  - sl_device_init_lfxo_s0.c
  - sl_system_init.c
  - sl_system_process_action.c
  - app.c
  - sl_board_default_init.c
  - sl_power_manager_handler.c
  - main.c
  - message.c
  - parser.c
  - serialiser.c
  - memcpy-stub.c
  - memset.c
  - lock.c
  - crti.o
  - crtn.o
  - impure.c
  - dmactrl.c
  - findfp.c
  - reent.c
  - __text_application_ram_offset__
  - __Vectors
  - linker_storage_size
  - linker_vectors_begin
  - linker_nvm_size
  0xbc:
  - linker_vectors_end
  - __Vectors_Size
  - linker_code_begin
  - __Vectors_End
  0xbd: deregister_tm_clones
  0xd9: register_tm_clones
  0xfd: __do_global_dtors_aux
  0x125: frame_dummy
  0x149: _stack_init
  0x151:
  - _mainCRTStartup
  - _start
  0x1c5: sl_board_init
  0x1dd: sl_board_preinit
  0x1e9: _sbrk
  0x209: Reset_Handler
  0x269: SystemMaxCoreClockGet
  0x271: SystemHFClockGet
  0x329: SystemCoreClockGet
  0x349: SystemHFXOClockSet
  0x365: SystemInit
  0x375: SystemLFXOClockGet
  0x381: DmaBasicCallback
  0x39d: StartTransfer
  0x54d: DmaPingPongCallback
  0x599: DMADRV_AllocateChannel
  0x5f9: DMADRV_Init
  0x665: DMADRV_PauseTransfer
  0x6a9: DMADRV_ResumeTransfer
  0x6ed: DMADRV_TransferActive
  0x73d: GPIOINT_IRQDispatcher
  0x775: GPIOINT_Init
  0x7a5: GPIOINT_CallbackRegister
  0x7c9: GPIO_EVEN_IRQHandler
  0x7ed: GPIO_ODD_IRQHandler
  0x811: CheckParams
  0x835: addHandle
  0x885: GetTailBuffer
  0x8b9: GPIO_PinOutClear
  0x8fd: GPIO_PinOutSet
  0x941: InitializeDma
  0x96d: EnqueueBuffer
  0x9f1: HwFcGetClearToSendPin
  0xa45: HwFcManageClearToSend
  0xac5: StartReceiveDma
  0xb09: UARTDRV_ForceTransmit
  0xbf1: UARTDRV_PauseTransmit
  0xc21: UARTDRV_ResumeTransmit
  0xc61: UARTDRV_Receive
  0xcb9: ReceiveDmaComplete
  0xdb1: UARTDRV_InitLeuart
  0x1071: sl_uartdrv_sleep_on_isr_exit
  0x10a9: CMU_DivToLog2
  0x10d5: syncReg
  0x10e9: flashWaitStateControl.isra.0
  0x1125: flashWaitStateMax
  0x1149: CMU_UpdateWaitStates
  0x1169: CMU_ClockDivSet
  0x1305: CMU_ClockEnable
  0x1385: CMU_ClockSelectGet
  0x1411: lfClkGet
  0x149d: CMU_ClockFreqGet
  0x15c1: CMU_HFXOInit
  0x160d: CMU_LFXOInit
  0x166d: CMU_LFXOPrecisionSet
  0x1679: CMU_HFXOPrecisionSet
  0x1685: CMU_OscillatorEnable
  0x16dd: sli_em_cmu_HFClockSelectLFOsc
  0x1731: sli_em_cmu_HFClockSelectHFXO
  0x1759: __NVIC_GetPriority
  0x177d: CORE_NvicIRQDisabled
  0x17b1: CORE_IrqIsBlocked
  0x181d: DMA_Prepare
  0x18a1: BUS_RegBitWrite
  0x18c9: DMA_IRQHandler
  0x1951: DMA_ActivateBasic
  0x19ad: DMA_ActivatePingPong
  0x1a31: DMA_CfgChannel
  0x1a9d: DMA_CfgDescr
  0x1af9: DMA_ChannelEnabled
  0x1b21: DMA_ChannelRequestEnable
  0x1b55: DMA_RefreshPingPong
  0x1bfd: DMA_Reset
  0x1c59: DMA_Init
  0x1cbd: getErrataFixEmuE107En
  0x1ced: emState.part.0
  0x1d55: emState.constprop.0
  0x1d79: EMU_EnterEM2
  0x1dd9: EMU_EnterEM3
  0x1e55: GPIO_PinOutSet
  0x1e99: GPIO_PinOutClear
  0x1edd: GPIO_ExtIntConfig
  0x1f95: GPIO_PinModeSet
  0x2029: LEUART_BaudrateSet
  0x20a5: LEUART_Enable
  0x20e1: LEUART_Init
  0x2145: regSync
  0x2159: RTC_CompareSet
  0x21a5: RTC_Init
  0x21cd: SYSTEM_ChipRevisionGet
  0x221d: sl_device_init_hfxo
  0x2249: sl_device_init_nvic
  0x2285: get_lowest_em
  0x22a1: power_manager_notify_em_transition
  0x2315: clock_restore
  0x236d: on_clock_wakeup_timeout
  0x2391: update_em1_requirement
  0x23f9: sl_power_manager_init
  0x2461: sli_power_manager_update_em_requirement
  0x2565: sli_power_manager_get_restore_delay
  0x2599: sli_power_manager_convert_delay_us_to_tick
  0x25b9: sl_power_manager_sleep
  0x2700: __heap_size
  0x27b1: sl_power_manager_is_latest_wakeup_internal
  0x27d1: sli_power_manager_init_hardware
  0x2821: EMU_EM23PostsleepHook
  0x285d: sli_power_manager_restore_states
  0x28ad: sli_power_manager_apply_em
  0x28e5: sli_power_manager_get_wakeup_process_time_overhead
  0x2901: sli_power_manager_low_frequency_restore
  0x292d: sli_power_manager_is_high_freq_accuracy_clk_used
  0x2939: update_delta_list
  0x2971: delta_list_insert_timer
  0x29c9: set_comparator_for_next_timer
  0x2a25: create_timer
  0x2a95: delta_list_remove_timer
  0x2acd: sl_sleeptimer_init
  0x2b41: sl_sleeptimer_stop_timer
  0x2b91: sl_sleeptimer_get_remaining_time_of_first_timer
  0x2bf1: sli_sleeptimer_is_power_manager_timer_next_to_expire
  0x2c19: sl_sleeptimer_get_timer_frequency
  0x2c25: process_timer_irq
  0x2d7d: sl_sleeptimer_is_power_manager_early_restore_timer_latest_to_expire
  0x2d95: sleeptimer_hal_init_timer
  0x2df9: sleeptimer_hal_get_counter
  0x2e1d: sleeptimer_hal_enable_int
  0x2e4d: sleeptimer_hal_disable_int
  0x2e79: sleeptimer_hal_set_compare
  0x2ee5: sleeptimer_hal_set_int
  0x2ef5: sli_sleeptimer_hal_is_int_status_set
  0x2f29: sleeptimer_hal_get_timer_frequency
  0x2f35: RTC_IRQHandler
  0x2fa5: sli_sleeptimer_set_pm_em_requirement
  0x2fd5: sl_device_init_clocks
  0x301d: sl_platform_init
  0x3125: sl_uartdrv_set_default
  0x3139: sl_uartdrv_init_instances
  0x3159: UART_rx_callback
  0x31cd: uartdrv_app_init
  0x3221: __aeabi_drsub
  0x3229:
  - __aeabi_dsub
  - __subdf3
  0x322d:
  - __adddf3
  - __aeabi_dadd
  0x34a5:
  - __aeabi_ui2d
  - __floatunsidf
  0x34c5:
  - __floatsidf
  - __aeabi_i2d
  0x34e9:
  - __extendsfdf2
  - __aeabi_f2d
  0x352d:
  - __aeabi_ul2d
  - __floatundidf
  0x353d:
  - __floatdidf
  - __aeabi_l2d
  0x3599:
  - __fixunsdfsi
  - __aeabi_d2uiz
  0x35d9: __aeabi_uldivmod
  0x3609: __udivmoddi4
  0x38bd:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x38c1: exit
  0x38e5: __libc_init_array
  0x392d: malloc
  0x393d: sbrk_aligned
  0x3981: _malloc_r
  0x3a81: __malloc_lock
  0x3a8d: __malloc_unlock
  0x3a99: _sbrk_r
  0x3ab9: fmin
  0x3af1: __fpclassifyd
  0x3b49:
  - __gtdf2
  - __gedf2
  0x3b51:
  - __ltdf2
  - __ledf2
  0x3b59:
  - __cmpdf2
  - __eqdf2
  - __nedf2
  0x3bd5: __aeabi_cdrcmple
  0x3be5:
  - __aeabi_cdcmple
  - __aeabi_cdcmpeq
  0x3bf5: __aeabi_dcmpeq
  0x3c09: __aeabi_dcmplt
  0x3c1d: __aeabi_dcmple
  0x3c31: __aeabi_dcmpge
  0x3c45: __aeabi_dcmpgt
  0x3c59: sl_board_enable_vcom
  0x3c6b: sl_board_configure_vcom
  0x3c6f: assertEFM
  0x3c71: sl_slist_init
  0x3c77: _exit
  0x3c79:
  - TIMER2_IRQHandler
  - DebugMon_Handler
  - USART0_TX_IRQHandler
  - I2C0_IRQHandler
  - HardFault_Handler
  - LEUART1_IRQHandler
  - SysTick_Handler
  - USART1_RX_IRQHandler
  - PendSV_Handler
  - NMI_Handler
  - USART1_TX_IRQHandler
  - MSC_IRQHandler
  - ADC0_IRQHandler
  - UsageFault_Handler
  - LEUART0_IRQHandler
  - UART0_TX_IRQHandler
  - TIMER0_IRQHandler
  - LCD_IRQHandler
  - PCNT2_IRQHandler
  - UART0_RX_IRQHandler
  - LETIMER0_IRQHandler
  - TIMER1_IRQHandler
  - USART2_RX_IRQHandler
  - Default_Handler
  - PCNT0_IRQHandler
  - sl_app_properties
  - PCNT1_IRQHandler
  - ACMP0_IRQHandler
  - USART0_RX_IRQHandler
  - MemManage_Handler
  - SVC_Handler
  - DAC0_IRQHandler
  - CMU_IRQHandler
  - AES_IRQHandler
  - VCMP_IRQHandler
  - BusFault_Handler
  - USART2_TX_IRQHandler
  0x3c7b: SystemLFRCOClockGet
  0x3c81: DMADRV_PeripheralMemory
  0x3cb5: ConfigGpio
  0x3d93: EnableTransmitter
  0x3dc7: EnableReceiver
  0x3dfb: DisableReceiver
  0x3e2b: DequeueBuffer.isra.0
  0x3e71: FcApplyState
  0x3ecd: sli_em_cmu_SetHFLEConfigSystemCoreClock
  0x3ecf: CORE_EnterCritical
  0x3ed7: CORE_ExitCritical
  0x3edd: CORE_EnterAtomic
  0x3ee9: CORE_ExitAtomic
  0x3eef: EMU_EM23PresleepHook
  0x3ef1: EMU_EFPEM23PresleepHook
  0x3ef3: EMU_EFPEM23PostsleepHook
  0x3ef5: EMU_Save
  0x3ef9: EMU_Restore
  0x3efd: BUS_RegMaskedWrite
  0x3f1b: LEUART_Sync
  0x3f29: LEUART_Tx
  0x3f3d: USART_Tx
  0x3f47: sl_device_init_emu
  0x3f4b: sl_device_init_lfxo
  0x3f6d: sli_power_manager_initiate_restore
  0x3f83: sli_power_manager_save_states
  0x3f87: sli_power_manager_handle_pre_deepsleep_operations
  0x3f89: sli_power_manager_restore_high_freq_accuracy_clk
  0x3f8b: sli_power_manager_is_high_freq_accuracy_clk_ready
  0x3f8f: sli_power_manager_get_default_high_frequency_minimum_offtime
  0x3f97: sl_sleeptimer_restart_timer
  0x3fd5: sl_sleeptimer_get_tick_count
  0x3fed: sl_system_init
  0x4007: sl_system_process_action
  0x401d: app_init
  0x4021: app_process_action
  0x4025: sl_board_default_init
  0x4027: sl_driver_init
  0x4035: sl_service_init
  0x4043: sl_stack_init
  0x4045: sl_internal_app_init
  0x4047: sl_platform_process_action
  0x4049: sl_service_process_action
  0x404b: sl_stack_process_action
  0x404d: sl_internal_app_process_action
  0x404f: sl_power_manager_is_ok_to_sleep
  0x4057: sl_power_manager_sleep_on_isr_exit
  0x4091: main
  0x40a9: mqtt_message_init
  0x40b1: mqtt_parser_init
  0x40bd: mqtt_parser_buffer
  0x40c7: mqtt_parser_execute
  0x46c3: mqtt_serialiser_init
  0x46c9: mqtt_serialiser_size
  0x472d: mqtt_serialiser_write
  0x4877: app_is_ok_to_sleep
  0x487b: app_sleep_on_isr_exit
  0x487f: uartdrv_app_process_action
  0x4881: memcpy
  0x489d: memset
  0x48ad: __retarget_lock_acquire_recursive
  0x48af: __retarget_lock_release_recursive
  0x48c0: linker_code_end
  0x48c1: _init
  0x48cd: _fini
  0x48d8: __code_classification_validator_start__
  0x4900: __code_classification_validator_end__
  0x4cec: CSWTCH.53
  0x4cf6: CSWTCH.52
  0x4d00: CSWTCH.51
  0x4d09: CSWTCH.56
  0x4d10:
  - __EH_FRAME_BEGIN__
  - __exidx_start
  0x4d18:
  - __exidx_end
  - __copy_table_start__
  0x4d24:
  - __etext
  - __zero_table_end__
  - __zero_table_start__
  - __copy_table_end__
  0x4eb0:
  - __lma_ramfuncs_end__
  - __lma_ramfuncs_start__
  0x20000:
  - linker_nvm_end
  - linker_storage_end
  - __nvm3Base
  - __main_flash_end__
  - linker_storage_begin
  - linker_nvm_begin
  0x20000000:
  - sl_stack
  - __StackLimit
  0x20001000:
  - heap_end.0
  - __data_start__
  - __StackTop
  - __stack
  0x20001004: SystemCoreClock
  0x20001008: SystemLFXOClock
  0x2000100c: SystemHFXOClock
  0x20001010: sl_uartdrv_leuart_init_vcom
  0x20001028: sl_uartdrv_leuart_vcom_tx_buffer
  0x200010a8: sl_uartdrv_leuart_vcom_rx_buffer
  0x20001128: sl_uartdrv_leuart_vcom_handle
  0x2000112c: _impure_ptr
  0x20001130: _impure_data
  0x2000117c: hfxo_precision
  0x2000117e: lfxo_precision
  0x20001180: comp_int_disabled
  0x20001184:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20001188:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x2000118c:
  - __TMC_END__
  - __bss_start__
  - __data_end__
  0x20001200: dmaControlBlock
  0x20001300: dma_buf
  0x20001364: object.0
  0x2000137c: dmaCallBack
  0x200013dc: chTable
  0x2000147c: gpioCallbacks
  0x2000167c: uartdrvHandle
  0x2000168c: cmuStatus.1
  0x20001690: wakeup_time_config_overhead_tick
  0x20001694: high_frequency_min_offtime_tick
  0x20001698: clock_wakeup_timer_handle
  0x200016b8: sleeptimer_frequency
  0x200016bc: power_manager_em_transition_event_list
  0x200016c0: cmu_status
  0x200016c4: process_wakeup_overhead_tick
  0x200016c8: hf_x_oscillator_wakeup_time_tc_inital
  0x200016cc: hfxo_wakeup_time_tick
  0x200016d0: max_millisecond_conversion
  0x200016d4: last_delta_update_count
  0x200016d8: timer_head
  0x200016dc: timer_frequency
  0x200016e0: compare_value_32
  0x200016e4: sli_uartdrv_default_handle
  0x200016e8: sl_uartdrv_leuart_vcom_handle_data
  0x20001748: message
  0x2000178c: parser
  0x20001798: __malloc_sbrk_start
  0x2000179c: __malloc_free_list
  0x200017a0: __sf
  0x200018d8: __stdio_exit_handler
  0x200018dc: errno
  0x200018e0: overflow_counter
  0x200018e2: completed.1
  0x200018e3: initialized
  0x200018e4: uartdrvHandleIsInitialized
  0x200018e5: hfClock.0
  0x200018e6: is_restored_from_hfxo_isr_internal
  0x200018e7: is_restored_from_hfxo_isr
  0x200018e8: is_actively_waiting_for_clock_restore
  0x200018e9: is_hf_x_oscillator_not_preserved
  0x200018ea: requirement_on_em1_added
  0x200018eb: is_states_saved
  0x200018ec: is_sleeping_waiting_for_clock_restore
  0x200018ed: waiting_clock_restore_from_em
  0x200018ee: requirement_high_accuracy_hf_clock_counter
  0x200018ef: requirement_em_table
  0x200018f1: current_em
  0x200018f2: is_initialized
  0x200018f3: is_hf_x_oscillator_already_started
  0x200018f4: is_hf_x_oscillator_used
  0x200018f5: sleep_on_isr_exit
  0x200018f6: next_timer_to_expire_is_power_manager
  0x200018f7: is_sleeptimer_initialized
  0x200018f8: rtc_overflow_count
  0x200018f9: serialiser
  0x200018fa: __lock___malloc_recursive_mutex
  0x200018fc:
  - __vma_ramfuncs_start__
  - __ramfuncs_start__
  - __text_application_ram_start__
  - __bss_end__
  - __vma_ramfuncs_end__
  - __text_application_ram_end__
  - __ramfuncs_end__
  0x20001900:
  - sl_heap
  - __HeapBase
  - end
  - __end__
  - _end
  0x20004000:
  - __HeapLimit
  - __ram_end__
