interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: SAM3X_spi_spi_dmac_slave_example_flash.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x14e44
symbols:
  0x0:
  - startup_sam3x.c
  - crtstuff.c
  - sysclk.c
  - read.c
  - write.c
  - init.c
  - dmac.c
  - pio.c
  - pio_handler.c
  - pmc.c
  - spi.c
  - spi_dmac_slave_example.c
  - uart.c
  - usart.c
  - exceptions.c
  - system_sam3x.c
  - syscalls.c
  - init.c
  - iprintf.c
  - memset.c
  - puts.c
  - setbuf.c
  - setvbuf.c
  - strlen-stub.c
  - vfprintf.c
  - wsetup.c
  - __call_atexit.c
  - atexit.c
  - fflush.c
  - findfp.c
  - fini.c
  - fputwc.c
  - mallocr.c
  - fvwrite.c
  - fwalk.c
  - locale.c
  - localeconv.c
  - lock.c
  - makebuf.c
  - malloc.c
  - mallocr.c
  - mbtowc_r.c
  - memchr-stub.c
  - lib_a-memcpy.o
  - memmove.c
  - mlock.c
  - mallocr.c
  - sbrkr.c
  - stdio.c
  - strncpy.c
  - wbuf.c
  - wcrtomb.c
  - wctomb_r.c
  - writer.c
  - __atexit.c
  - closer.c
  - fclose.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - readr.c
  - _aeabi_uldivmod.o
  - libgcc2.c
  - _dvmd_tls.o
  - impure.c
  - ctype_.c
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7-m/nofp/crti.o
  - /home/alejandro/Applications/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/thumb/v7-m/nofp/crtn.o
  - reent.c
  0x2000: __stack_size__
  0x80000:
  - _sfixed
  - exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80135: sysclk_init
  0x8017d: _read
  0x801b9: _write
  0x80211: board_init
  0x802c5: dmac_init
  0x802cf: dmac_set_priority_mode
  0x802db: dmac_enable
  0x802e1: dmac_enable_interrupt
  0x802e5: dmac_get_status
  0x802e9: dmac_channel_enable
  0x802f1: dmac_channel_disable
  0x802f9: dmac_channel_set_configuration
  0x80305: dmac_channel_single_buf_transfer_init
  0x80331: pio_set_peripheral
  0x8036d: pio_set_input
  0x8039f: pio_set_output
  0x803c5: pio_get_interrupt_status
  0x803c9: pio_get_interrupt_mask
  0x803cd: pio_set_pin_high
  0x803e7: pio_configure_pin
  0x804ab: pio_configure_pin_group
  0x8053d: pio_handler_process
  0x80585: PIOA_Handler
  0x80595: PIOB_Handler
  0x805a5: PIOC_Handler
  0x805b5: PIOD_Handler
  0x805c5: PIOE_Handler
  0x805d5: PIOF_Handler
  0x805e5: pmc_switch_mck_to_pllack
  0x80645: pmc_switch_mainck_to_xtal
  0x80699: pmc_osc_is_ready_mainck
  0x806a9: pmc_disable_pllack
  0x806b9: pmc_is_locked_pllack
  0x806c9: pmc_enable_periph_clk
  0x806e9: spi_set_peripheral_chip_select_value
  0x806ff: spi_set_clock_polarity
  0x8071d: spi_set_clock_phase
  0x8073b: spi_set_bits_per_transfer
  0x8074f: spi_set_baudrate_div
  0x80775: spi_set_transfer_delay
  0x80791: spi_slave_transfer
  0x80805: usart_serial_getchar
  0x808a1: usart_serial_putchar
  0x80935: DMAC_Handler
  0x80a7d: main
  0x80d25: uart_init
  0x80d5b: uart_write
  0x80d6b: uart_read
  0x80d7d: usart_write
  0x80d91: usart_read
  0x80da9:
  - DACC_Handler
  - DebugMon_Handler
  - TRNG_Handler
  - HardFault_Handler
  - TC2_Handler
  - SysTick_Handler
  - USART3_Handler
  - TWI1_Handler
  - PendSV_Handler
  - NMI_Handler
  - TC7_Handler
  - ADC_Handler
  - SMC_Handler
  - USART0_Handler
  - RTT_Handler
  - EFC1_Handler
  - RTC_Handler
  - UsageFault_Handler
  - TC6_Handler
  - WDT_Handler
  - CAN0_Handler
  - TC4_Handler
  - TC1_Handler
  - HSMCI_Handler
  - TC3_Handler
  - Dummy_Handler
  - TWI0_Handler
  - USART1_Handler
  - SSC_Handler
  - EFC0_Handler
  - PMC_Handler
  - PWM_Handler
  - CAN1_Handler
  - MemManage_Handler
  - SUPC_Handler
  - SVC_Handler
  - TC8_Handler
  - USART2_Handler
  - SDRAMC_Handler
  - SPI1_Handler
  - EMAC_Handler
  - UART_Handler
  - BusFault_Handler
  - RSTC_Handler
  - TC0_Handler
  - TC5_Handler
  - UOTGHS_Handler
  - SPI0_Handler
  0x80dad: Reset_Handler
  0x80e41: SystemCoreClockUpdate
  0x80f59: _sbrk
  0x80f8d: _close
  0x80f93: _fstat
  0x80f9d: _isatty
  0x80fa1: _lseek
  0x80fa5: __libc_init_array
  0x80fed: iprintf
  0x81015: memset
  0x810b5: _puts_r
  0x81151: puts
  0x81161: setbuf
  0x81171: setvbuf
  0x81311: strlen
  0x8136d: __sprint_r.part.0
  0x813e5: _vfiprintf_r
  0x82111: __sbprintf
  0x82199: __swsetup_r
  0x82269: register_fini
  0x8227d: atexit
  0x82289: __sflush_r
  0x823b9: _fflush_r
  0x82415: std
  0x82465: _cleanup_r
  0x82471: __sinit
  0x824cd: __sfp_lock_acquire
  0x824d9: __sfp_lock_release
  0x824e5: __libc_fini_array
  0x82511: __fputwc
  0x825b1: _fputwc_r
  0x82619: _malloc_trim_r
  0x826b9: _free_r
  0x828c5: __sfvwrite_r
  0x82bb1: _fwalk_reent
  0x82bf9: __locale_mb_cur_max
  0x82c05: _localeconv_r
  0x82c0d: __retarget_lock_init_recursive
  0x82c11: __retarget_lock_close_recursive
  0x82c15: __retarget_lock_acquire_recursive
  0x82c19: __retarget_lock_release_recursive
  0x82c1d: __swhatbuf_r
  0x82c79: __smakebuf_r
  0x82d0d: malloc
  0x82d1d: _malloc_r
  0x83279: __ascii_mbtowc
  0x832a5: memchr
  0x83325: memcpy
  0x83411: memmove
  0x834e5: __malloc_lock
  0x834f1: __malloc_unlock
  0x834fd: _realloc_r
  0x838dd: _sbrk_r
  0x83901: __sread
  0x83925: __swrite
  0x83965: __sseek
  0x83985: __sclose
  0x8398d: strncpy
  0x839f5: __swbuf_r
  0x83aa5: _wcrtomb_r
  0x83ae1: __ascii_wctomb
  0x83afd: _write_r
  0x83b29: __register_exitproc
  0x83bb5: _close_r
  0x83bd9: _fclose_r
  0x83ca5: _fstat_r
  0x83cd1: _isatty_r
  0x83cf5: _lseek_r
  0x83d21: _read_r
  0x83d4d: __aeabi_uldivmod
  0x83d7d: __udivmoddi4
  0x84041:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0x841c0: _global_impure_ptr
  0x841f8: blanks.7338
  0x84208: zeroes.7339
  0x84228: _ctype_
  0x8432d: _init
  0x84338:
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x8433c: __frame_dummy_init_array_entry
  0x84340: __init_array_end
  0x84341: _fini
  0x84351: __system_init_flash_veneer
  0x84358:
  - __do_global_dtors_aux_fini_array_entry
  - __fini_array_start
  0x8435c:
  - __fini_array_end
  - _efixed
  0x84364: _etext
  0x20070000: _srelocate
  0x20070001: SystemInit
  0x200700a5: system_init_flash
  0x2007012c: g_ul_slave_cmd
  0x20070130: SystemCoreClock
  0x20070134: _impure_ptr
  0x20070138: impure_data
  0x20070560: __atexit_recursive_mutex
  0x20070564: __global_locale
  0x200706d0: __malloc_av_
  0x20070ad8: __malloc_sbrk_base
  0x20070adc: __malloc_trim_threshold
  0x20070ae0:
  - completed.8911
  - _sbss
  - _szero
  - _erelocate
  0x20070ae4: object.8916
  0x20070afc: gs_interrupt_sources
  0x20070b6c: g_ul_spi_state
  0x20070b70: heap.5364
  0x20070b74: __malloc_current_mallinfo
  0x20070b9c: __malloc_max_sbrked_mem
  0x20070ba0: __malloc_max_total_mem
  0x20070ba4: __malloc_top_pad
  0x20070ba8: ptr_get
  0x20070bac: ptr_put
  0x20070bb0: stdio_base
  0x20070bb4: g_uc_role
  0x20070bb8: g_ul_master_cmd
  0x20070bbc: g_ul_test_block_number
  0x20070bc0: g_uc_spi_buffer
  0x20070c00: spi_status
  0x20070c58: g_ul_master_recv_done
  0x20070c5c: g_ul_spi_clock
  0x20070c60: __lock___atexit_recursive_mutex
  0x20070c64: __lock___arc4random_mutex
  0x20070c68: __lock___env_recursive_mutex
  0x20070c6c: __lock___sinit_recursive_mutex
  0x20070c70: __lock___malloc_recursive_mutex
  0x20070c74: __lock___at_quick_exit_mutex
  0x20070c78: __lock___dd_hash_mutex
  0x20070c7c: __lock___tz_mutex
  0x20070c80: __lock___sfp_recursive_mutex
  0x20070c84: errno
  0x20070c88:
  - _ebss
  - _ezero
  - _sstack
  0x20072c88:
  - _estack
  - _end
  0x20087ffc: __ram_end__
