interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: NUC123_PDMA_usart.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x12600
symbols:
  0x0:
  - ./CMSIS/CMSIS/gcc/startup_NUC123.o
  - crtstuff.c
  - /home/alejandro/local/gcc-arm-none-eabi-6-2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/lib/thumb/v6-m/crt0.o
  - main.c
  - clk.c
  - pdma.c
  - retarget.c
  - sys.c
  - uart.c
  - _syscalls.c
  - system_NUC123.c
  - _thumb1_case_uqi.o
  - _udivsi3.o
  - _dvmd_tls.o
  - errno.c
  - exit.c
  - init.c
  - memset.c
  - printf.c
  - putchar.c
  - puts.c
  - rget.c
  - wbuf.c
  - wsetup.c
  - fflush.c
  - findfp.c
  - fwalk.c
  - makebuf.c
  - nano-mallocr.c
  - nano-mallocr.c
  - nano-vfprintf.c
  - nano-vfprintf_i.c
  - putc.c
  - refill.c
  - sbrkr.c
  - stdio.c
  - writer.c
  - closer.c
  - fstatr.c
  - isattyr.c
  - lseekr.c
  - memchr-stub.c
  - mlock.c
  - readr.c
  - sbrk.c
  - _exit.c
  - /home/alejandro/local/gcc-arm-none-eabi-6-2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/thumb/v6-m/crti.o
  - /home/alejandro/local/gcc-arm-none-eabi-6-2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/thumb/v6-m/crtn.o
  - impure.c
  - crtstuff.c
  - __Vectors
  0xc0:
  - __Vectors_Size
  - __Vectors_End
  0xc1: __do_global_dtors_aux
  0xe9: frame_dummy
  0x100: Heap_Size
  0x121:
  - _mainCRTStartup
  - _start
  0x199: ClearBuf
  0x1a7: BuildSrcPattern
  0x1d1: PDMA_UART_TxTest
  0x20d: PDMA_UART_RxTest
  0x249: PDMA_Callback_0
  0x281: PDMA_Callback_1
  0x2e5: PDMA_IRQHandler
  0x315: UART0_IRQHandler
  0x32d: PDMA_UART
  0x400: Stack_Size
  0x4c5: SYS_Init
  0x555: UART0_Init
  0x571: UART1_Init
  0x58d: main
  0x5ed: CLK_SetHCLK
  0x629: CLK_SetModuleClock
  0x6d5: CLK_EnableXtalRC
  0x6e5: CLK_EnableModuleClock
  0x701: CLK_EnablePLL
  0x895: CLK_SetCoreClock
  0x911: CLK_WaitClockReady
  0x915: PDMA_Open
  0x925: PDMA_Close
  0x931: PDMA_SetTransferCnt
  0x969: PDMA_SetTransferAddr
  0x989: PDMA_SetTransferMode
  0xad9: PDMA_Trigger
  0xaf1: PDMA_EnableInt
  0xb05: PDMA_DisableInt
  0xb19: Hard_Fault_Handler
  0xb89: HardFault_Handler
  0xba9: _write
  0xbe1: _read
  0xbf9: SYS_ResetModule
  0xc19: CLK_GetPLLClockFreq
  0xc75: UART_DisableInt
  0xc99: UART_EnableInt
  0xcbd: UART_Open
  0xd4d: _close
  0xd5d: _fstat
  0xd6d: _isatty
  0xd7b: _lseek
  0xd8d: Reset_Handler
  0xdb5:
  - GPCDF_IRQHandler
  - I2C0_IRQHandler
  - SysTick_Handler
  - PendSV_Handler
  - NMI_Handler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - PS2_IRQHandler
  - CAN1_IRQHandler
  - USBD_IRQHandler
  - SPI1_IRQHandler
  - TMR0_IRQHandler
  - ACMP_IRQHandler
  - I2S_IRQHandler
  - RTC_IRQHandler
  - PWRWU_IRQHandler
  - EINT1_IRQHandler
  - PWMA_IRQHandler
  - Default_Handler
  - ADC_IRQHandler
  - TMR2_IRQHandler
  - BOD_IRQHandler
  - SPI2_IRQHandler
  - WDT_IRQHandler
  - SVC_Handler
  - SC012_IRQHandler
  - GPAB_IRQHandler
  - EINT0_IRQHandler
  - CAN0_IRQHandler
  - TMR3_IRQHandler
  - SPI0_IRQHandler
  - SPI3_IRQHandler
  - TMR1_IRQHandler
  0xdb9: SH_DoCommand
  0xdc1: SystemCoreClockUpdate
  0xe6d: SystemInit
  0xe71: __gnu_thumb1_case_uqi
  0xe84: .udivsi3_skip_div0_test
  0xe85:
  - __udivsi3
  - __aeabi_uidiv
  0xf91: __aeabi_uidivmod
  0xf99:
  - __aeabi_ldiv0
  - __aeabi_idiv0
  0xf9d: __errno
  0xfa9: exit
  0xfd5: __libc_init_array
  0x101d: memset
  0x102d:
  - printf
  - iprintf
  0x1061: putchar
  0x1089: _puts_r
  0x1149: puts
  0x115d: __srget_r
  0x11bd: __swbuf_r
  0x1269: __swsetup_r
  0x1355: __sflush_r
  0x1469: _fflush_r
  0x14c1: fflush
  0x14e9: _cleanup_r
  0x14f9: std.isra.0
  0x1541: __sfmoreglue
  0x156d: __sinit
  0x15d5: __sfp
  0x1655: _fwalk
  0x168d: _fwalk_reent
  0x16d1: __swhatbuf_r
  0x1721: __smakebuf_r
  0x17a9: _free_r
  0x183d: _malloc_r
  0x18f9: __sfputc_r
  0x1923: __sfputs_r
  0x1949:
  - _vfiprintf_r
  - _vfprintf_r
  0x1b81: _printf_common
  0x1c5d: _printf_i
  0x1e91: _putc_r
  0x1efd: lflush
  0x1f15: __srefill_r
  0x2035: _sbrk_r
  0x2059: __sread
  0x2081: __swrite
  0x20b9: __sseek
  0x20e5: __sclose
  0x20f1: _write_r
  0x2119: _close_r
  0x213d: _fstat_r
  0x2161: _isatty_r
  0x2185: _lseek_r
  0x21ad: memchr
  0x21c3: __malloc_lock
  0x21c5: __malloc_unlock
  0x21c9: _read_r
  0x21f1: _sbrk
  0x220d: _exit
  0x2211: _init
  0x221d: _fini
  0x24bc: _global_impure_ptr
  0x24c0: __sf_fake_stderr
  0x24e0: __sf_fake_stdin
  0x2500: __sf_fake_stdout
  0x2554:
  - __EH_FRAME_BEGIN__
  - __FRAME_END__
  0x2558: __exidx_start
  0x2560:
  - __exidx_end
  - __etext
  0x20000000:
  - __data_start__
  - UART_TEST_LENGTH
  0x20000004: CyclesPerUs
  0x20000008: PllClock
  0x2000000c: SystemCoreClock
  0x20000010: gau32ClkSrcTbl
  0x20000030: _impure_ptr
  0x20000034: impure_data
  0x20000094:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  0x20000098:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x2000009c:
  - __JCR_LIST__
  - __JCR_END__
  0x200000a0:
  - completed.8663
  - __bss_start__
  - __data_end__
  0x200000a4: object.8668
  0x200000bc: g_u32TwoChannelPdmaTest
  0x200000c0: __malloc_free_list
  0x200000c4: __malloc_sbrk_start
  0x200000c8: heap_end.4116
  0x200000cc: IsTestOver
  0x200000d0: SrcArray
  0x20000110: IntCnt
  0x20000114: DestArray
  0x20000154: errno
  0x20000158:
  - __HeapBase
  - end
  - __bss_end__
  - __end__
  0x20000258: __HeapLimit
  0x20004c00: __StackLimit
  0x20005000:
  - __StackTop
  - __stack
