interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .data:
    base_addr: 0x10000000
    permissions: rw-
    size: 0x30c
  dynamically_added_crash_region_10007ff8:
    base_addr: 0x10002000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x1a000000
    file: periph_uart_sg.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1310c
symbols:
  0x0:
  - cr_startup_lpc18xx.c
  - sysinit.c
  - uart.c
  - board.c
  - board_sysinit.c
  - chip_18xx_43xx.c
  - clock_18xx_43xx.c
  - gpdma_18xx_43xx.c
  - gpio_18xx_43xx.c
  - ring_buffer.c
  - sysinit_18xx_43xx.c
  - uart_18xx_43xx.c
  - _cr__main.c
  - memcpy.c
  - memset.c
  - initio.c
  - setvbuf.c
  - _fdopen.c
  - fclose.c
  - fflush.c
  - fseek.c
  - ftell.c
  - remove.c
  - strlen.c
  - _do_fflush.c
  - _fflush.c
  - _writebuf.c
  - alloc.c
  - _deferredlazyseek.c
  - division_64.o
  - division_idiv0.o
  - memcpy.o
  - __sys_close.c
  - __sys_flen.c
  - __sys_istty.c
  - __sys_remove.c
  - __sys_seek.c
  - __sys_tmpnam.c
  - __ciob.c
  - errno.c
  0x310c: _image_size
  0x10000000:
  - uartABStart
  - __base_RamLoc32
  - _end_uninit_RESERVED
  - _start_uninit_RESERVED
  - _data
  - __base_RAM
  0x10000030: uartABComplete
  0x10000054: isDMATx
  0x10000058: GPDMA_LUTPerAddr
  0x100000d0:
  - _bss
  - num_correct
  - _edata
  0x100000d4:
  - DMADest_Buffer
  - dma_buf_1
  0x100000d8:
  - dma_buf_2
  - DMADest_Buffer_2
  0x100000dc: txring
  0x100000f0: rxring
  0x10000104: dmaChannelNumTx
  0x10000105: dmaChannelNumRx
  0x10000108: channelTC
  0x1000010c: channelTCErr
  0x10000110: SystemCoreClock
  0x10000114: audio_usb_pll_freq
  0x1000011c: ChannelHandlerArray
  0x10000124: ABsyncSts
  0x10000128: errno
  0x1000012c: __Ciob
  0x1000030c:
  - _noinit
  - _ebss
  - _end_noinit
  - _pvHeapStart
  0x10008000:
  - __top_RAM
  - __top_RamLoc32
  - _vStackTop
  0x10080000:
  - __base_RAM2
  - __base_RamLoc40
  0x1008a000:
  - __top_RAM2
  - __top_RamLoc40
  0x1a000000:
  - __vectors_start__
  - __base_Flash
  - _image_start
  - __base_MFlashA512
  - g_pfnVectors
  0x1a000114:
  - __section_table_start
  - __data_section_table
  0x1a000150:
  - __data_section_table_end
  - __bss_section_table
  0x1a000178:
  - __bss_section_table_end
  - __section_table_end
  0x1a000179: data_init
  0x1a0001bd: bss_init
  0x1a0001f5: NMI_Handler
  0x1a0001fd: HardFault_Handler
  0x1a000205: MemManage_Handler
  0x1a00020d: BusFault_Handler
  0x1a000215: UsageFault_Handler
  0x1a00021d: SVC_Handler
  0x1a000225: DebugMon_Handler
  0x1a00022d: PendSV_Handler
  0x1a000235: SysTick_Handler
  0x1a00023d:
  - TIMER2_IRQHandler
  - RIT_IRQHandler
  - I2C0_IRQHandler
  - SDIO_IRQHandler
  - ATIMER_IRQHandler
  - I2C1_IRQHandler
  - UART1_IRQHandler
  - GPIO5_IRQHandler
  - CAN1_IRQHandler
  - USB1_IRQHandler
  - I2S0_IRQHandler
  - TIMER3_IRQHandler
  - SGPIO_IRQHandler
  - ADC0_IRQHandler
  - GPIO6_IRQHandler
  - IntDefaultHandler
  - GPIO1_IRQHandler
  - SSP0_IRQHandler
  - ADC1_IRQHandler
  - FLASHEEPROM_IRQHandler
  - RTC_IRQHandler
  - TIMER0_IRQHandler
  - LCD_IRQHandler
  - TIMER1_IRQHandler
  - UART2_IRQHandler
  - GPIO2_IRQHandler
  - I2S1_IRQHandler
  - SSP1_IRQHandler
  - USB0_IRQHandler
  - GPIO3_IRQHandler
  - SCT_IRQHandler
  - WDT_IRQHandler
  - GPIO7_IRQHandler
  - SPIFI_IRQHandler
  - QEI_IRQHandler
  - ETH_IRQHandler
  - CAN0_IRQHandler
  - GINT0_IRQHandler
  - DAC_IRQHandler
  - GPIO0_IRQHandler
  - EVRT_IRQHandler
  - UART3_IRQHandler
  - MCPWM_IRQHandler
  - GINT1_IRQHandler
  - GPIO4_IRQHandler
  0x1a000245: ResetISR
  0x1a00031d: SystemInit
  0x1a000341: NVIC_EnableIRQ
  0x1a000371: NVIC_DisableIRQ
  0x1a0003a5: NVIC_SetPriority
  0x1a0003f9: Chip_UART_IntEnable
  0x1a000419: Chip_UART_SetupFIFOS
  0x1a000435: pwcheck_success
  0x1a000451: pwcheck_passed_1
  0x1a00046d: pwcheck_passed_2
  0x1a000489: pwcheck_passed_3
  0x1a0004a5: pwcheck_passed_4
  0x1a0004c1: pwcheck_passed_5
  0x1a0004dd: pwcheck_passed_6
  0x1a0004f9: pwcheck_passed_7
  0x1a000515: pwcheck_passed_8
  0x1a000531: check_password_scatter_gather
  0x1a0005cd: App_DMA_Init
  0x1a0005f5: App_DMA_DeInit
  0x1a000629: App_DMA_Test
  0x1a000739: DMA_IRQHandler
  0x1a00079d: UART0_IRQHandler
  0x1a0007bd: main
  0x1a00083d: Chip_SCU_PinMuxSet
  0x1a00086d: Chip_ENET_RMIIEnable
  0x1a000895: Chip_GPIO_SetPinState
  0x1a0008cb: Chip_GPIO_SetPinDIROutput
  0x1a000907: Chip_UART_TXEnable
  0x1a00091f: Chip_UART_SendByte
  0x1a00093b: Chip_UART_ConfigData
  0x1a000955: Chip_UART_ReadLineStatus
  0x1a00096b: __sys_write
  0x1a0009a3: Board_UART_Init
  0x1a0009c9: Board_Debug_Init
  0x1a0009f9: Board_UARTPutChar
  0x1a000a2d: Board_LED_Init
  0x1a000a8d: Board_Init
  0x1a000ab1: Chip_SCU_PinMuxSet
  0x1a000ae1: Chip_SCU_SetPinMuxing
  0x1a000b2d: Chip_CREG_SetFlashAcceleration
  0x1a000b81: Board_SetupMuxing
  0x1a000b95: Board_SetupClocking
  0x1a000c15: Board_SystemInit
  0x1a000c25: SystemCoreClockUpdate
  0x1a000c3d: ABS
  0x1a000c5d: pll_calc_divs
  0x1a000d81: pll_get_frac
  0x1a000ef7: Chip_Clock_GetDivRate
  0x1a000f39: Chip_Clock_FindBaseClock
  0x1a000fc5: Chip_Clock_EnableCrystal
  0x1a001035: Chip_Clock_CalcMainPLLValue
  0x1a00110d: Chip_Clock_GetMainPLLHz
  0x1a0011c9: Chip_Clock_GetDividerSource
  0x1a001209: Chip_Clock_GetDividerDivisor
  0x1a00123d: Chip_Clock_GetClockInputHz
  0x1a00137d: Chip_Clock_GetBaseClocktHz
  0x1a0013a1: Chip_Clock_SetBaseClock
  0x1a00143d: Chip_Clock_GetBaseClock
  0x1a001489: Chip_Clock_EnableOpts
  0x1a001505: Chip_Clock_GetRate
  0x1a00158d: configDMAMux
  0x1a001789: makeCtrlWord
  0x1a0018d1: setupChannel
  0x1a00198d: Chip_GPDMA_Init
  0x1a0019f9: Chip_GPDMA_Stop
  0x1a001a61: Chip_GPDMA_Interrupt
  0x1a001acd: Chip_GPDMA_InitChannelCfg
  0x1a001bd1: Chip_GPDMA_IntGetStatus
  0x1a001c8d: Chip_GPDMA_ClearIntPending
  0x1a001ccb: Chip_GPDMA_ChannelCmd
  0x1a001d11: Chip_GPDMA_PrepareDescriptor
  0x1a001dd5: Chip_GPDMA_SGTransfer
  0x1a001ea3: Chip_GPIO_Init
  0x1a001eb5: RingBuffer_GetCount
  0x1a001ed5: RingBuffer_IsFull
  0x1a001efb: RingBuffer_IsEmpty
  0x1a001f23: RingBuffer_Insert
  0x1a001f7f: RingBuffer_Pop
  0x1a001fdd: Chip_Clock_DisableMainPLL
  0x1a001ff9: Chip_Clock_SetupMainPLL
  0x1a002039: Chip_Clock_MainPLLLocked
  0x1a00205d: Chip_SetupCoreClock
  0x1a0021b9: RingBuffer_IsEmpty
  0x1a0021e1: Chip_UART_TXDisable
  0x1a0021f9: Chip_UART_SendByte
  0x1a002215: Chip_UART_ReadByte
  0x1a00222d: Chip_UART_IntDisable
  0x1a00224f: Chip_UART_ReadIntIDReg
  0x1a002265: Chip_UART_SetupFIFOS
  0x1a00227f: Chip_UART_ConfigData
  0x1a002299: Chip_UART_EnableDivisorAccess
  0x1a0022b7: Chip_UART_DisableDivisorAccess
  0x1a0022d5: Chip_UART_SetDivisorLatches
  0x1a0022fb: Chip_UART_ReadLineStatus
  0x1a002311: Chip_UART_SetAutoBaudReg
  0x1a002331: Chip_UART_GetIndex
  0x1a00239d: Chip_UART_ABIntHandler
  0x1a002409: Chip_UART_Init
  0x1a00248d: Chip_UART_Send
  0x1a0024dd: Chip_UART_SendBlocking
  0x1a002527: Chip_UART_RXIntHandlerRB
  0x1a002563: Chip_UART_TXIntHandlerRB
  0x1a0025b7: Chip_UART_IRQRBHandler
  0x1a002601: Chip_UART_SetBaudFDR
  0x1a002781: Chip_UART_GetABEOStatus
  0x1a00279d: Chip_UART_ABCmd
  0x1a00281d: __main
  0x1a00282b: memcpy
  0x1a00282f: memset
  0x1a002835: _initio
  0x1a0028ad: setvbuf
  0x1a0028eb: _fdopen
  0x1a002953: fclose
  0x1a0029ad: fflush
  0x1a0029e9: fseek
  0x1a002ae1: ftell
  0x1a002b25: remove
  0x1a002b39: strlen
  0x1a002b87: _do_fflush
  0x1a002bc7: _fflush
  0x1a002c19: _Cwritebuf
  0x1a002c85: free
  0x1a002cb5: _deferredlazyseek
  0x1a002cf5: __aeabi_uldivmod
  0x1a002cf9: __bhs_ldivmod1
  0x1a002d14: ldiv32
  0x1a002d1c: ldiv_return
  0x1a002d32: ldiv_sign
  0x1a002d44: ldiv64
  0x1a002dcc: ldiv_res01
  0x1a002de2: ldiv_divzero
  0x1a002dee: udiv6432
  0x1a002df6: udiv6432_loop1
  0x1a002e0a: udiv6432_entry
  0x1a002e0c: udiv6432_loop
  0x1a002e69: __aeabi_idiv0
  0x1a002e6b: __aeabi_memcpy
  0x1a002e75:
  - __aeabi_memcpy4
  - __aeabi_memcpy8
  0x1a002e78: copy4
  0x1a002e8e: copy1
  0x1a002e9f: __aeabi_lowlevel_memset
  0x1a002eb2: __bhs_memset4
  0x1a002eb4: memset4
  0x1a002ec0: memset1
  0x1a002ec4: memset1a
  0x1a002ed1: __sys_close
  0x1a002ed7: __sys_flen
  0x1a002edd: __sys_istty
  0x1a002ee3: __sys_remove
  0x1a002ee9: __sys_seek
  0x1a002eef: __sys_tmpnam
  0x1a002ef4: ExtRateIn
  0x1a002ef8: OscRateIn
  0x1a002efc: gpioLEDBits
  0x1a002f04: InitClkStates
  0x1a002f10: pinmuxing
  0x1a002f44: periph_to_base
  0x1a002fa8: GPDMA_LUTPerBurst
  0x1a002fc8: GPDMA_LUTPerWid
  0x1a002fe8: InitClkStates
  0x1a003024: UART_PClock
  0x1a00302c: UART_BClock
  0x1a003038: __num_Ciob_streams
  0x1a00303c:
  - __exidx_end
  - _etext
  - __exidx_start
  0x1a00310c: _image_end
  0x1a080000:
  - __top_MFlashA512
  - __top_Flash
  0x1b000000:
  - __base_Flash2
  - __base_MFlashB512
  0x1b080000:
  - __top_Flash2
  - __top_MFlashB512
  0x20000000:
  - __base_RamAHB32
  - __base_RAM3
  0x20008000:
  - __top_RamAHB32
  - __base_RamAHB16
  - __base_RAM4
  - __top_RAM3
  0x2000c000:
  - __base_RamAHB_ETB16
  - __top_RAM4
  - __base_RAM5
  - __top_RamAHB16
  0x20010000:
  - __top_RamAHB_ETB16
  - __top_RAM5
