interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: F103_I2C_OneBoard_Communication_DMAAndIT.bin
    is_entry: true
    ivt_offset: 0x0
    permissions: r-x
    size: 0x10a90
symbols:
  0x0:
  - Example/SW4STM32/startup_stm32f103xb.o
  - crtstuff.c
  - system_stm32f1xx.c
  - stm32f1xx_ll_rcc.c
  - stm32f1xx_ll_utils.c
  - main.c
  - stm32f1xx_it.c
  - init.c
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crti.o
  - /home/alejandro/Ac6/SystemWorkbench/plugins/fr.ac6.mcu.externaltools.arm-none.linux64_1.17.0.201812190825/tools/compiler/bin/../lib/gcc/arm-none-eabi/7.3.1/thumb/v7-m/crtn.o
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x800010d: __do_global_dtors_aux
  0x8000131: frame_dummy
  0x800014d: SystemInit
  0x8000199: RCC_GetHCLKClockFreq
  0x80001b1: RCC_GetPCLK1ClockFreq
  0x80001c9: RCC_GetPCLK2ClockFreq
  0x80001e1: RCC_PLL_GetFreqDomain_SYS
  0x8000215: RCC_GetSystemClockFreq
  0x8000231: LL_RCC_GetSystemClocksFreq
  0x8000251: LL_Init1msTick
  0x800026d: LL_mDelay
  0x8000281: LL_SetSystemCoreClock
  0x800028d: Reset_Handler
  0x8000290: CopyDataInit
  0x8000298: LoopCopyDataInit
  0x80002a6: FillZerobss
  0x80002ac: LoopFillZerobss
  0x80002d4:
  - Infinite_Loop
  - Default_Handler
  0x80002d5:
  - RTC_Alarm_IRQHandler
  - EXTI2_IRQHandler
  - TIM1_CC_IRQHandler
  - PVD_IRQHandler
  - EXTI3_IRQHandler
  - EXTI0_IRQHandler
  - ADC1_2_IRQHandler
  - SPI1_IRQHandler
  - TAMPER_IRQHandler
  - USART3_IRQHandler
  - RTC_IRQHandler
  - DMA1_Channel7_IRQHandler
  - CAN1_RX1_IRQHandler
  - TIM4_IRQHandler
  - DMA1_Channel6_IRQHandler
  - TIM3_IRQHandler
  - RCC_IRQHandler
  - TIM1_TRG_COM_IRQHandler
  - DMA1_Channel1_IRQHandler
  - EXTI9_5_IRQHandler
  - SPI2_IRQHandler
  - DMA1_Channel5_IRQHandler
  - EXTI4_IRQHandler
  - USB_LP_CAN1_RX0_IRQHandler
  - USB_HP_CAN1_TX_IRQHandler
  - DMA1_Channel3_IRQHandler
  - TIM1_UP_IRQHandler
  - WWDG_IRQHandler
  - TIM2_IRQHandler
  - TIM1_BRK_IRQHandler
  - EXTI1_IRQHandler
  - USART2_IRQHandler
  - DMA1_Channel2_IRQHandler
  - CAN1_SCE_IRQHandler
  - FLASH_IRQHandler
  - USART1_IRQHandler
  - USBWakeUp_IRQHandler
  0x80002d9: LL_APB2_GRP1_EnableClock
  0x80002f5: LL_GPIO_SetPinMode
  0x8000323: LL_GPIO_SetPinOutputType.constprop.11
  0x8000359: LL_GPIO_SetPinSpeed.constprop.12
  0x8000391: Configure_DMA
  0x8000421: Configure_I2C_Slave
  0x80004f1: Configure_I2C_Master
  0x800060d: Activate_I2C_Slave
  0x800062d: Activate_I2C_Master
  0x800064d: Buffercmp8
  0x8000671: LED_Init
  0x800068d: LED_Blinking
  0x80006ad: UserButton_Init
  0x8000719: WaitForUserButtonPress
  0x8000741: Handle_I2C_Slave
  0x8000751: Handle_I2C_Master
  0x8000785: SystemClock_Config
  0x8000815: main
  0x8000851: UserButton_Callback
  0x800085d: Slave_Reception_Callback
  0x800087d: Transfer_Complete_Callback
  0x8000899: Transfer_Error_Callback
  0x80008b1: Error_Callback
  0x80008d1: Slave_Complete_Callback
  0x80008fd: NMI_Handler
  0x80008ff: HardFault_Handler
  0x8000901: MemManage_Handler
  0x8000903: BusFault_Handler
  0x8000905: UsageFault_Handler
  0x8000907: SVC_Handler
  0x8000909: DebugMon_Handler
  0x800090b: PendSV_Handler
  0x800090d: SysTick_Handler
  0x8000911: EXTI15_10_IRQHandler
  0x8000929: I2C1_EV_IRQHandler
  0x8000995: I2C1_ER_IRQHandler
  0x8000999: I2C2_EV_IRQHandler
  0x80009d5: I2C2_ER_IRQHandler
  0x80009d9: DMA1_Channel4_IRQHandler
  0x80009fd: __libc_init_array
  0x8000a44: __EH_FRAME_BEGIN__
  0x8000a45: _init
  0x8000a51: _fini
  0x8000a5c:
  - _etext
  - AHBPrescTable
  0x8000a6c: APBPrescTable
  0x8000a74:
  - __frame_dummy_init_array_entry
  - __preinit_array_end
  - __init_array_start
  - __preinit_array_start
  - __exidx_end
  - __exidx_start
  0x8000a78:
  - __do_global_dtors_aux_fini_array_entry
  - __init_array_end
  0x8000a7c: _sidata
  0x20000000:
  - SystemCoreClock
  - _sdata
  0x20000004: ubNbDataToTransmit
  0x20000008: pTransmitBuffer
  0x2000000c: aLedOn
  0x20000014:
  - completed.8655
  - _sbss
  - __bss_start__
  - _edata
  0x20000018: object.8660
  0x20000030: ubButtonPress
  0x20000031: ubTransferComplete
  0x20000032: ubReceiveIndex
  0x20000033: aReceiveBuffer
  0x20000044:
  - _ebss
  - __bss_end__
  0x20005000: _estack
  0xf108f85f: BootRAM
